begin;
create temp table qa_ids as select gen_random_uuid() school,gen_random_uuid() other_school,gen_random_uuid() owner_user,gen_random_uuid() teacher_user,gen_random_uuid() colleague_user,gen_random_uuid() staff_user;
grant select on qa_ids to authenticated;
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) select u,'authenticated','authenticated',u::text||'@qa.invalid','{}','{}',now(),now() from qa_ids cross join lateral unnest(array[owner_user,teacher_user,colleague_user,staff_user])u;
insert into public.sc_schools(id,name,created_by,is_internal_test) select school,'QA Agenda Rollback',owner_user,true from qa_ids union all select other_school,'QA Other Agenda Rollback',colleague_user,true from qa_ids;
insert into public.sc_members(school_id,user_id,role) select school,owner_user,'owner' from qa_ids union all select school,teacher_user,'teacher' from qa_ids union all select school,colleague_user,'teacher' from qa_ids union all select school,staff_user,'staff' from qa_ids;
insert into public.sc_subscriptions(school_id,status,trial_ends_at,current_period_end) select school,'active',now()+interval '7 days',now()+interval '30 days' from qa_ids;
select set_config('request.jwt.claim.sub',owner_user::text,true) from qa_ids;
set local role authenticated;
do $$declare q record;p jsonb;id uuid;begin
 select * into q from qa_ids;
 p:=jsonb_build_object('title','QA Target Teacher','event_date',(now() at time zone 'Asia/Jakarta')::date,'start_time',((now() at time zone 'Asia/Jakarta')-interval '1 minute')::time,'end_time',((now() at time zone 'Asia/Jakarta')-interval '30 seconds')::time,'category','meeting','scope','school','audience_type','school','participants','[]'::jsonb,'attendance_required',true,'attendance_target','roles','attendance_roles',jsonb_build_array('teacher'),'attendance_users','[]'::jsonb,'attendance_address','QA Test Address','attendance_latitude',0,'attendance_longitude',0,'checkin_open_minutes',30,'checkin_close_minutes',60);
 id:=public.sc_save_calendar_event_v4(q.school,null,p);perform set_config('qa.roles_event',id::text,true);perform set_config('qa.payload',p::text,true);
 begin perform public.sc_event_check_in(q.school,id,0,0,10);raise exception 'FAIL creator not target accepted';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin perform public.sc_save_calendar_event_v4(q.school,null,p||'{"attendance_latitude":null}');raise exception 'FAIL null coordinates';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin perform public.sc_save_calendar_event_v4(q.school,null,p||'{"attendance_roles":["viewer"]}');raise exception 'FAIL viewer targeted';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin perform public.sc_save_calendar_event_v4(q.school,null,p||jsonb_build_object('attendance_target','users','attendance_users',jsonb_build_array(gen_random_uuid())));raise exception 'FAIL foreign user targeted';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 id:=public.sc_save_calendar_event_v4(q.school,null,p||jsonb_build_object('attendance_target','users','attendance_users',jsonb_build_array(q.teacher_user)));perform set_config('qa.users_event',id::text,true);
 id:=public.sc_save_calendar_event_v4(q.school,null,p||jsonb_build_object('attendance_required',false));perform set_config('qa.disabled_event',id::text,true);
 id:=public.sc_save_calendar_event_v4(q.school,null,p||jsonb_build_object('event_date',((now() at time zone 'Asia/Jakarta')::date)+1));perform set_config('qa.future_event',id::text,true);
end $$;
reset role;
select set_config('request.jwt.claim.sub',teacher_user::text,true) from qa_ids;
set local role authenticated;
do $$declare q record;v public.sc_event_attendance;v2 public.sc_event_attendance;id uuid:=current_setting('qa.roles_event')::uuid;begin select * into q from qa_ids;
 begin perform public.sc_event_check_in(q.school,id,0,0.00117,100);raise exception 'FAIL >100m with GPS tolerance accepted';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin perform public.sc_event_check_in(q.school,id,null,null,10);raise exception 'FAIL no GPS';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin perform public.sc_event_check_in(q.school,id,0,0,101);raise exception 'FAIL poor accuracy';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin perform public.sc_event_check_in(q.other_school,id,0,0,10);raise exception 'FAIL cross tenant';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin perform public.sc_event_check_in(q.school,current_setting('qa.disabled_event')::uuid,0,0,10);raise exception 'FAIL attendance disabled';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin perform public.sc_event_check_in(q.school,current_setting('qa.future_event')::uuid,0,0,10);raise exception 'FAIL time window';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 v:=public.sc_event_check_in(q.school,id,0,0.00081,10);v2:=public.sc_event_check_in(q.school,id,0,0,10);if v.check_in_at is distinct from v2.check_in_at then raise exception 'FAIL duplicate altered timestamp';end if;
 begin perform public.sc_event_check_out(q.school,id,0,0.00117,10);raise exception 'FAIL outside checkout';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 v:=public.sc_event_check_out(q.school,id,0,0,10);if v.check_out_at is null then raise exception 'FAIL check out';end if;
 perform public.sc_event_check_in(q.school,current_setting('qa.users_event')::uuid,0,0,10);
 begin perform public.sc_save_calendar_event_v4(q.school,null,current_setting('qa.payload')::jsonb);raise exception 'FAIL teacher configured attendance';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin insert into public.sc_event_attendance(school_id,event_id,user_id,status)values(q.school,id,q.colleague_user,'present');raise exception 'FAIL direct attendance bypass';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
end $$;
reset role;
select set_config('request.jwt.claim.sub',colleague_user::text,true) from qa_ids;
set local role authenticated;
do $$declare q record;begin select * into q from qa_ids;begin perform public.sc_event_check_in(q.school,current_setting('qa.users_event')::uuid,0,0,10);raise exception 'FAIL other teacher on selected users';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;end $$;
reset role;
select set_config('request.jwt.claim.sub',staff_user::text,true) from qa_ids;
set local role authenticated;
do $$declare q record;begin select * into q from qa_ids;begin perform public.sc_event_check_in(q.school,current_setting('qa.roles_event')::uuid,0,0,10);raise exception 'FAIL staff on teacher role event';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;if exists(select 1 from public.sc_event_attendance where school_id=q.school) then raise exception 'FAIL colleague attendance disclosure';end if;end $$;
reset role;
select 'PASS targeted roles/users, creator exclusion, strict 100m, GPS accuracy, server time, check-out, idempotence, tenant/RLS and unauthorized writes; rolled back' result;
rollback;
