-- Live database regression with isolated random fixtures, always rolled back. No customer records touched.
begin;
create temp table qa_ids as select gen_random_uuid() school,gen_random_uuid() other_school,gen_random_uuid() owner_user,gen_random_uuid() teacher_user,gen_random_uuid() colleague_user,gen_random_uuid() staff_user,gen_random_uuid() class_a,gen_random_uuid() class_b,gen_random_uuid() program,gen_random_uuid() event;
grant select on qa_ids to authenticated;
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at) select u,'authenticated','authenticated',u::text||'@qa.invalid','{}','{}',now(),now() from qa_ids cross join lateral unnest(array[owner_user,teacher_user,colleague_user,staff_user])u;
insert into public.sc_schools(id,name,created_by,is_internal_test) select school,'QA Journal Rollback School',owner_user,true from qa_ids union all select other_school,'QA Other Rollback School',colleague_user,true from qa_ids;
insert into public.sc_members(school_id,user_id,role) select school,owner_user,'owner' from qa_ids union all select school,teacher_user,'teacher' from qa_ids union all select school,colleague_user,'teacher' from qa_ids union all select school,staff_user,'staff' from qa_ids;
insert into public.sc_subscriptions(school_id,status,trial_ends_at,current_period_end) select school,'active',now()+interval '7 days',now()+interval '30 days' from qa_ids;
insert into public.sc_staff(school_id,user_id,name,staff_type) select school,teacher_user,'QA Teacher','teacher' from qa_ids union all select school,colleague_user,'QA Colleague','teacher' from qa_ids union all select school,staff_user,'QA Staff','staff' from qa_ids;
insert into public.sc_classes(id,school_id,name,academic_year) select class_a,school,'QA A','2026/2027' from qa_ids union all select class_b,school,'QA B','2026/2027' from qa_ids;
insert into public.sc_teacher_assignments(school_id,teacher_id,class_id,mode) select school,teacher_user,class_a,'subject' from qa_ids union all select school,colleague_user,class_b,'subject' from qa_ids;
insert into public.sc_students(school_id,class_id,name,nis) select school,class_a,'QA Student '||i,i::text from qa_ids cross join generate_series(1,1005)i;
insert into public.sc_students(school_id,class_id,name,nis) select school,class_b,'QA Other Student','2001' from qa_ids;
insert into public.sc_student_attendance(school_id,student_id,class_id,attendance_date,lesson_key,mark,recorded_by) select s.school_id,s.id,s.class_id,(now() at time zone 'Asia/Jakarta')::date,'Harian',case when s.nis::int<=1001 then 'present' else 'absent' end,q.owner_user from public.sc_students s join qa_ids q on q.school=s.school_id;
insert into public.sc_grades(school_id,student_id,class_id,subject,assessment_name,assessment_date,score,max_score,recorded_by) select s.school_id,s.id,s.class_id,'Matematika','QA Nilai',(now() at time zone 'Asia/Jakarta')::date,40,50,q.owner_user from public.sc_students s join qa_ids q on q.school=s.school_id where s.nis='1';
insert into public.sc_finance_transactions(school_id,occurred_at,kind,category,amount,description,created_by,status) select school,(now() at time zone 'Asia/Jakarta')::date,'income','general',100,'QA Income',owner_user,'posted' from qa_ids union all select school,(now() at time zone 'Asia/Jakarta')::date,'expense','general',30,'QA Expense',owner_user,'posted' from qa_ids union all select school,(now() at time zone 'Asia/Jakarta')::date,'income','general',9000,'QA Voided',owner_user,'void' from qa_ids;
insert into public.sc_programs(id,school_id,title) select program,school,'QA Program' from qa_ids;
insert into public.sc_program_tasks(school_id,program_id,title,created_by) select school,program,'QA Task '||i,owner_user from qa_ids cross join generate_series(1,1005)i;
insert into public.sc_calendar_events(id,school_id,title,event_date,created_by,scope) select event,school,'QA Agenda',(now() at time zone 'Asia/Jakarta')::date,owner_user,'school' from qa_ids;
select set_config('request.jwt.claim.sub',teacher_user::text,true) from qa_ids;
set local role authenticated;
do $$ declare q record; jid uuid; payload jsonb; a jsonb; v date:=(now() at time zone 'Asia/Jakarta')::date;
begin
 select * into q from qa_ids;
 payload:=jsonb_build_object('kind','student','journal_date',v,'title','QA Pengamatan','activity','Pengamatan belajar faktual','class_id',q.class_a,'student_id',(select id from public.sc_students where school_id=q.school and nis='1'),'event_id',q.event,'task_id',(select id from public.sc_program_tasks where school_id=q.school limit 1));
 jid:=public.sc_save_work_journal(q.school,null,payload);perform set_config('qa.journal',jid::text,true);
 if (select count(*) from public.sc_work_journals where id=jid)<>1 then raise exception 'FAIL journal save/RLS';end if;
 begin perform public.sc_save_work_journal(q.school,null,payload||jsonb_build_object('class_id',q.class_b));raise exception 'FAIL cross-class accepted';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin perform public.sc_save_work_journal(q.other_school,null,payload);raise exception 'FAIL other-school accepted';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin perform public.sc_save_work_journal(q.school,null,payload||jsonb_build_object('journal_date',v+1));raise exception 'FAIL future date accepted';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin insert into public.sc_grades(school_id,student_id,class_id,subject,assessment_name,assessment_date,score,max_score,recorded_by) select q.school,id,q.class_a,'QA','Invalid class',v,40,50,q.teacher_user from public.sc_students where school_id=q.school and class_id=q.class_b;raise exception 'FAIL mismatched student grade';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 a:=public.sc_dashboard_analytics(q.school,v,v);
 if (a->'student'->0->>'total')::int<>1005 or (a->'grades'->0->>'average')::numeric<>80 or jsonb_array_length(a->'finance')<>0 or (a->'program'->0->>'count')::int<>1005 then raise exception 'FAIL analytics teacher scope / >1000 / grade normalization / finance privacy: %',a;end if;
 if jsonb_array_length(a->'journals')<>0 then raise exception 'FAIL draft included in dashboard';end if;
 perform public.sc_work_journal_action(q.school,jid,'submit');
 begin perform public.sc_save_work_journal(q.school,jid,payload);raise exception 'FAIL submitted journal edited';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 begin perform public.sc_work_journal_action(q.school,jid,'review','Self review');raise exception 'FAIL teacher self review';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
end $$;
reset role;
select set_config('request.jwt.claim.sub',colleague_user::text,true) from qa_ids;
set local role authenticated;
do $$declare q record;begin select * into q from qa_ids;
 if exists(select 1 from public.sc_work_journals where id=current_setting('qa.journal')::uuid) then raise exception 'FAIL colleague read journal';end if;
 begin perform public.sc_work_journal_action(q.school,current_setting('qa.journal')::uuid,'archive');raise exception 'FAIL colleague changed journal';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
end $$;
reset role;
select set_config('request.jwt.claim.sub',owner_user::text,true) from qa_ids;
set local role authenticated;
do $$declare q record; a jsonb;jid uuid:=current_setting('qa.journal')::uuid; v date:=(now() at time zone 'Asia/Jakarta')::date;begin select * into q from qa_ids;
 perform public.sc_work_journal_action(q.school,jid,'revision','Lengkapi hasil pengamatan');
 if (select status from public.sc_work_journals where id=jid)<>'revision' then raise exception 'FAIL revision';end if;
 a:=public.sc_dashboard_analytics(q.school,v,v);
 if (a->'student'->0->>'total')::int<>1006 or (a->'finance'->0->>'income')::numeric<>100 or (a->'finance'->0->>'expense')::numeric<>30 then raise exception 'FAIL manager analytics %',a;end if;
 begin perform public.sc_dashboard_analytics(q.other_school,v,v);raise exception 'FAIL other-school analytics';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
end $$;
reset role;
select set_config('request.jwt.claim.sub',teacher_user::text,true) from qa_ids;
set local role authenticated;
do $$declare q record; a jsonb;jid uuid:=current_setting('qa.journal')::uuid; v date:=(now() at time zone 'Asia/Jakarta')::date;begin select * into q from qa_ids;
 perform public.sc_save_work_journal(q.school,jid,jsonb_build_object('kind','student','journal_date',v,'title','QA Pengamatan Revisi','activity','Pengamatan dilengkapi hasil faktual','result','Hasil sesuai pengamatan','class_id',q.class_a,'student_id',(select id from public.sc_students where school_id=q.school and nis='1')));
 perform public.sc_work_journal_action(q.school,jid,'submit');
 a:=public.sc_ai_school_context(q.school,v,v);
 if (a->'summary'->'journals'->0->>'student')::int<>1 or a->'summary'?'finance' then raise exception 'FAIL AI summary scope';end if;
end $$;
reset role;
select set_config('request.jwt.claim.sub',owner_user::text,true) from qa_ids;
set local role authenticated;
do $$declare q record;jid uuid:=current_setting('qa.journal')::uuid;begin select * into q from qa_ids;
 perform public.sc_work_journal_action(q.school,jid,'review','Hasil sudah diperiksa');
 perform public.sc_work_journal_action(q.school,jid,'archive');perform public.sc_work_journal_action(q.school,jid,'restore');
 begin perform public.sc_work_journal_action(q.school,jid,'delete','QA permanent deletion');raise exception 'FAIL unarchived delete';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
 perform public.sc_work_journal_action(q.school,jid,'archive');perform public.sc_work_journal_action(q.school,jid,'delete','QA permanent deletion');
 if exists(select 1 from public.sc_work_journals where id=jid) then raise exception 'FAIL permanent delete';end if;
end $$;
reset role;
select set_config('request.jwt.claim.sub',staff_user::text,true) from qa_ids;
set local role authenticated;
do $$declare q record;jid uuid;v date:=(now() at time zone 'Asia/Jakarta')::date;begin select * into q from qa_ids;
 jid:=public.sc_save_work_journal(q.school,null,jsonb_build_object('kind','daily','journal_date',v,'title','QA Jurnal Staf','activity','Kegiatan administrasi staf'));
 perform public.sc_work_journal_action(q.school,jid,'submit');
 begin perform public.sc_ai_school_context(q.school,v,v);raise exception 'FAIL staff AI context accepted';exception when others then if sqlerrm like 'FAIL%' then raise;end if;end;
end $$;
reset role;
-- No authentication may read journal data or execute functions.
select set_config('request.jwt.claim.sub','',true);
set local role anon;
do $$begin begin perform public.sc_dashboard_analytics(gen_random_uuid(),current_date,current_date);raise exception 'FAIL anon analytics';exception when insufficient_privilege then null;end;end $$;
reset role;
select 'PASS journal workflow, relation validation, tenant/role privacy, archived permanent delete, review, staff access, >1000 counts, normalized grades, void exclusion and AI scope. Transaction rolled back.' as result;
rollback;
