"use client";

import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import type {User} from "@supabase/supabase-js";
import {LayoutDashboard,Users,Clock3,Activity,Sparkles,BookOpen,ShieldAlert,HeartHandshake,School as SchoolIcon,ListChecks,Wallet,CreditCard,Settings,Moon,Sun,LogOut,Menu,ChevronRight,Plus,RefreshCw,ReceiptText,CalendarDays,KeyRound} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import StaffWorkflows from "@/components/StaffWorkflows";
import SchoolData from "@/components/SchoolData";
import MasterAdvanced from "@/components/MasterAdvanced";
import MasterHub from "@/components/MasterHub";
import AIWorkbench from "@/components/AIWorkbench";
import DocumentCenter from "@/components/DocumentCenter";
import Supervision from "@/components/Supervision";
import SchoolProfile from "@/components/SchoolProfile";
import CommandBoard from "@/components/CommandBoard";
import FinancePanel from "@/components/FinancePanel";
import PayrollPanel from "@/components/PayrollPanel";
import BKPanel from "@/components/BKPanel";
import AcademicAdvanced from "@/components/AcademicAdvanced";
import DisciplinePanel from "@/components/DisciplinePanel";
import UniversalOrchestrator from "@/components/UniversalOrchestrator";
import PaymentWall from "@/components/PaymentWall";
import BillingPanel from "@/components/BillingPanel";
import PerformanceReviews from "@/components/PerformanceReviews";
import SchoolCalendar from "@/components/SchoolCalendar";
import AccessPanel from "@/components/AccessPanel";
import {modules,canAccess,isAdmin,type School,type Role,type ModuleKey,type Membership,type Staff} from "@/lib/modules";

type SchoolAccess={school:School;role:Role};
type Attendance={id:string;duty_date:string;check_in_at:string|null;check_out_at:string|null;status:string;source:string;user_id:string;notes:string|null};
type RecordItem={id:string;module_key:string;title:string;notes:string|null;status:string;created_at:string};
type Summary={present_days:number;late_days:number;programs:number;trainings:number;verified_events:number};
const icons={overview:LayoutDashboard,master:Users,calendar:CalendarDays,attendance:Clock3,performance:Activity,guru_ai:Sparkles,kepsek_ai:SchoolIcon,buku_kerja:BookOpen,disiplin:ShieldAlert,bk:HeartHandshake,command:ListChecks,sikas:Wallet,gajian:CreditCard,payslip:ReceiptText,access:KeyRound,settings:Settings};
const allowedRecordModules=["guru_ai","kepsek_ai","buku_kerja","disiplin","command","sikas","gajian"];
const formatDate=(s:string|null|undefined)=>s?new Date(s).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"}):"—";
const schoolDay=(tz:string)=>{const p=new Intl.DateTimeFormat("en-US",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const get=(k:string)=>p.find(x=>x.type===k)?.value||"";return get("year")+"-"+get("month")+"-"+get("day")};
function feedback(error:unknown){return error instanceof Error?error.message:String(error)}

export default function Home(){
 const db=useMemo(()=>browserDb(),[]);
 const [mounted,setMounted]=useState(false),[user,setUser]=useState<User|null>(null);
 const [schools,setSchools]=useState<SchoolAccess[]>([]),[schoolId,setSchoolId]=useState(""),[module,setModule]=useState<ModuleKey>("overview");
 const [loading,setLoading]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[register,setRegister]=useState(false);
 const [newSchool,setNewSchool]=useState(""),[inviteCode,setInviteCode]=useState(""),[inviteRole,setInviteRole]=useState<Role>("teacher"),[inviteResult,setInviteResult]=useState("");
 const [theme,setTheme]=useState("light"),[openMenu,setOpenMenu]=useState(false),[expandedNav,setExpandedNav]=useState<ModuleKey|null>(null),[featureFocus,setFeatureFocus]=useState(""),[liveTime,setLiveTime]=useState(new Date());
 const [staff,setStaff]=useState<Staff[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[records,setRecords]=useState<RecordItem[]>([]);
 const [recordTitle,setRecordTitle]=useState(""),[recordNotes,setRecordNotes]=useState(""),[summary,setSummary]=useState<Summary|null>(null),[performanceUser,setPerformanceUser]=useState("");const [ownAttendance,setOwnAttendance]=useState<Attendance|null>(null);
 const [aiPrompt,setAiPrompt]=useState(""),[aiAnswer,setAiAnswer]=useState(""),[subscription,setSubscription]=useState<{status:string;trial_ends_at:string;current_period_end:string|null}|null>(null),[subscriptionSchoolId,setSubscriptionSchoolId]=useState("");
 useEffect(()=>{if(!db||!user)return;void db.rpc("sc_is_platform_admin").then(({data})=>{if(data===true&&window.location.pathname==="/app")window.location.replace("/admin")})},[db,user]);
 const access=schools.find(s=>s.school.id===schoolId); const role=access?.role||"viewer";
 const selected=modules.find(m=>m.key===module)||modules[0]; const visible=modules.filter(m=>canAccess(m,role));
 const isManager=isAdmin(role)||role==="hr";
 useEffect(()=>{setMounted(true);const t=localStorage.getItem("school-control-theme")||"light";setTheme(t);document.body.dataset.theme=t;const id=setInterval(()=>setLiveTime(new Date()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{if(!db)return;void db.auth.getUser().then(({data})=>setUser(data.user)); const {data:{subscription:sub}}=db.auth.onAuthStateChange((_event,session)=>setUser(session?.user||null));return ()=>sub.unsubscribe();},[db]);
 useEffect(()=>{if(!db||!user){setSchools([]);setSchoolId("");return;}let active=true;(async()=>{
 const {data:m,error:e}=await db.from("sc_members").select("school_id,role").eq("user_id",user.id);
 if(e){if(active)setError(e.message);return;} const memberships=(m||[]) as Membership[];
 const {data:s,error:se}=memberships.length?await db.from("sc_schools").select("id,name,timezone").in("id",memberships.map(x=>x.school_id)): {data:[],error:null};
 if(se){if(active)setError(se.message);return;}
 const found=memberships.flatMap(x=>{const sch=(s||[]).find(y=>y.id===x.school_id);return sch?[{school:sch as School,role:x.role}]:[];});
 if(active){setSchools(found);setSchoolId(prev=>found.some(x=>x.school.id===prev)?prev:(found[0]?.school.id||""));}
 })();return ()=>{active=false};},[db,user]);
 useEffect(()=>{if(!db||!schoolId)return;let alive=true;(async()=>{
 const [{data:a},{data:st},{data:sub}]=await Promise.all([
 db.from("sc_attendance").select("id,duty_date,check_in_at,check_out_at,status,source,user_id,notes").eq("school_id",schoolId).order("duty_date",{ascending:false}).limit(30),
 db.from("sc_staff").select("id,school_id,user_id,name,position,shift_start,late_tolerance_minutes").eq("school_id",schoolId).order("name"),
 db.from("sc_subscriptions").select("status,trial_ends_at,current_period_end").eq("school_id",schoolId).maybeSingle()
 ]);if(alive){setAttendance((a||[]) as Attendance[]);setStaff((st||[]) as Staff[]);setSubscription(sub||null);setSubscriptionSchoolId(schoolId);}
 })();return ()=>{alive=false};},[db,schoolId]);
 useEffect(()=>{if(!db||!schoolId||!user)return;let alive=true;(async()=>{const {data}=await db.from("sc_attendance").select("*").eq("school_id",schoolId).eq("user_id",user.id).eq("duty_date",schoolDay(access?.school.timezone||"Asia/Jakarta")).maybeSingle();if(alive)setOwnAttendance((data||null) as Attendance|null);})();return ()=>{alive=false}},[db,schoolId,user,access?.school.timezone]);
 useEffect(()=>{if(!db||!schoolId)return;let alive=true;(async()=>{
 if(allowedRecordModules.includes(module)){const {data,error:e}=await db.from("sc_records").select("id,module_key,title,notes,status,created_at").eq("school_id",schoolId).eq("module_key",module).order("created_at",{ascending:false}).limit(40);if(alive){setRecords((data||[]) as RecordItem[]);if(e)setError(e.message);}}
 if(module==="performance"){const {data,error:e}=await db.rpc("sc_performance_summary",{p_school:schoolId,p_user:performanceUser||user?.id});if(alive){setSummary((data||null) as Summary|null);if(e)setError(e.message);}}
 })();return ()=>{alive=false};},[db,schoolId,module,user,performanceUser]);
 async function refresh(){if(!db||!schoolId)return;const [{data:a},{data:s}]=await Promise.all([db.from("sc_attendance").select("*").eq("school_id",schoolId).order("duty_date",{ascending:false}).limit(30),db.from("sc_staff").select("id,school_id,user_id,name,position,shift_start,late_tolerance_minutes").eq("school_id",schoolId).order("name")]);setAttendance((a||[]) as Attendance[]);setStaff((s||[]) as Staff[]);const day=schoolDay(access?.school.timezone||"Asia/Jakarta");const {data:own}=await db.from("sc_attendance").select("*").eq("school_id",schoolId).eq("user_id",user!.id).eq("duty_date",day).maybeSingle();setOwnAttendance((own||null) as Attendance|null);if(module==="performance"){const {data}=await db.rpc("sc_performance_summary",{p_school:schoolId,p_user:performanceUser||user!.id});setSummary((data||null) as Summary|null)}}
 async function run(job:()=>Promise<void>){setLoading(true);setError("");setMessage("");try{await job()}catch(e){setError(feedback(e))}finally{setLoading(false)}}
 async function auth(){if(!db)return;await run(async()=>{const r=register?await db.auth.signUp({email:email.trim(),password}):await db.auth.signInWithPassword({email:email.trim(),password});if(r.error)throw r.error;if(register&&!r.data.session)setMessage("Akun dibuat. Selesaikan aktivasi bila konfirmasi email masih diwajibkan pada proyek database.");});}
 async function createSchool(){if(!db||!newSchool.trim())return;await run(async()=>{const {error:e}=await db.rpc("sc_create_school",{p_name:newSchool.trim()});if(e)throw e;setNewSchool("");setMessage("Sekolah dan masa uji coba 3 hari telah dibuat.");const {data:m}=await db.from("sc_members").select("school_id,role").eq("user_id",user!.id);const {data:s}=await db.from("sc_schools").select("id,name,timezone");const all=(m||[]).flatMap(x=>{const z=(s||[]).find(y=>y.id===x.school_id);return z?[{school:z as School,role:x.role as Role}]:[]});setSchools(all);if(all.length)setSchoolId(all[all.length-1].school.id);});}
 async function acceptInvite(){if(!db)return;await run(async()=>{const {error:e}=await db.rpc("sc_accept_invite",{p_code:inviteCode.trim()});if(e)throw e;setMessage("Undangan diterima. Muat ulang untuk memilih sekolah.");setInviteCode("");window.location.reload();});}
 async function createInvite(){if(!db)return;await run(async()=>{const {data,error:e}=await db.rpc("sc_create_invite",{p_school:schoolId,p_role:inviteRole});if(e)throw e;setInviteResult(String(data||""));setMessage("Kode undangan sekali pakai dibuat. Bagikan secara pribadi.");});}
 async function selfStaff(){if(!db)return;await run(async()=>{const {error:e}=await db.rpc("sc_ensure_own_staff",{p_school:schoolId});if(e)throw e;await refresh();setMessage("Profil SDM Anda telah diaktifkan.");});}
 async function clock(action:"sc_check_in"|"sc_check_out"){if(!db)return;await run(async()=>{const {error:e}=await db.rpc(action,{p_school:schoolId});if(e)throw e;await refresh();setMessage(action==="sc_check_in"?"Presensi masuk tercatat menggunakan waktu server.":"Presensi pulang tercatat menggunakan waktu server.");});}
 async function createRecord(){if(!db)return;await run(async()=>{const {error:e}=await db.from("sc_records").insert({school_id:schoolId,module_key:module,title:recordTitle.trim(),notes:recordNotes.trim()||null});if(e)throw e;const {data}=await db.from("sc_records").select("id,module_key,title,notes,status,created_at").eq("school_id",schoolId).eq("module_key",module).order("created_at",{ascending:false}).limit(40);setRecords((data||[]) as RecordItem[]);setRecordTitle("");setRecordNotes("");setMessage("Catatan tersimpan pada ruang kerja sekolah.");});}
 async function checkout(plan:"monthly"|"yearly"="monthly"){if(!db)return;await run(async()=>{const {data:{session}}=await db.auth.getSession();if(!session)throw Error("Masuk kembali untuk melanjutkan.");const response=await fetch("/api/billing/checkout",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.access_token},body:JSON.stringify({school_id:schoolId,plan})});const result=await response.json();if(!response.ok||!result.redirect_url)throw Error(result.error||"Checkout belum tersedia.");window.location.assign(result.redirect_url);});}
 async function checkSubscription(){if(!db||!schoolId)return;const {data,error:e}=await db.from("sc_subscriptions").select("status,trial_ends_at,current_period_end").eq("school_id",schoolId).maybeSingle();if(e)setError(e.message);else{setSubscription(data||null);setSubscriptionSchoolId(schoolId);if(data?.status==="active"&&data.current_period_end&&Date.parse(data.current_period_end)>Date.now())setMessage("Langganan aktif. Selamat kembali!")}}
 async function askAI(){if(!db)return;await run(async()=>{const {data:{session}}=await db.auth.getSession();if(!session)throw Error("Sesi berakhir. Silakan masuk kembali.");const response=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.access_token},body:JSON.stringify({school_id:schoolId,module,prompt:aiPrompt})});const result=await response.json();if(!response.ok)throw Error(result.error||"Asisten belum tersedia.");setAiAnswer(result.text||"Tidak ada jawaban.");});}
 function changeTheme(){const next=theme==="light"?"dark":"light";setTheme(next);document.body.dataset.theme=next;localStorage.setItem("school-control-theme",next);}
 function choose(m:ModuleKey,feature=""){setModule(m);setFeatureFocus(feature);setExpandedNav(m);setOpenMenu(false);setError("");setMessage("");}
 if(!mounted)return <div className="authwrap"><div className="panel">Memuat School Control…</div></div>;
 if(!db)return <div className="authwrap"><div className="authbox panel"><img width="48" src="/school-control-mark.svg" alt="School Control"/><h1>School Control</h1><p>Fondasi aplikasi siap. Hubungkan proyek Supabase khusus melalui environment Vercel untuk mengaktifkan login dan penyimpanan nyata.</p><p className="hint">NEXT_PUBLIC_SUPABASE_URL dan NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY belum terisi. Mode data palsu sengaja tidak disediakan.</p></div></div>;
 if(!user)return <div className="authwrap"><div className="authbox"><div className="flow"><img width="47" src="/school-control-mark.svg" alt=""/><div><h1>School Control</h1><small>Satu Sistem, Semua Urusan Sekolah</small></div></div><div className="panel"><h2>{register?"Daftarkan akun utama":"Masuk ke sekolah"}</h2><p className="muted">Satu akun sekolah, akses masing-masing pengguna, data tetap terpisah.</p><form className="fields" onSubmit={e=>{e.preventDefault();void auth()}}><label className="field full">Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field full">Kata sandi<input type="password" autoComplete={register?"new-password":"current-password"} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="button" disabled={loading}>{loading?"Mohon tunggu…":register?"Daftar":"Masuk"}</button><button className="button secondary" type="button" onClick={()=>setRegister(!register)}>{register?"Sudah punya akun? Masuk":"Belum punya akun? Daftar"}</button></form>{error&&<p className="banner error">{error}</p>}{message&&<p className="banner success">{message}</p>}</div></div></div>;
 if(!schoolId)return <div className="authwrap"><div className="authbox"><div className="flow"><img width="46" src="/school-control-mark.svg" alt=""/><h1>Mulai School Control</h1></div><div className="panel"><h2>Buat sekolah</h2><p className="muted">Masa uji coba 3 hari diaktifkan otomatis. Anda menjadi pemilik akun utama.</p><form className="fields" onSubmit={e=>{e.preventDefault();void createSchool()}}><label className="field full">Nama sekolah<input required value={newSchool} maxLength={120} onChange={e=>setNewSchool(e.target.value)}/></label><button className="button" disabled={loading}>Buat Sekolah</button></form><h3 style={{marginTop:28}}>Sudah diundang?</h3><form className="fields" onSubmit={e=>{e.preventDefault();void acceptInvite()}}><label className="field full">Kode undangan<input required value={inviteCode} onChange={e=>setInviteCode(e.target.value)}/></label><button className="button secondary" disabled={loading}>Gabung Sekolah</button></form><div className="flow" style={{marginTop:20}}><button className="iconbutton" onClick={()=>void db.auth.signOut()}>Keluar</button></div>{error&&<p className="banner error">{error}</p>}{message&&<p className="banner success">{message}</p>}</div></div></div>;
 const trialExpired=subscription?.status==="trial" && new Date(subscription.trial_ends_at).getTime()<=Date.now();const myStaff=staff.find(s=>s.user_id===user.id);const myAttendance=ownAttendance;const today=new Date().toLocaleDateString("id-ID",{timeZone:access?.school.timezone||"Asia/Jakarta"});
 const sections=[...new Set(visible.map(m=>m.section))];
 const Nav=({mobile=false}:{mobile?:boolean})=><>{sections.map(section=><div key={section}><div className="navgroup">{section}</div>{visible.filter(m=>m.section===section).map(m=>{const Icon=icons[m.key];const expanded=expandedNav===m.key;return <div className="navitem" key={m.key}><button className={"navbtn "+(module===m.key?"active":"")} onClick={()=>{if(module===m.key)setExpandedNav(expanded?null:m.key);else choose(m.key)}}><Icon size={18}/><span>{m.label}</span><ChevronRight className={"navchev "+(expanded?"open":"")} size={14}/></button>{expanded&&m.features.length>0&&<div className="navchildren">{m.features.map(f=><button key={f} className={module===m.key&&featureFocus===f?"active":""} onClick={()=>choose(m.key,f)}>{f}</button>)}</div>}</div>})}</div>)}</>;
 if(subscriptionSchoolId!==schoolId)return <div className="authwrap"><div className="panel">Memeriksa status langganan sekolah…</div></div>;
 const subscriptionOpen=!!subscription&&((subscription.status==="trial"&&Date.parse(subscription.trial_ends_at)>Date.now())||(subscription.status==="active"&&!!subscription.current_period_end&&Date.parse(subscription.current_period_end)>Date.now()));
 if(!subscriptionOpen)return <div><div className="flow" style={{justifyContent:"space-between",padding:"16px 22px"}}><Link href="/" className="lp-brand"><img src="/school-control-mark.svg" alt="" width={35} height={35}/><strong>School Control</strong></Link><button className="button secondary" onClick={()=>void db.auth.signOut()}>Keluar</button></div>{error&&<div className="banner error" role="alert">{error}</div>}<PaymentWall schoolName={access?.school.name||"Sekolah"} trialEnd={subscription?.trial_ends_at||new Date().toISOString()} status={subscription?.status||"unknown"} owner={role==="owner"} busy={loading} onCheckout={plan=>void checkout(plan)} onRefresh={()=>void checkSubscription()}/></div>;
 return <div className="shell">
  <aside className="side"><div className="brand"><img src="/school-control-mark.svg" alt=""/><div><strong>School Control</strong><small>Satu Sistem, Semua Urusan Sekolah</small></div></div><Nav/></aside>
  <main className="main"><header className="top"><div><small>{access?.school.name} · {role.replaceAll("_"," ")}</small><h1>{selected.label}</h1></div><div className="actions"><button className="iconbutton" aria-label="Ganti tema" onClick={changeTheme}>{theme==="light"?<Moon size={17}/>:<Sun size={17}/>}</button><button className="iconbutton" aria-label="Segarkan" onClick={()=>void refresh()}><RefreshCw size={17}/></button><button className="iconbutton" aria-label="Keluar" onClick={()=>void db.auth.signOut()}><LogOut size={17}/></button></div></header>
  <div className="content">{error&&<div role="alert" className="banner error">{error}</div>}{message&&<div role="status" className="banner success">{message}</div>}<div className="featurebar">{selected.features.map(feature=><button key={feature} className={featureFocus===feature?"active":""} onClick={()=>setFeatureFocus(feature)}>{feature}</button>)}</div>
  {module==="overview"&&<><div className="banner">Satu sekolah, satu ruang kerja. <b>{trialExpired?"Uji coba berakhir":subscription?.status==="trial"?"Uji coba aktif":subscription?.status||"Status langganan belum tersedia"}</b>{subscription?.status==="trial"?" · Berakhir "+formatDate(subscription.trial_ends_at):""}.</div><UniversalOrchestrator role={role} onRoute={choose}/><div className="grid"><div className="card"><label>SDM</label><strong>{staff.length}</strong></div><div className="card"><label>Presensi</label><strong>{attendance.length}</strong></div><div className="card"><label>Profil</label><strong>{myStaff?"Aktif":"Belum"}</strong></div><div className="card"><label>Peran</label><strong style={{fontSize:20}}>{role.replaceAll("_"," ")}</strong></div></div><SchoolCalendar schoolId={schoolId} userId={user.id} role={role} compact/><div className="intro"><section className="panel"><h2>Mulai presensi pribadi</h2><p>Kehadiran masuk dan pulang dicatat otomatis berdasarkan waktu server. Riwayat dipakai sebagai salah satu bukti evaluasi, bukan satu-satunya penilaian.</p><button className="button" onClick={()=>choose("attendance")}>Buka Presensi <ChevronRight size={13}/></button></section><section className="panel"><h2>Program & pengelolaan sekolah</h2><p>Susun program, PIC, pembelajaran, keuangan dan laporan pada satu struktur data yang konsisten.</p><button className="button secondary" onClick={()=>choose("command")}>Buka Program & Tugas <ChevronRight size={13}/></button></section></div></>}
  {module==="master"&&<MasterHub schoolId={schoolId} role={role} focus={featureFocus}/>}\n  {module==="calendar"&&<SchoolCalendar schoolId={schoolId} userId={user.id} role={role}/>}
  {module==="attendance"&&<>
 {(!featureFocus||featureFocus==="Check-in/check-out")&&<section className="panel"><div className="flow" style={{justifyContent:"space-between"}}><div><h2>Presensi Realtime</h2><strong className="live-clock">{liveTime.toLocaleTimeString("id-ID",{timeZone:access?.school.timezone||"Asia/Jakarta",hour:"2-digit",minute:"2-digit",second:"2-digit"})}</strong></div><span className="pill">{myAttendance?.status||"Belum presensi"}</span></div>{!myStaff?<div className="banner">Profil SDM belum terhubung. Buka Data Induk → Guru & tenaga kependidikan.</div>:<div className="grid" style={{gridTemplateColumns:"repeat(2,minmax(0,1fr))",marginBottom:16}}><div className="card"><label>Jam masuk</label><strong style={{fontSize:23}}>{myAttendance?.check_in_at?formatDate(myAttendance.check_in_at):"—"}</strong></div><div className="card"><label>Jam pulang</label><strong style={{fontSize:23}}>{myAttendance?.check_out_at?formatDate(myAttendance.check_out_at):"—"}</strong></div></div>}<div className="flow"><button className="button" disabled={loading||!myStaff||!!myAttendance?.check_in_at} onClick={()=>void clock("sc_check_in")}>Absen Masuk</button><button className="button secondary" disabled={loading||!myAttendance?.check_in_at||!!myAttendance?.check_out_at} onClick={()=>void clock("sc_check_out")}>Absen Pulang</button></div></section>}
 {(!featureFocus||featureFocus==="Riwayat kehadiran")&&<section className="panel"><h2>Riwayat Kehadiran {isManager?"Sekolah":"Pribadi"}</h2><div className="tablewrap"><table className="data-table"><thead><tr><th>Tanggal</th><th>Masuk</th><th>Pulang</th><th>Status</th></tr></thead><tbody>{attendance.map(a=><tr key={a.id}><td>{a.duty_date}</td><td>{formatDate(a.check_in_at)}</td><td>{formatDate(a.check_out_at)}</td><td><span className="pill">{a.status}</span></td></tr>)}</tbody></table>{!attendance.length&&<div className="empty">Belum ada presensi tercatat.</div>}</div></section>}
 {(!featureFocus||featureFocus==="Jadwal/shift")&&<StaffWorkflows kind="staff" schoolId={schoolId} userId={user.id} role={role} staff={staff} onChanged={refresh}/>}
 {(!featureFocus||featureFocus==="Koreksi beralasan")&&<StaffWorkflows kind="attendance" schoolId={schoolId} userId={user.id} role={role} staff={staff} onChanged={refresh}/>}
 {(!featureFocus||featureFocus==="Izin"||featureFocus==="Cuti")&&<StaffWorkflows kind="leave" schoolId={schoolId} userId={user.id} role={role} staff={staff} onChanged={refresh}/>}
 </>}
 {module==="performance"&&<>
 {(!featureFocus||featureFocus==="Kehadiran")&&<><div className="banner">Rekap faktual untuk pembinaan dan evaluasi. Tidak ada skor otomatis yang menentukan baik/buruknya seorang guru.</div>{isManager&&<div className="panel"><label className="field">Lihat rekap SDM<select value={performanceUser} onChange={e=>setPerformanceUser(e.target.value)}><option value="">Diri sendiri</option>{staff.filter(x=>x.user_id&&x.user_id!==user.id).map(x=><option key={x.id} value={x.user_id!}>{x.name}</option>)}</select></label></div>}<div className="grid"><div className="card"><label>Hari hadir tercatat</label><strong>{summary?.present_days??"—"}</strong></div><div className="card"><label>Hari terlambat pribadi</label><strong>{summary?.late_days??"—"}</strong></div><div className="card"><label>Partisipasi program</label><strong>{summary?.programs??"—"}</strong></div><div className="card"><label>Pelatihan</label><strong>{summary?.trainings??"—"}</strong></div></div></>}
 {(!featureFocus||["Partisipasi program","Pelatihan","Bukti capaian"].includes(featureFocus))&&<StaffWorkflows kind="performance" schoolId={schoolId} userId={user.id} role={role} staff={staff} onChanged={refresh}/>}
 {(!featureFocus||["Evaluasi","Tanggapan guru"].includes(featureFocus))&&<PerformanceReviews schoolId={schoolId} userId={user.id} role={role} staff={staff} focus={featureFocus}/>}
 </>}
 {module==="access"&&<AccessPanel schoolId={schoolId} role={role}/>}\n {module==="settings"&&<>
 {(!featureFocus||["Langganan","Riwayat pembayaran"].includes(featureFocus))&&<section className="panel"><h2>Workspace & Langganan</h2><div className="fields"><label className="field">Pilih sekolah<select value={schoolId} onChange={e=>setSchoolId(e.target.value)}>{schools.map(x=><option key={x.school.id} value={x.school.id}>{x.school.name}</option>)}</select></label><div><span className="pill">{subscription?.status||"Belum aktif"}</span><p className="hint">Akhir masa uji coba: {formatDate(subscription?.trial_ends_at)}</p></div></div><div className="flow"><button className="button secondary" onClick={changeTheme}>{theme==="light"?"Aktifkan Mode Gelap":"Aktifkan Mode Terang"}</button>{role==="owner"&&<button className="button" disabled={loading} onClick={()=>void checkout("monthly")}>Perpanjang Langganan</button>}</div></section>}
 {(!featureFocus||featureFocus==="Undang anggota")&&isAdmin(role)&&<section className="panel"><h2>Undang Anggota</h2><div className="fields"><label className="field">Peran<select value={inviteRole} onChange={e=>setInviteRole(e.target.value as Role)}>{(["principal","vice_principal","teacher","counselor","hr","treasurer","staff","viewer"] as Role[]).map(x=><option key={x} value={x}>{x}</option>)}</select></label><button className="button" disabled={loading} onClick={()=>void createInvite()}>Buat Undangan</button></div>{inviteResult&&<div className="banner"><b>Kode sekali pakai:</b> <code style={{overflowWrap:"anywhere"}}>{inviteResult}</code></div>}</section>}
 {(!featureFocus||["Profil sekolah","Memori sekolah"].includes(featureFocus))&&<SchoolProfile schoolId={schoolId} role={role} focus={featureFocus}/>}
 {(!featureFocus||["Langganan","Riwayat pembayaran"].includes(featureFocus))&&<BillingPanel schoolId={schoolId} isOwner={role==="owner"} busy={loading} onCheckout={plan=>void checkout(plan)} focus={featureFocus}/>}
 </>}
 {module==="guru_ai"&&<><AIWorkbench module="guru_ai" schoolId={schoolId} focus={featureFocus}/>{(!featureFocus||featureFocus!=="Riwayat draf")&&<DocumentCenter schoolId={schoolId} userId={user.id} role={role} teacherOnly focus={featureFocus}/>}</>}
  {module==="kepsek_ai"&&<>
 {(!featureFocus||["PBD/EDS","KSP/KOSP","RKJM","RKT","RKAS","SOP"].includes(featureFocus))&&<AIWorkbench module="kepsek_ai" schoolId={schoolId} focus={featureFocus}/>}
 {(!featureFocus||["PBD/EDS","KSP/KOSP","RKJM","RKT","RKAS","SOP","Pusat dokumen","Persetujuan dokumen"].includes(featureFocus))&&<DocumentCenter schoolId={schoolId} userId={user.id} role={role} focus={featureFocus}/>}
 {(!featureFocus||featureFocus==="Supervisi guru")&&<Supervision schoolId={schoolId} role={role} staff={staff} userId={user.id}/>}
 {!featureFocus&&<SchoolProfile schoolId={schoolId} role={role}/>}
 </>}
 {module==="buku_kerja"&&<><SchoolData mode="academic" schoolId={schoolId} userId={user.id} role={role} focus={featureFocus}/><AcademicAdvanced schoolId={schoolId} userId={user.id} role={role} focus={featureFocus}/></>}
  {module==="disiplin"&&<DisciplinePanel schoolId={schoolId} userId={user.id} role={role} focus={featureFocus}/>}
  {module==="command"&&<CommandBoard schoolId={schoolId} userId={user.id} role={role} staff={staff} focus={featureFocus}/>}
  {module==="sikas"&&<FinancePanel schoolId={schoolId} userId={user.id} focus={featureFocus}/>}
  {module==="gajian"&&<PayrollPanel schoolId={schoolId} role={role} staff={staff} focus={featureFocus}/>}
  {module==="payslip"&&<PayrollPanel schoolId={schoolId} role={role} staff={staff} selfOnly focus={featureFocus}/>}
  {module==="bk"&&<>{role==="counselor"?<BKPanel schoolId={schoolId} userId={user.id} focus={featureFocus}/>:<section className="panel"><h2>Bimbingan Konseling</h2><div className="banner">Data kasus hanya dibuka untuk Guru BK.</div></section>}</>}
  </div></main>
  {openMenu&&<div className="mobiledrawer"><div className="panel"><div className="flow" style={{justifyContent:"space-between"}}><strong>Semua fitur</strong><button className="iconbutton" onClick={()=>setOpenMenu(false)}>Tutup</button></div><Nav mobile/></div></div>}
  <nav className="bottomnav" aria-label="Navigasi utama">{(["overview","calendar","attendance","master"] as ModuleKey[]).map(k=>{const Icon=icons[k];return <button key={k} className={module===k?"active":""} onClick={()=>choose(k)}><Icon size={20}/>{modules.find(x=>x.key===k)?.label}</button>})}<button onClick={()=>setOpenMenu(true)}><Menu size={20}/>Menu</button></nav>
 </div>;
}
