import Link from "next/link";
import {ArrowRight,ArrowUpRight,BookOpenCheck,BriefcaseBusiness,CalendarCheck2,Check,ChevronRight,ClipboardCheck,GraduationCap,HeartHandshake,Layers3,LockKeyhole,Menu,ShieldCheck,Sparkles,UsersRound,WalletCards,Clock3,FileText,Quote,Smartphone,Headphones,CheckCircle2} from "lucide-react";
import {plans,rupiah} from "@/lib/pricing";
import "./landing.css";
const services=[
 {icon:GraduationCap,title:"Perangkat Ajar AI",desc:"Rancang bahan ajar, LKPD, modul dan asesmen melalui satu ruang kerja."},
 {icon:BookOpenCheck,title:"Pembelajaran & Penilaian",desc:"Jurnal, presensi, nilai dan rekap kelas mengikuti data induk yang sama."},
 {icon:ClipboardCheck,title:"Disiplin & Prestasi",desc:"Kejadian, prestasi, pembinaan dan tindak lanjut siswa terdokumentasi."},
 {icon:HeartHandshake,title:"Bimbingan Konseling",desc:"Layanan konseling privat, riwayat layanan, dan tindak lanjut terbatas konselor."},
 {icon:Layers3,title:"Program, Tugas & Agenda",desc:"Program sekolah, PIC, tenggat, notula dan bukti kegiatan terkumpul."},
 {icon:WalletCards,title:"Keuangan & Tagihan",desc:"Kas, rekening, anggaran, pembayaran dan laporan transaksi sekolah."},
 {icon:BriefcaseBusiness,title:"Presensi, SDM & Payroll",desc:"Presensi pribadi guru, cuti, kinerja, payroll dan slip gaji privat."},
 {icon:Sparkles,title:"Perencanaan & Supervisi",desc:"Pendamping penyusunan PBD, KSP/KOSP, RKT, RKAS dan supervisi."}
];
const steps=[["01","Daftarkan sekolah","Buat akun utama dan workspace sekolah baru. Tidak perlu memindahkan data dari aplikasi sebelumnya."],["02","Nikmati 7 hari gratis","Jelajahi modul, tambah anggota, isi data pertama dan coba alur kerja. Tanpa kartu pembayaran."],["03","Lanjutkan School Control Pro","Seluruh data tetap tersimpan saat trial berakhir. Perpanjang untuk melanjutkan kegiatan sekolah."]];
const faq=[
 ["Apakah harus berlangganan sebelum mencoba?","Tidak. Sekolah baru mendapatkan akses uji coba 7 hari sejak workspace dibuat. Setelah itu pemilik sekolah bisa memilih paket bulanan atau tahunan."],
 ["Berapa akun yang didapat satu sekolah?","Satu sekolah menggunakan satu akun utama untuk berlangganan. Kepala sekolah dapat mengundang anggota dengan akun pribadi serta peran berbeda."],
 ["Apakah data BK bisa dibaca semua guru?","Tidak. Catatan dan penanganan konseling dibatasi kepada konselor berwenang. Manajemen hanya menerima ringkasan agregat."],
 ["Apakah setelah trial data sekolah terhapus?","Tidak. Data yang sudah dicatat tetap disimpan. Operasional berbayar hanya dapat dilanjutkan setelah langganan aktif."],
 ["Apakah pembayaran per guru?","Tidak. Paket dihitung per workspace sekolah, bukan per guru. Penggunaan dan kuota fitur AI tetap mengikuti kebijakan paket."],
 ["Bisa dipakai melalui HP?","Bisa. School Control didesain responsif untuk desktop, tablet dan ponsel."] 
];
export default function Landing(){
 return <div className="lp">
 <header className="lp-header"><div className="lp-container lp-nav"><Link className="lp-brand" href="https://school-control-pro.vercel.app/" aria-label="Beranda School Control"><img src="/school-control-mark.svg" alt="" width="38" height="38"/><span><b>School Control</b><small>School Management Platform</small></span></Link><nav aria-label="Navigasi website" className="lp-navlinks"><a href="#fitur">Fitur</a><a href="#cara-kerja">Cara Kerja</a><a href="#harga">Harga</a><a href="#faq">FAQ</a></nav><div className="lp-nav-cta"><Link href="https://school-control-pro.vercel.app/masuk" className="lp-login">Masuk</Link><Link href="https://school-control-pro.vercel.app/daftar" className="lp-btn lp-btn-sm">Coba Gratis <ArrowUpRight size={15}/></Link></div></div></header>
 <main>
 <section className="lp-hero"><div className="lp-container lp-hero-grid"><div className="lp-hero-copy"><div className="lp-eyebrow"><span className="lp-live"/> WORKSPACE DIGITAL UNTUK SEKOLAH</div><h1>Sekolah terkelola.<br/><em>Semua dalam</em><br/>satu kendali.</h1><p>Administrasi guru, pembelajaran, kesiswaan, program kerja, keuangan, SDM, dokumen dan AI bekerja dalam satu sistem dengan data induk yang sama.</p><div className="lp-hero-actions"><Link className="lp-btn" href="https://school-control-pro.vercel.app/daftar">Mulai Gratis 7 Hari <ArrowRight size={19}/></Link><a href="#fitur" className="lp-btn-ghost">Lihat Semua Fitur <ChevronRight size={17}/></a></div><div className="lp-hero-perks"><span><Check size={15}/> Tidak perlu kartu kredit</span><span><Check size={15}/> Satu langganan per sekolah</span></div></div><div className="lp-hero-visual"><div className="lp-photo"><img src="https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=1200&q=85" alt="Lingkungan pembelajaran di sekolah"/></div><div className="lp-dashboard"><div className="lp-dash-top"><span className="lp-dash-dot"/><span className="lp-dash-dot"/><span className="lp-dash-dot"/><small>School Control · Preview</small></div><div className="lp-dash-inner"><div className="lp-dash-bar"><div className="lp-dash-logo">SC</div><div><b>Dashboard Sekolah</b><span>Ringkasan ruang kerja</span></div><span className="lp-pill">Aktif</span></div><div className="lp-dash-cards"><div><small>Guru & Staf</small><b>SDM</b><span>Kelola kehadiran</span></div><div><small>Program Sekolah</small><b>PIC</b><span>Pantau progres</span></div><div><small>Keuangan</small><b>Kas</b><span>Rekap terpusat</span></div></div><div className="lp-chart"><div className="lp-chart-line"/><div className="lp-chart-line lp-chart-line2"/><div className="lp-chart-line lp-chart-line3"/><div className="lp-chart-line lp-chart-line4"/><div className="lp-chart-line lp-chart-line5"/><div className="lp-chart-caption"><span>Aktivitas sekolah</span><b>Terintegrasi</b></div></div><div className="lp-dash-footer"><span><CalendarCheck2 size={16}/> Presensi & Jadwal</span><span><ShieldCheck size={16}/> Akses berdasarkan peran</span></div></div></div><div className="lp-float lp-float-1"><CheckCircle2 size={23}/><span><b>Semua saling terhubung</b><small>Tanpa input berulang</small></span></div><div className="lp-float lp-float-2"><Sparkles size={20}/><span><b>Asisten AI</b><small>Perencanaan lebih ringkas</small></span></div></div></div></section>
 <section className="lp-trust"><div className="lp-container lp-trust-inner"><span>DIRANCANG UNTUK</span><b>Kepala Sekolah</b><b>Guru & Wali Kelas</b><b>Tim BK</b><b>Bendahara</b><b>Manajemen SDM</b></div></section>
 <section className="lp-section" id="fitur"><div className="lp-container"><div className="lp-section-head"><span className="lp-kicker">SATU EKOSISTEM</span><h2>Berbagai kebutuhan sekolah.<br/><em>Satu aplikasi yang rapi.</em></h2><p>Tidak perlu berpindah dari aplikasi satu ke aplikasi lain. Modul memakai identitas sekolah, siswa dan tenaga pendidik yang konsisten.</p></div><div className="lp-services">{services.map(({icon:Icon,title,desc},i)=><article className="lp-service" key={title}><div className="lp-service-icon"><Icon size={23}/></div><div className="lp-service-number">0{i+1}</div><h3>{title}</h3><p>{desc}</p><span>Terhubung ke data induk <ArrowUpRight size={15}/></span></article>)}</div></div></section>
 <section className="lp-feature-band"><div className="lp-container lp-feature-layout"><div className="lp-feature-photo"><img src="/school-learning-illustration.svg" alt="Lingkungan pendidikan dan pembelajaran"/><div className="lp-feature-chip"><Clock3 size={20}/> Presensi mandiri setiap guru</div></div><div className="lp-feature-text"><span className="lp-kicker">LEBIH DARI SEKADAR ADMINISTRASI</span><h2>Setiap pekerjaan tercatat. Setiap progres terlihat.</h2><p>Dari guru masuk sekolah hingga pelaksanaan program tahunan, semua dapat ditelusuri sesuai hak akses setiap pengguna.</p><div className="lp-feature-list"><div><CalendarCheck2/><span><b>Presensi guru pribadi</b><small>Check-in dan check-out menggunakan waktu server, jadwal, cuti, serta riwayat nyata.</small></span></div><div><FileText/><span><b>Dokumen dan laporan</b><small>Catatan program, supervisi dan rancangan dokumen dikelola dalam satu workspace.</small></span></div><div><LockKeyhole/><span><b>Data privat per sekolah</b><small>Setiap sekolah memiliki ruang data sendiri dengan akses sesuai jabatan.</small></span></div></div><Link className="lp-btn lp-btn-ink" href="https://school-control-pro.vercel.app/daftar">Coba di Sekolah Saya <ArrowRight size={18}/></Link></div></div></section>
 <section className="lp-section lp-how" id="cara-kerja"><div className="lp-container"><div className="lp-section-head"><span className="lp-kicker">MULAI TANPA RIBET</span><h2>Mulai menggunakan<br/><em>dalam tiga langkah.</em></h2></div><div className="lp-steps">{steps.map(([num,title,desc])=><div className="lp-step" key={num}><span>{num}</span><h3>{title}</h3><p>{desc}</p></div>)}</div></div></section>
 <section className="lp-section lp-price-section" id="harga"><div className="lp-container"><div className="lp-section-head"><span className="lp-kicker">HARGA YANG MUDAH DIPAHAMI</span><h2>Satu sekolah.<br/><em>School Control Pro.</em></h2><p>Coba seluruh ruang kerja selama 7 hari. Pilih paket untuk melanjutkan setelah masa uji coba, tanpa kehilangan catatan yang sudah dibuat.</p></div><div className="lp-price-grid"><div className="lp-price-card"><div className="lp-plan-head"><span>FLEKSIBEL</span><h3>Bulanan</h3><p>Untuk sekolah yang ingin memulai secara bertahap.</p></div><div className="lp-price">{rupiah(plans.monthly.price)}<small>/30 hari</small></div><div className="lp-plan-perks"><span><Check/> Semua modul terintegrasi</span><span><Check/> Template laporan milik sekolah</span><span><Check/> Undang anggota per peran</span><span><Check/> 200 generator AI per bulan</span></div><Link className="lp-btn lp-btn-outline" href="https://school-control-pro.vercel.app/daftar?paket=monthly">Mulai Uji Coba <ArrowRight size={17}/></Link></div><div className="lp-price-card lp-price-featured"><span className="lp-popular">NILAI LEBIH UNTUK SEKOLAH</span><div className="lp-plan-head"><span>TAHUNAN</span><h3>Tahunan</h3><p>Hemat setara 2 bulan; fitur sama dengan bulanan.</p></div><div className="lp-price">{rupiah(plans.yearly.price)}<small>/365 hari</small></div><div className="lp-plan-perks"><span><Check/> Semua fitur paket bulanan</span><span><Check/> Masa aktif 365 hari</span><span><Check/> Satu workspace sekolah</span><span><Check/> Kelanjutan seluruh riwayat kerja</span></div><Link className="lp-btn lp-btn-white" href="https://school-control-pro.vercel.app/daftar?paket=yearly">Coba Gratis 7 Hari <ArrowRight size={17}/></Link></div></div><p className="lp-price-note">Satu paket per sekolah. Trial 7 hari mencakup 15 permintaan generator AI. Kuota berlangganan 200 permintaan per bulan kalender UTC, dipakai bersama anggota sekolah. Pembayaran baru diproses setelah pengguna memilih paket dan mengonfirmasi transaksi.</p></div></section>
 <section className="lp-section lp-faq" id="faq"><div className="lp-container lp-faq-grid"><div><span className="lp-kicker">PERTANYAAN UMUM</span><h2>Yang sering<br/><em>ditanyakan.</em></h2><p>Informasi dasar penggunaan, uji coba, akun tim dan privasi data sekolah.</p><Link className="lp-btn-ghost" href="https://school-control-pro.vercel.app/daftar">Daftarkan sekolah <ArrowRight size={17}/></Link></div><div>{faq.map(([q,a])=><details className="lp-faq-item" key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>
 <section className="lp-cta"><div className="lp-container lp-cta-inner"><div><span className="lp-kicker">SAATNYA SEKOLAH LEBIH TERKELOLA</span><h2>Mulai dari sekolah Anda.<br/>Beres dalam satu kendali.</h2><p>Gunakan gratis selama 7 hari. Masukkan data sekolah Anda sendiri dan jelajahi semua modul dalam satu workspace.</p></div><Link className="lp-btn lp-btn-white" href="https://school-control-pro.vercel.app/daftar">Daftar Gratis Sekarang <ArrowUpRight size={19}/></Link></div></section>
 </main><footer className="lp-footer"><div className="lp-container"><div className="lp-footer-top"><div><Link className="lp-brand" href="https://school-control-pro.vercel.app/"><img src="/school-control-mark.svg" alt="" width="38" height="38"/><span><b>School Control</b><small>School Management Platform</small></span></Link><p>Platform terpadu untuk membantu sekolah menyelenggarakan administrasi, pembelajaran dan manajemen tim dengan lebih rapi.</p></div><div><strong>Jelajahi</strong><a href="#fitur">Fitur Aplikasi</a><a href="#cara-kerja">Cara Kerja</a><a href="#harga">Berlangganan</a><a href="#faq">FAQ</a></div><div><strong>Akun</strong><Link href="https://school-control-pro.vercel.app/masuk">Masuk</Link><Link href="https://school-control-pro.vercel.app/daftar">Daftar Sekolah</Link><Link href="https://school-control-pro.vercel.app/app">Workspace Sekolah</Link></div></div><div className="lp-footer-bottom"><span>© {new Date().getFullYear()} School Control. Seluruh hak dilindungi.</span><span><ShieldCheck size={15}/> Akses data berdasarkan peran dan sekolah</span></div></div></footer>
 </div>;
}
