"use client";
import {useEffect,useMemo,useState} from "react";
import {Download,FileSpreadsheet,Plus,Save,Sparkles,Trash2,Upload} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import {downloadExcel,readExcel} from "@/lib/excel";
import {issueAndExport,loadReportIdentity,previewOfficialReport,type OfficialReportModel} from "@/lib/report-engine";
import type {Role} from "@/lib/modules";

type Assignment={id:string;teacher_id:string;class_id:string;subject_id:string|null;mode:string};
type C={id:string;name:string;grade:string|null};
type Subject={id:string;name:string};
type Schedule={id:string;assignment_id:string;weekday:number;starts_at:string;ends_at:string;room:string|null;note:string|null;active:boolean};
type Pref={mode:string};
const DAYS=["Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu"];
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"});
export default function AcademicLegacyParity({schoolId,userId,role,focus}:{schoolId:string;userId:string;role:Role;focus:string}){
 const db=useMemo(()=>browserDb(),[]),[assignments,setAssignments]=useState<Assignment[]>([]),[classes,setClasses]=useState<C[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]);
 const [mode,setMode]=useState("gabungan"),[assignmentId,setAssignmentId]=useState(""),[weekday,setWeekday]=useState(1),[start,setStart]=useState("07:00"),[end,setEnd]=useState("08:00"),[room,setRoom]=useState(""),[note,setNote]=useState("");
 const [assistant,setAssistant]=useState(""),[answer,setAnswer]=useState(""),[month,setMonth]=useState(today().slice(0,7)),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const manager=["owner","principal","vice_principal"].includes(role);
 async function load(){if(!db)return;const [a,c,s,sc,p]=await Promise.all([
  db.from("sc_teacher_assignments").select("id,teacher_id,class_id,subject_id,mode").eq("school_id",schoolId).order("created_at"),
  db.from("sc_classes").select("id,name,grade").eq("school_id",schoolId).order("name"),
  db.from("sc_subjects").select("id,name").eq("school_id",schoolId).order("name"),
  db.from("sc_teacher_schedules").select("id,assignment_id,weekday,starts_at,ends_at,room,note,active").eq("school_id",schoolId).order("weekday").order("starts_at"),
  db.from("sc_teacher_preferences").select("mode").eq("school_id",schoolId).eq("user_id",userId).maybeSingle()
 ]);setAssignments((a.data||[]) as Assignment[]);setClasses((c.data||[]) as C[]);setSubjects((s.data||[]) as Subject[]);setSchedules((sc.data||[]) as Schedule[]);if(p.data?.mode)setMode(p.data.mode);if(!assignmentId){const mine=(a.data||[]).find((x:any)=>x.teacher_id===userId)||(a.data||[])[0];if(mine)setAssignmentId(mine.id)}}
 useEffect(()=>{void load()},[db,schoolId,userId]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const available=manager?assignments:assignments.filter(a=>a.teacher_id===userId);
 const label=(a:Assignment|undefined)=>{if(!a)return "Penugasan tidak ditemukan";const c=classes.find(x=>x.id===a.class_id)?.name||"Kelas",s=subjects.find(x=>x.id===a.subject_id)?.name||"Wali kelas";return c+" · "+s};
 async function saveMode(){if(!db)return;await run(async()=>{const {error}=await db.from("sc_teacher_preferences").upsert({school_id:schoolId,user_id:userId,mode},{onConflict:"school_id,user_id"});if(error)throw error;setOk("Mode kerja guru tersimpan.")})}
 async function saveSchedule(){if(!db||!assignmentId||start>=end)return;await run(async()=>{const {error}=await db.from("sc_teacher_schedules").insert({school_id:schoolId,assignment_id:assignmentId,weekday,starts_at:start,ends_at:end,room:room.trim()||null,note:note.trim()||null,active:true});if(error)throw error;setRoom("");setNote("");setOk("Jadwal mingguan ditambahkan.")})}
 async function remove(id:string){if(!db||!confirm("Hapus jadwal ini?"))return;await run(async()=>{const {error}=await db.from("sc_teacher_schedules").delete().eq("id",id);if(error)throw error;setOk("Jadwal dihapus.")})}
 async function template(){await downloadExcel("template-jadwal-mingguan-school-control.xlsx",[{name:"JADWAL_MINGGUAN",rows:[{Hari:"Senin",Kelas:"VIII A",Mata_Pelajaran:"Matematika",Mulai:"07:00",Selesai:"08:00",Ruang:"VIII A",Catatan:"Materi / pengingat"}]},{name:"Panduan",rows:[{Kolom:"Hari",Keterangan:"Senin sampai Minggu"},{Kolom:"Kelas",Keterangan:"Harus sama dengan Data Induk"},{Kolom:"Mata_Pelajaran",Keterangan:"Kosongkan untuk agenda wali kelas"}]}])}
 async function importFile(file?:File){if(!file||!db)return;await run(async()=>{const rows=await readExcel(file);let n=0;for(const x of rows){const day=DAYS.findIndex(d=>d.toLowerCase()===String(x.Hari||"").trim().toLowerCase())+1,cn=String(x.Kelas||"").trim().toLowerCase(),sn=String(x.Mata_Pelajaran||"").trim().toLowerCase(),cl=classes.find(c=>c.name.toLowerCase()===cn),sub=subjects.find(s=>s.name.toLowerCase()===sn),a=available.find(a=>a.class_id===cl?.id&&(!sn||a.subject_id===sub?.id));if(!day||!a)continue;const {error}=await db.from("sc_teacher_schedules").insert({school_id:schoolId,assignment_id:a.id,weekday:day,starts_at:String(x.Mulai||"07:00").slice(0,5),ends_at:String(x.Selesai||"08:00").slice(0,5),room:String(x.Ruang||"")||null,note:String(x.Catatan||"")||null,active:true});if(!error)n++}setOk(n+" jadwal berhasil diimpor.")})}
 async function ask(){if(!db||assistant.trim().length<3)return;await run(async()=>{const {data:{session}}=await db.auth.getSession();if(!session)throw Error("Sesi berakhir.");const startMonth=month+"-01",next=new Date(month+"-01T00:00:00");next.setMonth(next.getMonth()+1);const nextMonth=next.toISOString().slice(0,10);const [a,g,j]=await Promise.all([
  db.from("sc_student_attendance").select("attendance_date,mark,lesson_key").eq("school_id",schoolId).gte("attendance_date",startMonth).lt("attendance_date",nextMonth).limit(800),
  db.from("sc_grades").select("score,subject,assessment_name").eq("school_id",schoolId).gte("assessment_date",startMonth).lt("assessment_date",nextMonth).limit(800),
  db.from("sc_teacher_journals").select("lesson_date,subject,topic,notes").eq("school_id",schoolId).gte("lesson_date",startMonth).lt("lesson_date",nextMonth).limit(200)
 ]);const counts=(a.data||[]).reduce((o:any,x:any)=>(o[x.mark]=(o[x.mark]||0)+1,o),{});const avg=(g.data||[]).length?(g.data||[]).reduce((n:any,x:any)=>n+Number(x.score||0),0)/(g.data||[]).length:0;const context="Bulan "+month+". Presensi: "+JSON.stringify(counts)+". Rata-rata nilai: "+avg.toFixed(1)+". Jurnal terbaru: "+(j.data||[]).slice(-10).map((x:any)=>x.lesson_date+" "+x.subject+" "+x.topic).join("; ");const response=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.access_token},body:JSON.stringify({school_id:schoolId,module:"guru_ai",prompt:"Anda sedang membantu administrasi kelas berdasarkan data aktual berikut. Jangan mengarang data di luar konteks.\n"+context+"\n\nPermintaan guru: "+assistant})});const result=await response.json();if(!response.ok)throw Error(result.error||"AI belum tersedia.");setAnswer(result.text||"")})}
 async function buildBookReport(){if(!db)throw Error("Database belum siap.");const from=month+"-01",d=new Date(from+"T00:00:00");d.setMonth(d.getMonth()+1);const to=d.toISOString().slice(0,10);const [a,g,j,st,identity]=await Promise.all([
  db.from("sc_student_attendance").select("attendance_date,lesson_key,mark,notes,student_id").eq("school_id",schoolId).gte("attendance_date",from).lt("attendance_date",to).limit(5000),
  db.from("sc_grades").select("assessment_date,subject,assessment_name,score,max_score,assessment_category,student_id").eq("school_id",schoolId).gte("assessment_date",from).lt("assessment_date",to).limit(5000),
  db.from("sc_teacher_journals").select("lesson_date,subject,topic,notes,class_id,teacher_name_snapshot,class_name_snapshot").eq("school_id",schoolId).gte("lesson_date",from).lt("lesson_date",to).limit(1000),
  db.from("sc_students").select("id,name,nis,class_id").eq("school_id",schoolId).limit(5000),
  loadReportIdentity(db,schoolId)
 ]);const students=(st.data||[]) as any[],student=(id:string)=>students.find(x=>x.id===id),att=(a.data||[]) as any[],grades=(g.data||[]) as any[],journals=(j.data||[]) as any[];
 const avg=grades.length?grades.reduce((n,x)=>n+(Number(x.max_score)>0?Number(x.score)/Number(x.max_score)*100:Number(x.score)||0),0)/grades.length:0;
 const period=new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(from+"T12:00:00"));
 const model:OfficialReportModel={moduleKey:"buku_kerja",documentType:"laporan_buku_kerja",prefix:"BKJ",title:"Laporan Buku Kerja Guru",subtitle:"Presensi, penilaian, jurnal mengajar dan jadwal mingguan",periodLabel:period,periodStart:from,periodEnd:new Date(new Date(to+"T00:00:00").getTime()-86400000).toISOString().slice(0,10),orientation:"landscape",status:"approved",metrics:[
  {label:"Catatan presensi",value:String(att.length)},{label:"Nilai tercatat",value:String(grades.length)},{label:"Rata-rata nilai",value:avg.toFixed(1)},{label:"Jurnal mengajar",value:String(journals.length)}
 ],sections:[
  {title:"Rekap Presensi",columns:["Tanggal","NIS","Nama Siswa","Kelas","Status","Jenis/Mapel","Catatan"],rows:att.map(x=>{const s=student(x.student_id);return [x.attendance_date,s?.nis||"—",s?.name||"Siswa",classes.find(k=>k.id===s?.class_id)?.name||"—",x.mark,x.lesson_key||"Harian",x.notes||"—"]})},
  {title:"Rekap Penilaian",columns:["Tanggal","NIS","Nama Siswa","Mata Pelajaran","Asesmen","Kategori","Nilai","Maks."],rows:grades.map(x=>{const s=student(x.student_id);return [x.assessment_date,s?.nis||"—",s?.name||"Siswa",x.subject||"—",x.assessment_name||"—",x.assessment_category||"—",x.score,x.max_score||100]})},
  {title:"Jurnal Mengajar",columns:["Tanggal","Guru","Kelas","Mata Pelajaran","Topik","Catatan"],rows:journals.map(x=>[x.lesson_date,x.teacher_name_snapshot||"—",x.class_name_snapshot||classes.find(k=>k.id===x.class_id)?.name||"—",x.subject||"—",x.topic||"—",x.notes||"—"])},
  {title:"Jadwal Mingguan",columns:["Hari","Kelas / Mata Pelajaran","Mulai","Selesai","Ruang","Catatan"],rows:schedules.map(s=>[DAYS[s.weekday-1],label(assignments.find(a=>a.id===s.assignment_id)),s.starts_at,s.ends_at,s.room||"—",s.note||"—"])}
 ]};
 return {identity,model};
 }
 async function exportReport(format:"pdf"|"docx"|"xlsx"){if(!db)return;await run(async()=>{const {identity,model}=await buildBookReport();const issued=await issueAndExport(db,schoolId,identity,model,format);setOk("Laporan "+format.toUpperCase()+" diterbitkan dengan nomor "+issued.document_number+" dan masuk arsip.")})}
 async function previewReport(){if(!db)return;await run(async()=>{const {identity,model}=await buildBookReport();previewOfficialReport(identity,{...model,status:"draft"});setOk("Preview draft dibuka. Nomor dokumen belum dipakai.")})}

 if(focus==="Mode Kerja Guru")return <section className="panel"><h2>Mode Kerja Guru</h2><p className="muted">Mode memengaruhi cara membaca presensi, kelas, jadwal, dan rekap pribadi.</p><div className="fields"><label className="field">Mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="wali_kelas">Wali kelas</option><option value="guru_mapel">Guru mata pelajaran</option><option value="gabungan">Wali kelas + guru mapel</option></select></label><button className="button" onClick={()=>void saveMode()}><Save size={15}/> Simpan</button></div>{ok&&<div className="banner success">{ok}</div>}</section>;

 if(focus==="Asisten Kelas")return <section className="panel"><div className="sectionhead"><div><h2>Asisten Kelas</h2><p className="muted">Membaca ringkasan presensi, nilai dan jurnal pada bulan yang dipilih.</p></div><Sparkles/></div><div className="fields"><label className="field">Bulan<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><label className="field full">Permintaan<textarea rows={5} value={assistant} onChange={e=>setAssistant(e.target.value)} placeholder="Contoh: Analisis pola presensi dan susun tindak lanjut kelas."/></label><button className="button" disabled={busy||assistant.trim().length<3} onClick={()=>void ask()}>{busy?"Menganalisis…":"Kirim"}</button></div>{answer&&<div className="banner" style={{whiteSpace:"pre-wrap"}}>{answer}</div>}{error&&<div className="banner error">{error}</div>}</section>;

 if(focus==="Laporan Lengkap")return <section className="panel"><div className="sectionhead"><div><h2>Rekap & Laporan Lengkap</h2><p className="muted">Dokumen resmi gabungan presensi, nilai, jurnal dan jadwal. Preview menggunakan watermark DRAFT; ekspor final memperoleh nomor dokumen dan otomatis masuk arsip.</p></div><FileSpreadsheet/></div><div className="fields"><label className="field">Bulan<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div className="flow"><button className="button secondary" disabled={busy} onClick={()=>void previewReport()}>Preview Draft</button><button className="button" disabled={busy} onClick={()=>void exportReport("xlsx")}><Download size={15}/> Excel</button><button className="button secondary" disabled={busy} onClick={()=>void exportReport("docx")}><Download size={15}/> Word .docx</button><button className="button secondary" disabled={busy} onClick={()=>void exportReport("pdf")}><Download size={15}/> PDF / Cetak</button></div></div>{ok&&<div className="banner success">{ok}</div>}{error&&<div className="banner error">{error}</div>}</section>;

 return <section className="panel"><div className="sectionhead"><div><h2>Jadwal Mengajar Mingguan</h2><p className="muted">Jadwal rutin Senin–Minggu, terhubung dengan penugasan guru dari Data Induk.</p></div><div className="flow"><button className="button secondary" onClick={()=>void template()}><Download size={14}/> Template</button><label className="button secondary"><Upload size={14}/> Import<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>void importFile(e.target.files?.[0])}/></label></div></div><div className="fields"><label className="field full">Kelas & Mata Pelajaran<select value={assignmentId} onChange={e=>setAssignmentId(e.target.value)}><option value="">Pilih penugasan</option>{available.map(a=><option key={a.id} value={a.id}>{label(a)}</option>)}</select></label><label className="field">Hari<select value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{DAYS.map((d,i)=><option key={d} value={i+1}>{d}</option>)}</select></label><label className="field">Mulai<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field">Selesai<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="field">Ruang<input value={room} onChange={e=>setRoom(e.target.value)}/></label><label className="field full">Catatan<input value={note} onChange={e=>setNote(e.target.value)}/></label><button className="button" disabled={busy||!assignmentId||start>=end} onClick={()=>void saveSchedule()}><Plus size={15}/> Tambah Jadwal</button></div><div style={{display:"grid",gap:8,marginTop:18}}>{schedules.filter(s=>available.some(a=>a.id===s.assignment_id)).map(s=><div className="entry" key={s.id}><div><strong>{DAYS[s.weekday-1]} · {label(assignments.find(a=>a.id===s.assignment_id)!)}</strong><small>{s.starts_at.slice(0,5)}–{s.ends_at.slice(0,5)} · {s.room||"Tanpa ruang"} · {s.note||"Tanpa catatan"}</small></div><button className="button danger" onClick={()=>void remove(s.id)}><Trash2 size={14}/> Hapus</button></div>)}</div>{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;
}
