"use client";
import {useEffect,useMemo,useState} from "react";
import {Plus} from "lucide-react";
import DataEntryModal from "@/components/DataEntryModal";
import {browserDb} from "@/lib/supabase";
import {csvExport,saveCsv} from "@/lib/csv";
import {isAdmin,type Role} from "@/lib/modules";
type C={id:string;name:string;academic_year:string};type S={id:string;name:string;nis:string|null;class_id:string|null;status:string};type A={student_id:string;attendance_date:string;lesson_key:string;mark:string};type G={student_id:string;score:number;subject:string;assessment_name:string};
const day=()=>{const a=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const f=(k:string)=>a.find(z=>z.type===k)?.value||"";return f("year")+"-"+f("month")+"-"+f("day")};
export default function AcademicAdvanced({schoolId,userId,role,focus}:{schoolId:string;userId:string;role:Role;focus?:string}){
 const db=useMemo(()=>browserDb(),[]);const manager=isAdmin(role);
 const [classes,setClasses]=useState<C[]>([]),[students,setStudents]=useState<S[]>([]),[att,setAtt]=useState<A[]>([]),[grades,setGrades]=useState<G[]>([]),[classId,setClassId]=useState(""),[date,setDate]=useState(day()),[lesson,setLesson]=useState("daily"),[marks,setMarks]=useState<Record<string,string>>({}),[month,setMonth]=useState(day().slice(0,7)),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState(""),[modal,setModal]=useState(false);
 const members=students.filter(s=>s.class_id===classId&&s.status==="active");
 const nextMonth=()=>{const [y,m]=month.split("-").map(Number);return String(y+(m===12?1:0))+"-"+String(m===12?1:m+1).padStart(2,"0")+"-01"};
 async function load(){if(!db)return;const [cl,st,as]=await Promise.all([db.from("sc_classes").select("id,name,academic_year").eq("school_id",schoolId).order("name"),db.from("sc_students").select("id,name,nis,class_id,status").eq("school_id",schoolId).order("name"),db.from("sc_teacher_assignments").select("class_id").eq("school_id",schoolId).eq("teacher_id",userId)]);const all=(cl.data||[]) as C[];const allowed=new Set((as.data||[]).map(x=>x.class_id));setClasses(manager?all:all.filter(c=>allowed.has(c.id)));setStudents((st.data||[]) as S[])}
 async function refreshReport(){if(!db||!classId)return;const start=month+"-01",end=nextMonth();const [a,g]=await Promise.all([db.from("sc_student_attendance").select("student_id,attendance_date,lesson_key,mark").eq("school_id",schoolId).eq("class_id",classId).gte("attendance_date",start).lt("attendance_date",end).limit(2000),db.from("sc_grades").select("student_id,score,subject,assessment_name").eq("school_id",schoolId).eq("class_id",classId).gte("assessment_date",start).lt("assessment_date",end).limit(2000)]);setAtt((a.data||[]) as A[]);setGrades((g.data||[]) as G[]);if(a.error)setError(a.error.message);if(g.error)setError(g.error.message)}
 useEffect(()=>{void load()},[db,schoolId,userId,role]);useEffect(()=>{void refreshReport()},[db,schoolId,classId,month]);
 async function save(){if(!db)return;setBusy(true);setError("");setOk("");try{const rows=Object.entries(marks).filter(([id,v])=>v&&members.some(s=>s.id===id)).map(([id,mark])=>({student_id:id,mark}));if(!rows.length)throw Error("Pilih setidaknya satu status presensi.");const {error:e}=await db.rpc("sc_bulk_attendance",{p_school:schoolId,p_day:date,p_lesson:lesson,p_rows:rows});if(e)throw e;setMarks({});setModal(false);await refreshReport();setOk(rows.length+" status kehadiran disimpan.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const statuses=[["present","Hadir"],["sick","Sakit"],["permission","Izin"],["absent","Alpa"]];
 const reportOnly=(focus||"").toLowerCase().includes("rekap")||(focus||"").toLowerCase().includes("laporan");
 const rows=members.map(s=>{const aa=att.filter(x=>x.student_id===s.id);const gg=grades.filter(x=>x.student_id===s.id);const count=(m:string)=>aa.filter(a=>a.mark===m).length;const avg=gg.length?Math.round(gg.reduce((a,g)=>a+Number(g.score),0)/gg.length*100)/100:null;return {s,p:count("present"),sk:count("sick"),i:count("permission"),a:count("absent"),avg}});
 const exportReport=()=>saveCsv("rekap-kelas-"+month+".csv",csvExport(["NIS","Nama","Hadir","Sakit","Izin","Alpa","Rata-rata Nilai"],rows.map(r=>[r.s.nis,r.s.name,r.p,r.sk,r.i,r.a,r.avg])));
 return <>
  <section className="panel"><div className="sectionhead"><div><h2>{reportOnly?"Rekap Pembelajaran":"Presensi Siswa"}</h2><p className="muted">Guru hanya dapat mengisi kelas yang ditugaskan. Input presensi dibuka melalui popup agar halaman utama tetap ringkas.</p></div>{!reportOnly&&<button className="button" disabled={!classId} onClick={()=>{setMarks({});setDate(day());setModal(true)}}><Plus size={15}/> Input Presensi</button>}</div>
   <div className="fields"><label className="field">Pilih kelas<select value={classId} onChange={e=>{setClassId(e.target.value);setMarks({})}}><option value="">Pilih kelas penugasan</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.academic_year}</option>)}</select></label><label className="field">Bulan Rekap<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label></div>
   {classId&&<><h3 style={{marginTop:25}}>Rekap Bulan {month}</h3><div className="tablewrap"><table className="data-table"><thead><tr><th>Siswa</th><th>H</th><th>S</th><th>I</th><th>A</th><th>Rerata nilai</th></tr></thead><tbody>{rows.map(r=><tr key={r.s.id}><td>{r.s.name}<small style={{display:"block"}}>{r.s.nis||"NIS belum tersedia"}</small></td><td>{r.p}</td><td>{r.sk}</td><td>{r.i}</td><td>{r.a}</td><td>{r.avg??"—"}</td></tr>)}</tbody></table></div><button className="button secondary" onClick={exportReport} style={{marginTop:10}}>Ekspor Rekap CSV / Excel</button></>}
   {!classId&&<div className="empty" style={{marginTop:15}}>Pilih kelas untuk melihat rekap atau menginput presensi.</div>}
  </section>
  <DataEntryModal open={modal} onClose={()=>setModal(false)} title="Input Presensi Siswa" subtitle={(classes.find(c=>c.id===classId)?.name||"Kelas")+" · tentukan tanggal dan jenis pembelajaran"} wide>
   <div className="fields"><label className="field">Tanggal<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Jenis / Mata pelajaran<input value={lesson} onChange={e=>setLesson(e.target.value)} placeholder="Harian / Matematika / Jam ke-2"/></label></div>
   <div className="flow modal-quick-actions"><button type="button" className="button secondary" onClick={()=>setMarks(Object.fromEntries(members.map(s=>[s.id,"present"])))}>Tandai Semua Hadir</button><button type="button" className="button secondary" onClick={()=>setMarks({})}>Kosongkan</button></div>
   <div className="attendance-modal-list">{members.map(s=><div className="entry" key={s.id}><div><strong>{s.name}</strong><small>{s.nis||"NIS belum tersedia"}</small></div><select aria-label={"Presensi "+s.name} value={marks[s.id]||""} onChange={e=>setMarks(m=>({...m,[s.id]:e.target.value}))}><option value="">Belum dipilih</option>{statuses.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></div>)}{!members.length&&<div className="empty">Belum ada siswa aktif pada kelas ini.</div>}</div>
   <div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setModal(false)}>Batal</button><button type="button" className="button" disabled={busy||!members.length||!lesson.trim()} onClick={()=>void save()}>{busy?"Menyimpan…":"Simpan Presensi"}</button></div>
  </DataEntryModal>
  {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}
 </>;
}
