"use client";
import {useEffect,useMemo,useState} from "react";
import {Archive,Check,Copy,KeyRound,MessageSquare,Plus,RotateCcw,Save,Sparkles,Trash2} from "lucide-react";
import {browserDb} from "@/lib/supabase";

type Project={id:string;name:string;module:string;context:Record<string,unknown>;status:string;created_at:string;updated_at:string};
type Draft={id:string;template_key:string;title:string;prompt:string;content:string;created_at:string};
type Output={id:string;project_id:string;tool_key:string;title:string;content:string;version:number;is_final:boolean;created_at:string};
type Msg={id:string;project_id:string|null;role:"user"|"assistant";content:string;created_at:string};
const KEY="school-control-personal-gemini-key";
const OAUTH="school-control-personal-gemini-oauth";
const MODEL="school-control-gemini-model";
const FALLBACK="school-control-gemini-fallback";
const nowTitle=()=>new Date().toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"});

export default function AIProjectManager({schoolId,module="guru_ai",mode}:{schoolId:string;module?:"guru_ai"|"kepsek_ai";mode:"projects"|"chat"|"outputs"|"connection"}){
 const db=useMemo(()=>browserDb(),[]),[projects,setProjects]=useState<Project[]>([]),[drafts,setDrafts]=useState<Draft[]>([]),[outputs,setOutputs]=useState<Output[]>([]),[messages,setMessages]=useState<Msg[]>([]);
 const [projectId,setProjectId]=useState(""),[name,setName]=useState(""),[prompt,setPrompt]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const [key,setKey]=useState(()=>typeof window!=="undefined"?localStorage.getItem(KEY)||"":"");
 const [oauth,setOauth]=useState(()=>typeof window!=="undefined"?localStorage.getItem(OAUTH)||"":"");
 const [model,setModel]=useState(()=>typeof window!=="undefined"?localStorage.getItem(MODEL)||"gemini-2.5-flash":"gemini-2.5-flash");
 const [fallback,setFallback]=useState(()=>typeof window!=="undefined"?localStorage.getItem(FALLBACK)||"gemini-2.5-flash-lite":"gemini-2.5-flash-lite");
 const [compareA,setCompareA]=useState(""),[compareB,setCompareB]=useState("");
 async function load(){if(!db)return;const [p,d,o,m]=await Promise.all([
  db.from("sc_ai_projects").select("id,name,module,context,status,created_at,updated_at").eq("school_id",schoolId).eq("module",module).order("updated_at",{ascending:false}),
  db.from("sc_ai_drafts").select("id,template_key,title,prompt,content,created_at").eq("school_id",schoolId).eq("module_key",module).order("created_at",{ascending:false}).limit(100),
  db.from("sc_ai_outputs").select("id,project_id,tool_key,title,content,version,is_final,created_at").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(150),
  db.from("sc_ai_messages").select("id,project_id,role,content,created_at").eq("school_id",schoolId).eq("module",module).order("created_at",{ascending:true}).limit(200)
 ]);setProjects((p.data||[]) as Project[]);setDrafts((d.data||[]) as Draft[]);setOutputs((o.data||[]) as Output[]);setMessages((m.data||[]) as Msg[]);if(!projectId&&p.data?.[0])setProjectId(p.data[0].id)}
 useEffect(()=>{void load()},[db,schoolId,module]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function addProject(){if(!db||name.trim().length<3)return;await run(async()=>{const {data,error}=await db.from("sc_ai_projects").insert({school_id:schoolId,name:name.trim(),module}).select("id").single();if(error)throw error;setName("");setProjectId(data.id);setOk("Proyek dibuat dan siap dipakai.")})}
 async function archiveProject(id:string){if(!db)return;await run(async()=>{const {error}=await db.from("sc_ai_projects").update({status:"archived",updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;setOk("Proyek diarsipkan.")})}
 async function importDraft(d:Draft){if(!db||!projectId)throw Error("Pilih proyek terlebih dahulu.");await run(async()=>{const same=outputs.filter(x=>x.project_id===projectId&&x.tool_key===d.template_key),version=Math.max(0,...same.map(x=>x.version))+1;const {error}=await db.from("sc_ai_outputs").insert({school_id:schoolId,project_id:projectId,tool_key:d.template_key,title:d.title,prompt:d.prompt,content:d.content,version});if(error)throw error;setOk("Draf dimasukkan sebagai versi "+version+".")})}
 async function setFinal(o:Output){if(!db)return;await run(async()=>{await db.from("sc_ai_outputs").update({is_final:false}).eq("project_id",o.project_id).eq("tool_key",o.tool_key);const {error}=await db.from("sc_ai_outputs").update({is_final:true}).eq("id",o.id);if(error)throw error;setOk("Versi final ditetapkan.")})}
 async function send(){if(!db||prompt.trim().length<3)return;await run(async()=>{const {data:{session}}=await db.auth.getSession();if(!session)throw Error("Sesi berakhir.");const userText=prompt.trim();setPrompt("");const {error:u}=await db.from("sc_ai_messages").insert({school_id:schoolId,project_id:projectId||null,module,role:"user",content:userText});if(u)throw u;const history=messages.filter(x=>!projectId||x.project_id===projectId).slice(-12).map(x=>(x.role==="user"?"Guru/Kepsek: ":"Asisten: ")+x.content).join("\n\n");const response=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.access_token,...(key.trim()?{"x-user-gemini-key":key.trim()}:{}),...(oauth.trim()?{"x-user-gemini-oauth":oauth.trim()}:{})},body:JSON.stringify({school_id:schoolId,module,model,fallback_model:fallback,prompt:"Gunakan konteks percakapan berikut bila relevan:\n"+history+"\n\nPesan terbaru:\n"+userText})});const j=await response.json();if(!response.ok)throw Error(j.error||"AI belum tersedia.");const {error:a}=await db.from("sc_ai_messages").insert({school_id:schoolId,project_id:projectId||null,module,role:"assistant",content:j.text||""});if(a)throw a;setOk("Percakapan tersimpan.")})}
 async function testConnection(){
  if(!db)return;
  setBusy(true);setError("");setOk("");
  try{
   const {data:{session}}=await db.auth.getSession();if(!session)throw Error("Sesi berakhir.");
   const response=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.access_token,...(key.trim()?{"x-user-gemini-key":key.trim()}:{}),...(oauth.trim()?{"x-user-gemini-oauth":oauth.trim()}:{})},body:JSON.stringify({school_id:schoolId,module,action:"test",model,fallback_model:fallback,prompt:"Balas tepat dengan teks KONEKSI OK"})});
   const result=await response.json();if(!response.ok)throw Error(result.error||"Koneksi gagal.");
   setOk("Koneksi berhasil · "+result.provider+" · "+result.model+".");
  }catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}
 }
 async function resetWorkspace(){
  if(!db)return;
  const phrase=window.prompt("Ketik RESET WORKSPACE untuk mengarsipkan semua proyek aktif dan menghapus kredensial AI lokal. Output dan riwayat tetap disimpan.");
  if(phrase!=="RESET WORKSPACE")return;
  await run(async()=>{
   const {error}=await db.from("sc_ai_projects").update({status:"archived",updated_at:new Date().toISOString()}).eq("school_id",schoolId).eq("module",module).eq("status","active");
   if(error)throw error;
   localStorage.removeItem(KEY);localStorage.removeItem(OAUTH);localStorage.removeItem(MODEL);localStorage.removeItem(FALLBACK);
   setKey("");setOauth("");setModel("gemini-2.5-flash");setFallback("gemini-2.5-flash-lite");setProjectId("");
   setOk("Workspace AI direset aman: proyek aktif diarsipkan, riwayat dan output tidak dihapus.");
  })
 }
 const projectOutputs=outputs.filter(x=>!projectId||x.project_id===projectId),chat=messages.filter(x=>!projectId||x.project_id===projectId);
 const projectPicker=<label className="field">Proyek<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Tanpa proyek</option>{projects.filter(p=>p.status==="active").map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>;

 if(mode==="connection")return <section className="panel"><div className="sectionhead"><div><h2>Koneksi AI & Model</h2><p className="muted">Opsional. Kredensial pribadi hanya disimpan di browser perangkat ini dan dikirim langsung ke endpoint AI saat dipakai. Jika kosong, School Control memakai provider server.</p></div><KeyRound/></div><div className="fields"><label className="field full">Gemini API Key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="API key pribadi (opsional)"/></label><label className="field full">OAuth Access Token<input type="password" value={oauth} onChange={e=>setOauth(e.target.value)} placeholder="OAuth token pribadi (opsional, diprioritaskan jika diisi)"/></label><label className="field">Model utama<select value={model} onChange={e=>setModel(e.target.value)}><option value="gemini-2.5-flash">gemini-2.5-flash</option><option value="gemini-2.5-flash-lite">gemini-2.5-flash-lite</option><option value="gemini-2.0-flash">gemini-2.0-flash</option></select></label><label className="field">Model fallback<select value={fallback} onChange={e=>setFallback(e.target.value)}><option value="gemini-2.5-flash-lite">gemini-2.5-flash-lite</option><option value="gemini-2.5-flash">gemini-2.5-flash</option><option value="gemini-2.0-flash">gemini-2.0-flash</option></select></label></div><div className="flow"><button className="button" onClick={()=>{localStorage.setItem(KEY,key.trim());localStorage.setItem(OAUTH,oauth.trim());localStorage.setItem(MODEL,model);localStorage.setItem(FALLBACK,fallback);setOk("Konfigurasi AI disimpan di perangkat ini.")}}><Save size={15}/> Simpan</button><button className="button secondary" disabled={busy} onClick={()=>void testConnection()}>{busy?"Menguji…":"Test Connection"}</button><button className="button danger" onClick={()=>{localStorage.removeItem(KEY);localStorage.removeItem(OAUTH);setKey("");setOauth("");setOk("Kredensial pribadi dihapus. Sistem kembali memakai AI server.")}}><Trash2 size={15}/> Hapus Kredensial</button><button className="button danger" disabled={busy} onClick={()=>void resetWorkspace()}>Reset Workspace AI</button></div>{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;

 if(mode==="projects")return <><section className="panel"><div className="sectionhead"><div><h2>Proyek {module==="guru_ai"?"Pembelajaran":"Manajemen Sekolah"}</h2><p className="muted">Pisahkan pekerjaan per proyek agar konteks, versi output, dan percakapan tidak tercampur.</p></div><Sparkles/></div><div className="fields"><label className="field full">Nama proyek<input value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Modul Relasi & Fungsi Kelas VIII"/></label><button className="button" disabled={busy||name.trim().length<3} onClick={()=>void addProject()}><Plus size={15}/> Buat Proyek</button></div>{projects.map(p=><div className="entry" key={p.id}><div><strong>{p.name}</strong><small>{p.status} · diperbarui {new Date(p.updated_at).toLocaleString("id-ID")}</small></div><div className="flow"><button className="button secondary" onClick={()=>setProjectId(p.id)}>Pilih</button>{p.status==="active"&&<button className="button danger" onClick={()=>void archiveProject(p.id)}><Archive size={14}/> Arsip</button>}</div></div>)}{!projects.length&&<div className="empty">Belum ada proyek.</div>}</section>{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</>;

 if(mode==="chat")return <section className="panel"><div className="sectionhead"><div><h2>{module==="guru_ai"?"Ngobrol AI Guru":"Asisten AI Kepala Sekolah"}</h2><p className="muted">Percakapan tersimpan per proyek dan dapat dilanjutkan kapan saja.</p></div><MessageSquare/></div>{projectPicker}<div style={{display:"grid",gap:10,marginTop:14}}>{chat.map(m=><div className={"banner "+(m.role==="assistant"?"":"success")} key={m.id}><strong>{m.role==="assistant"?"Asisten":"Anda"}</strong><p style={{whiteSpace:"pre-wrap",marginBottom:0}}>{m.content}</p></div>)}{!chat.length&&<div className="empty">Belum ada percakapan.</div>}</div><div className="fields" style={{marginTop:14}}><label className="field full">Pesan<textarea rows={5} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Tulis pertanyaan atau pekerjaan yang ingin dibantu…"/></label><button className="button" disabled={busy||prompt.trim().length<3} onClick={()=>void send()}>{busy?"Memproses…":"Kirim"}</button></div>{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;

 return <section className="panel"><div className="sectionhead"><div><h2>Riwayat, Versi & Hasil Final</h2><p className="muted">Draf generator dapat dimasukkan ke proyek sebagai versi. Bandingkan dua versi lalu tetapkan satu sebagai final tanpa menghapus versi lama.</p></div><RotateCcw/></div>{projectPicker}{projectOutputs.length>1&&<div className="panel" style={{marginTop:14}}><h3>Bandingkan Versi</h3><div className="fields"><label className="field">Versi A<select value={compareA} onChange={e=>setCompareA(e.target.value)}><option value="">Pilih</option>{projectOutputs.map(o=><option key={o.id} value={o.id}>{o.title} · v{o.version}</option>)}</select></label><label className="field">Versi B<select value={compareB} onChange={e=>setCompareB(e.target.value)}><option value="">Pilih</option>{projectOutputs.map(o=><option key={o.id} value={o.id}>{o.title} · v{o.version}</option>)}</select></label></div>{compareA&&compareB&&<div className="grid" style={{gridTemplateColumns:"repeat(2,minmax(0,1fr))"}}><div className="card"><strong style={{fontSize:14}}>Versi A</strong><p style={{whiteSpace:"pre-wrap"}}>{projectOutputs.find(o=>o.id===compareA)?.content}</p></div><div className="card"><strong style={{fontSize:14}}>Versi B</strong><p style={{whiteSpace:"pre-wrap"}}>{projectOutputs.find(o=>o.id===compareB)?.content}</p></div></div>}</div>}<h3 style={{marginTop:20}}>Draf terbaru</h3>{drafts.slice(0,20).map(d=><div className="entry" key={d.id}><div><strong>{d.title}</strong><small>{d.template_key} · {new Date(d.created_at).toLocaleString("id-ID")}</small></div><button className="button secondary" disabled={!projectId||busy} onClick={()=>void importDraft(d)}><Copy size={14}/> Jadikan versi baru</button></div>)}<h3 style={{marginTop:24}}>Versi proyek</h3>{projectOutputs.map(o=><div className="entry" key={o.id}><div><strong>{o.title} · v{o.version}</strong><small>{o.tool_key} · {o.is_final?"FINAL":"draf"} · {new Date(o.created_at).toLocaleString("id-ID")}</small></div><div className="flow"><button className="button secondary" onClick={()=>navigator.clipboard?.writeText(o.content)}>Salin</button>{!o.is_final&&<button className="button" onClick={()=>void setFinal(o)}><Check size={14}/> Jadikan Final</button>}</div></div>)}{!projectOutputs.length&&<div className="empty">Belum ada versi pada proyek ini.</div>}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;
}
