"use client";
import {useRealtimeRefresh} from "@/lib/school-realtime";
import SearchableSelect from "@/components/SearchableSelect";
import {errorMessage} from "@/lib/error-message";
import {useEffect,useMemo,useState,useRef} from "react";
import {Archive,Check,Copy,KeyRound,MessageSquare,Plus,RotateCcw,Save,Sparkles,Trash2} from "lucide-react";
import "./ai-chat.css";
import {browserDb} from "@/lib/supabase";

type Project={id:string;name:string;module:string;context:Record<string,unknown>;status:string;created_at:string;updated_at:string};
type Draft={id:string;template_key:string;title:string;prompt:string;content:string;created_at:string};
type Output={id:string;project_id:string;tool_key:string;title:string;content:string;version:number;is_final:boolean;created_at:string};
type Msg={id:string;project_id:string|null;role:"user"|"assistant";content:string;created_at:string};
const KEY="school-control-personal-gemini-key";
const nowTitle=()=>new Date().toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"});

export default function AIProjectManager({schoolId,module="guru_ai",mode}:{schoolId:string;module?:"guru_ai"|"kepsek_ai";mode:"projects"|"chat"|"outputs"|"connection"}){
 const db=useMemo(()=>browserDb(),[]),[projects,setProjects]=useState<Project[]>([]),[drafts,setDrafts]=useState<Draft[]>([]),[outputs,setOutputs]=useState<Output[]>([]),[messages,setMessages]=useState<Msg[]>([]);
 const [projectId,setProjectId]=useState(""),[name,setName]=useState(""),[prompt,setPrompt]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const endRef=useRef<HTMLDivElement>(null);
 const [pending,setPending]=useState("");
 const [key,setKey]=useState(()=>typeof window!=="undefined"?localStorage.getItem(KEY)||"":"");
 useRealtimeRefresh(schoolId,()=>load());
 async function load(){if(!db)return;const [p,d,o,m]=await Promise.all([
  db.from("sc_ai_projects").select("id,name,module,context,status,created_at,updated_at").eq("school_id",schoolId).eq("module",module).order("updated_at",{ascending:false}),
  db.from("sc_ai_drafts").select("id,template_key,title,prompt,content,created_at").eq("school_id",schoolId).eq("module_key",module).order("created_at",{ascending:false}).limit(100),
  db.from("sc_ai_outputs").select("id,project_id,tool_key,title,content,version,is_final,created_at").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(150),
  db.from("sc_ai_messages").select("id,project_id,role,content,created_at").eq("school_id",schoolId).eq("module",module).order("created_at",{ascending:true}).limit(200)
 ]);setProjects((p.data||[]) as Project[]);setDrafts((d.data||[]) as Draft[]);setOutputs((o.data||[]) as Output[]);setMessages((m.data||[]) as Msg[]);if(!projectId&&p.data?.[0])setProjectId(p.data[0].id)}
 useEffect(()=>{void load()},[db,schoolId,module]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function addProject(){if(!db||name.trim().length<3)return;await run(async()=>{const {data,error}=await db.from("sc_ai_projects").insert({school_id:schoolId,name:name.trim(),module}).select("id").single();if(error)throw error;setName("");setProjectId(data.id);setOk("Proyek dibuat dan siap dipakai.")})}
 async function archiveProject(id:string){if(!db)return;await run(async()=>{const {error}=await db.from("sc_ai_projects").update({status:"archived",updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;setOk("Proyek diarsipkan.")})}
 async function importDraft(d:Draft){if(!db||!projectId)throw Error("Pilih proyek terlebih dahulu.");await run(async()=>{const same=outputs.filter(x=>x.project_id===projectId&&x.tool_key===d.template_key),version=Math.max(0,...same.map(x=>x.version))+1;const {error}=await db.from("sc_ai_outputs").insert({school_id:schoolId,project_id:projectId,tool_key:d.template_key,title:d.title,prompt:d.prompt,content:d.content,version});if(error)throw error;setOk("Draf dimasukkan sebagai versi "+version+".")})}
 async function setFinal(o:Output){if(!db)return;await run(async()=>{await db.from("sc_ai_outputs").update({is_final:false}).eq("project_id",o.project_id).eq("tool_key",o.tool_key);const {error}=await db.from("sc_ai_outputs").update({is_final:true}).eq("id",o.id);if(error)throw error;setOk("Versi final ditetapkan.")})}
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:"smooth",block:"nearest"})},[messages,pending,busy]);
 async function send(){if(!db||prompt.trim().length<3)return;await run(async()=>{const {data:{session}}=await db.auth.getSession();if(!session)throw Error("Sesi berakhir.");const userText=prompt.trim();const selectedProject=projectId;setPending(userText);const history=messages.filter(x=>x.project_id===(selectedProject||null)).slice(-12).map(x=>(x.role==="user"?"Guru/Kepsek: ":"Asisten: ")+x.content).join("\n\n");const response=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.access_token,...(key.trim()?{"x-user-gemini-key":key.trim()}:{})},body:JSON.stringify({school_id:schoolId,module,prompt:"Gunakan konteks percakapan berikut bila relevan:\n"+history+"\n\nPesan terbaru:\n"+userText})});const j=await response.json();if(!response.ok)throw Error(j.error||"AI belum tersedia.");if(typeof j.text!=="string"||!j.text.trim())throw Error("Gemini belum menghasilkan jawaban. Silakan kirim ulang.");const {error:a}=await db.from("sc_ai_messages").insert([{school_id:schoolId,project_id:selectedProject||null,module,role:"user",content:userText},{school_id:schoolId,project_id:selectedProject||null,module,role:"assistant",content:j.text}]);if(a)throw a;setPrompt("");setOk("")});setPending("")}

 const projectOutputs=outputs.filter(x=>!projectId||x.project_id===projectId),chat=messages.filter(x=>x.project_id===(projectId||null));
 const projectPicker=<label className="field">Proyek<SearchableSelect label="Proyek" value={projectId} disabled={busy} onChange={e=>setProjectId(e.target.value)}><option value="">Tanpa proyek</option>{projects.filter(p=>p.status==="active").map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</SearchableSelect></label>;

 if(mode==="connection")return <section className="panel"><div className="sectionhead"><div><h2>Koneksi AI Pribadi</h2><p className="muted">Opsional. Jika kosong, School Control memakai AI server. Key pribadi disimpan hanya di browser perangkat ini.</p></div><KeyRound/></div><div className="fields"><label className="field full">Gemini API Key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Tempel API key pribadi"/></label></div><div className="flow"><button className="button" onClick={()=>{if(key.trim()&&!/^[\x21-\x7E]{20,512}$/.test(key.trim())){setError("Tempel key lengkap tanpa spasi atau baris baru.");return;}setError("");localStorage.setItem(KEY,key.trim());setOk("Key pribadi disimpan di perangkat ini.")}}><Save size={15}/> Simpan</button><button className="button danger" onClick={()=>{localStorage.removeItem(KEY);setKey("");setOk("Key pribadi dihapus dari perangkat ini.")}}><Trash2 size={15}/> Hapus</button></div>{error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success">{ok}</div>}<p className="muted">Mendukung key standar dan authorization key terbaru (AQ.). Buat atau periksa key di <a href="https://aistudio.google.com/api-keys" target="_blank" rel="noreferrer">Google AI Studio</a>. Key dikirim ke Google melalui server saat menjalankan AI.</p></section>;

 if(mode==="projects")return <><section className="panel"><div className="sectionhead"><div><h2>Proyek {module==="guru_ai"?"Pembelajaran":"Manajemen Sekolah"}</h2><p className="muted">Pisahkan pekerjaan per proyek agar konteks, versi output, dan percakapan tidak tercampur.</p></div><Sparkles/></div><div className="fields"><label className="field full">Nama proyek<input value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Modul Relasi & Fungsi Kelas VIII"/></label><button className="button" disabled={busy||name.trim().length<3} onClick={()=>void addProject()}><Plus size={15}/> Buat Proyek</button></div>{projects.map(p=><div className="entry" key={p.id}><div><strong>{p.name}</strong><small>{p.status} · diperbarui {new Date(p.updated_at).toLocaleString("id-ID")}</small></div><div className="flow"><button className="button secondary" onClick={()=>setProjectId(p.id)}>Pilih</button>{p.status==="active"&&<button className="button danger" onClick={()=>void archiveProject(p.id)}><Archive size={14}/> Arsip</button>}</div></div>)}{!projects.length&&<div className="empty">Belum ada proyek.</div>}</section>{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</>;

 if(mode==="chat")return <section className="panel ai-chat"><div className="sectionhead"><div><h2>{module==="guru_ai"?"Asisten AI Guru":"Asisten AI Kepala Sekolah"}</h2><p className="muted">Ajukan pertanyaan atau lanjutkan pekerjaan dalam proyek.</p></div><MessageSquare/></div>{projectPicker}<div className="ai-chat-messages" role="log" aria-label="Percakapan AI" aria-live="polite">{chat.map(m=><article className={"ai-chat-bubble "+m.role} key={m.id}><strong>{m.role==="assistant"?"Asisten":"Anda"}</strong><p>{m.content}</p></article>)}{pending&&<article className="ai-chat-bubble user"><strong>Anda</strong><p>{pending}</p></article>}{busy&&<div className="ai-chat-thinking" role="status">Asisten sedang menyiapkan jawaban…</div>}{!chat.length&&!pending&&<div className="empty"><Sparkles size={28}/><h3>Apa yang ingin dibantu?</h3><p>Coba: bantu susun agenda mengajar atau jelaskan strategi pembelajaran untuk kelas saya.</p></div>}<div ref={endRef}/></div><form className="ai-chat-composer" onSubmit={e=>{e.preventDefault();void send()}}><label className="field">Pesan<textarea aria-label="Pesan" rows={3} disabled={busy} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Tulis pertanyaan atau pekerjaan yang ingin dibantu…"/></label><button className="button" disabled={busy||prompt.trim().length<3} type="submit">{busy?"Memproses…":"Kirim pesan"}</button></form>{error&&<div className="banner error" role="alert">{error} Pesan tetap tersedia di kolom input untuk dicoba kembali.</div>}<small className="muted">Jawaban AI merupakan draf. Periksa data dan kesesuaiannya sebelum digunakan.</small></section>;

 return <section className="panel"><div className="sectionhead"><div><h2>Riwayat, Versi & Hasil Final</h2><p className="muted">Draf generator dapat dimasukkan ke proyek sebagai versi. Satu versi dapat ditandai final tanpa menghapus versi lama.</p></div><RotateCcw/></div>{projectPicker}<h3 style={{marginTop:20}}>Draf terbaru</h3>{drafts.slice(0,20).map(d=><div className="entry" key={d.id}><div><strong>{d.title}</strong><small>{d.template_key} · {new Date(d.created_at).toLocaleString("id-ID")}</small></div><button className="button secondary" disabled={!projectId||busy} onClick={()=>void importDraft(d)}><Copy size={14}/> Jadikan versi baru</button></div>)}<h3 style={{marginTop:24}}>Versi proyek</h3>{projectOutputs.map(o=><div className="entry" key={o.id}><div><strong>{o.title} · v{o.version}</strong><small>{o.tool_key} · {o.is_final?"FINAL":"draf"} · {new Date(o.created_at).toLocaleString("id-ID")}</small></div><div className="flow"><button className="button secondary" onClick={()=>navigator.clipboard?.writeText(o.content)}>Salin</button>{!o.is_final&&<button className="button" onClick={()=>void setFinal(o)}><Check size={14}/> Jadikan Final</button>}</div></div>)}{!projectOutputs.length&&<div className="empty">Belum ada versi pada proyek ini.</div>}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;
}
