"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {aiTemplates,type AiModule} from "@/lib/education-templates";
type Draft={id:string;template_key:string|null;title:string;content:string;created_at:string};
export default function AIWorkbench({module,schoolId,focus}:{module:AiModule;schoolId:string;focus?:string}){
 const db=useMemo(()=>browserDb(),[]);const [template,setTemplate]=useState(""),[context,setContext]=useState(""),[output,setOutput]=useState(""),[title,setTitle]=useState(""),[drafts,setDrafts]=useState<Draft[]>([]),[error,setError]=useState(""),[ok,setOk]=useState(""),[busy,setBusy]=useState(false);
 const config=aiTemplates[module].find(t=>t.key===template);
 async function load(){if(!db)return;const {data}=await db.from("sc_ai_drafts").select("id,template_key,title,content,created_at").eq("school_id",schoolId).eq("module_key",module).order("created_at",{ascending:false}).limit(30);setDrafts((data||[]) as Draft[])}
 useEffect(()=>{void load()},[db,schoolId,module]);
 useEffect(()=>{const f=(focus||"").toLowerCase();if(!f)return;const found=aiTemplates[module].find(t=>t.label.toLowerCase().includes(f)||f.includes(t.label.toLowerCase()));if(found)setTemplate(found.key)},[focus,module]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function generate(){if(!db||!config)return;await run(async()=>{const {data:{session}}=await db.auth.getSession();if(!session)throw Error("Masuk kembali untuk menjalankan AI.");const response=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+session.access_token},body:JSON.stringify({school_id:schoolId,module,prompt:config.prompt+"\nKonteks atau instruksi tambahan: "+context})});const j=await response.json();if(!response.ok)throw Error(j.error||"AI belum tersedia.");setOutput(j.text||"");setTitle(config.label);setOk("Draf selesai dibuat, periksa dan sunting sebelum disimpan.")})}
 async function store(){if(!db)return;await run(async()=>{const {error}=await db.rpc("sc_store_ai_draft",{p_school:schoolId,p_module:module,p_template:template,p_title:title,p_prompt:context,p_content:output});if(error)throw error;await load();setOk("Draf AI disimpan ke riwayat pribadi.")})}
 async function removeDraft(id:string){if(!db||!confirm("Hapus draf AI ini?"))return;await run(async()=>{const {error}=await db.rpc("sc_delete_auxiliary",{p_school:schoolId,p_entity:"ai_draft",p_id:id});if(error)throw error;await load();setOk("Draf dihapus.")})}
 return <><section className="panel"><h2>{module==="guru_ai"?"Generator Bahan Ajar":"Asisten AI Kepala Sekolah"}</h2><p className="muted">Alur asli generator disatukan: pilih jenis dokumen, berikan konteks sekolah, buat draf, tinjau, sunting, lalu simpan. AI tidak membaca data BK rahasia.</p><div className="fields"><label className="field full">Jenis generator<select value={template} onChange={e=>setTemplate(e.target.value)}><option value="">Pilih jenis</option>{aiTemplates[module].map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select></label><label className="field full">Konteks sekolah dan permintaan khusus<textarea value={context} onChange={e=>setContext(e.target.value)} rows={5} placeholder="Kelas, mapel, tujuan, sasaran, fakta yang diketahui…"/></label></div><div className="flow" style={{marginTop:12}}><button className="button" disabled={busy||!template||context.trim().length<10} onClick={()=>void generate()}>{busy?"Memproses…":"Buat Draf AI"}</button></div>{output&&<div className="panel"><h3>Editor Hasil AI</h3><label className="field">Judul<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field" style={{marginTop:12}}>Isi dokumen<textarea value={output} rows={17} style={{minHeight:310}} onChange={e=>setOutput(e.target.value)}/></label><button className="button" disabled={busy||title.trim().length<2} style={{marginTop:12}} onClick={()=>void store()}>Simpan Riwayat</button></div>}</section><section className="panel"><h2>Riwayat Hasil AI Saya</h2>{drafts.map(d=><div className="entry" key={d.id}><div><strong>{d.title}</strong><small>{d.created_at.slice(0,10)} · {d.template_key}</small></div><div className="flow"><button className="button secondary" onClick={()=>{setTitle(d.title);setOutput(d.content)}}>Buka</button><button className="button danger" onClick={()=>void removeDraft(d.id)}>Hapus</button></div></div>)}{!drafts.length&&<div className="empty">Belum ada draf.</div>}</section>{error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
}
