"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
type Order={order_id:string;gross_amount:number;period_days:number;status:string;paid_at:string|null;created_at:string};
type Sub={status:string;trial_ends_at:string;current_period_end:string|null};
type Plans={monthly:{price:number};yearly:{price:number}};
const rupiah=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v)||0);
const date=(s:string|null)=>s?new Date(s).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"}):"—";
export default function BillingPanel({schoolId,isOwner,busy,onCheckout,focus}:{schoolId:string;isOwner:boolean;busy:boolean;onCheckout:(p:"monthly"|"yearly")=>void;focus?:string}){
 const db=useMemo(()=>browserDb(),[]);const [sub,setSub]=useState<Sub|null>(null),[orders,setOrders]=useState<Order[]>([]),[plans,setPlans]=useState<Plans|null>(null),[error,setError]=useState("");
 async function load(){if(!db)return;const [s,o]=await Promise.all([db.from("sc_subscriptions").select("status,trial_ends_at,current_period_end").eq("school_id",schoolId).maybeSingle(),db.from("sc_payment_orders").select("order_id,gross_amount,period_days,status,paid_at,created_at").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(30)]);if(s.error)setError(s.error.message);if(o.error)setError(o.error.message);setSub(s.data||null);setOrders((o.data||[]) as Order[])}
 useEffect(()=>{void load();void fetch("/api/plans").then(r=>r.json()).then(setPlans).catch(()=>{})},[db,schoolId]);
 const f=(focus||"").toLowerCase();const historyOnly=f.includes("riwayat");const subscriptionOnly=f.includes("langganan");
 return <section className="panel"><div className="flow" style={{justifyContent:"space-between"}}><div><h2>School Control Pro</h2><p className="muted">Seluruh modul dan template laporan sekolah. Trial 7 hari: 15 permintaan generator AI. Langganan: 200 permintaan per bulan kalender UTC, bersama seluruh anggota. Tahunan hemat setara 2 bulan.</p></div><span className="pill">{sub?.status||"Memuat..."}</span></div><div className="grid"><div className="card"><label>Trial berakhir</label><strong style={{fontSize:15}}>{date(sub?.trial_ends_at||null)}</strong></div><div className="card"><label>Aktif hingga</label><strong style={{fontSize:15}}>{date(sub?.current_period_end||null)}</strong></div></div>{!historyOnly&&<div className="flow" style={{marginTop:16}}>{isOwner&&plans&&<><button className="button secondary" disabled={busy} onClick={()=>onCheckout("monthly")}>Bulanan · {rupiah(plans.monthly.price)}</button><button className="button" disabled={busy} onClick={()=>onCheckout("yearly")}>Tahunan · {rupiah(plans.yearly.price)}</button></>}</div>}{!subscriptionOnly&&<><h3 style={{marginTop:27}}>Riwayat Pesanan</h3><div className="tablewrap"><table className="data-table"><thead><tr><th>Tanggal</th><th>Order ID</th><th>Nominal</th><th>Durasi</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.order_id}><td>{date(o.created_at)}</td><td><small>{o.order_id}</small></td><td>{rupiah(o.gross_amount)}</td><td>{o.period_days} hari</td><td><span className="pill">{o.status}</span></td></tr>)}</tbody></table>{orders.length===0&&<div className="empty">Belum ada pesanan.</div>}</div></>}<button className="button secondary" onClick={()=>void load()} style={{marginTop:15}}>Periksa Status Terbaru</button>{error&&<div className="banner error" role="alert">{error}</div>}</section>;
}
