"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
type Student={id:string;name:string;nis:string|null;class_id:string|null;status:string};
type Case={id:string;student_id:string;category:string;status:string;follow_up_date:string|null;confidential_notes:string|null;assigned_counselor:string};
type BKRecord={id:string;case_id:string|null;student_id:string;kind:string;domain:string;happened_on:string;title:string;notes:string|null;follow_up_on:string|null};
type Attendance={student_id:string;attendance_date:string;mark:string;lesson_key:string};
const kinds=[["need","Pemetaan kebutuhan"],["counseling","Konseling individu"],["group","Konseling kelompok"],["classical","Layanan klasikal"],["rpl","RPL layanan"],["program","Program BK"],["agenda","Agenda"],["followup","Tindak lanjut"],["visit","Kunjungan rumah"],["referral","Rujukan"],["career","Perencanaan karier"],["document","Dokumen"]];
const date=()=>{const p=new Intl.DateTimeFormat("en-US",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:"Asia/Jakarta"}).formatToParts(new Date());const g=(x:string)=>p.find(y=>y.type===x)?.value||"";return g("year")+"-"+g("month")+"-"+g("day")};
export default function BKPanel({schoolId,userId,focus}:{schoolId:string;userId:string;focus?:string}){
 const db=useMemo(()=>browserDb(),[]);const [students,setStudents]=useState<Student[]>([]),[cases,setCases]=useState<Case[]>([]),[records,setRecords]=useState<BKRecord[]>([]),[att,setAtt]=useState<Attendance[]>([]);
 const [tab,setTab]=useState("cases"),[studentId,setStudentId]=useState(""),[caseId,setCaseId]=useState(""),[domain,setDomain]=useState("Pribadi"),[kind,setKind]=useState("need"),[topic,setTopic]=useState(""),[notes,setNotes]=useState(""),[followDate,setFollowDate]=useState(""),[day,setDay]=useState(date());
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const studentName=(id:string)=>students.find(s=>s.id===id)?.name||"Siswa";
 async function load(){if(!db)return;const [s,c,r,a]=await Promise.all([
 db.from("sc_students").select("id,name,nis,class_id,status").eq("school_id",schoolId).order("name"),
 db.from("sc_bk_cases").select("id,student_id,category,status,follow_up_date,confidential_notes,assigned_counselor").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(120),
 db.from("sc_bk_records").select("id,case_id,student_id,kind,domain,happened_on,title,notes,follow_up_on").eq("school_id",schoolId).order("happened_on",{ascending:false}).limit(200),
 db.from("sc_student_attendance").select("student_id,attendance_date,mark,lesson_key").eq("school_id",schoolId).order("attendance_date",{ascending:false}).limit(100)
 ]);setStudents((s.data||[]) as Student[]);setCases((c.data||[]) as Case[]);setRecords((r.data||[]) as BKRecord[]);setAtt((a.data||[]) as Attendance[]);if(c.error)setError(c.error.message);else if(r.error)setError(r.error.message)}
 useEffect(()=>{void load()},[db,schoolId]);
 useEffect(()=>{const f=(focus||"").toLowerCase();if(f.includes("tindak lanjut"))setTab("followup");else if(f.includes("riwayat"))setTab("history");else if(f.includes("kasus"))setTab("cases");else if(f)setTab("service")},[focus]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Layanan BK tersimpan secara privat.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function insert(table:string,row:Record<string,unknown>){if(!db)throw Error("Database tidak terhubung");const {error}=await db.from(table).insert({...row,school_id:schoolId});if(error)throw error}
 async function updateCase(c:Case,status:string){if(!db)return;await run(async()=>{const {error}=await db.rpc("sc_update_bk_case",{p_school:schoolId,p_case:c.id,p_status:status,p_follow_up:c.follow_up_date});if(error)throw error})}
 const studentField=<label className="field">Siswa<select value={studentId} required onChange={e=>setStudentId(e.target.value)}><option value="">Pilih siswa</option>{students.filter(s=>s.status==="active").map(s=><option key={s.id} value={s.id}>{s.name} · {s.nis||"—"}</option>)}</select></label>;
 const domainField=<label className="field">Bidang layanan<select value={domain} onChange={e=>setDomain(e.target.value)}>{["Pribadi","Sosial","Belajar","Karier"].map(d=><option key={d} value={d}>{d}</option>)}</select></label>;
 const textField=(label:string,v:string,cb:(x:string)=>void,type="text")=><label className="field">{label}<input type={type} value={v} required onChange={e=>cb(e.target.value)}/></label>;
 const caseRows=cases.filter(c=>!studentId||c.student_id===studentId);
 const related=records.filter(r=>!studentId||r.student_id===studentId);
 return <><div className="banner">Privasi BK: catatan ini hanya ditampilkan kepada konselor yang ditugaskan. Dashboard kepala sekolah tidak menerima nama siswa, isi sesi, atau catatan rahasia.</div><div className="flow" style={{marginBottom:15}}>{[["cases","Kasus"],["service","Layanan & RPL"],["history","Riwayat Siswa"],["followup","Tindak Lanjut"]].map(([k,n])=><button key={k} className={"button "+(tab===k?"":"secondary")} onClick={()=>setTab(k)}>{n}</button>)}</div>
 {tab==="cases"&&<section className="panel"><h2>Register Kasus BK</h2><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await insert("sc_bk_cases",{student_id:studentId,assigned_counselor:userId,category:topic.trim(),confidential_notes:notes.trim()||null,follow_up_date:followDate||null});setTopic("");setNotes("")})}}>{studentField}{textField("Kebutuhan / Topik",topic,setTopic)}{textField("Tanggal tindak lanjut (opsional)",followDate,setFollowDate,"date")}<label className="field full">Catatan rahasia<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Hanya konselor yang ditugaskan"/></label><button className="button" disabled={busy||!studentId||topic.trim().length<3}>Buat Kasus</button></form>{caseRows.map(c=><div className="entry" key={c.id}><div><strong>{studentName(c.student_id)} · {c.category}</strong><small>Status {c.status} · Tindak lanjut {c.follow_up_date||"—"}</small><small>Catatan: {c.confidential_notes||"Belum ada"}</small></div><div className="flow"><span className="pill">{c.status}</span>{c.status!=="closed"&&<button className="button secondary" disabled={busy} onClick={()=>void updateCase(c,c.status==="open"?"ongoing":"closed")}>{c.status==="open"?"Mulai Penanganan":"Selesaikan"}</button>}</div></div>)}{!caseRows.length&&<div className="empty">Belum ada kasus untuk konselor ini.</div>}</section>}
 {tab==="service"&&<section className="panel"><h2>Jurnal Layanan BK</h2><p className="muted">Pemetaan kebutuhan, konseling, layanan klasikal, RPL, program, agenda, home visit, rujukan dan perencanaan karier menggunakan master siswa yang sama.</p><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await insert("sc_bk_records",{case_id:caseId||null,student_id:studentId,counselor_id:userId,kind,domain,title:topic.trim(),notes:notes.trim()||null,happened_on:day,follow_up_on:followDate||null,confidential:true});setTopic("");setNotes("")})}}>{studentField}<label className="field">Kasus terkait<select value={caseId} onChange={e=>{setCaseId(e.target.value);const c=cases.find(x=>x.id===e.target.value);if(c)setStudentId(c.student_id)}}><option value="">Tanpa kasus</option>{cases.filter(c=>!studentId||c.student_id===studentId).map(c=><option key={c.id} value={c.id}>{studentName(c.student_id)} · {c.category}</option>)}</select></label><label className="field">Jenis layanan<select value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(([k,n])=><option key={k} value={k}>{n}</option>)}</select></label>{domainField}{textField("Judul layanan / RPL",topic,setTopic)}{textField("Tanggal kegiatan",day,setDay,"date")}{textField("Rencana tindak lanjut (opsional)",followDate,setFollowDate,"date")}<label className="field full">Tujuan, metode, temuan, evaluasi dan tindak lanjut<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={6}/></label><button className="button" disabled={busy||!studentId||topic.trim().length<3}>Simpan Layanan</button></form></section>}
 {tab==="history"&&<section className="panel"><h2>Riwayat Siswa 360°</h2>{studentField}{att.filter(a=>!studentId||a.student_id===studentId).slice(0,30).map((a,i)=><div className="entry" key={a.student_id+a.attendance_date+a.lesson_key+i}><div><strong>{studentName(a.student_id)} · {a.attendance_date}</strong><small>{a.lesson_key} · {a.mark}</small></div></div>)}<h3>Jurnal Layanan Privat</h3>{related.map(r=><div className="entry" key={r.id}><div><strong>{r.title} · {r.kind}</strong><small>{studentName(r.student_id)} · {r.domain} · {r.happened_on}</small><small>{r.notes||"Tanpa catatan"} · Lanjut: {r.follow_up_on||"—"}</small></div></div>)}{!related.length&&<div className="empty">Belum ada riwayat layanan.</div>}</section>}
 {tab==="followup"&&<section className="panel"><h2>Tindak Lanjut Kasus dan Layanan</h2>{cases.filter(c=>c.status!=="closed").map(c=><div className="entry" key={c.id}><div><strong>{studentName(c.student_id)} · {c.category}</strong><small>Rencana tindak lanjut: {c.follow_up_date||"Belum dijadwalkan"}</small></div><button className="button secondary" onClick={()=>{setCaseId(c.id);setStudentId(c.student_id);setKind("followup");setTopic("Tindak lanjut "+c.category);setTab("service")}}>Catat Tindak Lanjut</button></div>)}</section>}
 {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
}
