"use client";
import {useRealtimeRefresh} from "@/lib/school-realtime";
import SearchableSelect from "@/components/SearchableSelect";
import RecordListTools,{useRecordList} from "@/components/RecordListTools";
import {recordDateKey} from "@/lib/record-list";
import {readAllRows} from "@/lib/read-all-rows";
import {errorMessage} from "@/lib/error-message";
import {useEffect,useMemo,useState} from "react";
import {Check,Download,FileCheck2,Plus} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import {issueAndExport,loadReportIdentity,previewOfficialReport,type OfficialReportModel} from "@/lib/report-engine";
import type {Role,Staff} from "@/lib/modules";

type P={id:string;title:string;status:string;deadline:string|null;pic_id:string|null;created_at:string};
type T={id:string;program_id:string;title:string;status:string;pic_id:string|null;due_at:string|null;problem:string|null;result:string|null};
type M={id:string;title:string;held_at:string;minutes:string;decisions:string;follow_up_status:string};
type E={id:string;target_type:string;target_id:string;description:string|null;status:string;verified_at:string|null;review_note:string|null;created_at:string};
const day=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"});

export default function CommandLegacyParity({schoolId,userId,role,staff,focus}:{schoolId:string;userId:string;role:Role;staff:Staff[];focus:string}){
 const db=useMemo(()=>browserDb(),[]),manager=["owner","principal","vice_principal"].includes(role);
 const [programs,setPrograms]=useState<P[]>([]),[tasks,setTasks]=useState<T[]>([]),[meetings,setMeetings]=useState<M[]>([]),[evidence,setEvidence]=useState<E[]>([]);
 const [meetingId,setMeetingId]=useState(""),[programId,setProgramId]=useState(""),[title,setTitle]=useState(""),[pic,setPic]=useState(""),[due,setDue]=useState(day()),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 useRealtimeRefresh(schoolId,()=>load());
 async function load(){if(!db)return;const [p,t,m,e]=await Promise.all([
  readAllRows(db.from("sc_programs").select("id,title,status,deadline,pic_id,created_at").eq("school_id",schoolId).is("archived_at",null).order("created_at",{ascending:false}).order("id")),
  readAllRows(db.from("sc_program_tasks").select("id,program_id,title,status,pic_id,due_at,problem,result").eq("school_id",schoolId).is("archived_at",null).order("created_at",{ascending:false}).order("id")),
  readAllRows(db.from("sc_meetings").select("id,title,held_at,minutes,decisions,follow_up_status").eq("school_id",schoolId).is("archived_at",null).order("held_at",{ascending:false}).order("id")),
  readAllRows(db.from("sc_evidence").select("id,target_type,target_id,description,status,verified_at,review_note,created_at").eq("school_id",schoolId).order("created_at",{ascending:false}).order("id"))
 ]);setPrograms((p.data||[]) as P[]);setTasks((t.data||[]) as T[]);setMeetings((m.data||[]) as M[]);setEvidence((e.data||[]) as E[])}
 useEffect(()=>{void load()},[db,schoolId]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 const person=(id:string|null)=>staff.find(s=>s.user_id===id)?.name||"Belum ditugaskan";
 async function verify(e:E,approved:boolean){if(!db||!manager)return;await run(async()=>{const note=prompt(approved?"Catatan verifikasi (opsional)":"Alasan revisi")||null;const {error}=await db.from("sc_evidence").update({status:approved?"verified":"needs_revision",verified_by:userId,verified_at:approved?new Date().toISOString():null,review_note:note}).eq("id",e.id);if(error)throw error;setOk(approved?"Bukti diverifikasi.":"Bukti dikembalikan untuk revisi.")})}
 async function meetingTask(){if(!db||!meetingId||!programId||title.trim().length<3)return;await run(async()=>{const {error}=await db.from("sc_program_tasks").insert({school_id:schoolId,program_id:programId,title:title.trim(),pic_id:pic||null,due_at:due+"T23:59:00+07:00",status:"todo",created_by:userId});if(error)throw error;await db.from("sc_meetings").update({follow_up_status:"in_progress"}).eq("id",meetingId);setTitle("");setOk("Keputusan rapat menjadi tugas tindak lanjut.")})}
 const evidenceList=useRecordList(evidence,e=>[e.description,e.status,e.target_type,e.target_type==="program"?programs.find(p=>p.id===e.target_id)?.title:tasks.find(t=>t.id===e.target_id)?.title].join(" "));
 const meetingList=useRecordList(meetings,m=>[m.title,m.minutes,m.decisions].join(" "));
 const summary=programs.map(p=>{const pt=tasks.filter(t=>t.program_id===p.id),done=pt.filter(t=>t.status==="done").length,pe=evidence.filter(e=>e.target_type==="program"&&e.target_id===p.id),verified=pe.filter(e=>e.status==="verified").length;return {p,total:pt.length,done,progress:pt.length?Math.round(done/pt.length*100):0,evidence:pe.length,verified}});
 const summaryList=useRecordList(summary.map(x=>({...x,id:x.p.id,date:x.p.deadline||x.p.created_at})),x=>x.p.title);
 function programModel():OfficialReportModel{return {moduleKey:"command",documentType:"laporan_program",prefix:"PROG",title:"Laporan Program Kerja dan Progres Sekolah",subtitle:"Rekap program, PIC, tugas, kendala, hasil rapat dan verifikasi bukti",orientation:"landscape",status:"approved",metrics:[{label:"Jumlah program",value:String(programs.length)},{label:"Jumlah tugas",value:String(tasks.length)},{label:"Tugas selesai",value:String(tasks.filter(t=>t.status==="done").length)},{label:"Bukti terverifikasi",value:String(evidence.filter(e=>e.status==="verified").length)}],sections:[
  {title:"Rekap Program",columns:["Program","Status","Deadline","PIC","Tugas Selesai","Total Tugas","Progres","Bukti","Bukti Terverifikasi"],rows:summary.map(x=>[x.p.title,x.p.status,x.p.deadline||"—",person(x.p.pic_id),x.done,x.total,x.progress+"%",x.evidence,x.verified])},
  {title:"Rincian Tugas",columns:["Program","Tugas","Status","PIC","Deadline","Kendala","Hasil"],rows:tasks.map(t=>[programs.find(p=>p.id===t.program_id)?.title||"—",t.title,t.status,person(t.pic_id),t.due_at?.slice(0,10)||"—",t.problem||"—",t.result||"—"])},
  {title:"Hasil Rapat dan Tindak Lanjut",columns:["Rapat","Tanggal","Keputusan","Status Tindak Lanjut"],rows:meetings.map(m=>[m.title,m.held_at?.slice(0,10)||"—",m.decisions||"—",m.follow_up_status])}
 ]}}
 async function exportReport(format:"pdf"|"docx"|"xlsx"){if(!db)return;await run(async()=>{const identity=await loadReportIdentity(db,schoolId),model=programModel(),issued=await issueAndExport(db,schoolId,identity,model,format);setOk("Laporan "+issued.document_number+" diterbitkan dan masuk arsip.")})}
 async function previewReport(){if(!db)return;await run(async()=>{const identity=await loadReportIdentity(db,schoolId);previewOfficialReport(identity,{...programModel(),status:"draft"});setOk("Preview draft dibuka tanpa memakai nomor dokumen.")})}

 if(focus==="Verifikasi Bukti")return <section className="panel"><div className="sectionhead"><div><h2>Verifikasi Bukti Kegiatan</h2><p className="muted">Progres berbasis bukti: manajemen memverifikasi atau meminta revisi.</p></div><FileCheck2/></div><RecordListTools list={evidenceList} label="bukti kegiatan" busy={busy}/>{evidenceList.visible.map(e=><div className="entry" key={e.id}><div><strong>{e.target_type==="program"?programs.find(p=>p.id===e.target_id)?.title:tasks.find(t=>t.id===e.target_id)?.title||"Bukti kegiatan"}</strong><small>{recordDateKey(e.created_at)} · {e.description||"Tanpa keterangan"} · {e.status}</small>{e.review_note&&<p>{e.review_note}</p>}</div><div className="flow"><span className="pill">{e.status}</span>{manager&&e.status!=="verified"&&<><button className="button" onClick={()=>void verify(e,true)}><Check size={14}/> Verifikasi</button><button className="button secondary" onClick={()=>void verify(e,false)}>Revisi</button></>}</div></div>)}{!evidence.length&&<div className="empty">Belum ada bukti kegiatan.</div>}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;

 if(focus==="Tindak Lanjut Rapat")return <section className="panel"><div className="sectionhead"><div><h2>Tindak Lanjut Hasil Rapat</h2><p className="muted">Keputusan rapat dapat langsung diturunkan menjadi tugas, PIC dan deadline.</p></div><Plus/></div><div className="fields"><label className="field">Rapat<SearchableSelect label="Rapat" value={meetingId} onChange={e=>setMeetingId(e.target.value)}><option value="">Pilih rapat</option>{meetings.map(m=><option key={m.id} value={m.id}>{m.held_at?.slice(0,10)} · {m.title}</option>)}</SearchableSelect></label><label className="field">Program<SearchableSelect label="Program" value={programId} onChange={e=>setProgramId(e.target.value)}><option value="">Pilih program</option>{programs.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</SearchableSelect></label><label className="field full">Tugas tindak lanjut<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field">PIC<SearchableSelect label="PIC" value={pic} onChange={e=>setPic(e.target.value)}><option value="">Belum ditentukan</option>{staff.filter(s=>s.user_id).map(s=><option key={s.id} value={s.user_id!}>{s.name}</option>)}</SearchableSelect></label><label className="field">Deadline<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><button className="button" disabled={busy||!meetingId||!programId||title.trim().length<3} onClick={()=>void meetingTask()}>Buat Tugas</button></div><RecordListTools list={meetingList} label="rapat" busy={busy}/>{meetingList.visible.map(m=><div className="entry" key={m.id}><div><strong>{m.title}</strong><small>{m.held_at?.slice(0,10)} · {m.follow_up_status}</small><p>{m.decisions||"Belum ada keputusan."}</p></div></div>)}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;

 return <section className="panel"><div className="sectionhead"><div><h2>Laporan Program & Progres</h2><p className="muted">Dokumen formal program, PIC, tugas, keputusan rapat, kendala dan bukti terverifikasi.</p></div><div className="flow"><button className="button secondary" disabled={busy} onClick={()=>void previewReport()}>Preview Draft</button><button className="button secondary" disabled={busy} onClick={()=>void exportReport("xlsx")}><Download size={14}/> Excel</button><button className="button secondary" disabled={busy} onClick={()=>void exportReport("docx")}><Download size={14}/> Word</button><button className="button" disabled={busy} onClick={()=>void exportReport("pdf")}><Download size={14}/> PDF</button></div></div><RecordListTools list={summaryList} label="program" busy={busy}/>{summaryList.visible.map(x=><div className="entry" key={x.p.id}><div><strong>{x.p.title}</strong><small>PIC {person(x.p.pic_id)} · {x.done}/{x.total} tugas · {x.verified}/{x.evidence} bukti terverifikasi</small></div><span className="pill">{x.progress}%</span></div>)}{!summary.length&&<div className="empty">Belum ada program.</div>}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;
}
