"use client";
import {useEffect,useMemo,useState} from "react";
import {Check,Download,FileCheck2,Plus} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import {downloadExcel} from "@/lib/excel";
import {downloadCsv,downloadWord,printPdf,reportTable} from "@/lib/report-export";
import type {Role,Staff} from "@/lib/modules";

type P={id:string;title:string;status:string;deadline:string|null;pic_id:string|null};
type T={id:string;program_id:string;title:string;status:string;pic_id:string|null;due_at:string|null;problem:string|null;result:string|null};
type M={id:string;title:string;held_at:string;minutes:string;decisions:string;follow_up_status:string};
type E={id:string;target_type:string;target_id:string;description:string|null;status:string;verified_at:string|null;review_note:string|null};
type H={id:string;entity_type:"program"|"task";entity_id:string;action:string;status:string|null;summary:string|null;actor_id:string|null;created_at:string};
const day=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"});

export default function CommandLegacyParity({schoolId,userId,role,staff,focus}:{schoolId:string;userId:string;role:Role;staff:Staff[];focus:string}){
 const db=useMemo(()=>browserDb(),[]),manager=["owner","principal","vice_principal"].includes(role);
 const [programs,setPrograms]=useState<P[]>([]),[tasks,setTasks]=useState<T[]>([]),[meetings,setMeetings]=useState<M[]>([]),[evidence,setEvidence]=useState<E[]>([]),[history,setHistory]=useState<H[]>([]);
 const [meetingId,setMeetingId]=useState(""),[programId,setProgramId]=useState(""),[title,setTitle]=useState(""),[pic,setPic]=useState(""),[due,setDue]=useState(day()),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 async function load(){if(!db)return;const [p,t,m,e,h]=await Promise.all([
  db.from("sc_programs").select("id,title,status,deadline,pic_id").eq("school_id",schoolId).order("created_at",{ascending:false}),
  db.from("sc_program_tasks").select("id,program_id,title,status,pic_id,due_at,problem,result").eq("school_id",schoolId).order("created_at",{ascending:false}),
  db.from("sc_meetings").select("id,title,held_at,minutes,decisions,follow_up_status").eq("school_id",schoolId).order("held_at",{ascending:false}),
  db.from("sc_evidence").select("id,target_type,target_id,description,status,verified_at,review_note").eq("school_id",schoolId).order("created_at",{ascending:false}),
  db.from("sc_program_history").select("id,entity_type,entity_id,action,status,summary,actor_id,created_at").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(1000)
 ]);setPrograms((p.data||[]) as P[]);setTasks((t.data||[]) as T[]);setMeetings((m.data||[]) as M[]);setEvidence((e.data||[]) as E[]);setHistory((h.data||[]).map((x:any)=>({...x,id:String(x.id)})) as H[])}
 useEffect(()=>{void load()},[db,schoolId]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const person=(id:string|null)=>staff.find(s=>s.user_id===id)?.name||"Belum ditugaskan";
 async function verify(e:E,approved:boolean){if(!db||!manager)return;await run(async()=>{const note=prompt(approved?"Catatan verifikasi (opsional)":"Alasan revisi")||null;const {error}=await db.from("sc_evidence").update({status:approved?"verified":"needs_revision",verified_by:userId,verified_at:approved?new Date().toISOString():null,review_note:note}).eq("id",e.id);if(error)throw error;setOk(approved?"Bukti diverifikasi.":"Bukti dikembalikan untuk revisi.")})}
 async function meetingTask(){if(!db||!meetingId||!programId||title.trim().length<3)return;await run(async()=>{const {error}=await db.from("sc_program_tasks").insert({school_id:schoolId,program_id:programId,title:title.trim(),pic_id:pic||null,due_at:due+"T23:59:00+07:00",status:"todo",created_by:userId});if(error)throw error;await db.from("sc_meetings").update({follow_up_status:"in_progress"}).eq("id",meetingId);setTitle("");setOk("Keputusan rapat menjadi tugas tindak lanjut.")})}
 const summary=programs.map(p=>{const pt=tasks.filter(t=>t.program_id===p.id),done=pt.filter(t=>t.status==="done").length,pe=evidence.filter(e=>e.target_type==="program"&&e.target_id===p.id),verified=pe.filter(e=>e.status==="verified").length;return {p,total:pt.length,done,progress:pt.length?Math.round(done/pt.length*100):0,evidence:pe.length,verified}});
 async function exportReport(){await downloadExcel("laporan-program-school-control.xlsx",[{name:"Program",rows:summary.map(x=>({Program:x.p.title,Status:x.p.status,Deadline:x.p.deadline,PIC:person(x.p.pic_id),Tugas_Selesai:x.done,Total_Tugas:x.total,Progres:x.progress+"%",Bukti:x.evidence,Bukti_Terverifikasi:x.verified}))},{name:"Tugas",rows:tasks.map(t=>({Program:programs.find(p=>p.id===t.program_id)?.title||"",Tugas:t.title,Status:t.status,PIC:person(t.pic_id),Deadline:t.due_at?.slice(0,10),Kendala:t.problem,Hasil:t.result}))},{name:"Rapat",rows:meetings.map(m=>({Rapat:m.title,Tanggal:m.held_at?.slice(0,10),Keputusan:m.decisions,Tindak_Lanjut:m.follow_up_status}))},{name:"Riwayat Progres",rows:history.map(h=>({Waktu:h.created_at,Jenis:h.entity_type,Data:h.entity_type==="program"?programs.find(p=>p.id===h.entity_id)?.title||h.entity_id:tasks.find(t=>t.id===h.entity_id)?.title||h.entity_id,Aksi:h.action,Status:h.status||"",Ringkasan:h.summary||""}))}]);setOk("Laporan Excel dibuat.")}
 function portableReport(kind:"word"|"pdf"|"csv"){
  const programRows=summary.map(x=>[x.p.title,x.p.status,x.p.deadline||"",person(x.p.pic_id),x.done+"/"+x.total,x.progress+"%",x.verified+"/"+x.evidence]);
  const taskRows=tasks.map(t=>[programs.find(p=>p.id===t.program_id)?.title||"",t.title,t.status,person(t.pic_id),t.due_at?.slice(0,10)||"",t.problem||"",t.result||""]);
  const histRows=history.map(h=>[new Date(h.created_at).toLocaleString("id-ID"),h.entity_type,h.entity_type==="program"?programs.find(p=>p.id===h.entity_id)?.title||h.entity_id:tasks.find(t=>t.id===h.entity_id)?.title||h.entity_id,h.action,h.status||"",h.summary||""]);
  const html="<h2>Program</h2>"+reportTable(["Program","Status","Deadline","PIC","Tugas","Progres","Bukti"],programRows)+"<h2>Tugas</h2>"+reportTable(["Program","Tugas","Status","PIC","Deadline","Kendala","Hasil"],taskRows)+"<h2>Riwayat Progres</h2>"+reportTable(["Waktu","Jenis","Data","Aksi","Status","Ringkasan"],histRows);
  if(kind==="word")downloadWord("laporan-program-school-control.doc","Laporan Program & Progres",html);
  else if(kind==="pdf")printPdf("Laporan Program & Progres",html);
  else downloadCsv("laporan-program-school-control.csv",["Jenis","Kolom1","Kolom2","Kolom3","Kolom4","Kolom5","Kolom6","Kolom7"],[...programRows.map(r=>["Program",...r]),...taskRows.map(r=>["Tugas",...r]),...histRows.map(r=>["Riwayat",...r])]);
  setOk("Laporan "+kind.toUpperCase()+" dibuat.");
 }

 if(focus==="Verifikasi Bukti")return <section className="panel"><div className="sectionhead"><div><h2>Verifikasi Bukti Kegiatan</h2><p className="muted">Progres berbasis bukti: manajemen memverifikasi atau meminta revisi.</p></div><FileCheck2/></div>{evidence.map(e=><div className="entry" key={e.id}><div><strong>{e.target_type==="program"?programs.find(p=>p.id===e.target_id)?.title:tasks.find(t=>t.id===e.target_id)?.title||"Bukti kegiatan"}</strong><small>{e.description||"Tanpa keterangan"} · {e.status}</small>{e.review_note&&<p>{e.review_note}</p>}</div><div className="flow"><span className="pill">{e.status}</span>{manager&&e.status!=="verified"&&<><button className="button" onClick={()=>void verify(e,true)}><Check size={14}/> Verifikasi</button><button className="button secondary" onClick={()=>void verify(e,false)}>Revisi</button></>}</div></div>)}{!evidence.length&&<div className="empty">Belum ada bukti kegiatan.</div>}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;

 if(focus==="Riwayat Progres")return <section className="panel"><div className="sectionhead"><div><h2>Riwayat Perubahan Progres</h2><p className="muted">Setiap perubahan program dan tugas tersimpan otomatis sebagai timeline. Riwayat ini tidak bergantung pada status terakhir.</p></div><FileCheck2/></div>{history.map(h=><div className="entry" key={h.id}><div><strong>{h.entity_type==="program"?programs.find(p=>p.id===h.entity_id)?.title||"Program":tasks.find(t=>t.id===h.entity_id)?.title||"Tugas"}</strong><small>{new Date(h.created_at).toLocaleString("id-ID")} · {h.action} · {h.status||"—"}</small>{h.summary&&<p>{h.summary}</p>}</div><span className="pill">{h.entity_type}</span></div>)}{!history.length&&<div className="empty">Belum ada perubahan progres tercatat.</div>}</section>;

 if(focus==="Tindak Lanjut Rapat")return <section className="panel"><div className="sectionhead"><div><h2>Tindak Lanjut Hasil Rapat</h2><p className="muted">Keputusan rapat dapat langsung diturunkan menjadi tugas, PIC dan deadline.</p></div><Plus/></div><div className="fields"><label className="field">Rapat<select value={meetingId} onChange={e=>setMeetingId(e.target.value)}><option value="">Pilih rapat</option>{meetings.map(m=><option key={m.id} value={m.id}>{m.held_at?.slice(0,10)} · {m.title}</option>)}</select></label><label className="field">Program<select value={programId} onChange={e=>setProgramId(e.target.value)}><option value="">Pilih program</option>{programs.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label className="field full">Tugas tindak lanjut<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field">PIC<select value={pic} onChange={e=>setPic(e.target.value)}><option value="">Belum ditentukan</option>{staff.filter(s=>s.user_id).map(s=><option key={s.id} value={s.user_id!}>{s.name}</option>)}</select></label><label className="field">Deadline<input type="date" value={due} onChange={e=>setDue(e.target.value)}/></label><button className="button" disabled={busy||!meetingId||!programId||title.trim().length<3} onClick={()=>void meetingTask()}>Buat Tugas</button></div>{meetings.map(m=><div className="entry" key={m.id}><div><strong>{m.title}</strong><small>{m.held_at?.slice(0,10)} · {m.follow_up_status}</small><p>{m.decisions||"Belum ada keputusan."}</p></div></div>)}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;

 return <section className="panel"><div className="sectionhead"><div><h2>Laporan Program & Progres</h2><p className="muted">Tugas selesai, bukti terverifikasi dan timeline perubahan dihitung dari data aktual.</p></div><div className="flow"><button className="button" onClick={()=>void exportReport()}><Download size={14}/> Excel</button><button className="button secondary" onClick={()=>portableReport("word")}><Download size={14}/> Word</button><button className="button secondary" onClick={()=>portableReport("csv")}><Download size={14}/> CSV</button><button className="button secondary" onClick={()=>portableReport("pdf")}><Download size={14}/> PDF</button></div></div>{summary.map(x=><div className="entry" key={x.p.id}><div><strong>{x.p.title}</strong><small>PIC {person(x.p.pic_id)} · {x.done}/{x.total} tugas · {x.verified}/{x.evidence} bukti terverifikasi</small></div><span className="pill">{x.progress}%</span></div>)}{!summary.length&&<div className="empty">Belum ada program.</div>}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;
}
