"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {isAdmin,type Role,type Staff} from "@/lib/modules";
type Program={id:string;title:string;status:string;deadline:string|null;pic_id:string|null;owner_id:string|null};
type Task={id:string;program_id:string;title:string;status:string;pic_id:string|null;due_at:string|null;problem:string|null;result:string|null};
type Meeting={id:string;title:string;held_at:string;minutes:string;decisions:string};
type Agenda={id:string;title:string;event_date:string;category:string;notes:string|null};
type Evidence={id:string;target_type:string;target_id:string;file_path:string;description:string|null};
const localDay=()=>{const x=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const val=(t:string)=>x.find(y=>y.type===t)?.value||"";return val("year")+"-"+val("month")+"-"+val("day")};
export default function CommandBoard({schoolId,role,staff,userId,focus}:{schoolId:string;role:Role;staff:Staff[];userId:string;focus?:string}){
 const db=useMemo(()=>browserDb(),[]),manager=isAdmin(role);
 const [programs,setPrograms]=useState<Program[]>([]),[tasks,setTasks]=useState<Task[]>([]),[meetings,setMeetings]=useState<Meeting[]>([]),[agenda,setAgenda]=useState<Agenda[]>([]),[evidence,setEvidence]=useState<Evidence[]>([]);
 const [tab,setTab]=useState("program"),[title,setTitle]=useState(""),[date,setDate]=useState(localDay()),[pic,setPic]=useState(""),[programId,setProgramId]=useState(""),[notes,setNotes]=useState(""),[decisions,setDecisions]=useState(""),[problem,setProblem]=useState(""),[result,setResult]=useState(""),[category,setCategory]=useState("school"),[status,setStatus]=useState("ongoing"),[targetType,setTargetType]=useState("program"),[targetId,setTargetId]=useState(""),[file,setFile]=useState<File|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const staffName=(id:string|null)=>staff.find(x=>x.user_id===id)?.name||"Belum ditugaskan";
 async function load(){if(!db)return;const results=await Promise.all([
 db.from("sc_programs").select("id,title,status,deadline,pic_id,owner_id").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(100),
 db.from("sc_program_tasks").select("id,program_id,title,status,pic_id,due_at,problem,result").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(150),
 db.from("sc_meetings").select("id,title,held_at,minutes,decisions").eq("school_id",schoolId).order("held_at",{ascending:false}).limit(60),
 db.from("sc_calendar_events").select("id,title,event_date,category,notes").eq("school_id",schoolId).order("event_date",{ascending:false}).limit(70),
 db.from("sc_evidence").select("id,target_type,target_id,file_path,description").eq("school_id",schoolId).limit(150)
 ]);setPrograms((results[0].data||[]) as Program[]);setTasks((results[1].data||[]) as Task[]);setMeetings((results[2].data||[]) as Meeting[]);setAgenda((results[3].data||[]) as Agenda[]);setEvidence((results[4].data||[]) as Evidence[]);for(const r of results){if(r.error){setError(r.error.message);break}}}
 useEffect(()=>{void load()},[db,schoolId]);
 useEffect(()=>{const f=(focus||"").toLowerCase();if(f.includes("program")||f.includes("pic"))setTab("program");else if(f.includes("tugas")||f.includes("deadline")||f.includes("progres")||f.includes("kendala"))setTab("task");else if(f.includes("rapat"))setTab("meeting");else if(f.includes("agenda"))setTab("calendar");else if(f.includes("bukti"))setTab("evidence")},[focus]);
 async function job(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Data operasional tersimpan.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function insert(table:string,row:Record<string,unknown>){if(!db)throw Error("Database tidak terhubung.");const {error}=await db.from(table).insert({...row,school_id:schoolId});if(error)throw error}
 async function rpc(fn:string,args:Record<string,unknown>){if(!db)throw Error("Database tidak terhubung.");const {error}=await db.rpc(fn,args);if(error)throw error}
 async function upload(){if(!db||!file)throw Error("Pilih bukti yang ingin diunggah.");if(file.size>10*1024*1024)throw Error("Batas file 10 MB.");if(!targetId)throw Error("Pilih program atau tugas.");const path=schoolId+"/"+targetType+"/"+crypto.randomUUID()+"-"+file.name.replace(/[^\w.\-]/g,"_").slice(0,90);const {error:u}=await db.storage.from("sc-evidence").upload(path,file,{upsert:false,contentType:file.type});if(u)throw u;await insert("sc_evidence",{target_type:targetType,target_id:targetId,file_path:path,description:notes.trim()||null,uploaded_by:userId});setFile(null)}
 async function openEvidence(path:string){if(!db)return;const {data,error}=await db.storage.from("sc-evidence").createSignedUrl(path,60);if(error){setError(error.message);return}if(data?.signedUrl)window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 const pickStaff=<label className="field">PIC / Penanggung jawab<select value={pic} onChange={e=>setPic(e.target.value)}><option value="">Belum ditentukan</option>{staff.filter(s=>s.user_id).map(s=><option key={s.id} value={s.user_id!}>{s.name}</option>)}</select></label>;
 const nameField=<label className="field">Judul<input required maxLength={180} value={title} onChange={e=>setTitle(e.target.value)}/></label>;
 const dateField=<label className="field">Tanggal / Target<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label>;
 return <><div className="flow" style={{marginBottom:15}}>{[["program","Program & PIC"],["task","Tugas & Progres"],["meeting","Hasil Rapat"],["calendar","Agenda"],["evidence","Bukti Kegiatan"]].map(([k,n])=><button key={k} className={"button "+(tab===k?"":"secondary")} onClick={()=>setTab(k)}>{n}</button>)}</div>
 {tab==="program"&&<section className="panel"><h2>Program Sekolah</h2><p className="muted">Satu program memiliki PIC, tenggat, status dan bukti. Status diverifikasi manajemen setelah bukti tersedia.</p>{manager&&<form className="fields" onSubmit={e=>{e.preventDefault();void job(async()=>{await insert("sc_programs",{title:title.trim(),owner_id:userId,pic_id:pic||null,deadline:date,status:"planned"});setTitle("")})}}>{nameField}{dateField}{pickStaff}<button className="button" disabled={busy||!title.trim()}>Tambah Program</button></form>}{programs.map(p=><div className="entry" key={p.id}><div><strong>{p.title}</strong><small>{p.deadline||"Tanpa tanggal"} · PIC: {staffName(p.pic_id)} · {evidence.filter(x=>x.target_type==="program"&&x.target_id===p.id).length} bukti</small></div><div className="flow"><span className="pill">{p.status}</span>{manager&&<select value={p.status} disabled={busy} aria-label={"Status "+p.title} onChange={e=>void job(()=>rpc("sc_update_program",{p_school:schoolId,p_program:p.id,p_status:e.target.value,p_pic:p.pic_id,p_result:"Perubahan status melalui Command Pro"}))}>{["planned","ongoing","blocked","completed","verified"].map(z=><option key={z} value={z}>{z}</option>)}</select>}</div></div>)}{!programs.length&&<div className="empty">Belum ada program.</div>}</section>}
 {tab==="task"&&<section className="panel"><h2>Tugas dan Tindak Lanjut</h2><p className="muted">Tugas terkait program, memiliki PIC, tenggat, kendala dan hasil. PIC hanya mengubah tugasnya sendiri.</p>{role!=="viewer"&&<form className="fields" onSubmit={e=>{e.preventDefault();void job(async()=>{await insert("sc_program_tasks",{program_id:programId,title:title.trim(),pic_id:pic||null,due_at:date+"T23:59:00+07:00",created_by:userId});setTitle("")})}}><label className="field">Program<select required value={programId} onChange={e=>setProgramId(e.target.value)}><option value="">Pilih program</option>{programs.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>{nameField}{dateField}{pickStaff}<button className="button" disabled={busy||!programId||!title.trim()}>Tambah Tugas</button></form>}{tasks.map(t=><div className="entry" key={t.id}><div><strong>{t.title}</strong><small>{programs.find(p=>p.id===t.program_id)?.title} · PIC: {staffName(t.pic_id)} · {t.due_at?.slice(0,10)||"—"}</small><small>{t.problem?"Kendala: "+t.problem:""} {t.result?"Hasil: "+t.result:""}</small></div><div className="flow"><span className="pill">{t.status}</span>{(manager||t.pic_id===userId)&&<button className="button secondary" disabled={busy} onClick={()=>{const next=prompt("Status: todo / doing / blocked / review / done",t.status);if(!next)return;const prob=prompt("Kendala (opsional)",t.problem||"")||"";const res=prompt("Hasil (opsional)",t.result||"")||"";void job(()=>rpc("sc_decide_task",{p_school:schoolId,p_task:t.id,p_status:next,p_problem:prob,p_result:res}))}}>Perbarui</button>}</div></div>)}{!tasks.length&&<div className="empty">Belum ada tugas.</div>}</section>}
 {tab==="meeting"&&<section className="panel"><h2>Rapat dan Keputusan</h2>{role!=="viewer"&&<form className="fields" onSubmit={e=>{e.preventDefault();void job(async()=>{await insert("sc_meetings",{title:title.trim(),held_at:date+"T09:00:00+07:00",minutes:notes.trim(),decisions:decisions.trim(),created_by:userId});setTitle("");setNotes("");setDecisions("")})}}>{nameField}{dateField}<label className="field full">Notula<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="field full">Keputusan<textarea value={decisions} onChange={e=>setDecisions(e.target.value)}/></label><button className="button" disabled={busy||!title.trim()}>Simpan Rapat</button></form>}{meetings.map(m=><div className="entry" key={m.id}><div><strong>{m.title}</strong><small>{m.held_at.slice(0,10)} · Notula: {m.minutes||"—"} · Keputusan: {m.decisions||"—"}</small></div></div>)}</section>}
 {tab==="calendar"&&<section className="panel"><h2>Agenda Sekolah</h2>{role!=="viewer"&&<form className="fields" onSubmit={e=>{e.preventDefault();void job(async()=>{await insert("sc_calendar_events",{title:title.trim(),event_date:date,category,notes:notes.trim()||null,created_by:userId});setTitle("");setNotes("")})}}>{nameField}{dateField}<label className="field">Kategori<select value={category} onChange={e=>setCategory(e.target.value)}>{["school","teaching","meeting","training","other"].map(z=><option key={z} value={z}>{z}</option>)}</select></label><label className="field full">Keterangan<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="button" disabled={busy||!title.trim()}>Tambah Agenda</button></form>}{agenda.map(a=><div className="entry" key={a.id}><div><strong>{a.title}</strong><small>{a.event_date} · {a.category} · {a.notes||""}</small></div></div>)}</section>}
 {tab==="evidence"&&<section className="panel"><h2>Penyimpanan Bukti Privat</h2><p className="muted">File disimpan dalam bucket privat per sekolah; tautan hanya berlaku sementara. Pilih kegiatan sebelum mengunggah.</p>{role!=="viewer"&&<div className="fields"><label className="field">Jenis bukti<select value={targetType} onChange={e=>{setTargetType(e.target.value);setTargetId("")}}><option value="program">Program</option><option value="task">Tugas</option></select></label><label className="field">Kegiatan<select value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">Pilih kegiatan</option>{(targetType==="program"?programs:tasks).map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label className="field full">Lampiran<input type="file" accept=".jpg,.jpeg,.png,.webp,.pdf,.docx,.txt" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="button" disabled={busy||!file||!targetId} onClick={()=>void job(upload)}>Unggah Bukti</button></div>}{evidence.filter(e=>["program","task"].includes(e.target_type)).map(e=><div className="entry" key={e.id}><div><strong>{e.file_path.split("/").pop()}</strong><small>{e.target_type} · {e.description||""}</small></div><button className="button secondary" onClick={()=>void openEvidence(e.file_path)}>Lihat Berkas</button></div>)}</section>}
 {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
}
