"use client";
import {useRealtimeRefresh} from "@/lib/school-realtime";
import {readAllRows} from "@/lib/read-all-rows";
import SearchableSelect from "@/components/SearchableSelect";
import {errorMessage} from "@/lib/error-message";
import {useEffect,useMemo,useState} from "react";
import {Download,Plus,Upload} from "lucide-react";
import RecordListTools,{useRecordList,RecordCheckbox,type RecordBatchAction} from "@/components/RecordListTools";
import DataEntryModal from "@/components/DataEntryModal";
import {browserDb} from "@/lib/supabase";
import {downloadExcel,readExcel,type SheetRows} from "@/lib/excel";
import {isAdmin,type Role,type Staff} from "@/lib/modules";
type Program={id:string;title:string;status:string;deadline:string|null;pic_id:string|null;owner_id:string|null;archived_at:string|null};
type Task={id:string;program_id:string;title:string;status:string;pic_id:string|null;due_at:string|null;problem:string|null;result:string|null;archived_at:string|null};
type Meeting={id:string;title:string;held_at:string;minutes:string;decisions:string;archived_at:string|null};
type Agenda={id:string;title:string;event_date:string;category:string;notes:string|null};
type Evidence={id:string;target_type:string;target_id:string;file_path:string;description:string|null};
type ModalKind="program"|"task"|"meeting"|"calendar"|"evidence"|null;
const localDay=()=>{const x=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const val=(t:string)=>x.find(y=>y.type===t)?.value||"";return val("year")+"-"+val("month")+"-"+val("day")};
export default function CommandBoard({schoolId,role,staff,userId,focus}:{schoolId:string;role:Role;staff:Staff[];userId:string;focus?:string}){
 const db=useMemo(()=>browserDb(),[]),manager=isAdmin(role);
 const [programs,setPrograms]=useState<Program[]>([]),[tasks,setTasks]=useState<Task[]>([]),[meetings,setMeetings]=useState<Meeting[]>([]),[agenda,setAgenda]=useState<Agenda[]>([]),[evidence,setEvidence]=useState<Evidence[]>([]);
 const [tab,setTab]=useState("program"),[modal,setModal]=useState<ModalKind>(null),[title,setTitle]=useState(""),[date,setDate]=useState(localDay()),[pic,setPic]=useState(""),[programId,setProgramId]=useState(""),[notes,setNotes]=useState(""),[decisions,setDecisions]=useState(""),[category,setCategory]=useState("school"),[targetType,setTargetType]=useState("program"),[targetId,setTargetId]=useState(""),[file,setFile]=useState<File|null>(null);
 const [showArchive,setShowArchive]=useState(false);
 const [editingId,setEditingId]=useState<string|null>(null),[taskStatus,setTaskStatus]=useState("todo"),[taskProblem,setTaskProblem]=useState(""),[taskResult,setTaskResult]=useState("");
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState(""),[importRows,setImportRows]=useState<SheetRows>([]),[importFile,setImportFile]=useState("");
 const staffName=(id:string|null)=>staff.find(x=>x.user_id===id)?.name||"Belum ditugaskan";
 useRealtimeRefresh(schoolId,()=>load());
 async function load(){if(!db)return;const results=await Promise.all([
  readAllRows(db.from("sc_programs").select("id,title,status,deadline,pic_id,owner_id,archived_at").eq("school_id",schoolId).order("created_at",{ascending:false}).order("id")),
  readAllRows(db.from("sc_program_tasks").select("id,program_id,title,status,pic_id,due_at,problem,result,archived_at").eq("school_id",schoolId).order("created_at",{ascending:false}).order("id")),
  readAllRows(db.from("sc_meetings").select("id,title,held_at,minutes,decisions,archived_at").eq("school_id",schoolId).order("held_at",{ascending:false}).order("id")),
  readAllRows(db.from("sc_calendar_events").select("id,title,event_date,category,notes").eq("school_id",schoolId).order("event_date",{ascending:false}).order("id")),
  readAllRows(db.from("sc_evidence").select("id,target_type,target_id,file_path,description").eq("school_id",schoolId).order("id"))
 ]);setPrograms((results[0].data||[]) as Program[]);setTasks((results[1].data||[]) as Task[]);setMeetings((results[2].data||[]) as Meeting[]);setAgenda((results[3].data||[]) as Agenda[]);setEvidence((results[4].data||[]) as Evidence[]);for(const r of results){if(r.error){setError(r.error.message);break}}}
 useEffect(()=>{void load()},[db,schoolId]);
 useEffect(()=>{const f=(focus||"").toLowerCase();setModal(null);if(f.includes("program")||f.includes("pic"))setTab("program");else if(f.includes("tugas")||f.includes("deadline")||f.includes("progres")||f.includes("kendala"))setTab("task");else if(f.includes("rapat"))setTab("meeting");else if(f.includes("agenda"))setTab("calendar");else if(f.includes("bukti"))setTab("evidence")},[focus]);
 async function job(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Data operasional tersimpan.")}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function insert(table:string,row:Record<string,unknown>){if(!db)throw Error("Database tidak terhubung.");const {error}=await db.from(table).insert({...row,school_id:schoolId});if(error)throw error}
 async function rpc(fn:string,args:Record<string,unknown>){if(!db)throw Error("Database tidak terhubung.");const {error}=await db.rpc(fn,args);if(error)throw error}
 async function editEntity(entity:string,id:string,patch:Record<string,unknown>){await job(()=>rpc("sc_update_operational",{p_school:schoolId,p_entity:entity,p_id:id,p_patch:patch}))}
 async function archiveEntity(entity:string,id:string,archive:boolean){await job(()=>rpc("sc_archive_operational",{p_school:schoolId,p_entity:entity,p_id:id,p_archive:archive}))}
 async function deleteEntity(entity:string,id:string){if(!confirm("Hapus permanen data ini? Tindakan tidak dapat dibatalkan dan akan dicatat di audit log."))return;await job(()=>rpc("sc_delete_operational",{p_school:schoolId,p_entity:entity,p_id:id}))}
 async function upload(){if(!db||!file)throw Error("Pilih bukti yang ingin diunggah.");if(file.size>10*1024*1024)throw Error("Batas file 10 MB.");if(!targetId)throw Error("Pilih program atau tugas.");const path=schoolId+"/"+targetType+"/"+crypto.randomUUID()+"-"+file.name.replace(/[^\w.\-]/g,"_").slice(0,90);const {error:u}=await db.storage.from("sc-evidence").upload(path,file,{upsert:false,contentType:file.type});if(u)throw u;await insert("sc_evidence",{target_type:targetType,target_id:targetId,file_path:path,description:notes.trim()||null,uploaded_by:userId});setFile(null);setNotes("");setModal(null)}
 async function openEvidence(path:string){if(!db)return;const {data,error}=await db.storage.from("sc-evidence").createSignedUrl(path,60);if(error){setError(error.message);return}if(data?.signedUrl)window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 const pickStaff=<label className="field">PIC / Penanggung jawab<SearchableSelect label="PIC / Penanggung jawab" value={pic} onChange={e=>setPic(e.target.value)}><option value="">Belum ditentukan</option>{staff.filter(s=>s.user_id).map(s=><option key={s.id} value={s.user_id!}>{s.name}</option>)}</SearchableSelect></label>;
 function open(kind:Exclude<ModalKind,null>){setEditingId(null);setTaskStatus("todo");setTaskProblem("");setTaskResult("");setTitle("");setDate(localDay());setPic("");setProgramId("");setNotes("");setDecisions("");setCategory("school");setTargetType("program");setTargetId("");setFile(null);setModal(kind)}
 function editProgram(p:Program){open("program");setEditingId(p.id);setTitle(p.title);setDate(p.deadline||"");setPic(p.pic_id||"")}
 function editTask(t:Task){open("task");setEditingId(t.id);setTitle(t.title);setDate(t.due_at?.slice(0,10)||"");setPic(t.pic_id||"");setProgramId(t.program_id);setTaskStatus(t.status);setTaskProblem(t.problem||"");setTaskResult(t.result||"")}
 function editMeeting(m:Meeting){open("meeting");setEditingId(m.id);setTitle(m.title);setDate(m.held_at.slice(0,10));setNotes(m.minutes);setDecisions(m.decisions)}
 function editAgenda(a:Agenda){open("calendar");setEditingId(a.id);setTitle(a.title);setDate(a.event_date);setCategory(a.category);setNotes(a.notes||"")}
 const canAdd=role!=="viewer"&&(tab!=="program"||manager);
 const modalKind:ModalKind=tab==="program"?"program":tab==="task"?"task":tab==="meeting"?"meeting":tab==="calendar"?"calendar":"evidence";
 const heading=tab==="program"?(focus==="PIC"?"Penanggung Jawab Program":"Program Sekolah"):tab==="task"?(["Deadline","Progres","Kendala"].includes(focus||"")?focus!:"Tugas & Tindak Lanjut"):tab==="meeting"?"Rapat & Keputusan":tab==="calendar"?"Agenda Program":"Bukti Kegiatan";
 async function templateExcel(){if(tab==="evidence")return;const guide=[{Ketentuan:"Gunakan nama PIC yang sudah ada pada Data Induk. Hapus baris contoh sebelum import. Tanggal memakai format YYYY-MM-DD."}];if(tab==="program")return downloadExcel("template-program-kerja-school-control.xlsx",[{name:"PROGRAM",rows:[{Program:"Program Literasi",PIC:"Nama Guru",Deadline:localDay(),Status:"planned"}]},{name:"Panduan",rows:guide}]);if(tab==="task")return downloadExcel("template-tugas-program-school-control.xlsx",[{name:"TUGAS",rows:[{Program:"Program Literasi",Tugas:"Koordinasi tim",PIC:"Nama Guru",Deadline:localDay(),Status:"todo",Kendala:"",Hasil:""}]},{name:"Panduan",rows:guide}]);if(tab==="meeting")return downloadExcel("template-rapat-school-control.xlsx",[{name:"RAPAT",rows:[{Rapat:"Rapat Evaluasi",Tanggal:localDay(),Notula:"Pokok pembahasan",Keputusan:"Keputusan rapat"}]},{name:"Panduan",rows:guide}]);return downloadExcel("template-agenda-program-school-control.xlsx",[{name:"AGENDA",rows:[{Agenda:"Pelaksanaan Program Literasi",Tanggal:localDay(),Kategori:"program",Keterangan:"Keterangan agenda"}]},{name:"Panduan",rows:guide}])}
 async function readImport(file?:File){if(!file||tab==="evidence")return;setError("");try{if(file.size>8_000_000)throw Error("File maksimal 8 MB.");const rr=await readExcel(file);if(rr.length>2000)throw Error("Maksimal 2.000 baris per import.");setImportRows(rr);setImportFile(file.name);setOk(file.name+" siap diimport · "+rr.length+" baris.")}catch(e){setError(errorMessage(e))}}
 async function commitImport(){if(!db||!importRows.length||tab==="evidence")return;setBusy(true);setError("");setOk("");try{let imported=0,skipped=0;for(const raw of importRows){if(tab==="program"){if(!manager){skipped++;continue}const name=String(raw.Program||raw.Nama_Program||raw.title||"").trim(),deadline=String(raw.Deadline||raw.deadline||"").slice(0,10),status=String(raw.Status||raw.status||"planned").trim(),picName=String(raw.PIC||raw.pic||"").trim(),person=picName?staff.find(s=>s.name.trim().toLowerCase()===picName.toLowerCase()&&s.user_id):undefined;if(!name||!["planned","ongoing","blocked","completed","verified"].includes(status)|| (deadline&&!/^\d{4}-\d{2}-\d{2}$/.test(deadline)) || (picName&&!person)){skipped++;continue}await insert("sc_programs",{title:name,owner_id:userId,pic_id:person?.user_id||null,deadline:deadline||null,status});imported++;continue}
 if(tab==="task"){const programName=String(raw.Program||raw.program||"").trim(),name=String(raw.Tugas||raw.Task||raw.title||"").trim(),deadline=String(raw.Deadline||raw.deadline||"").slice(0,10),status=String(raw.Status||raw.status||"todo").trim(),picName=String(raw.PIC||raw.pic||"").trim(),program=programs.find(p=>p.title.trim().toLowerCase()===programName.toLowerCase()),person=picName?staff.find(s=>s.name.trim().toLowerCase()===picName.toLowerCase()&&s.user_id):undefined;if(!program||!name||!["todo","doing","blocked","review","done"].includes(status)||(deadline&&!/^\d{4}-\d{2}-\d{2}$/.test(deadline))||(picName&&!person)){skipped++;continue}await insert("sc_program_tasks",{program_id:program.id,title:name,pic_id:person?.user_id||null,due_at:deadline?deadline+"T23:59:00+07:00":null,status,problem:String(raw.Kendala||raw.problem||"").trim()||null,result:String(raw.Hasil||raw.result||"").trim()||null,created_by:userId});imported++;continue}
 if(tab==="meeting"){const name=String(raw.Rapat||raw.Nama_Rapat||raw.title||"").trim(),day=String(raw.Tanggal||raw.date||"").slice(0,10);if(!name||!/^\d{4}-\d{2}-\d{2}$/.test(day)){skipped++;continue}await insert("sc_meetings",{title:name,held_at:day+"T09:00:00+07:00",minutes:String(raw.Notula||raw.minutes||"").trim(),decisions:String(raw.Keputusan||raw.decisions||"").trim(),created_by:userId});imported++;continue}
 const name=String(raw.Agenda||raw.Nama_Agenda||raw.title||"").trim(),day=String(raw.Tanggal||raw.date||"").slice(0,10),cat=String(raw.Kategori||raw.category||"program").trim();if(!name||!/^\d{4}-\d{2}-\d{2}$/.test(day)||!["school","teaching","meeting","training","program","other"].includes(cat)){skipped++;continue}await insert("sc_calendar_events",{title:name,event_date:day,category:cat,notes:String(raw.Keterangan||raw.Catatan||raw.notes||"").trim()||null,created_by:userId,scope:"school",owner_user_id:userId});imported++}
 await db.from("sc_import_history").insert({school_id:schoolId,module_key:"command",import_kind:tab,file_name:importFile||"import.xlsx",row_count:importRows.length,imported_count:imported,skipped_count:skipped,details:{target:tab}});setImportRows([]);setImportFile("");await load();setOk("Import "+heading+" selesai: "+imported+" masuk, "+skipped+" dilewati.")}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 const taskRows=tasks.filter(t=>Boolean(t.archived_at)===showArchive).filter(t=>focus!=="Kendala"||t.status==="blocked"||Boolean(t.problem?.trim())).sort((a,b)=>focus==="Deadline"?(a.due_at||"9999").localeCompare(b.due_at||"9999"):0);
 const programProgress=programs.filter(p=>Boolean(p.archived_at)===showArchive).map(p=>{const list=tasks.filter(t=>t.program_id===p.id&&!t.archived_at),done=list.filter(t=>t.status==="done").length;return {p,total:list.length,done,blocked:list.filter(t=>t.status==="blocked").length,percent:list.length?Math.round(done/list.length*100):0}});
 async function exportExcel(){if(tab==="program")return downloadExcel("program-kerja-school-control.xlsx",[{name:"PROGRAM",rows:programs.map(p=>({Program:p.title,PIC:staffName(p.pic_id),Deadline:p.deadline||"",Status:p.status}))}]);if(tab==="task")return downloadExcel("tugas-program-school-control.xlsx",[{name:"TUGAS",rows:tasks.map(t=>({Program:programs.find(p=>p.id===t.program_id)?.title||"",Tugas:t.title,PIC:staffName(t.pic_id),Deadline:t.due_at?.slice(0,10)||"",Status:t.status,Kendala:t.problem||"",Hasil:t.result||""}))}]);if(tab==="meeting")return downloadExcel("rapat-school-control.xlsx",[{name:"RAPAT",rows:meetings.map(m=>({Rapat:m.title,Tanggal:m.held_at.slice(0,10),Notula:m.minutes,Keputusan:m.decisions}))}]);if(tab==="calendar")return downloadExcel("agenda-program-school-control.xlsx",[{name:"AGENDA",rows:agenda.map(a=>({Agenda:a.title,Tanggal:a.event_date,Kategori:a.category,Keterangan:a.notes||""}))}])}
 const records=tab==="program"?programs.filter(p=>Boolean(p.archived_at)===showArchive).map(p=>({id:p.id,text:p.title+" "+staffName(p.pic_id),status:p.status})):tab==="task"?taskRows.map(t=>({id:t.id,text:[t.title,staffName(t.pic_id),t.problem,t.result,programs.find(p=>p.id===t.program_id)?.title].join(" "),status:t.status})):tab==="meeting"?meetings.filter(m=>Boolean(m.archived_at)===showArchive).map(m=>({id:m.id,text:[m.title,m.minutes,m.decisions].join(" "),status:""})):tab==="calendar"?agenda.map(a=>({id:a.id,text:[a.title,a.notes,a.category].join(" "),status:a.category})):evidence.filter(e=>["program","task"].includes(e.target_type)).map(e=>({id:e.id,text:[e.file_path,e.description].join(" "),status:e.target_type}));
 const list=useRecordList(records,x=>x.text,[{key:"status",label:"Filter status",options:[...new Set(records.map(x=>x.status).filter(Boolean))].map(x=>({value:x,label:x})),value:x=>x.status}]);const pageIds=new Set(list.visible.map(x=>x.id));
 const batchActions:RecordBatchAction[]=["program","task","meeting"].includes(tab)?[{key:"archive",label:showArchive?"Pulihkan pilihan":"Arsipkan pilihan",description:"Status arsip berubah; data serta hubungan ke program tetap tersimpan.",run:id=>rpc("sc_archive_operational",{p_school:schoolId,p_entity:tab,p_id:id,p_archive:!showArchive})},...(showArchive?[{key:"delete",label:"Hapus permanen pilihan",description:"Hapus arsip yang dipilih. Riwayat dan relasi yang dilindungi akan ditolak sistem.",danger:true,run:(id:string)=>rpc("sc_delete_operational",{p_school:schoolId,p_entity:tab,p_id:id})}]:[])]:[];
 return <>
  <section className="panel"><div className="sectionhead"><div><h2>{heading}</h2><p className="muted">{tab==="program"?"Kelola program, PIC, tenggat, status dan bukti.":tab==="task"?"Tugas ditautkan ke program, PIC, tenggat, kendala dan hasil.":tab==="meeting"?"Notula dan keputusan rapat terdokumentasi.":tab==="calendar"?"Agenda operasional program yang juga masuk kalender sekolah.":"Unggah bukti privat yang terkait program atau tugas."}</p></div><div className="flow">{["program","task","meeting"].includes(tab)&&<button className="button secondary" onClick={()=>setShowArchive(value=>!value)}>{showArchive?"Lihat data aktif":"Lihat arsip"}</button>}{tab!=="evidence"&&<><button className="button secondary" onClick={()=>void templateExcel()}><Download size={14}/> Template</button><label className="button secondary"><Upload size={14}/> Import Excel<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>void readImport(e.target.files?.[0])}/></label><button className="button secondary" onClick={()=>void exportExcel()}><Download size={14}/> Export</button></>}{canAdd&&<button className="button" onClick={()=>open(modalKind as Exclude<ModalKind,null>)}>{tab==="evidence"?<Upload size={15}/>:<Plus size={15}/>} {tab==="evidence"?"Unggah Bukti":"Tambah Data"}</button>}</div></div>{importRows.length>0&&<div className="banner"><strong>{importFile} · {importRows.length} baris siap untuk {heading}</strong><div className="flow" style={{marginTop:8}}><button className="button" disabled={busy} onClick={()=>void commitImport()}>Proses Import</button><button className="button secondary" onClick={()=>{setImportRows([]);setImportFile("")}}>Batal</button></div></div>}
   <RecordListTools list={list} label="program/tugas" actions={batchActions} canSelect={manager&&batchActions.length>0} onRefresh={load} busy={busy}/>
   {tab==="program"&&<>{focus==="PIC"&&<div className="grid">{[{id:"",name:"Belum ditugaskan"},...staff.filter(s=>s.user_id).map(s=>({id:s.user_id!,name:s.name}))].map(person=>{const owned=programs.filter(p=>!p.archived_at&&(p.pic_id||"")===person.id),assigned=tasks.filter(t=>!t.archived_at&&(t.pic_id||"")===person.id);return <div className="card" key={person.id}><label>{person.name}</label><strong>{owned.length} program</strong><small>{assigned.length} tugas · {assigned.filter(t=>t.status==="done").length} selesai</small>{owned.map(p=><p key={p.id}>{p.title}</p>)}</div>})}</div>}{programs.filter(p=>Boolean(p.archived_at)===showArchive&&pageIds.has(p.id)).map(p=><div className="entry" key={p.id}>{manager&&<RecordCheckbox list={list} id={p.id} label={p.title} disabled={busy}/>}<div className="record-main"><strong>{p.title}</strong><small>{p.deadline||"Tanpa tanggal"} · PIC: {staffName(p.pic_id)} · {evidence.filter(x=>x.target_type==="program"&&x.target_id===p.id).length} bukti</small></div><div className="flow"><span className="pill">{p.status}</span>{focus==="PIC"&&manager&&<select disabled={busy} aria-label={"PIC "+p.title} value={p.pic_id||""} onChange={e=>void job(()=>rpc("sc_update_program",{p_school:schoolId,p_program:p.id,p_status:p.status,p_pic:e.target.value||null,p_result:"Penetapan PIC"}))}><option value="">Belum ditugaskan</option>{staff.filter(s=>s.user_id).map(s=><option key={s.id} value={s.user_id!}>{s.name}</option>)}</select>}{manager&&<button className="button secondary" onClick={()=>editProgram(p)}>Edit</button>}{manager&&<button className="button secondary" disabled={busy} onClick={()=>void archiveEntity("program",p.id,!p.archived_at)}>{p.archived_at?"Pulihkan":"Arsipkan"}</button>}{manager&&p.archived_at&&<button className="button danger" disabled={busy} onClick={()=>void deleteEntity("program",p.id)}>Hapus permanen</button>}{manager&&<select value={p.status} disabled={busy} aria-label={"Status "+p.title} onChange={e=>void job(()=>rpc("sc_update_program",{p_school:schoolId,p_program:p.id,p_status:e.target.value,p_pic:p.pic_id,p_result:"Perubahan status melalui Program, Tugas & Agenda"}))}>{["planned","ongoing","blocked","completed","verified"].map(z=><option key={z} value={z}>{z}</option>)}</select>}</div></div>)}{!programs.filter(p=>Boolean(p.archived_at)===showArchive).length&&<div className="empty">{showArchive?"Belum ada program di arsip.":"Belum ada program aktif."}</div>}</>}
   {tab==="task"&&<>{focus==="Progres"&&<div className="grid">{programProgress.map(x=><div className="card" key={x.p.id}><label>{x.p.title}</label><strong>{x.percent}%</strong><small>{x.done}/{x.total} tugas selesai · {x.blocked} terhambat</small></div>)}</div>}{focus==="Deadline"&&<div className="banner">Tugas diurutkan berdasarkan deadline terdekat. Tugas selesai tetap tersimpan untuk riwayat.</div>}{taskRows.filter(t=>pageIds.has(t.id)).map(t=><div className="entry" key={t.id}>{manager&&<RecordCheckbox list={list} id={t.id} label={t.title} disabled={busy}/>}<div className="record-main"><strong>{t.title}</strong><small>{programs.find(p=>p.id===t.program_id)?.title||"Program"} · PIC: {staffName(t.pic_id)} · {t.due_at?.slice(0,10)||"—"}</small><small>{focus==="Deadline"&&t.due_at&&t.status!=="done"&&new Date(t.due_at).getTime()<Date.now()?"Melewati deadline · ":""}{t.problem?"Kendala: "+t.problem:""} {t.result?"Hasil: "+t.result:""}</small></div><div className="flow"><span className="pill">{t.status}</span>{(manager||t.pic_id===userId)&&<button className="button secondary" disabled={busy} onClick={()=>editTask(t)}>Perbarui</button>}{(manager||t.pic_id===userId)&&<button className="button secondary" onClick={()=>editTask(t)}>Edit</button>}{(manager||t.pic_id===userId)&&<button className="button secondary" disabled={busy} onClick={()=>void archiveEntity("task",t.id,!t.archived_at)}>{t.archived_at?"Pulihkan":"Arsipkan"}</button>}{(manager||t.pic_id===userId)&&t.archived_at&&<button className="button danger" disabled={busy} onClick={()=>void deleteEntity("task",t.id)}>Hapus permanen</button>}</div></div>)}{!taskRows.length&&<div className="empty">{showArchive?"Belum ada tugas di arsip.":"Belum ada tugas aktif."}</div>}</>}
   {tab==="meeting"&&<>{meetings.filter(m=>Boolean(m.archived_at)===showArchive&&pageIds.has(m.id)).map(m=><div className="entry" key={m.id}>{manager&&<RecordCheckbox list={list} id={m.id} label={m.title} disabled={busy}/>}<div className="record-main"><strong>{m.title}</strong><small>{m.held_at.slice(0,10)} · Notula: {m.minutes||"—"} · Keputusan: {m.decisions||"—"}</small></div><div className="flow"><button className="button secondary" onClick={()=>editMeeting(m)}>Edit</button>{role!=="viewer"&&<button className="button secondary" disabled={busy} onClick={()=>void archiveEntity("meeting",m.id,!m.archived_at)}>{m.archived_at?"Pulihkan":"Arsipkan"}</button>}{role!=="viewer"&&m.archived_at&&<button className="button danger" disabled={busy} onClick={()=>void deleteEntity("meeting",m.id)}>Hapus permanen</button>}</div></div>)}{!meetings.filter(m=>Boolean(m.archived_at)===showArchive).length&&<div className="empty">{showArchive?"Belum ada rapat di arsip.":"Belum ada rapat aktif."}</div>}</>}
   {tab==="calendar"&&<>{agenda.filter(a=>pageIds.has(a.id)).map(a=><div className="entry" key={a.id}><div><strong>{a.title}</strong><small>{a.event_date} · {a.category} · {a.notes||""}</small></div><div className="flow"><button className="button secondary" onClick={()=>editAgenda(a)}>Edit</button><button className="button danger" onClick={()=>void deleteEntity("calendar",a.id)}>Hapus</button></div></div>)}{!agenda.length&&<div className="empty">Belum ada agenda.</div>}</>}
   {tab==="evidence"&&<>{evidence.filter(e=>["program","task"].includes(e.target_type)&&pageIds.has(e.id)).map(e=><div className="entry" key={e.id}><div><strong>{e.file_path.split("/").pop()}</strong><small>{e.target_type} · {e.description||""}</small></div><button className="button secondary" onClick={()=>void openEvidence(e.file_path)}>Lihat Berkas</button></div>)}{!evidence.length&&<div className="empty">Belum ada bukti kegiatan.</div>}</>}
  </section>
  <DataEntryModal open={modal==="program"} onClose={()=>setModal(null)} title={editingId?"Edit Program Kerja":"Tambah Program Kerja"} subtitle="Tetapkan nama program, PIC, dan tenggat sejak awal.">{error&&<div className="banner error" role="alert">{error}</div>}<div className="fields"><label className="field full">Nama Program<input value={title} onChange={e=>setTitle(e.target.value)} autoFocus/></label><label className="field">Tenggat<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{pickStaff}</div><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Batal</button><button className="button" disabled={busy||!title.trim()} onClick={()=>void job(async()=>{if(title.trim().length<3)throw Error("Judul program minimal 3 karakter.");if(editingId)await rpc("sc_save_command_record",{p_school:schoolId,p_entity:"program",p_id:editingId,p_patch:{title:title.trim(),pic_id:pic||null,deadline:date}});else await insert("sc_programs",{title:title.trim(),owner_id:userId,pic_id:pic||null,deadline:date||null,status:"planned"});setModal(null)})}>Simpan Program</button></div></DataEntryModal>
  <DataEntryModal open={modal==="task"} onClose={()=>setModal(null)} title={editingId?"Edit Tugas":"Tambah Tugas"} subtitle="Hubungkan tugas ke program, pilih PIC, dan tentukan deadline.">{error&&<div className="banner error" role="alert">{error}</div>}<div className="fields"><label className="field full">Program<SearchableSelect label="Program" disabled={Boolean(editingId)} value={programId} onChange={e=>setProgramId(e.target.value)}><option value="">Pilih program</option>{programs.filter(p=>!p.archived_at||p.id===programId).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</SearchableSelect></label><label className="field full">Judul Tugas<input value={title} onChange={e=>setTitle(e.target.value)} autoFocus/></label><label className="field">Deadline<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{pickStaff}{editingId&&<><label className="field">Status<SearchableSelect label="Status" value={taskStatus} onChange={e=>setTaskStatus(e.target.value)}>{["todo","doing","blocked","review","done"].map(status=><option key={status}>{status}</option>)}</SearchableSelect></label><label className="field full">Kendala<textarea value={taskProblem} onChange={e=>setTaskProblem(e.target.value)}/></label><label className="field full">Hasil<textarea value={taskResult} onChange={e=>setTaskResult(e.target.value)}/></label></>}</div><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Batal</button><button className="button" disabled={busy||!programId||!title.trim()} onClick={()=>void job(async()=>{if(title.trim().length<3)throw Error("Judul tugas minimal 3 karakter.");if(editingId){await rpc("sc_save_command_record",{p_school:schoolId,p_entity:"task",p_id:editingId,p_patch:{title:title.trim(),pic_id:pic||null,due_at:date?date+"T23:59:00+07:00":null,problem:taskProblem,result:taskResult,status:taskStatus}})}else await insert("sc_program_tasks",{program_id:programId,title:title.trim(),pic_id:pic||null,due_at:date?date+"T23:59:00+07:00":null,created_by:userId});setModal(null)})}>Simpan Tugas</button></div></DataEntryModal>
  <DataEntryModal open={modal==="meeting"} onClose={()=>setModal(null)} title={editingId?"Edit Rapat & Keputusan":"Catat Rapat & Keputusan"} subtitle="Dokumentasikan agenda rapat, tanggal, notula, dan keputusan akhir.">{error&&<div className="banner error" role="alert">{error}</div>}<div className="fields"><label className="field full">Nama / Agenda Rapat<input value={title} onChange={e=>setTitle(e.target.value)} autoFocus/></label><label className="field">Tanggal<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field full">Notula<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={6}/></label><label className="field full">Keputusan<textarea value={decisions} onChange={e=>setDecisions(e.target.value)} rows={4}/></label></div><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Batal</button><button className="button" disabled={busy||!title.trim()} onClick={()=>void job(async()=>{if(title.trim().length<3||!date)throw Error("Isi judul rapat minimal 3 karakter dan tanggal.");if(editingId)await rpc("sc_save_command_record",{p_school:schoolId,p_entity:"meeting",p_id:editingId,p_patch:{title:title.trim(),held_at:date+"T09:00:00+07:00",minutes:notes.trim(),decisions:decisions.trim()}});else await insert("sc_meetings",{title:title.trim(),held_at:date+"T09:00:00+07:00",minutes:notes.trim(),decisions:decisions.trim(),created_by:userId});setModal(null)})}>Simpan Rapat</button></div></DataEntryModal>
  <DataEntryModal open={modal==="calendar"} onClose={()=>setModal(null)} title={editingId?"Edit Agenda Program":"Tambah Agenda Program"} subtitle="Agenda ini ikut masuk ke kalender sekolah. Untuk peserta dan presensi agenda gunakan menu Agenda Sekolah.">{error&&<div className="banner error" role="alert">{error}</div>}<div className="fields"><label className="field full">Nama Agenda<input value={title} onChange={e=>setTitle(e.target.value)} autoFocus/></label><label className="field">Tanggal<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Kategori<SearchableSelect label="Kategori" value={category} onChange={e=>setCategory(e.target.value)}><option value="school">Sekolah</option><option value="teaching">Pembelajaran</option><option value="meeting">Rapat</option><option value="training">Pelatihan</option><option value="program">Program</option><option value="other">Lainnya</option></SearchableSelect></label><label className="field full">Keterangan<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={5}/></label></div><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Batal</button><button className="button" disabled={busy||!title.trim()} onClick={()=>void job(async()=>{if(title.trim().length<3||!date)throw Error("Isi judul agenda minimal 3 karakter dan tanggal.");if(editingId)await rpc("sc_save_command_record",{p_school:schoolId,p_entity:"calendar",p_id:editingId,p_patch:{title:title.trim(),event_date:date,category,notes:notes.trim()}});else await insert("sc_calendar_events",{title:title.trim(),event_date:date,category,notes:notes.trim()||null,created_by:userId,scope:"school",owner_user_id:userId});setModal(null)})}>Simpan Agenda</button></div></DataEntryModal>
  <DataEntryModal open={modal==="evidence"} onClose={()=>setModal(null)} title="Unggah Bukti Kegiatan" subtitle="File disimpan privat dan hanya dibuka menggunakan tautan sementara."><div className="fields"><label className="field">Jenis bukti<SearchableSelect label="Jenis bukti" value={targetType} onChange={e=>{setTargetType(e.target.value);setTargetId("")}}><option value="program">Program</option><option value="task">Tugas</option></SearchableSelect></label><label className="field">Kegiatan<SearchableSelect label="Kegiatan" value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">Pilih kegiatan</option>{(targetType==="program"?programs:tasks).map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</SearchableSelect></label><label className="field full">Keterangan bukti<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3}/></label><label className="field full">Lampiran<input type="file" accept=".jpg,.jpeg,.png,.webp,.pdf,.docx,.txt" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Batal</button><button className="button" disabled={busy||!file||!targetId} onClick={()=>void job(upload)}>Unggah Bukti</button></div></DataEntryModal>
  {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}
 </>;
}
