"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {LayoutDashboard,UsersRound,GraduationCap,ClipboardCheck,HeartHandshake,Layers3,WalletCards,BriefcaseBusiness,Sparkles,BookOpenCheck,LogOut,CalendarCheck2,FileText,CheckCircle2,AlertTriangle,Clock3,BarChart3,Search,ChevronRight} from "lucide-react";
import "./demo.css";

const menu=[
 ["overview","Beranda",LayoutDashboard],
 ["guru","Guru AI",Sparkles],
 ["buku","Buku Kerja",BookOpenCheck],
 ["disiplin","Disiplin Pro",ClipboardCheck],
 ["bk","BK Pro",HeartHandshake],
 ["command","Command Pro",Layers3],
 ["kepsek","Kepsek AI",GraduationCap],
 ["finance","SIKAS Pro",WalletCards],
 ["payroll","Gajian Pro",BriefcaseBusiness],
] as const;

type Key=typeof menu[number][0];

const cards={
 overview:{title:"Ringkasan Sekolah",desc:"Contoh tampilan dashboard terintegrasi.",body:<><div className="demo-grid"><div className="demo-stat"><small>Guru & Staf</small><strong>42</strong><span>39 hadir hari ini</span></div><div className="demo-stat"><small>Siswa</small><strong>486</strong><span>18 rombel aktif</span></div><div className="demo-stat"><small>Program Berjalan</small><strong>12</strong><span>4 perlu tindak lanjut</span></div><div className="demo-stat"><small>Kas Sekolah</small><strong>Rp128,4 jt</strong><span>rekap seluruh akun</span></div></div><div className="demo-panels"><section><h3>Aktivitas Hari Ini</h3>{["Presensi guru selesai 39/42","Rapat evaluasi kurikulum 10.00","2 program menunggu bukti","Rekap kas diperbarui"].map((x,i)=><div className="demo-row" key={x}><span className="dot"/><b>{x}</b><small>{["07.25","09.00","10.35","11.10"][i]}</small></div>)}</section><section><h3>Status Modul</h3>{["Guru AI","Buku Kerja","Disiplin Pro","BK Pro","Command Pro","Kepsek AI","SIKAS Pro","Gajian Pro"].map(x=><div className="demo-row" key={x}><CheckCircle2 size={16}/><b>{x}</b><small>Aktif</small></div>)}</section></div></>},
 guru:{title:"Guru AI",desc:"Generator perangkat ajar dan bahan pembelajaran.",body:<><div className="demo-toolbar"><button>Modul Ajar</button><button>LKPD</button><button>Soal & Asesmen</button></div><section className="demo-form"><label>Mata Pelajaran<input value="Matematika" readOnly/></label><label>Kelas<input value="VIII" readOnly/></label><label>Tujuan Pembelajaran<textarea value="Memahami relasi dan fungsi melalui masalah kontekstual." readOnly/></label><button className="demo-primary">Buat Draf AI</button></section></>},
 buku:{title:"Buku Kerja Digital",desc:"Presensi siswa, nilai, jurnal, agenda dan rekap kelas.",body:<><div className="demo-toolbar"><button>Presensi</button><button>Nilai</button><button>Jurnal</button><button>Rekap</button></div><section><h3>Kelas VIII A · Hari ini</h3>{["Alya Putri","Bagas Pratama","Citra Rahma","Dimas Saputra"].map((x,i)=><div className="demo-row" key={x}><b>{x}</b><small>{i===3?"Izin":"Hadir"}</small></div>)}</section></>},
 disiplin:{title:"Disiplin Pro",desc:"Pelanggaran, prestasi, pembinaan dan tindak lanjut siswa.",body:<><div className="demo-grid"><div className="demo-stat"><small>Pelanggaran Bulan Ini</small><strong>14</strong></div><div className="demo-stat"><small>Prestasi</small><strong>9</strong></div><div className="demo-stat"><small>Pembinaan Aktif</small><strong>5</strong></div></div><section><h3>Riwayat Terbaru</h3>{["Terlambat datang · VIII B","Juara lomba sains · IX A","Pembinaan kedisiplinan · VII C"].map(x=><div className="demo-row" key={x}><AlertTriangle size={16}/><b>{x}</b><button>Lihat</button></div>)}</section></>},
 bk:{title:"BK Pro",desc:"Ruang konseling privat untuk konselor yang ditugaskan.",body:<><div className="demo-note">Mode demo hanya memperlihatkan struktur fitur. Catatan konseling pribadi tidak ditampilkan.</div><div className="demo-toolbar"><button>Kasus</button><button>Layanan & RPL</button><button>Riwayat Siswa</button><button>Tindak Lanjut</button></div><section><h3>Ringkasan Agregat</h3><div className="demo-grid"><div className="demo-stat"><small>Kasus Aktif</small><strong>7</strong></div><div className="demo-stat"><small>Tindak Lanjut</small><strong>4</strong></div></div></section></>},
 command:{title:"Command Pro",desc:"Program kerja, PIC, deadline, rapat, tugas dan bukti.",body:<><div className="demo-toolbar"><button>Program & PIC</button><button>Tugas</button><button>Hasil Rapat</button><button>Agenda</button><button>Bukti</button></div>{["Program Literasi Sekolah","Persiapan ANBK","Evaluasi Kurikulum"].map((x,i)=><div className="demo-project" key={x}><div><b>{x}</b><small>PIC: {["Waka Kurikulum","Tim IT","Kepala Sekolah"][i]}</small></div><span>{[74,45,90][i]}%</span><div className="demo-progress"><i style={{width:[74,45,90][i]+"%"}}/></div></div>)}</>},
 kepsek:{title:"Kepsek AI",desc:"PBD, KSP/KOSP, RKJM, RKT, RKAS, SOP dan supervisi.",body:<><div className="demo-toolbar"><button>PBD</button><button>KSP/KOSP</button><button>RKT</button><button>RKAS</button><button>Supervisi</button></div><section><h3>Dokumen Kerja</h3>{["RKT Tahun Ajaran 2026/2027","KOSP Sekolah","Program Supervisi Semester 1"].map((x,i)=><div className="demo-row" key={x}><FileText size={16}/><b>{x}</b><small>{["Review","Draft","Disetujui"][i]}</small></div>)}</section></>},
 finance:{title:"SIKAS Pro",desc:"Kas, rekening, anggaran, tagihan siswa dan laporan.",body:<><div className="demo-grid"><div className="demo-stat"><small>Pemasukan</small><strong>Rp84 jt</strong></div><div className="demo-stat"><small>Pengeluaran</small><strong>Rp37 jt</strong></div><div className="demo-stat"><small>Sisa Anggaran</small><strong>Rp47 jt</strong></div></div><section><h3>Transaksi Terbaru</h3>{["Dana kegiatan masuk","Belanja ATK","Pembayaran internet sekolah"].map((x,i)=><div className="demo-row" key={x}><WalletCards size={16}/><b>{x}</b><small>{["Rp12.000.000","Rp1.450.000","Rp850.000"][i]}</small></div>)}</section></>},
 payroll:{title:"Gajian Pro",desc:"Presensi guru pribadi, cuti, kinerja, payroll dan slip gaji.",body:<><div className="demo-toolbar"><button>Presensi Saya</button><button>Cuti</button><button>Kinerja</button><button>Payroll</button><button>Slip Saya</button></div><div className="demo-grid"><div className="demo-stat"><small>Check-in Hari Ini</small><strong>06:58</strong><span>Tepat waktu</span></div><div className="demo-stat"><small>Kehadiran Bulan Ini</small><strong>96%</strong></div><div className="demo-stat"><small>Payroll September</small><strong>Locked</strong></div></div><section><h3>Slip Gaji</h3><div className="demo-row"><b>September 2026</b><small>Rp5.850.000</small><button>Cetak</button></div></section></>},
} satisfies Record<Key,{title:string;desc:string;body:React.ReactNode}>;

export default function Demo(){
 const [active,setActive]=useState<Key>("overview");
 const current=cards[active];
 return <div className="demo-shell"><aside><div className="demo-brand"><img src="/school-control-mark.svg" width={38} height={38} alt=""/><span><b>School Control</b><small>Mode Demo Read Only</small></span></div><nav>{menu.map(([k,label,Icon])=><button className={active===k?"active":""} key={k} onClick={()=>setActive(k)}><Icon size={18}/>{label}<ChevronRight size={15}/></button>)}</nav><Link className="demo-exit" href="/masuk"><LogOut size={17}/> Keluar Demo</Link></aside><main><header><div><span className="demo-kicker">DEMO WORKSPACE · DATA CONTOH</span><h1>{current.title}</h1><p>{current.desc}</p></div><div className="demo-search"><Search size={16}/><span>Cari fitur…</span></div></header><div className="demo-banner">Mode Demo tidak terhubung ke data pelanggan dan tidak menyimpan perubahan.</div><div className="demo-content">{current.body}</div></main></div>;
}
