"use client";
import {useEffect,useState} from "react";
import {LayoutDashboard,Database,BookOpenCheck,Sparkles,ClipboardCheck,HeartHandshake,ListChecks,WalletCards,BriefcaseBusiness,Settings,LogOut,CheckCircle2,AlertTriangle,FileText,Clock3,BarChart3,Search,ChevronRight,GraduationCap,ReceiptText,Sun,Moon,CalendarDays,KeyRound,Plus,Pencil,Trash2} from "lucide-react";
import "./demo.css";

const menu=[
 ["overview","Beranda",LayoutDashboard],
 ["master","Data Induk",Database],
 ["calendar","Agenda Sekolah",CalendarDays],
 ["teaching","Perangkat Ajar AI",Sparkles],
 ["academic","Pembelajaran & Penilaian",BookOpenCheck],
 ["student","Disiplin & Prestasi",ClipboardCheck],
 ["counseling","Bimbingan Konseling",HeartHandshake],
 ["planning","Perencanaan & Supervisi",GraduationCap],
 ["execution","Program, Tugas & Agenda",ListChecks],
 ["attendance","Presensi, Jadwal & Cuti",Clock3],
 ["performance","Kinerja & Pengembangan",BarChart3],
 ["finance","Keuangan & Tagihan",WalletCards],
 ["payroll","Payroll & Slip",BriefcaseBusiness],
 ["access","Akses & Peran",KeyRound],
 ["settings","Pengaturan Sekolah",Settings],
] as const;
type Key=typeof menu[number][0];

const data:Record<Key,{title:string;desc:string;features:string[];body:React.ReactNode}>={
 overview:{title:"Beranda Sekolah",desc:"Ringkasan operasional seluruh sekolah dalam satu layar.",features:["Aktivitas hari ini","Peringatan tugas","Agenda","Universal AI Orchestrator"],body:<><div className="demo-grid"><div className="demo-stat"><small>Guru & Staf</small><strong>42</strong><span>39 hadir hari ini</span></div><div className="demo-stat"><small>Siswa</small><strong>486</strong><span>18 rombel aktif</span></div><div className="demo-stat"><small>Program Berjalan</small><strong>12</strong><span>4 perlu tindak lanjut</span></div><div className="demo-stat"><small>Kas Sekolah</small><strong>Rp128,4 jt</strong><span>seluruh akun kas</span></div></div><div className="demo-panels"><section><h3>Aktivitas Hari Ini</h3>{["Presensi guru selesai 39/42","Rapat evaluasi kurikulum 10.00","2 program menunggu bukti","Rekap kas diperbarui"].map((x,i)=><div className="demo-row" key={x}><span className="dot"/><b>{x}</b><small>{["07.25","09.00","10.35","11.10"][i]}</small></div>)}</section><section><h3>Pekerjaan Prioritas</h3>{["Lengkapi bukti program literasi","Review RKT semester","Verifikasi pembayaran siswa","Tindak lanjut supervisi"].map(x=><div className="demo-row" key={x}><CheckCircle2 size={16}/><b>{x}</b><small>Terhubung</small></div>)}</section></div></>},
 master:{title:"Data Induk",desc:"Data utama sekolah.",features:["Siswa","Kelas","Guru & Tenaga Kependidikan","Mata pelajaran","Penugasan guru","Import/Export"],body:<><div className="demo-toolbar">{["Siswa","Kelas","Guru & Staf","Mata Pelajaran","Penugasan","Import/Export"].map(x=><button key={x}>{x}</button>)}</div><section><h3>Data Siswa</h3>{["Alya Putri · VIII A","Bagas Pratama · VIII A","Citra Rahma · VIII B","Dimas Saputra · IX A"].map(x=><div className="demo-row" key={x}><Database size={16}/><b>{x}</b><small>Aktif</small></div>)}</section></>},
 calendar:{title:"Agenda Sekolah",desc:"Kalender kegiatan sekolah.",features:["Kalender Bulan","Agenda Besok","Agenda Bulan Depan","Tambah Agenda"],body:<section><h3>Kalender Agenda</h3><div className="demo-grid"><div className="demo-stat"><small>Besok</small><strong>2</strong><span>Rapat wali kelas</span></div><div className="demo-stat"><small>Bulan Depan</small><strong>6</strong><span>Agenda terjadwal</span></div></div></section>},
 teaching:{title:"Perangkat Ajar AI",desc:"Perangkat pembelajaran AI.",features:["Modul Ajar","RPP","LKPD","Bahan Ajar","Soal","Asesmen","Riwayat Draf"],body:<><div className="demo-toolbar">{["Modul Ajar","RPP","LKPD","Bahan Ajar","Soal & Asesmen"].map(x=><button key={x}>{x}</button>)}</div><section className="demo-form"><label>Mata Pelajaran<input value="Matematika" readOnly/></label><label>Kelas<input value="VIII" readOnly/></label><label>Tujuan Pembelajaran<textarea value="Memahami relasi dan fungsi melalui masalah kontekstual." readOnly/></label><button className="demo-primary">Buat Draf AI</button></section></>},
 academic:{title:"Pembelajaran & Penilaian",desc:"Administrasi kelas harian memakai data siswa dan kelas yang sama.",features:["Presensi Siswa","Nilai","Jurnal Mengajar","Agenda","Rekap Bulanan","Laporan Kelas","Import/Export Excel"],body:<><div className="demo-toolbar">{["Presensi","Nilai","Jurnal","Agenda","Rekap","Laporan","Import/Export"].map(x=><button key={x}>{x}</button>)}</div><section><h3>Kelas VIII A · Hari ini</h3>{["Alya Putri","Bagas Pratama","Citra Rahma","Dimas Saputra"].map((x,i)=><div className="demo-row" key={x}><b>{x}</b><small>{i===3?"Izin":"Hadir"}</small></div>)}</section></>},
 student:{title:"Disiplin & Prestasi",desc:"Riwayat perilaku dan capaian siswa sampai tindak lanjut selesai.",features:["Pelanggaran","Prestasi","Pembinaan","Tindak Lanjut","Filter Kelas","Rekap"],body:<><div className="demo-grid"><div className="demo-stat"><small>Pelanggaran Bulan Ini</small><strong>14</strong></div><div className="demo-stat"><small>Prestasi</small><strong>9</strong></div><div className="demo-stat"><small>Pembinaan Aktif</small><strong>5</strong></div></div><section><h3>Riwayat Terbaru</h3>{["Terlambat datang · VIII B","Juara lomba sains · IX A","Pembinaan kedisiplinan · VII C"].map(x=><div className="demo-row" key={x}><AlertTriangle size={16}/><b>{x}</b><button>Lihat</button></div>)}</section></>},
 counseling:{title:"Bimbingan Konseling",desc:"Layanan privat konselor dengan riwayat dan tindak lanjut siswa.",features:["Pemetaan Kebutuhan","Kasus","Konseling Individu","Konseling Kelompok","Layanan Klasikal","RPL","Kunjungan Rumah","Rujukan","Karier","Tindak Lanjut"],body:<><div className="demo-toolbar">{["Kasus","Layanan","RPL","Riwayat Siswa","Tindak Lanjut"].map(x=><button key={x}>{x}</button>)}</div><section><h3>Ringkasan Layanan</h3><div className="demo-grid"><div className="demo-stat"><small>Kasus Aktif</small><strong>7</strong></div><div className="demo-stat"><small>Tindak Lanjut</small><strong>4</strong></div><div className="demo-stat"><small>Layanan Bulan Ini</small><strong>18</strong></div></div></section></>},
 planning:{title:"Perencanaan & Supervisi",desc:"Perencanaan sekolah, dokumen kerja, persetujuan dan supervisi akademik.",features:["PBD/EDS","KSP/KOSP","RKJM","RKT","RKAS","SOP","Supervisi Guru","Pusat Dokumen","Persetujuan"],body:<><div className="demo-toolbar">{["PBD/EDS","KSP/KOSP","RKJM","RKT","RKAS","SOP","Supervisi"].map(x=><button key={x}>{x}</button>)}</div><section><h3>Dokumen Kerja</h3>{["RKT Tahun Ajaran 2026/2027","KOSP Sekolah","Program Supervisi Semester 1"].map((x,i)=><div className="demo-row" key={x}><FileText size={16}/><b>{x}</b><small>{["Review","Draft","Disetujui"][i]}</small></div>)}</section></>},
 execution:{title:"Program, Tugas & Agenda",desc:"Eksekusi program dari PIC, deadline, kendala sampai bukti.",features:["Program Kerja","PIC","Tugas","Deadline","Progres","Kendala","Hasil Rapat","Agenda","Bukti"],body:<><div className="demo-toolbar">{["Program","Tugas","Rapat","Agenda","Bukti"].map(x=><button key={x}>{x}</button>)}</div>{["Program Literasi Sekolah","Persiapan ANBK","Evaluasi Kurikulum"].map((x,i)=><div className="demo-project" key={x}><div><b>{x}</b><small>PIC: {["Waka Kurikulum","Tim IT","Kepala Sekolah"][i]}</small></div><span>{[74,45,90][i]}%</span><div className="demo-progress"><i style={{width:[74,45,90][i]+"%"}}/></div></div>)}</>},
 attendance:{title:"Presensi, Jadwal & Cuti",desc:"Kehadiran pribadi guru dengan waktu server dan alur izin/cuti.",features:["Check-in","Check-out","Jadwal/Shift","Riwayat","Koreksi Beralasan","Izin","Cuti"],body:<><div className="demo-grid"><div className="demo-stat"><small>Check-in Hari Ini</small><strong>06:58</strong><span>Tepat waktu</span></div><div className="demo-stat"><small>Kehadiran Bulan Ini</small><strong>96%</strong></div><div className="demo-stat"><small>Cuti Tersisa</small><strong>7 hari</strong></div></div><section><h3>Riwayat Kehadiran</h3>{["30 Sep · 06:58 · Hadir","29 Sep · 07:03 · Hadir","28 Sep · Cuti disetujui"].map(x=><div className="demo-row" key={x}><Clock3 size={16}/><b>{x}</b><small>Tercatat</small></div>)}</section></>},
 performance:{title:"Kinerja & Pengembangan",desc:"Evaluasi berbasis bukti tanpa vonis otomatis.",features:["Kehadiran","Program Sekolah","Pelatihan","Bukti Capaian","Evaluasi","Tanggapan Guru"],body:<><div className="demo-grid"><div className="demo-stat"><small>Kehadiran</small><strong>96%</strong></div><div className="demo-stat"><small>Program Diikuti</small><strong>8</strong></div><div className="demo-stat"><small>Pelatihan</small><strong>3</strong></div></div><section><h3>Bukti Pengembangan</h3>{["Pelatihan Kurikulum","PIC Program Literasi","Supervisi pembelajaran"].map(x=><div className="demo-row" key={x}><CheckCircle2 size={16}/><b>{x}</b><small>Terverifikasi</small></div>)}</section></>},
 finance:{title:"Keuangan, Anggaran & Tagihan",desc:"Pembukuan sekolah dari kas sampai pembayaran siswa.",features:["Kas/Rekening","Pemasukan","Pengeluaran","Anggaran","Tagihan Siswa","Pembayaran","Kuitansi","Laporan","Ekspor"],body:<><div className="demo-grid"><div className="demo-stat"><small>Pemasukan</small><strong>Rp84 jt</strong></div><div className="demo-stat"><small>Pengeluaran</small><strong>Rp37 jt</strong></div><div className="demo-stat"><small>Sisa Anggaran</small><strong>Rp47 jt</strong></div></div><section><h3>Transaksi Terbaru</h3>{["Dana kegiatan masuk","Belanja ATK","Pembayaran internet sekolah"].map((x,i)=><div className="demo-row" key={x}><WalletCards size={16}/><b>{x}</b><small>{["Rp12.000.000","Rp1.450.000","Rp850.000"][i]}</small></div>)}</section></>},
 payroll:{title:"Payroll & Slip",desc:"Komponen gaji, review, approval, pembayaran dan slip pribadi.",features:["Gaji Pokok","Tunjangan","Potongan","Draft Payroll","Review","Approval","Kunci Periode","Pembayaran","Slip"],body:<><div className="demo-toolbar">{["Komponen Gaji","Payroll","Approval","Slip Saya"].map(x=><button key={x}>{x}</button>)}</div><div className="demo-grid"><div className="demo-stat"><small>Payroll September</small><strong>Locked</strong></div><div className="demo-stat"><small>Total Pegawai</small><strong>42</strong></div><div className="demo-stat"><small>Slip Terbit</small><strong>42</strong></div></div><section><h3>Slip Gaji</h3><div className="demo-row"><ReceiptText size={16}/><b>September 2026</b><small>Rp5.850.000</small></div></section></>},
 access:{title:"Akses & Peran",desc:"Struktur akses pengguna.",features:["Kepala Sekolah","Wakil Kepala Sekolah","Guru","Guru BK","Bendahara","SDM / HR","Staf","Viewer"],body:<section><h3>Struktur Akses</h3>{["Kepala Sekolah · akses utama","Guru · pembelajaran & siswa","Staf · presensi & agenda","Bendahara · keuangan","Guru BK · konseling"].map(x=><div className="demo-row" key={x}><KeyRound size={16}/><b>{x}</b><small>Aktif</small></div>)}</section>},
 settings:{title:"Pengaturan Sekolah",desc:"Profil dan langganan.",features:["Profil Sekolah","Undang Anggota","Peran & Akses","Memori Sekolah","Langganan","Riwayat Pembayaran"],body:<section className="demo-form"><label>Nama Sekolah<input value="SMP Harapan Bangsa" readOnly/></label><label>Tahun Ajaran<input value="2026/2027" readOnly/></label><label>Langganan<input value="Aktif" readOnly/></label><label>Peran Akun<input value="Owner" readOnly/></label></section>},
};

export default function DemoWorkspace(){
 const [active,setActive]=useState<Key>("overview"),[expanded,setExpanded]=useState<Key|null>(null),[subFeature,setSubFeature]=useState(""),[draftTitle,setDraftTitle]=useState(""),[draftDetail,setDraftDetail]=useState(""),[draftDate,setDraftDate]=useState(()=>new Date().toLocaleDateString("en-CA")),[saved,setSaved]=useState<Record<string,{id:string;title:string;detail:string;date:string}[]>>({});
 const [ready,setReady]=useState(false),[theme,setTheme]=useState<"light"|"dark">("light");
useEffect(()=>{if(sessionStorage.getItem("sc_internal_review")!=="1"){window.location.replace("/masuk");return}const t=localStorage.getItem("school-control-theme")==="dark"?"dark":"light";setTheme(t);document.body.dataset.theme=t;try{setSaved(JSON.parse(localStorage.getItem("sc_internal_workspace_data")||"{}"))}catch{}setReady(true)},[]);
 if(!ready)return null;
 const current=data[active];
 function toggleTheme(){const next=theme==="light"?"dark":"light";setTheme(next);localStorage.setItem("school-control-theme",next);document.body.dataset.theme=next}
 function persist(next:Record<string,{id:string;title:string;detail:string;date:string}[]>){setSaved(next);localStorage.setItem("sc_internal_workspace_data",JSON.stringify(next))}
 function addDraft(){if(draftTitle.trim().length<2)return;const item={id:crypto.randomUUID(),title:draftTitle.trim(),detail:draftDetail.trim(),date:draftDate};persist({...saved,[active]:[...(saved[active]||[]),item]});setDraftTitle("");setDraftDetail("")}
 function editDraft(id:string){const item=(saved[active]||[]).find(x=>x.id===id);if(!item)return;const title=prompt("Nama data",item.title);if(!title)return;const detail=prompt("Keterangan",item.detail)||"";persist({...saved,[active]:(saved[active]||[]).map(x=>x.id===id?{...x,title,detail}:x)})}
 function deleteDraft(id:string){if(!confirm("Hapus data ini?"))return;persist({...saved,[active]:(saved[active]||[]).filter(x=>x.id!==id)})}
 function logout(){sessionStorage.removeItem("sc_internal_review");window.location.replace("/masuk")}
 return <div className="demo-shell"><aside><div className="demo-brand"><img src="/school-control-mark.svg" width={38} height={38} alt=""/><span><b>School Control</b><small>Satu Sistem, Semua Urusan Sekolah</small></span></div><nav>{menu.map(([k,label,Icon])=><div className="demo-navitem" key={k}><button className={active===k?"active":""} onClick={()=>{setActive(k);setExpanded(expanded===k?null:k);setSubFeature("")}}><Icon size={18}/>{label}<ChevronRight className={active===k?"open":""} size={15}/></button>{expanded===k&&<div className="demo-navchildren">{data[k].features.map(f=><button key={f} className={subFeature===f?"selected":""} onClick={()=>setSubFeature(f)}>{f}</button>)}</div>}</div>)}</nav><button className="demo-exit" onClick={logout}><LogOut size={17}/> Keluar</button></aside><main><header><div><span className="demo-kicker">SCHOOL CONTROL / WORKSPACE SEKOLAH</span><h1>{current.title}</h1><p>{current.desc}</p></div><div className="demo-head-actions"><button className="demo-theme" onClick={toggleTheme}>{theme==="light"?<Moon size={16}/>:<Sun size={16}/>} {theme==="light"?"Gelap":"Terang"}</button><div className="demo-search"><Search size={16}/><span>Cari fitur…</span></div></div></header><div className="demo-feature-strip">{current.features.map(x=><button className={subFeature===x?"active":""} key={x} onClick={()=>setSubFeature(x)}>{x}</button>)}</div>{subFeature&&<div className="demo-selected-feature"><strong>{subFeature}</strong><span> · bagian dari {current.title}. Menu ini memakai data dan alur yang sama dengan fitur terkait.</span></div>}<div className="demo-content">{current.body}{!["overview","access","settings"].includes(active)&&<section><div className="sectionhead"><h3>Input Data</h3><span className="pill">Paket Aktif</span></div><div className="demo-form"><label>Nama / Judul<input value={draftTitle} onChange={e=>setDraftTitle(e.target.value)} placeholder="Masukkan data"/></label><label>Tanggal<input type="date" value={draftDate} onChange={e=>setDraftDate(e.target.value)}/></label><label style={{gridColumn:"1/-1"}}>Keterangan<textarea value={draftDetail} onChange={e=>setDraftDetail(e.target.value)} placeholder="Opsional"/></label><button className="demo-primary" onClick={addDraft}><Plus size={15}/> Tambah Data</button></div>{(saved[active]||[]).map(x=><div className="demo-row" key={x.id}><span className="dot"/><b>{x.title}<small style={{display:"block"}}>{x.date}{x.detail?" · "+x.detail:""}</small></b><div className="flow"><button onClick={()=>editDraft(x.id)}><Pencil size={14}/></button><button onClick={()=>deleteDraft(x.id)}><Trash2 size={14}/></button></div></div>)}</section>}{active==="settings"&&<section><div className="demo-row"><CheckCircle2 size={16}/><b>Langganan</b><small>Aktif</small></div></section>}</div></main></div>;
}
