"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
type School={name:string;address:string|null;principal_name:string|null;logo_url:string|null};
type Template={title:string;subtitle:string;city:string;signerTitle:string;footer:string;showLogo:boolean};
const base:Template={title:"LAPORAN DISIPLIN & PRESTASI SISWA",subtitle:"Rekap kejadian, pembinaan, tindak lanjut dan prestasi",city:"",signerTitle:"Kepala Sekolah",footer:"Dokumen ini dihasilkan dari School Control.",showLogo:true};
export default function DisciplineReportTemplate({schoolId}:{schoolId:string}){
 const db=useMemo(()=>browserDb(),[]),[school,setSchool]=useState<School>({name:"Sekolah",address:null,principal_name:null,logo_url:null}),[form,setForm]=useState<Template>(base),[ok,setOk]=useState("");
 useEffect(()=>{if(!db)return;(async()=>{const {data}=await db.from("sc_schools").select("name,address,principal_name,logo_url").eq("id",schoolId).maybeSingle();if(data)setSchool(data as School);try{const saved=localStorage.getItem("sc-discipline-report-template-"+schoolId);if(saved)setForm({...base,...JSON.parse(saved)})}catch{}})()},[db,schoolId]);
 function set<K extends keyof Template>(k:K,v:Template[K]){setForm(x=>({...x,[k]:v}))}
 function save(){localStorage.setItem("sc-discipline-report-template-"+schoolId,JSON.stringify(form));setOk("Template laporan tersimpan di perangkat ini. Identitas sekolah tetap diambil dari Pengaturan Sekolah.")}
 function printPreview(){const w=window.open("","_blank");if(!w)return;const logo=form.showLogo&&school.logo_url?"<img src='"+school.logo_url.replace(/'/g,"")+"' style='max-height:75px;max-width:90px'/>":"";w.document.write("<!doctype html><html><head><meta charset='utf-8'><title>Template Laporan</title><style>body{font:13px Arial;margin:36px;color:#111}.head{display:grid;grid-template-columns:100px 1fr 100px;align-items:center;text-align:center;border-bottom:3px solid #111;padding-bottom:12px}.head h1{font-size:19px;margin:0}.head p{margin:4px}.title{text-align:center;margin:28px 0}.box{border:1px solid #999;padding:16px;margin:12px 0}.sign{margin-left:auto;width:260px;margin-top:45px;text-align:center}.footer{margin-top:55px;border-top:1px solid #bbb;padding-top:8px;font-size:10px;color:#666}</style></head><body><div class='head'><div>"+logo+"</div><div><h1>"+school.name+"</h1><p>"+(school.address||"Alamat sekolah")+"</p></div><div></div></div><div class='title'><h2>"+form.title+"</h2><p>"+form.subtitle+"</p></div><div class='box'><b>Contoh isi laporan</b><p>Nama siswa, kelas, tanggal kejadian/prestasi, kategori, tindak lanjut, bukti dan status penyelesaian akan ditampilkan pada bagian ini.</p></div><div class='sign'><p>"+(form.city||"................")+", ................</p><p>"+form.signerTitle+"</p><br/><br/><b>"+(school.principal_name||"Nama Penandatangan")+"</b></div><div class='footer'>"+form.footer+"</div></body></html>");w.document.close();w.focus();w.print()}
 return <section className="panel"><div className="sectionhead"><div><h2>Template Laporan Disiplin & Prestasi</h2><p className="muted">Atur kop, judul, penandatangan dan footer. Logo, nama dan alamat sekolah mengambil data dari Pengaturan Sekolah → Branding / Profil.</p></div></div><div className="fields"><label className="field full">Judul Laporan<input value={form.title} onChange={e=>set("title",e.target.value)}/></label><label className="field full">Subjudul<input value={form.subtitle} onChange={e=>set("subtitle",e.target.value)}/></label><label className="field">Kota Penandatangan<input value={form.city} onChange={e=>set("city",e.target.value)} placeholder="Surabaya"/></label><label className="field">Jabatan Penandatangan<input value={form.signerTitle} onChange={e=>set("signerTitle",e.target.value)}/></label><label className="field full">Footer<input value={form.footer} onChange={e=>set("footer",e.target.value)}/></label><label className="field"><span>Tampilkan logo sekolah</span><input type="checkbox" checked={form.showLogo} onChange={e=>set("showLogo",e.target.checked)}/></label></div><div className="report-preview"><div className="report-head">{form.showLogo&&school.logo_url?<img src={school.logo_url} alt="Logo"/>:<div className="report-logo-placeholder">LOGO</div>}<div><b>{school.name}</b><span>{school.address||"Alamat sekolah belum diisi"}</span></div></div><h3>{form.title}</h3><p>{form.subtitle}</p><div className="report-sample">Area tabel laporan: siswa · kelas · jenis kejadian/prestasi · tindak lanjut · bukti · status</div><div className="report-sign"><span>{form.signerTitle}</span><b>{school.principal_name||"Nama penandatangan belum diisi"}</b></div></div><div className="flow" style={{marginTop:14}}><button className="button" onClick={save}>Simpan Template</button><button className="button secondary" onClick={printPreview}>Preview / Cetak</button></div>{ok&&<div className="banner success">{ok}</div>}</section>;
}
