"use client";
import {useEffect,useMemo,useState} from "react";
import {Eye,Save} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import {loadReportIdentity,previewOfficialReport,type OfficialReportModel,type ReportIdentity} from "@/lib/report-engine";

type Template={title:string;subtitle:string;signerTitle:string;footer:string;classification:"internal"|"restricted"|"confidential"};
const base:Template={title:"LAPORAN DISIPLIN & PRESTASI SISWA",subtitle:"Rekap kejadian, pembinaan, tindak lanjut dan prestasi",signerTitle:"Kepala Sekolah",footer:"School Control · Dokumen kesiswaan",classification:"restricted"};

export default function DisciplineReportTemplate({schoolId}:{schoolId:string}){
 const db=useMemo(()=>browserDb(),[]),[identity,setIdentity]=useState<ReportIdentity|null>(null),[form,setForm]=useState<Template>(base),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 async function load(){if(!db)return;try{const data=await loadReportIdentity(db,schoolId);setIdentity(data);const settings=(data.report_settings||{}) as any;setForm({...base,...(settings.discipline||{})})}catch(e){setError(e instanceof Error?e.message:String(e))}}
 useEffect(()=>{void load()},[db,schoolId]);
 function set<K extends keyof Template>(k:K,v:Template[K]){setForm(x=>({...x,[k]:v}))}
 async function save(){if(!db)return;setBusy(true);setError("");setOk("");try{const {error}=await db.rpc("sc_update_report_settings",{p_school:schoolId,p_patch:{discipline:form}});if(error)throw error;await load();setOk("Template disiplin tersimpan di akun sekolah dan berlaku di semua perangkat.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 function model():OfficialReportModel{return {moduleKey:"disiplin",documentType:"template_disiplin",prefix:"DIS",title:form.title,subtitle:form.subtitle,orientation:"landscape",confidentiality:form.classification,status:"draft",footer:form.footer,metrics:[{label:"Pelanggaran",value:"12",note:"contoh preview"},{label:"Prestasi",value:"7",note:"contoh preview"},{label:"Pembinaan",value:"5"},{label:"Tindak lanjut aktif",value:"2"}],sections:[{title:"Contoh Rekap Disiplin dan Prestasi",columns:["Tanggal","NIS","Nama Siswa","Kelas","Jenis","Kejadian/Prestasi","Poin","Tindak Lanjut"],rows:[["01-10-2026","12345","Contoh Siswa","VIII A","Pelanggaran","Contoh kejadian","2","Pembinaan"],["02-10-2026","12346","Contoh Siswa 2","VIII A","Prestasi","Contoh prestasi","10","Apresiasi"]]}],signatures:[{role:"Disusun oleh",name:"BK / Kesiswaan"},{role:form.signerTitle,name:identity?.principal_name||"Nama Kepala Sekolah",identifier:identity?.principal_nip?"NIP. "+identity.principal_nip:null}]}}
 function preview(){if(!identity)return;try{previewOfficialReport(identity,model());setOk("Preview template dibuka dengan watermark DRAFT.")}catch(e){setError(e instanceof Error?e.message:String(e))}}
 return <section className="panel"><div className="sectionhead"><div><h2>Template Laporan Disiplin & Prestasi</h2><p className="muted">Pengaturan ini sekarang tersimpan permanen di workspace sekolah, bukan lagi di browser. Identitas, NPSN, logo, NIP, tanda tangan dan stempel mengikuti Pengaturan Sekolah.</p></div></div>
 <div className="fields"><label className="field full">Judul Laporan<input value={form.title} onChange={e=>set("title",e.target.value)}/></label><label className="field full">Subjudul<input value={form.subtitle} onChange={e=>set("subtitle",e.target.value)}/></label><label className="field">Jabatan Penandatangan<input value={form.signerTitle} onChange={e=>set("signerTitle",e.target.value)}/></label><label className="field">Klasifikasi<select value={form.classification} onChange={e=>set("classification",e.target.value as Template["classification"])}><option value="internal">Internal Sekolah</option><option value="restricted">Terbatas</option><option value="confidential">Rahasia</option></select></label><label className="field full">Footer<input value={form.footer} onChange={e=>set("footer",e.target.value)}/></label></div>
 <div className="report-preview"><div className="report-head">{identity?.logo_url?<img src={identity.logo_url} alt="Logo"/>:<div className="report-logo-placeholder">LOGO</div>}<div><b>{identity?.name||"Nama Sekolah"}</b><span>{identity?.npsn?"NPSN "+identity.npsn+" · ":""}{identity?.address||"Alamat sekolah belum diisi"}</span></div></div><h3>{form.title}</h3><p>{form.subtitle}</p><div className="report-sample">Kop sekolah · nomor dokumen · rekap kejadian · pembinaan · tindak lanjut · pengesahan · arsip snapshot</div><div className="report-sign"><span>{form.signerTitle}</span><b>{identity?.principal_name||"Nama penandatangan belum diisi"}</b><small>{identity?.principal_nip?"NIP. "+identity.principal_nip:""}</small></div></div>
 <div className="flow" style={{marginTop:14}}><button className="button" disabled={busy||form.title.trim().length<3} onClick={()=>void save()}><Save size={14}/> Simpan Template</button><button className="button secondary" disabled={!identity} onClick={preview}><Eye size={14}/> Preview A4</button></div>{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;
}
