"use client";
import {useEffect,useMemo,useState} from "react";
import {Archive,Download,FileText,RotateCcw,Trash2,Upload} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import {readExcel} from "@/lib/excel";
import {downloadOfficialDocx,issueAndExport,issueReport,loadReportIdentity,previewOfficialReport,printOfficialReport,type OfficialReportModel} from "@/lib/report-engine";
import type {Role} from "@/lib/modules";

type Student={id:string;name:string;nis:string|null;class_id:string|null;status:string;archived_at:string|null};
type C={id:string;name:string};
type EventRow={id:string;student_id:string;event_type:string;item_name_snapshot:string;category_snapshot:string;points_snapshot:number;occurred_at:string;chronology:string|null};
type Master={id:string;type:string;name:string;category:string|null;points:number};
type Doc={id:string;student_id:string;document_type:string;document_number:string;title:string;status:string;issued_at:string;content_snapshot:Record<string,unknown>};
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"});
const norm=(v:unknown)=>String(v??"").trim().toLocaleLowerCase("id-ID");
const docLabels:Record<string,string>={notice:"Surat Pemberitahuan Orang Tua/Wali",parent_call:"Surat Panggilan Orang Tua/Wali",coaching:"Surat Pembinaan Peserta Didik",history:"Laporan Riwayat Kedisiplinan Siswa"};
export default function DisciplineLegacyParity({schoolId,userId,role,focus}:{schoolId:string;userId:string;role:Role;focus:string}){
 const db=useMemo(()=>browserDb(),[]),[students,setStudents]=useState<Student[]>([]),[classes,setClasses]=useState<C[]>([]),[events,setEvents]=useState<EventRow[]>([]),[master,setMaster]=useState<Master[]>([]),[docs,setDocs]=useState<Doc[]>([]),[school,setSchool]=useState<any>(null);
 const [selected,setSelected]=useState(""),[fileName,setFileName]=useState(""),[preview,setPreview]=useState<Record<string,unknown>[]>([]),[docType,setDocType]=useState("notice"),[reportMonth,setReportMonth]=useState(today().slice(0,7)),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const canWrite=["owner","principal","vice_principal","teacher","counselor"].includes(role);
 async function load(){if(!db)return;const [s,c,e,m,d,sc]=await Promise.all([
  db.from("sc_students").select("id,name,nis,class_id,status,archived_at").eq("school_id",schoolId).order("name"),
  db.from("sc_classes").select("id,name").eq("school_id",schoolId).order("name"),
  db.from("sc_discipline_events").select("id,student_id,event_type,item_name_snapshot,category_snapshot,points_snapshot,occurred_at,chronology").eq("school_id",schoolId).order("occurred_at",{ascending:false}).limit(1000),
  db.from("sc_discipline_master_items").select("id,type,name,category,points").eq("school_id",schoolId).eq("is_active",true),
  db.from("sc_discipline_documents").select("id,student_id,document_type,document_number,title,status,issued_at,content_snapshot").eq("school_id",schoolId).order("issued_at",{ascending:false}).limit(200),
  db.from("sc_schools").select("name,npsn,address,city,principal_name,principal_nip,logo_url,signature_url,stamp_url,report_settings").eq("id",schoolId).maybeSingle()
 ]);setStudents((s.data||[]) as Student[]);setClasses((c.data||[]) as C[]);setEvents((e.data||[]) as EventRow[]);setMaster((m.data||[]) as Master[]);setDocs((d.data||[]) as Doc[]);setSchool(sc.data||null)}
 useEffect(()=>{void load()},[db,schoolId]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const className=(id:string|null)=>classes.find(c=>c.id===id)?.name||"—";
 async function archive(id:string,value:boolean){if(!db)return;await run(async()=>{const {error}=await db.rpc("sc_archive_student",{p_school:schoolId,p_student:id,p_archive:value});if(error)throw error;setOk(value?"Siswa dipindahkan ke arsip.":"Siswa dipulihkan.")})}
 async function finalDelete(id:string){if(!db)return;const phrase=prompt("Ketik HAPUS PERMANEN untuk menghapus siswa dari daftar operasional. Riwayat referensial tetap dipertahankan untuk audit.");if(phrase!=="HAPUS PERMANEN")return;await run(async()=>{const {error}=await db.rpc("sc_soft_delete_student",{p_school:schoolId,p_student:id});if(error)throw error;setOk("Siswa dikeluarkan permanen dari daftar operasional.")})}
 async function read(file?:File){if(!file)return;try{const rows=await readExcel(file);if(rows.length>3000)throw Error("Maksimal 3.000 baris per import.");setPreview(rows as Record<string,unknown>[]);setFileName(file.name)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function commitImport(){if(!db||!preview.length)return;await run(async()=>{let imported=0,skipped=0;const currentMaster=[...master];for(const raw of preview){const name=String(raw.Nama||raw.Nama_Siswa||raw.Siswa||"").trim(),klass=String(raw.Kelas||"").trim(),item=String(raw.Pelanggaran||raw.Prestasi||raw.Kejadian||raw.Item||"").trim(),rawType=norm(raw.Jenis||raw.Kategori||""),type=raw.Prestasi||rawType.includes("prestasi")?"achievement":"violation",date=String(raw.Tanggal||today()).slice(0,10),points=Math.abs(Number(raw.Poin||raw.Point||0)||0),student=students.find(s=>norm(s.name)===norm(name)&&(!klass||norm(className(s.class_id))===norm(klass)));if(!student||!item){skipped++;continue}let mi=currentMaster.find(m=>m.type===type&&norm(m.name)===norm(item));if(!mi){const {data,error}=await db.from("sc_discipline_master_items").insert({school_id:schoolId,type,name:item,category:String(raw.Kategori||type),points,is_active:true}).select("id,type,name,category,points").single();if(error)throw error;mi=data as Master;currentMaster.push(mi)}const {error}=await db.from("sc_discipline_events").insert({school_id:schoolId,student_id:student.id,master_item_id:mi.id,event_type:type,item_name_snapshot:item,category_snapshot:mi.category||String(raw.Kategori||""),points_snapshot:points,occurred_at:date,occurred_at_ts:date+"T08:00:00+07:00",chronology:String(raw.Kronologi||raw.Catatan||"")||null,recorder_name:String(raw.Pencatat||"Import Excel"),created_by:userId,category:type,title:item});if(error)throw error;imported++}await db.from("sc_import_history").insert({school_id:schoolId,module_key:"disiplin",import_kind:"historical_incidents",file_name:fileName,row_count:preview.length,imported_count:imported,skipped_count:skipped,details:{source:"legacy-discipline"}});setPreview([]);setFileName("");setOk("Import selesai: "+imported+" masuk, "+skipped+" dilewati.")})}
 function disciplineModel(title:string,type:string,snapshot:Record<string,unknown>):OfficialReportModel{const st=(snapshot as any).student||{},ev=((snapshot as any).events||[]) as any[];return {moduleKey:"disiplin",documentType:type,prefix:"DIS",title,subtitle:"Dokumen pembinaan, disiplin dan prestasi peserta didik",orientation:"portrait",confidentiality:"restricted",status:"issued",metrics:[{label:"Nama siswa",value:st.name||"—"},{label:"NIS",value:st.nis||"—"},{label:"Kelas",value:st.class_name||"—"},{label:"Catatan terkait",value:String(ev.length)}],sections:[{title:"Riwayat Terkait",columns:["Tanggal","Jenis/Kejadian","Kategori","Poin","Kronologi/Catatan"],rows:ev.map(x=>[x.occurred_at,x.item_name_snapshot||"—",x.category_snapshot||x.event_type||"—",x.points_snapshot??0,x.chronology||"—"])}],signatures:[{role:"Mengetahui / Menetapkan",name:school?.principal_name||"Kepala Sekolah",identifier:school?.principal_nip?"NIP. "+school.principal_nip:null}]}}
 async function issueDoc(){if(!db||!selected)return;await run(async()=>{const s=students.find(x=>x.id===selected);if(!s)throw Error("Pilih siswa.");const related=events.filter(e=>e.student_id===selected),snapshot={student:{name:s.name,nis:s.nis,class_name:className(s.class_id)},school,events:related.slice(0,50),generated_at:new Date().toISOString()};const identity=await loadReportIdentity(db,schoolId),model=disciplineModel(docLabels[docType],docType,snapshot);const issued=await issueReport(db,schoolId,model,identity);const {error}=await db.from("sc_discipline_documents").insert({school_id:schoolId,student_id:selected,document_type:docType,document_number:issued.document_number,title:docLabels[docType],content_snapshot:snapshot,issued_by:userId});if(error)throw error;setOk("Dokumen "+issued.document_number+" diterbitkan dan masuk arsip laporan sekolah.")})}
 async function exportDoc(d:Doc,format:"preview"|"pdf"|"docx"){if(!db)return;await run(async()=>{const identity=await loadReportIdentity(db,schoolId),model=disciplineModel(d.title,d.document_type,d.content_snapshot||{});if(format==="preview")previewOfficialReport(identity,model,d.document_number);if(format==="pdf")printOfficialReport(identity,model,d.document_number);if(format==="docx")await downloadOfficialDocx(identity,model,d.document_number);setOk(format==="docx"?"Word .docx berhasil dibuat.":"Dokumen siap dibuka / dicetak.")})}
 const trend=Object.entries(events.reduce((o:Record<string,number>,e)=>{const k=e.occurred_at.slice(0,7);o[k]=(o[k]||0)+1;return o},{})).sort().slice(-12);
 const scores=students.map(s=>{const ev=events.filter(e=>e.student_id===s.id),v=ev.filter(e=>e.event_type==="violation").reduce((n,e)=>n+Number(e.points_snapshot||0),0),a=ev.filter(e=>e.event_type==="achievement").reduce((n,e)=>n+Number(e.points_snapshot||0),0);return {s,v,a,net:Math.max(0,v-a)}}).sort((a,b)=>b.net-a.net);
 const monthEvents=events.filter(e=>e.occurred_at.startsWith(reportMonth));
 const monthStudents=students.map(s=>{const ev=monthEvents.filter(e=>e.student_id===s.id),viol=ev.filter(e=>e.event_type==="violation"),ach=ev.filter(e=>e.event_type==="achievement"),vp=viol.reduce((n,e)=>n+Number(e.points_snapshot||0),0),ap=ach.reduce((n,e)=>n+Number(e.points_snapshot||0),0);return {s,events:ev,violations:viol.length,achievements:ach.length,violationPoints:vp,achievementPoints:ap,net:Math.max(0,vp-ap)}}).filter(x=>x.events.length);
 function recapModel():OfficialReportModel{const label=new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric"}).format(new Date(reportMonth+"-01T12:00:00"));return {moduleKey:"disiplin",documentType:"rekap_disiplin_prestasi",prefix:"DIS-REKAP",title:String(school?.report_settings?.discipline_title||"Laporan Rekap Disiplin & Prestasi Siswa"),subtitle:String(school?.report_settings?.discipline_subtitle||"Rekap kejadian, pembinaan, tindak lanjut dan prestasi peserta didik"),periodLabel:label,periodStart:reportMonth+"-01",periodEnd:new Date(new Date(reportMonth+"-01T00:00:00").setMonth(new Date(reportMonth+"-01T00:00:00").getMonth()+1)-86400000).toISOString().slice(0,10),orientation:"landscape",confidentiality:"restricted",status:"approved",footer:String(school?.report_settings?.discipline_footer||"School Control · Dokumen kesiswaan"),metrics:[{label:"Total kejadian",value:String(monthEvents.length)},{label:"Pelanggaran",value:String(monthEvents.filter(e=>e.event_type==="violation").length)},{label:"Prestasi",value:String(monthEvents.filter(e=>e.event_type==="achievement").length)},{label:"Siswa tercatat",value:String(monthStudents.length)}],sections:[{title:"Rekapitulasi Per Siswa",columns:["NIS","Nama Siswa","Kelas","Pelanggaran","Prestasi","Poin Pelanggaran","Poin Prestasi","Poin Bersih"],rows:monthStudents.map(x=>[x.s.nis||"—",x.s.name,className(x.s.class_id),x.violations,x.achievements,x.violationPoints,x.achievementPoints,x.net])},{title:"Rincian Kejadian",columns:["Tanggal","NIS","Siswa","Kelas","Jenis","Kejadian","Kategori","Poin","Catatan"],rows:monthEvents.map(e=>{const s=students.find(x=>x.id===e.student_id);return [e.occurred_at,s?.nis||"—",s?.name||"Siswa",className(s?.class_id||null),e.event_type==="achievement"?"Prestasi":"Pelanggaran",e.item_name_snapshot,e.category_snapshot||"—",e.points_snapshot,e.chronology||"—"]})}],signatures:[{role:"Disusun oleh · BK / Kesiswaan",name:"........................"},{role:"Mengetahui · "+String(school?.report_settings?.signer_title||"Kepala Sekolah"),name:school?.principal_name||"Kepala Sekolah",identifier:school?.principal_nip?"NIP. "+school.principal_nip:null}]}}
 async function exportRecap(format:"pdf"|"docx"|"xlsx"){if(!db)return;await run(async()=>{const identity=await loadReportIdentity(db,schoolId),issued=await issueAndExport(db,schoolId,identity,recapModel(),format);setOk("Rekap "+issued.document_number+" diterbitkan dan masuk arsip.")})}
 async function previewRecap(){if(!db)return;await run(async()=>{const identity=await loadReportIdentity(db,schoolId);previewOfficialReport(identity,{...recapModel(),status:"draft"});setOk("Preview rekap draft dibuka tanpa memakai nomor dokumen.")})}

 if(focus==="Rekap & Laporan")return <section className="panel"><div className="sectionhead"><div><h2>Rekap & Laporan Disiplin</h2><p className="muted">Rekap bulanan resmi per siswa dan rincian kejadian. Ekspor final memperoleh nomor dokumen, pengesahan, serta snapshot arsip.</p></div><FileText/></div><div className="fields"><label className="field">Periode<input type="month" value={reportMonth} onChange={e=>setReportMonth(e.target.value)}/></label><div className="flow"><button className="button secondary" disabled={busy} onClick={()=>void previewRecap()}>Preview Draft</button><button className="button secondary" disabled={busy} onClick={()=>void exportRecap("xlsx")}><Download size={14}/> Excel</button><button className="button secondary" disabled={busy} onClick={()=>void exportRecap("docx")}><Download size={14}/> Word</button><button className="button" disabled={busy} onClick={()=>void exportRecap("pdf")}><Download size={14}/> PDF</button></div></div><div className="grid"><div className="card"><label>Total kejadian</label><strong>{monthEvents.length}</strong></div><div className="card"><label>Pelanggaran</label><strong>{monthEvents.filter(e=>e.event_type==="violation").length}</strong></div><div className="card"><label>Prestasi</label><strong>{monthEvents.filter(e=>e.event_type==="achievement").length}</strong></div><div className="card"><label>Siswa tercatat</label><strong>{monthStudents.length}</strong></div></div><div className="tablewrap"><table className="data-table"><thead><tr><th>Siswa</th><th>Kelas</th><th>Pelanggaran</th><th>Prestasi</th><th>Poin Pelanggaran</th><th>Poin Prestasi</th><th>Poin Bersih</th></tr></thead><tbody>{monthStudents.map(x=><tr key={x.s.id}><td><strong>{x.s.name}</strong><small style={{display:"block"}}>{x.s.nis||"NIS belum tersedia"}</small></td><td>{className(x.s.class_id)}</td><td>{x.violations}</td><td>{x.achievements}</td><td>{x.violationPoints}</td><td>{x.achievementPoints}</td><td>{x.net}</td></tr>)}</tbody></table></div>{!monthStudents.length&&<div className="empty">Belum ada kejadian pada periode ini.</div>}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;

 if(focus==="Arsip Siswa")return <section className="panel"><div className="sectionhead"><div><h2>Arsip Siswa</h2><p className="muted">Siswa diarsipkan tanpa menghilangkan riwayat disiplin. Data dapat dipulihkan sebelum penghapusan final dari daftar operasional.</p></div><Archive/></div>{students.filter(s=>s.status==="archived").map(s=><div className="entry" key={s.id}><div><strong>{s.name}</strong><small>{s.nis||"Tanpa NIS"} · {className(s.class_id)} · diarsip {s.archived_at?new Date(s.archived_at).toLocaleString("id-ID"):"—"}</small></div><div className="flow"><button className="button secondary" onClick={()=>void archive(s.id,false)}><RotateCcw size={14}/> Pulihkan</button><button className="button danger" onClick={()=>void finalDelete(s.id)}><Trash2 size={14}/> Hapus Permanen</button></div></div>)}{!students.some(s=>s.status==="archived")&&<div className="empty">Arsip kosong.</div>}<h3 style={{marginTop:20}}>Siswa aktif</h3>{students.filter(s=>s.status==="active").slice(0,100).map(s=><div className="entry" key={s.id}><div><strong>{s.name}</strong><small>{className(s.class_id)}</small></div>{canWrite&&<button className="button secondary" onClick={()=>void archive(s.id,true)}>Arsipkan</button>}</div>)}</section>;

 if(focus==="Import Riwayat")return <section className="panel"><div className="sectionhead"><div><h2>Import Riwayat Disiplin</h2><p className="muted">Membaca file catatan disiplin lama, mencocokkan Nama + Kelas, dan membuat master item bila belum ada.</p></div><Upload/></div><label className="button secondary"><Upload size={15}/> Pilih Excel<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>void read(e.target.files?.[0])}/></label>{preview.length>0&&<div className="banner"><strong>{fileName} · {preview.length} baris</strong><p>{preview.slice(0,3).map(x=>Object.values(x).slice(0,5).join(" | ")).join(" / ")}</p><button className="button" disabled={busy} onClick={()=>void commitImport()}>Import Catatan Sekarang</button></div>}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;

 if(focus==="Surat & Dokumen")return <section className="panel"><div className="sectionhead"><div><h2>Laporan & Surat Disiplin</h2><p className="muted">Nomor dokumen, snapshot riwayat dan arsip penerbitan disimpan agar dokumen lama tidak berubah saat data berikutnya bertambah.</p></div><FileText/></div><div className="fields"><label className="field">Siswa<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Pilih siswa</option>{students.filter(s=>s.status!=="deleted").map(s=><option key={s.id} value={s.id}>{s.name} · {className(s.class_id)}</option>)}</select></label><label className="field">Jenis dokumen<select value={docType} onChange={e=>setDocType(e.target.value)}>{Object.entries(docLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button className="button" disabled={!selected||busy} onClick={()=>void issueDoc()}>Terbitkan & Arsipkan</button></div>{docs.map(d=><div className="entry" key={d.id}><div><strong>{d.document_number} · {d.title}</strong><small>{students.find(s=>s.id===d.student_id)?.name||"Siswa"} · {new Date(d.issued_at).toLocaleString("id-ID")} · {d.status}</small></div><div className="flow"><button className="button secondary" disabled={busy} onClick={()=>void exportDoc(d,"preview")}>Preview</button><button className="button secondary" disabled={busy} onClick={()=>void exportDoc(d,"docx")}><Download size={14}/> Word</button><button className="button secondary" disabled={busy} onClick={()=>void exportDoc(d,"pdf")}><Download size={14}/> PDF</button></div></div>)}{!docs.length&&<div className="empty">Belum ada surat diterbitkan.</div>}</section>;

 return <section className="panel"><div className="sectionhead"><div><h2>Analitik Disiplin & Prestasi</h2><p className="muted">Tren kejadian, poin bersih, dan rekap siswa dari data nyata.</p></div><FileText/></div><div className="grid"><div className="card"><label>Total kejadian</label><strong>{events.length}</strong></div><div className="card"><label>Pelanggaran</label><strong>{events.filter(e=>e.event_type==="violation").length}</strong></div><div className="card"><label>Prestasi</label><strong>{events.filter(e=>e.event_type==="achievement").length}</strong></div><div className="card"><label>Siswa tercatat</label><strong>{new Set(events.map(e=>e.student_id)).size}</strong></div></div><h3>Tren bulanan</h3>{trend.map(([m,n])=><div className="entry" key={m}><strong>{m}</strong><span className="pill">{n} kejadian</span></div>)}<h3 style={{marginTop:20}}>Poin bersih per siswa</h3>{scores.slice(0,50).map(x=><div className="entry" key={x.s.id}><div><strong>{x.s.name}</strong><small>{className(x.s.class_id)} · Pelanggaran {x.v} · Prestasi {x.a}</small></div><span className="pill">{x.net} poin</span></div>)}</section>;
}
