"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {csvExport,saveCsv} from "@/lib/csv";
import {isAdmin,type Role} from "@/lib/modules";
type Student={id:string;name:string;nis:string|null;class_id:string|null;status:string};
type Class={id:string;name:string;academic_year:string};
type Incident={id:string;student_id:string;category:string;title:string;occurred_at:string;follow_up:string|null;created_by:string};
type Follow={id:string;event_id:string;action_taken:string;due_on:string|null;status:string;created_by:string};
const day=()=>{const a=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const f=(k:string)=>a.find(z=>z.type===k)?.value||"";return f("year")+"-"+f("month")+"-"+f("day")};
export default function DisciplinePanel({schoolId,role,userId,focus}:{schoolId:string;role:Role;userId:string;focus?:string}){
 const db=useMemo(()=>browserDb(),[]),manager=isAdmin(role);
 const [students,setStudents]=useState<Student[]>([]),[classes,setClasses]=useState<Class[]>([]),[incidents,setIncidents]=useState<Incident[]>([]),[followups,setFollowups]=useState<Follow[]>([]);
 const [tab,setTab]=useState("events"),[query,setQuery]=useState(""),[filterClass,setFilterClass]=useState(""),[studentId,setStudentId]=useState(""),[kind,setKind]=useState("violation"),[title,setTitle]=useState(""),[date,setDate]=useState(day()),[followup,setFollowup]=useState(""),[eventId,setEventId]=useState("");
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const name=(id:string)=>students.find(s=>s.id===id)?.name||"Siswa";
 async function load(){if(!db)return;const [s,c,i,f]=await Promise.all([db.from("sc_students").select("id,name,nis,class_id,status").eq("school_id",schoolId).order("name"),db.from("sc_classes").select("id,name,academic_year").eq("school_id",schoolId),db.from("sc_discipline_events").select("id,student_id,category,title,occurred_at,follow_up,created_by").eq("school_id",schoolId).order("occurred_at",{ascending:false}).limit(350),db.from("sc_discipline_followups").select("id,event_id,action_taken,due_on,status,created_by").eq("school_id",schoolId).limit(350)]);setStudents((s.data||[]) as Student[]);setClasses((c.data||[]) as Class[]);setIncidents((i.data||[]) as Incident[]);setFollowups((f.data||[]) as Follow[]);if(i.error)setError(i.error.message)}
 useEffect(()=>{void load()},[db,schoolId]);
 useEffect(()=>{const f=(focus||"").toLowerCase();if(f.includes("pembinaan")||f.includes("tindak"))setTab("followup");else if(f.includes("rekap"))setTab("report");else if(f.includes("pelanggaran")||f.includes("prestasi"))setTab("events")},[focus]);
 async function job(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Perubahan data disiplin dan prestasi tersimpan.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function insert(table:string,row:Record<string,unknown>){if(!db)throw Error("Database belum siap");const {error:e}=await db.from(table).insert({...row,school_id:schoolId});if(e)throw e}
 const matches=students.filter(s=>(!filterClass||s.class_id===filterClass)&&(!query||s.name.toLowerCase().includes(query.toLowerCase())||s.nis?.includes(query)));
 const filtered=incidents.filter(i=>!filterClass||matches.some(s=>s.id===i.student_id)).filter(i=>!query||matches.some(s=>s.id===i.student_id));
 const exportReport=()=>saveCsv("rekap-disiplin-school-control.csv",csvExport(["Tanggal","Siswa","NIS","Jenis","Kejadian","Tindak Lanjut"],filtered.map(i=>[i.occurred_at,name(i.student_id),students.find(s=>s.id===i.student_id)?.nis,i.category,i.title,i.follow_up])));
 return <><div className="flow" style={{marginBottom:15}}>{[["events","Kejadian & Prestasi"],["followup","Pembinaan / Tindak Lanjut"],["report","Rekap & Laporan"]].map(([k,n])=><button key={k} className={"button "+(tab===k?"":"secondary")} onClick={()=>setTab(k)}>{n}</button>)}</div>
 <section className="panel"><h2>Filter Data Sekolah</h2><div className="fields"><label className="field">Cari siswa / NIS<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari nama atau NIS…"/></label><label className="field">Kelas<select value={filterClass} onChange={e=>setFilterClass(e.target.value)}><option value="">Semua Kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.academic_year}</option>)}</select></label></div></section>
 {tab==="events"&&<section className="panel"><h2>Catat Kejadian, Pelanggaran & Prestasi</h2><p className="muted">Input manual tetap tersedia. Riwayat siswa yang diarsipkan tidak dihapus dari laporan.</p><form className="fields" onSubmit={e=>{e.preventDefault();void job(async()=>{await insert("sc_discipline_events",{student_id:studentId,category:kind,title:title.trim(),occurred_at:date,follow_up:followup.trim()||null,created_by:userId});setTitle("");setFollowup("")})}}><label className="field">Siswa<select value={studentId} required onChange={e=>setStudentId(e.target.value)}><option value="">Pilih Siswa</option>{matches.filter(s=>s.status==="active").map(s=><option key={s.id} value={s.id}>{s.name} · {s.nis||"—"}</option>)}</select></label><label className="field">Kategori<select value={kind} onChange={e=>setKind(e.target.value)}><option value="violation">Pelanggaran</option><option value="achievement">Prestasi</option><option value="coaching">Pembinaan</option></select></label><label className="field">Judul<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field">Tanggal<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field full">Langkah awal (opsional)<textarea value={followup} onChange={e=>setFollowup(e.target.value)}/></label><button className="button" disabled={busy||!studentId||title.trim().length<3}>Simpan Kejadian</button></form>{filtered.map(i=><div className="entry" key={i.id}><div><strong>{name(i.student_id)} · {i.title}</strong><small>{i.occurred_at} · {i.category} · {i.follow_up||"Belum ada tindak lanjut"}</small></div><button className="button secondary" onClick={()=>{setEventId(i.id);setTab("followup")}}>Tindak Lanjut</button></div>)}</section>}
 {tab==="followup"&&<section className="panel"><h2>Langkah Pembinaan</h2><form className="fields" onSubmit={e=>{e.preventDefault();void job(async()=>{await insert("sc_discipline_followups",{event_id:eventId,action_taken:followup.trim(),due_on:date,created_by:userId});setFollowup("")})}}><label className="field">Kejadian<select required value={eventId} onChange={e=>setEventId(e.target.value)}><option value="">Pilih Kejadian</option>{filtered.map(i=><option key={i.id} value={i.id}>{name(i.student_id)} · {i.title}</option>)}</select></label><label className="field">Target Selesai<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field full">Rencana tindakan<textarea value={followup} onChange={e=>setFollowup(e.target.value)} required/></label><button className="button" disabled={busy||!eventId||followup.trim().length<3}>Catat Tindak Lanjut</button></form>{followups.filter(f=>filtered.some(i=>i.id===f.event_id)).map(f=><div className="entry" key={f.id}><div><strong>{incidents.find(i=>i.id===f.event_id)?.title||"Kejadian"}</strong><small>{f.action_taken} · Target {f.due_on||"—"}</small></div><div className="flow"><span className="pill">{f.status}</span>{(manager||f.created_by===userId)&&f.status!=="completed"&&<button className="button secondary" disabled={busy} onClick={()=>void job(async()=>{if(!db)throw Error("Database belum siap");const {error:e}=await db.rpc("sc_decide_discipline_followup",{p_school:schoolId,p_followup:f.id,p_status:f.status==="open"?"in_progress":"completed"});if(e)throw e})}>Perbarui</button>}</div></div>)}</section>}
 {tab==="report"&&<section className="panel"><h2>Rekap Disiplin & Prestasi</h2><div className="grid"><div className="card"><label>Total kejadian terfilter</label><strong>{filtered.length}</strong></div><div className="card"><label>Pelanggaran</label><strong>{filtered.filter(x=>x.category==="violation").length}</strong></div><div className="card"><label>Prestasi</label><strong>{filtered.filter(x=>x.category==="achievement").length}</strong></div><div className="card"><label>Pembinaan</label><strong>{filtered.filter(x=>x.category==="coaching").length}</strong></div></div><button className="button" style={{marginTop:14}} onClick={exportReport}>Ekspor CSV Excel</button></section>}
 {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
}
