"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {isAdmin,type Role} from "@/lib/modules";
type Doc={id:string;kind:string;title:string;content:string;status:string;revision:number;created_by:string};
const kinds=["PBD","KSP","KOSP","RKJM","RKT","RKAS","SOP","SUPERVISION","TEACHING","REPORT","OTHER"];
const safe=(s:string)=>s.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
function printable(d:Doc){return "<!doctype html><html><head><meta charset='utf-8'><title>"+safe(d.title)+"</title><style>body{font:12pt Arial;margin:22mm;line-height:1.6}h1{font-size:20pt;border-bottom:1px solid #ccc;padding-bottom:10px}.body{white-space:pre-wrap}@media print{body{margin:12mm}}</style></head><body><h1>"+safe(d.title)+"</h1><small>"+safe(d.kind)+" · Revisi "+d.revision+" · "+safe(d.status)+"</small><div class='body'>"+safe(d.content)+"</div></body></html>"}
function word(d:Doc){const url=URL.createObjectURL(new Blob(["\uFEFF"+printable(d)],{type:"application/msword"}));const a=document.createElement("a");a.href=url;a.download=d.title.replace(/[^\w\- ]/g,"_").slice(0,65)+".doc";a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function pdf(d:Doc){const w=window.open("","_blank");if(!w)throw Error("Izinkan jendela cetak pada browser.");w.document.write(printable(d));w.document.close();w.focus();w.print()}
export default function DocumentCenter({schoolId,userId,role,teacherOnly=false}:{schoolId:string;userId:string;role:Role;teacherOnly?:boolean}){
 const db=useMemo(()=>browserDb(),[]),manager=isAdmin(role);
 const [docs,setDocs]=useState<Doc[]>([]),[selected,setSelected]=useState(""),[kind,setKind]=useState(teacherOnly?"TEACHING":"RKT"),[title,setTitle]=useState(""),[body,setBody]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 async function load(){if(!db)return;const {data,error}=await db.from("sc_documents").select("id,kind,title,content,status,revision,created_by").eq("school_id",schoolId).order("updated_at",{ascending:false}).limit(70);if(error)setError(error.message);else setDocs((data||[]) as Doc[])}
 useEffect(()=>{void load()},[db,schoolId]);
 function choose(id:string){setSelected(id);const d=docs.find(x=>x.id===id);setKind(d?.kind||"OTHER");setTitle(d?.title||"");setBody(d?.content||"")}
 async function task(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Perubahan dokumen tersimpan.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function save(submit:boolean){if(!db)return;await task(async()=>{const {data,error}=await db.rpc("sc_save_document",{p_school:schoolId,p_document:selected||null,p_kind:kind,p_title:title,p_content:body,p_submit:submit});if(error)throw error;setSelected(data)})}
 async function approve(id:string){if(!db)return;await task(async()=>{const {error}=await db.rpc("sc_approve_document",{p_school:schoolId,p_document:id});if(error)throw error})}
 async function remove(id:string){if(!db||!confirm("Hapus dokumen draft/review ini?"))return;await task(async()=>{const {error}=await db.rpc("sc_delete_auxiliary",{p_school:schoolId,p_entity:"document",p_id:id});if(error)throw error;if(selected===id){setSelected("");setTitle("");setBody("")}})}
 const editing=docs.find(d=>d.id===selected);
 return <><section className="panel"><h2>Pusat Dokumen dan Persetujuan</h2><p className="muted">Dokumen kerja menggunakan editor dan versi. Revisi hanya ketika draft/review, kemudian penanggung jawab menyetujui. Ekspor Word kompatibilitas .doc dan cetak/simpan PDF melalui browser.</p><div className="fields"><label className="field">Buka / Buat<select value={selected} onChange={e=>choose(e.target.value)}><option value="">Buat dokumen baru</option>{docs.map(d=><option key={d.id} value={d.id}>{d.title} · {d.status}</option>)}</select></label><label className="field">Jenis dokumen<select value={kind} onChange={e=>setKind(e.target.value)}>{kinds.filter(k=>!teacherOnly||["TEACHING","REPORT","OTHER"].includes(k)).map(k=><option key={k} value={k}>{k}</option>)}</select></label><label className="field full">Judul<input value={title} maxLength={180} onChange={e=>setTitle(e.target.value)}/></label><label className="field full">Isi<textarea value={body} rows={18} style={{minHeight:320}} onChange={e=>setBody(e.target.value)}/></label></div><div className="flow" style={{marginTop:12}}><button className="button secondary" disabled={busy||title.trim().length<3||!!editing&&["approved","archived"].includes(editing.status)} onClick={()=>void save(false)}>Simpan Draft</button><button className="button" disabled={busy||title.trim().length<3||!!editing&&["approved","archived"].includes(editing.status)} onClick={()=>void save(true)}>Ajukan Review</button>{editing&&<><button className="button secondary" onClick={()=>word(editing)}>Word (.doc)</button><button className="button secondary" onClick={()=>{try{pdf(editing)}catch(e){setError(String(e))}}}>Cetak / PDF</button></>}</div></section><section className="panel"><h2>Daftar Dokumen</h2>{docs.map(d=><div className="entry" key={d.id}><div><strong>{d.title}</strong><small>{d.kind} · Versi {d.revision} · {d.status}</small></div><div className="flow"><button className="button secondary" onClick={()=>choose(d.id)}>Buka</button>{manager&&d.status==="review"&&<button className="button" disabled={busy} onClick={()=>void approve(d.id)}>Setujui</button>}{["draft","review"].includes(d.status)&&(manager||d.created_by===userId)&&<button className="button danger" disabled={busy} onClick={()=>void remove(d.id)}>Hapus</button>}</div></div>)}{!docs.length&&<div className="empty">Belum ada dokumen.</div>}</section>{error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
}
