"use client";
import {useRealtimeRefresh} from "@/lib/school-realtime";
import {readAllRows} from "@/lib/read-all-rows";
import SearchableSelect from "@/components/SearchableSelect";
import {errorMessage} from "@/lib/error-message";
import {useEffect,useMemo,useState} from "react";
import {Plus} from "lucide-react";
import RecordListTools,{useRecordList,RecordCheckbox,type RecordBatchAction} from "@/components/RecordListTools";
import DataEntryModal from "@/components/DataEntryModal";
import {browserDb} from "@/lib/supabase";
import {csvExport,saveCsv} from "@/lib/csv";
import {downloadExcel,readExcel} from "@/lib/excel";
import {issueAndExport,loadReportIdentity,previewOfficialReport,type OfficialReportModel} from "@/lib/report-engine";
type Account={id:string;name:string;kind:string;opening_balance:number};
type Tx={id:string;occurred_at:string;kind:string;category:string;amount:number;account_id:string|null;description:string|null;number:string|null;activity_name:string|null;proof_path:string|null;status:string};
type Budget={id:string;fiscal_year:number;category:string;amount:number;notes:string|null;source_fund:string|null;activity_name:string|null};
type Student={id:string;name:string;nis:string|null};
type Bill={id:string;student_id:string;title:string;amount_due:number;due_on:string;period:string|null;status:string};
type Payment={id:string;bill_id:string;transaction_id:string;amount:number;receipt_no:string;paid_at:string;payment_method:string|null;proof_path:string|null};
type Totals={income:number;expense:number;opening:number;budget:number;billed:number;paid:number};
type Balance={account_id:string;account_name:string;kind:string;balance:number};
type ModalKind="account"|"transaction"|"budget"|"bill"|"payment"|null;
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const localDay=()=>{const p=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const v=(x:string)=>p.find(y=>y.type===x)?.value||"";return v("year")+"-"+v("month")+"-"+v("day")};
export default function FinancePanel({schoolId,userId,focus}:{schoolId:string;userId:string;focus?:string}){
 const db=useMemo(()=>browserDb(),[]);
 const [accounts,setAccounts]=useState<Account[]>([]),[tx,setTx]=useState<Tx[]>([]),[budgets,setBudgets]=useState<Budget[]>([]),[students,setStudents]=useState<Student[]>([]),[bills,setBills]=useState<Bill[]>([]),[payments,setPayments]=useState<Payment[]>([]),[totals,setTotals]=useState<Totals|null>(null),[balances,setBalances]=useState<Balance[]>([]);
 const [tab,setTab]=useState("overview"),[modal,setModal]=useState<ModalKind>(null),[name,setName]=useState(""),[accountKind,setAccountKind]=useState("cash"),[opening,setOpening]=useState("0"),[accountId,setAccountId]=useState(""),[txKind,setTxKind]=useState("income"),[category,setCategory]=useState(""),[activityName,setActivityName]=useState(""),[sourceFund,setSourceFund]=useState(""),[amount,setAmount]=useState(""),[description,setDescription]=useState(""),[date,setDate]=useState(localDay()),[year,setYear]=useState(String(new Date().getFullYear())),[period,setPeriod]=useState(localDay().slice(0,7)),[studentId,setStudentId]=useState(""),[billTitle,setBillTitle]=useState(""),[billId,setBillId]=useState(""),[receipt,setReceipt]=useState(""),[paymentMethod,setPaymentMethod]=useState("Tunai"),[proofFile,setProofFile]=useState<File|null>(null);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState(""),[financePreview,setFinancePreview]=useState<Record<string,unknown>[]>([]),[importFile,setImportFile]=useState(""),[reportKind,setReportKind]=useState("financial"),[reportMonth,setReportMonth]=useState(localDay().slice(0,7)),[reportAccount,setReportAccount]=useState("");
 useRealtimeRefresh(schoolId,()=>load());
 async function load(){if(!db)return;const r=await Promise.all([
 readAllRows(db.from("sc_finance_accounts").select("id,name,kind,opening_balance").eq("school_id",schoolId).order("name").order("id")),
 readAllRows(db.from("sc_finance_transactions").select("id,occurred_at,kind,category,amount,account_id,description,number,activity_name,proof_path,status").eq("school_id",schoolId).order("occurred_at",{ascending:false}).order("id")),
 readAllRows(db.from("sc_budget_lines").select("id,fiscal_year,category,amount,notes,source_fund,activity_name").eq("school_id",schoolId).order("fiscal_year",{ascending:false}).order("id")),
 readAllRows(db.from("sc_students").select("id,name,nis").eq("school_id",schoolId).eq("status","active").order("name").order("id")),
 readAllRows(db.from("sc_student_bills").select("id,student_id,title,amount_due,due_on,period,status").eq("school_id",schoolId).order("due_on",{ascending:false}).order("id")),
 readAllRows(db.from("sc_bill_payments").select("id,bill_id,transaction_id,amount,receipt_no,paid_at,payment_method,proof_path").eq("school_id",schoolId).order("paid_at",{ascending:false}).order("id")),
 db.rpc("sc_finance_summary",{p_school:schoolId}),db.rpc("sc_account_balances",{p_school:schoolId})
 ]);setAccounts((r[0].data||[]) as Account[]);setTx((r[1].data||[]) as Tx[]);setBudgets((r[2].data||[]) as Budget[]);setStudents((r[3].data||[]) as Student[]);setBills((r[4].data||[]) as Bill[]);setPayments((r[5].data||[]) as Payment[]);setTotals((r[6].data||null) as Totals|null);setBalances((r[7].data||[]) as Balance[]);for(const x of r){if(x.error){setError(x.error.message);break}}}
 useEffect(()=>{void load()},[db,schoolId]);
 useEffect(()=>{const f=(focus||"").toLowerCase();setModal(null);if(f.includes("dashboard"))setTab("dashboard");else if(f.includes("kas")||f.includes("rekening"))setTab("overview");else if(f.includes("pemasukan")){setTab("transaction");setTxKind("income")}else if(f.includes("pengeluaran")){setTab("transaction");setTxKind("expense")}else if(f.includes("realisasi")||f.includes("buku kas"))setTab("report");else if(f.includes("bukti"))setTab("transaction");else if(f.includes("anggaran"))setTab("budget");else if(f.includes("tagihan"))setTab("bill");else if(f.includes("pembayaran")||f.includes("kuitansi"))setTab("payment");else if(f.includes("laporan")||f.includes("import")||f.includes("export"))setTab("report")},[focus]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Data keuangan berhasil tersimpan.")}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function insert(table:string,row:Record<string,unknown>){if(!db)throw Error("Database belum terhubung");const {error}=await db.from(table).insert({...row,school_id:schoolId});if(error)throw error}
 async function rpc(fn:string,row:Record<string,unknown>){if(!db)throw Error("Database belum terhubung");const {data,error}=await db.rpc(fn,row);if(error)throw error;return data}
 async function uploadEvidence(file:File,prefix:string){
  if(!db)throw Error("Database belum terhubung");
  if(file.size>6*1024*1024)throw Error("Bukti maksimal 6 MB.");
  if(!["image/jpeg","image/png","image/webp","application/pdf"].includes(file.type))throw Error("Bukti harus berupa JPG, PNG, WebP, atau PDF.");
  const path=schoolId+"/finance/"+prefix+"-"+crypto.randomUUID()+"-"+file.name.replace(/[^\\w.-]/g,"_").slice(0,90);
  const {error}=await db.storage.from("sc-evidence").upload(path,file,{upsert:false,contentType:file.type});
  if(error)throw error;
  return path;
 }
 async function uploadProof(prefix:string){return proofFile?uploadEvidence(proofFile,prefix):null}
 async function viewProof(path:string|null){if(!db||!path)return;const {data,error}=await db.storage.from("sc-evidence").createSignedUrl(path,180);if(error){setError(error.message);return}window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 async function attachProof(kind:"transaction"|"payment",id:string,file:File|null){
  if(!file)return;
  await run(async()=>{const path=await uploadEvidence(file,kind);await rpc("sc_attach_finance_proof",{p_school:schoolId,p_kind:kind,p_record:id,p_path:path})});
 }

 async function editEntity(entity:string,id:string,patch:Record<string,unknown>){await run(()=>rpc("sc_update_operational",{p_school:schoolId,p_entity:entity,p_id:id,p_patch:patch}).then(()=>{}))}
 async function deleteEntity(entity:string,id:string){if(!confirm("Hapus data ini? Data bersejarah/terkait pembayaran akan ditolak."))return;await run(()=>rpc("sc_delete_operational",{p_school:schoolId,p_entity:entity,p_id:id}).then(()=>{}))}
 async function reverseTx(id:string){const reason=prompt("Alasan koreksi transaksi");if(!reason)return;await run(()=>rpc("sc_reverse_finance_transaction",{p_school:schoolId,p_tx:id,p_reason:reason}).then(()=>{}))}
 async function financeTemplate(){await downloadExcel("template-transaksi-keuangan-sekolapro.xlsx",[{name:"Transaksi",rows:[{Tanggal:"2026-09-30",Kas_Rekening:"Kas Tunai",Jenis:"income",Kategori:"Dana Kegiatan",Nominal:1000000,Uraian:"Contoh baris - hapus sebelum import"}]},{name:"Panduan",rows:[{Kolom:"Jenis",Keterangan:"Isi income untuk pemasukan atau expense untuk pengeluaran"},{Kolom:"Kas_Rekening",Keterangan:"Harus sama persis dengan nama kas/rekening yang sudah dibuat"}]}])}
 async function readFinance(file?:File){if(!file)return;try{const rows=await readExcel(file);if(rows.length>500)throw Error("Maksimal 500 transaksi");setFinancePreview(rows as Record<string,unknown>[]);setImportFile(file.name)}catch(e){setError(errorMessage(e))}}
 async function importFinance(){await run(async()=>{const rows=financePreview.map(x=>({occurred_at:String(x.Tanggal||""),account_name:String(x.Kas_Rekening||""),kind:String(x.Jenis||"").toLowerCase(),category:String(x.Kategori||""),amount:Number(x.Nominal||0),description:String(x.Uraian||"")}));await rpc("sc_import_finance_transactions",{p_school:schoolId,p_rows:rows});setFinancePreview([]);setImportFile("")})}
 const chooseAccount=<label className="field">Kas / Rekening<SearchableSelect label="Kas / Rekening" required value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Pilih kas</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.kind}</option>)}</SearchableSelect></label>;
 const bill=bills.find(b=>b.id===billId),paid=bill?payments.filter(p=>p.bill_id===bill.id).reduce((a,p)=>a+Number(p.amount),0):0;
 const studentName=(id:string)=>students.find(s=>s.id===id)?.name||"Siswa tidak aktif";
 const exportLedger=()=>saveCsv("buku-kas-"+reportMonth+"-sekolapro.csv",csvExport(["Tanggal","Nomor","Jenis","Kategori","Kas","Nominal","Keterangan","Bukti"],periodLedger.map(t=>[t.occurred_at,t.number,t.kind,t.category,accounts.find(a=>a.id===t.account_id)?.name,Number(t.amount),t.description,t.proof_path?"Ada":"Belum ada"])));
 const billPaid=(id:string)=>payments.filter(p=>p.bill_id===id).reduce((n,p)=>n+Number(p.amount),0);
 const budgetRealization=budgets.map(b=>{const spent=tx.filter(t=>t.status!=="void"&&t.kind==="expense"&&t.occurred_at.startsWith(String(b.fiscal_year))&&(b.activity_name?t.activity_name===b.activity_name:t.category===b.category)).reduce((n,t)=>n+Number(t.amount),0);return {...b,spent,remaining:Number(b.amount)-spent,percent:Number(b.amount)>0?Math.round(spent/Number(b.amount)*1000)/10:0}});
 const periodTransactions=tx.filter(t=>t.status!=="void"&&t.occurred_at.startsWith(reportMonth)&&(!reportAccount||t.account_id===reportAccount));
 const periodPayments=payments.filter(p=>p.paid_at.startsWith(reportMonth)&&(!reportAccount||tx.find(t=>t.id===p.transaction_id)?.account_id===reportAccount));
 const reportYear=Number(reportMonth.slice(0,4));
 const annualBudgets=budgetRealization.filter(b=>b.fiscal_year===reportYear);
 const periodIncome=periodTransactions.filter(t=>t.kind==="income").reduce((n,t)=>n+Number(t.amount),0);
 const periodExpense=periodTransactions.filter(t=>t.kind==="expense").reduce((n,t)=>n+Number(t.amount),0);
 const selectedAccounts=accounts.filter(a=>!reportAccount||a.id===reportAccount);
 const balanceAt=(account:Account,before:string)=>Number(account.opening_balance)+tx.filter(t=>t.status!=="void"&&t.account_id===account.id&&t.occurred_at<before).reduce((n,t)=>n+(t.kind==="income"?1:-1)*Number(t.amount),0);
 const periodStart=reportMonth+"-01";
 const periodEnd=new Date(Date.UTC(reportYear,Number(reportMonth.slice(5,7)),0)).toISOString().slice(0,10);
 const periodLabel=new Intl.DateTimeFormat("id-ID",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(periodStart+"T12:00:00Z"));
 const openingPeriod=selectedAccounts.reduce((n,a)=>n+balanceAt(a,periodStart),0);
 const closingPeriod=openingPeriod+periodIncome-periodExpense;
 const periodBills=bills.filter(b=>(b.period||b.due_on.slice(0,7))===reportMonth);
 const outstanding=bills.reduce((n,b)=>n+Math.max(0,Number(b.amount_due)-billPaid(b.id)),0);
 const periodLedger=[...periodTransactions].sort((a,b)=>a.occurred_at.localeCompare(b.occurred_at)||a.id.localeCompare(b.id));
 function financeReportModel():OfficialReportModel{
  const common={moduleKey:"sikas",orientation:"landscape" as const,status:"approved" as const,
   confidentiality:"restricted" as const,periodLabel,periodStart,periodEnd,
   notes:["Laporan internal Sekolapro. Pelaporan dan pengesahan dana pemerintah tetap mengikuti sistem resmi yang berlaku."]};
  if(reportKind==="bku"){
   let saldo=openingPeriod;
   return {...common,documentType:"buku_kas_umum",prefix:"BKU",title:"Buku Kas Umum",subtitle:"Mutasi kas dan rekening periode "+periodLabel,
    metrics:[{label:"Saldo awal",value:money(openingPeriod)},{label:"Pemasukan",value:money(periodIncome)},{label:"Pengeluaran",value:money(periodExpense)},{label:"Saldo akhir",value:money(closingPeriod)}],
    sections:[{title:"Buku Kas Umum",columns:["Tanggal","Nomor","Kas/Rekening","Kategori","Kegiatan","Uraian","Masuk","Keluar","Saldo berjalan"],
     rows:periodLedger.map(t=>{saldo+=(t.kind==="income"?1:-1)*Number(t.amount);return [t.occurred_at,t.number||"—",accounts.find(a=>a.id===t.account_id)?.name||"—",t.category,t.activity_name||"—",t.description||"—",t.kind==="income"?money(t.amount):"—",t.kind==="expense"?money(t.amount):"—",money(saldo)]})}]};
  }
  if(reportKind==="receivables"){
   return {...common,documentType:"tagihan_tunggakan",prefix:"PIUT",title:"Laporan Tagihan dan Tunggakan Siswa",
    subtitle:"Tagihan periode "+periodLabel+" dan status pembayaran saat laporan dibuat",
    metrics:[{label:"Tagihan periode",value:money(periodBills.reduce((n,b)=>n+Number(b.amount_due),0))},{label:"Terbayar",value:money(periodBills.reduce((n,b)=>n+billPaid(b.id),0))},{label:"Sisa periode",value:money(periodBills.reduce((n,b)=>n+Math.max(0,Number(b.amount_due)-billPaid(b.id)),0))},{label:"Piutang seluruh periode",value:money(outstanding)}],
    sections:[{title:"Tagihan Siswa",columns:["NIS","Siswa","Tagihan","Periode","Jatuh Tempo","Nilai","Terbayar","Sisa","Status"],
     rows:periodBills.map(b=>{const received=billPaid(b.id),due=Math.max(0,Number(b.amount_due)-received),st=students.find(x=>x.id===b.student_id);return [st?.nis||"—",st?.name||"Siswa",b.title,b.period||"—",b.due_on,money(b.amount_due),money(received),money(due),due===0?"Lunas":received>0?"Sebagian":"Belum bayar"]})}]};
  }
  if(reportKind==="payments"){
   return {...common,documentType:"pembayaran_kuitansi",prefix:"BYR",title:"Laporan Pembayaran dan Kuitansi",subtitle:"Penerimaan tagihan siswa periode "+periodLabel,
    metrics:[{label:"Pembayaran",value:String(periodPayments.length)},{label:"Total diterima",value:money(periodPayments.reduce((n,p)=>n+Number(p.amount),0))},{label:"Metode",value:String(new Set(periodPayments.map(p=>p.payment_method||"Lainnya")).size)},{label:"Bukti terlampir",value:String(periodPayments.filter(p=>p.proof_path).length)}],
    sections:[{title:"Riwayat Pembayaran",columns:["Tanggal","Kuitansi","NIS","Siswa","Tagihan","Metode","Kas/Rekening","Nominal","Bukti"],
     rows:periodPayments.map(p=>{const b=bills.find(x=>x.id===p.bill_id),st=students.find(x=>x.id===b?.student_id),transaction=tx.find(t=>t.id===p.transaction_id);return [p.paid_at.slice(0,10),p.receipt_no,st?.nis||"—",st?.name||"Siswa",b?.title||"Tagihan",p.payment_method||"—",accounts.find(a=>a.id===transaction?.account_id)?.name||"—",money(p.amount),p.proof_path?"Ada":"Belum ada"]})}]};
  }
  if(reportKind==="budget"){
   return {...common,documentType:"anggaran_realisasi",prefix:"ANG",title:"Laporan Anggaran dan Realisasi",subtitle:"Realisasi tahun anggaran "+reportYear,
    metrics:[{label:"Pagu anggaran",value:money(annualBudgets.reduce((n,b)=>n+Number(b.amount),0))},{label:"Realisasi",value:money(annualBudgets.reduce((n,b)=>n+b.spent,0))},{label:"Sisa",value:money(annualBudgets.reduce((n,b)=>n+b.remaining,0))},{label:"Kegiatan",value:String(annualBudgets.length)}],
    sections:[{title:"Rincian Anggaran Tahunan",columns:["Tahun","Sumber Dana","Kegiatan","Kategori","Pagu","Realisasi","Sisa","%"],
      rows:annualBudgets.map(b=>[b.fiscal_year,b.source_fund||"—",b.activity_name||"—",b.category,money(b.amount),money(b.spent),money(b.remaining),b.percent+"%"])}]};
  }
  return {...common,documentType:"keuangan_sekolah",prefix:"KEU",title:"Laporan Keuangan Sekolah",subtitle:"Rekap terpadu periode "+periodLabel,
   metrics:[{label:"Saldo awal",value:money(openingPeriod)},{label:"Pemasukan",value:money(periodIncome)},{label:"Pengeluaran",value:money(periodExpense)},{label:"Saldo akhir",value:money(closingPeriod)},{label:"Piutang seluruh periode",value:money(outstanding)}],
   sections:[
    {title:"Saldo Kas / Rekening Akhir Periode",columns:["Kas/Rekening","Jenis","Saldo akhir"],
     rows:selectedAccounts.map(a=>[a.name,a.kind,money(balanceAt(a,periodEnd+"~"))])},
    {title:"Mutasi Keuangan",columns:["Tanggal","Nomor","Kas/Rekening","Jenis","Kategori","Kegiatan","Keterangan","Nominal","Bukti"],
     rows:periodLedger.map(t=>[t.occurred_at,t.number||"—",accounts.find(a=>a.id===t.account_id)?.name||"—",t.kind==="income"?"Pemasukan":"Pengeluaran",t.category,t.activity_name||"—",t.description||"—",money(t.amount),t.proof_path?"Ada":"Belum ada"])},
    {title:"Tagihan Periode",columns:["Siswa","Tagihan","Nilai","Terbayar","Sisa"],
     rows:periodBills.map(b=>[studentName(b.student_id),b.title,money(b.amount_due),money(billPaid(b.id)),money(Math.max(0,Number(b.amount_due)-billPaid(b.id)))])},
    {title:"Ringkasan Anggaran Tahunan",columns:["Sumber Dana","Kegiatan/Kategori","Pagu","Realisasi","Sisa"],
     rows:annualBudgets.map(b=>[b.source_fund||"—",b.activity_name||b.category,money(b.amount),money(b.spent),money(b.remaining)])}
   ]};
 }

 async function exportOfficialFinance(format:"pdf"|"docx"|"xlsx"){if(!db)return;await run(async()=>{const identity=await loadReportIdentity(db,schoolId),model=financeReportModel(),issued=await issueAndExport(db,schoolId,identity,model,format);setOk("Laporan "+issued.document_number+" diterbitkan dan masuk arsip keuangan.")})}
 async function previewOfficialFinance(){if(!db)return;await run(async()=>{const identity=await loadReportIdentity(db,schoolId);previewOfficialReport(identity,{...financeReportModel(),status:"draft"});setOk("Preview draft dibuka tanpa memakai nomor dokumen.")})}
 function open(kind:Exclude<ModalKind,null>){setError("");setProofFile(null);if(kind==="account"){setName("");setAccountKind("cash");setOpening("0")}if(kind==="transaction"){setAccountId("");setCategory("");setActivityName("");setAmount("");setDescription("");setDate(localDay())}if(kind==="budget"){setCategory("");setActivityName("");setSourceFund("");setAmount("");setDescription("");setYear(String(new Date().getFullYear()))}if(kind==="bill"){setStudentId("");setBillTitle("");setPeriod(localDay().slice(0,7));setAmount("");setDate(localDay())}if(kind==="payment"){setBillId("");setAccountId("");setAmount("");setReceipt("");setPaymentMethod("Tunai")}setModal(kind)}
 const pageTitle=tab==="overview"?"Kas & Rekening":tab==="transaction"?(txKind==="income"?"Pemasukan":"Pengeluaran"):tab==="budget"?"Anggaran":tab==="bill"?"Tagihan Siswa":tab==="payment"?"Pembayaran & Kuitansi":"Laporan & Import";
 const modalForTab:ModalKind=tab==="overview"?"account":tab==="transaction"?"transaction":tab==="budget"?"budget":tab==="bill"?"bill":tab==="payment"?"payment":null;
 const records=tab==="overview"?accounts.map(a=>({id:a.id,text:a.name+" "+a.kind,group:a.kind})):tab==="transaction"?tx.filter(t=>t.kind===txKind).map(t=>({id:t.id,text:[t.category,t.description,t.occurred_at,accounts.find(a=>a.id===t.account_id)?.name].join(" "),group:t.account_id||""})):tab==="budget"?budgets.map(b=>({id:b.id,text:[b.category,b.activity_name,b.source_fund,b.fiscal_year,b.notes].join(" "),group:String(b.fiscal_year)})):tab==="bill"?bills.map(b=>({id:b.id,text:[studentName(b.student_id),students.find(s=>s.id===b.student_id)?.nis,b.title,b.period,b.due_on].join(" "),group:billPaid(b.id)>=Number(b.amount_due)?"paid":"unpaid"})):payments.map(p=>({id:p.id,text:[p.receipt_no,p.paid_at,bills.find(b=>b.id===p.bill_id)?.title,studentName(bills.find(b=>b.id===p.bill_id)?.student_id||"")].join(" "),group:p.payment_method||""}));
 const list=useRecordList(records,r=>r.text,[{key:"group",label:tab==="transaction"?"Kas / rekening":tab==="bill"?"Status tagihan":"Filter jenis / periode",options:[...new Set(records.map(r=>r.group).filter(Boolean))].map(v=>({value:v,label:tab==="transaction"?accounts.find(a=>a.id===v)?.name||v:v==="paid"?"Lunas":v==="unpaid"?"Belum lunas":v})),value:r=>r.group}]);const pageIds=new Set(list.visible.map(r=>r.id));
 const batchActions:RecordBatchAction[]=tab==="transaction"?[{key:"reverse",label:"Koreksi pilihan",description:"Buat transaksi penyeimbang dengan alasan koreksi yang sama. Transaksi asli dan jejak audit tetap disimpan.",reasonRequired:true,run:(id,reason)=>rpc("sc_reverse_finance_transaction",{p_school:schoolId,p_tx:id,p_reason:reason||""}).then(()=>{})}]:["overview","budget","bill"].includes(tab)?[{key:"delete",label:"Hapus pilihan",description:"Hapus data yang belum terpakai. Kas yang memiliki transaksi dan tagihan yang sudah dibayar dilindungi.",danger:true,eligible:id=>tab!=="bill"||billPaid(id)===0,run:id=>rpc("sc_delete_operational",{p_school:schoolId,p_entity:tab==="overview"?"finance_account":tab==="bill"?"bill":"budget",p_id:id}).then(()=>{})}]:[];
 function financeCheckbox(id:string,label:string){return tab==="dashboard"?null:<RecordCheckbox list={list} id={id} label={label} disabled={busy||(tab==="bill"&&billPaid(id)>0)}/>;}
 const excelToolbar=(tab==="transaction"||tab==="report")?<section className="panel excel-toolbar"><h2>Import & Template Transaksi</h2><div className="flow"><button className="button secondary" onClick={()=>void financeTemplate()}>Template Import Excel</button><label className="button secondary">Pilih Excel / CSV<input hidden type="file" accept=".xlsx,.xls,.csv,text/csv" onChange={e=>void readFinance(e.currentTarget.files?.[0])}/></label></div>{financePreview.length>0&&<div className="banner"><strong>{importFile} · {financePreview.length} baris</strong><p className="hint">Periksa nama kas/rekening dan nominal sebelum import. File dapat berisi pemasukan dan pengeluaran.</p><button className="button" onClick={()=>void importFinance()} disabled={busy}>Konfirmasi Import</button></div>}</section>:null;
 return <>
  {excelToolbar}
  <div className="grid"><div className="card"><label>Pemasukan tercatat</label><strong style={{fontSize:21}}>{money(totals?.income||0)}</strong></div><div className="card"><label>Pengeluaran</label><strong style={{fontSize:21}}>{money(totals?.expense||0)}</strong></div><div className="card"><label>Saldo kas keseluruhan</label><strong style={{fontSize:21}}>{money((totals?.opening||0)+(totals?.income||0)-(totals?.expense||0))}</strong></div><div className="card"><label>Tagihan belum dibayar</label><strong style={{fontSize:21}}>{money((totals?.billed||0)-(totals?.paid||0))}</strong></div></div>
  {tab==="dashboard"&&<section className="panel"><h2>Ringkasan Keuangan</h2><p className="muted">Saldo tiap kas dan transaksi terbaru. Kelola rekening melalui Kas/Rekening; catat transaksi melalui Pemasukan atau Pengeluaran.</p><h3>Saldo per kas / rekening</h3>{balances.map(b=><div className="entry" key={b.account_id}><strong>{b.account_name}</strong><b>{money(b.balance)}</b></div>)}{!balances.length&&<div className="empty">Buat kas atau rekening terlebih dahulu.</div>}<h3 style={{marginTop:20}}>Transaksi terbaru</h3>{tx.slice(0,8).map(t=><div className="entry" key={t.id}>{financeCheckbox(t.id,t.category)}<div className="record-main"><strong>{t.category}</strong><small>{t.occurred_at} · {t.kind==="income"?"Pemasukan":"Pengeluaran"}</small></div><b>{money(t.amount)}</b></div>)}{!tx.length&&<div className="empty">Belum ada transaksi keuangan.</div>}</section>}
  {tab!=="report"&&tab!=="dashboard"&&<section className="panel"><div className="sectionhead"><div><h2>{pageTitle}</h2><p className="muted">Daftar data keuangan. Input baru dibuka melalui popup agar transaksi lebih fokus dan mengurangi salah isi.</p></div>{modalForTab&&<button className="button" onClick={()=>open(modalForTab)}><Plus size={15}/> Tambah Data</button>}</div>
   <RecordListTools list={list} label="data keuangan" actions={batchActions} canSelect={batchActions.length>0} selectable={id=>tab!=="bill"||billPaid(id)===0} onRefresh={load} busy={busy}/>
   {tab==="overview"&&<>{accounts.filter(a=>pageIds.has(a.id)).map(a=>{const balance=Number(balances.find(b=>b.account_id===a.id)?.balance??a.opening_balance);return <div className="entry" key={a.id}>{financeCheckbox(a.id,a.name)}<div className="record-main"><strong>{a.name}</strong><small>{a.kind} · Saldo awal {money(a.opening_balance)}</small></div><div className="flow"><span className="pill">{money(balance)}</span><button className="button secondary" onClick={()=>{const n=prompt("Nama kas/rekening",a.name);const k=prompt("Jenis: cash / bank / ewallet / other",a.kind);const o=prompt("Saldo awal",String(a.opening_balance));if(n&&k&&o!==null)void editEntity("finance_account",a.id,{name:n,kind:k,opening_balance:Number(o)})}}>Edit</button><button className="button danger" onClick={()=>void deleteEntity("finance_account",a.id)}>Hapus</button></div></div>})}{!accounts.length&&<div className="empty">Belum ada kas atau rekening.</div>}</>}
   {tab==="transaction"&&<>{tx.filter(t=>t.kind===txKind&&pageIds.has(t.id)).map(t=><div className="entry" key={t.id}>{financeCheckbox(t.id,t.category)}<div className="record-main"><strong>{t.category}</strong><small>{t.occurred_at} · {accounts.find(a=>a.id===t.account_id)?.name||"Tanpa rekening"} · {t.description||""}</small></div><div className="flow"><b>{t.kind==="income"?"+":"−"}{money(t.amount)}</b><button className="button secondary" onClick={()=>void reverseTx(t.id)}>Koreksi</button></div></div>)}{!tx.filter(t=>t.kind===txKind).length&&<div className="empty">Belum ada transaksi.</div>}</>}
   {tab==="budget"&&<>{budgets.filter(b=>pageIds.has(b.id)).map(b=><div className="entry" key={b.id}>{financeCheckbox(b.id,"Data "+b.id)}<div className="record-main"><strong>{b.category} · {b.fiscal_year}</strong><small>{b.notes||"Tanpa rincian"}</small></div><div className="flow"><b>{money(b.amount)}</b><button className="button secondary" onClick={()=>{const cat=prompt("Kategori / kegiatan",b.category);const amt=prompt("Nominal",String(b.amount));const n=prompt("Catatan",b.notes||"")||"";if(cat&&amt!==null)void editEntity("budget",b.id,{category:cat,amount:Number(amt),notes:n})}}>Edit</button><button className="button danger" onClick={()=>void deleteEntity("budget",b.id)}>Hapus</button></div></div>)}{!budgets.length&&<div className="empty">Belum ada anggaran.</div>}</>}
   {tab==="bill"&&<>{bills.filter(b=>pageIds.has(b.id)).map(b=>{const got=payments.filter(p=>p.bill_id===b.id).reduce((v,p)=>v+Number(p.amount),0);return <div className="entry" key={b.id}>{financeCheckbox(b.id,"Data "+b.id)}<div className="record-main"><strong>{studentName(b.student_id)} · {b.title}</strong><small>Jatuh tempo {b.due_on} · Sudah diterima {money(got)}</small></div><div className="flow"><span className="pill">Sisa {money(Number(b.amount_due)-got)}</span><button className="button secondary" onClick={()=>{const t=prompt("Nama tagihan",b.title);const a=prompt("Nominal",String(b.amount_due));const due=prompt("Jatuh tempo YYYY-MM-DD",b.due_on);if(t&&a&&due)void editEntity("bill",b.id,{title:t,amount_due:Number(a),due_on:due})}}>Edit</button>{got===0&&<button className="button danger" onClick={()=>void deleteEntity("bill",b.id)}>Hapus</button>}</div></div>})}{!bills.length&&<div className="empty">Belum ada tagihan.</div>}</>}
   {tab==="payment"&&<>{payments.filter(p=>pageIds.has(p.id)).map(p=><div className="entry" key={p.id}><div><strong>{p.receipt_no}</strong><small>{p.paid_at.slice(0,10)} · {bills.find(b=>b.id===p.bill_id)?.title||"Tagihan"}</small></div><b>{money(p.amount)}</b></div>)}{!payments.length&&<div className="empty">Belum ada pembayaran.</div>}</>}
  </section>}
  {tab==="report"&&<section className="panel"><div className="sectionhead"><div><h2>Pusat Laporan & Import Keuangan</h2><p className="muted">Pilih jenis laporan resmi. Preview memakai watermark DRAFT; Word/Excel/PDF final mendapatkan nomor dokumen dan masuk arsip keuangan.</p></div></div><div className="fields"><label className="field">Jenis laporan<SearchableSelect label="Jenis laporan" value={reportKind} onChange={e=>setReportKind(e.target.value)}><option value="financial">Laporan Keuangan Sekolah</option><option value="receivables">Tagihan & Tunggakan</option><option value="payments">Pembayaran & Kuitansi</option><option value="budget">Anggaran & Realisasi</option></SearchableSelect></label></div><div className="flow"><button className="button secondary" disabled={busy} onClick={()=>void previewOfficialFinance()}>Preview Draft</button><button className="button secondary" disabled={busy} onClick={()=>void exportOfficialFinance("xlsx")}>Excel</button><button className="button secondary" disabled={busy} onClick={()=>void exportOfficialFinance("docx")}>Word</button><button className="button" disabled={busy} onClick={()=>void exportOfficialFinance("pdf")}>PDF</button><button className="button secondary" onClick={exportLedger}>CSV Buku Kas</button></div><div className="grid" style={{marginTop:18}}><div className="card"><label>Anggaran tercatat</label><strong style={{fontSize:18}}>{money(totals?.budget||0)}</strong></div><div className="card"><label>Total tagihan</label><strong style={{fontSize:18}}>{money(totals?.billed||0)}</strong></div><div className="card"><label>Total pembayaran</label><strong style={{fontSize:18}}>{money(totals?.paid||0)}</strong></div><div className="card"><label>Sisa piutang</label><strong style={{fontSize:18}}>{money((totals?.billed||0)-(totals?.paid||0))}</strong></div></div></section>}
  <DataEntryModal open={modal==="account"} onClose={()=>setModal(null)} title="Tambah Kas / Rekening" subtitle="Buat sumber dana yang akan dipakai transaksi, tagihan, dan laporan."><div className="fields"><label className="field">Nama Kas / Rekening<input value={name} onChange={e=>setName(e.target.value)} autoFocus/></label><label className="field">Jenis<SearchableSelect label="Jenis" value={accountKind} onChange={e=>setAccountKind(e.target.value)}><option value="cash">Tunai</option><option value="bank">Bank</option><option value="ewallet">E-Wallet</option><option value="other">Lainnya</option></SearchableSelect></label><label className="field">Saldo awal<input type="number" min={0} value={opening} onChange={e=>setOpening(e.target.value)}/></label></div><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Batal</button><button className="button" disabled={busy||!name.trim()} onClick={()=>void run(async()=>{await insert("sc_finance_accounts",{name:name.trim(),kind:accountKind,opening_balance:Number(opening)});setModal(null)})}>Simpan Kas</button></div></DataEntryModal>
  <DataEntryModal open={modal==="transaction"} onClose={()=>setModal(null)} title={txKind==="income"?"Tambah Pemasukan":"Tambah Pengeluaran"} subtitle="Pilih kas/rekening, kategori, kegiatan, tanggal, nominal, uraian dan bukti opsional."><div className="fields">{chooseAccount}<label className="field">Jenis<SearchableSelect label="Jenis" value={txKind} onChange={e=>setTxKind(e.target.value)}><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></SearchableSelect></label><label className="field">Tanggal<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Kategori<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="BOSP / Kegiatan / Operasional"/></label><label className="field">Kegiatan / sumber<input value={activityName} onChange={e=>setActivityName(e.target.value)} placeholder="Boleh diketik sendiri"/></label><label className="field">Nominal<input type="number" min={1} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field">Bukti opsional<input type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" onChange={e=>setProofFile(e.target.files?.[0]||null)}/></label><label className="field full">Uraian<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4}/></label></div><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Batal</button><button className="button" disabled={busy||!accountId||Number(amount)<=0||!category.trim()} onClick={()=>void run(async()=>{const proof=await uploadProof("transaction");await insert("sc_finance_transactions",{account_id:accountId,occurred_at:date,kind:txKind,category:category.trim(),activity_name:activityName.trim()||null,number:(txKind==="income"?"IN-":"OUT-")+date.replaceAll("-","")+"-"+crypto.randomUUID().slice(0,6).toUpperCase(),amount:Number(amount),description:description.trim()||null,proof_path:proof,status:"posted",created_by:userId});setModal(null)})}>Simpan Transaksi</button></div></DataEntryModal>
  <DataEntryModal open={modal==="budget"} onClose={()=>setModal(null)} title="Tambah Anggaran" subtitle="Catat sumber dana, kegiatan, pagu dan catatan agar realisasi dapat dihitung dari pengeluaran."><div className="fields"><label className="field">Tahun<input type="number" value={year} onChange={e=>setYear(e.target.value)}/></label><label className="field">Sumber dana<input value={sourceFund} onChange={e=>setSourceFund(e.target.value)} placeholder="BOSP / Komite / Hibah / lainnya"/></label><label className="field">Nama kegiatan<input value={activityName} onChange={e=>setActivityName(e.target.value)} placeholder="Contoh: Literasi sekolah"/></label><label className="field">Kategori<input value={category} onChange={e=>setCategory(e.target.value)} placeholder="Operasional / Program"/></label><label className="field">Pagu Anggaran<input type="number" min={0} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field full">Catatan<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label></div><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Batal</button><button className="button" disabled={busy||!category.trim()||Number(amount)<0} onClick={()=>void run(async()=>{await insert("sc_budget_lines",{fiscal_year:Number(year),source_fund:sourceFund.trim()||null,activity_name:activityName.trim()||null,category:category.trim(),amount:Number(amount),notes:description.trim()||null});setModal(null)})}>Simpan Anggaran</button></div></DataEntryModal>
  <DataEntryModal open={modal==="bill"} onClose={()=>setModal(null)} title="Terbitkan Tagihan Siswa" subtitle="Pilih siswa, periode, nama tagihan, jatuh tempo, dan nominal."><div className="fields"><label className="field">Siswa<SearchableSelect label="Siswa" value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Pilih siswa</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.nis||"—"}</option>)}</SearchableSelect></label><label className="field">Nama Tagihan<input value={billTitle} onChange={e=>setBillTitle(e.target.value)}/></label><label className="field">Periode<input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><label className="field">Jatuh Tempo<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">Nominal<input type="number" min={1} value={amount} onChange={e=>setAmount(e.target.value)}/></label></div><div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Batal</button><button className="button" disabled={busy||!studentId||!billTitle.trim()||Number(amount)<=0} onClick={()=>void run(async()=>{await insert("sc_student_bills",{student_id:studentId,title:billTitle.trim(),period:period||null,due_on:date,amount_due:Number(amount),status:"unpaid",created_by:userId});setModal(null)})}>Terbitkan Tagihan</button></div></DataEntryModal>
  <DataEntryModal open={modal==="payment"} onClose={()=>setModal(null)} title="Catat Pembayaran & Kuitansi" subtitle="Pembayaran otomatis masuk ke buku kas; metode dan bukti ikut tersimpan pada kuitansi."><div className="fields"><label className="field">Tagihan<SearchableSelect label="Tagihan" value={billId} onChange={e=>setBillId(e.target.value)}><option value="">Pilih tagihan</option>{bills.filter(b=>Number(b.amount_due)-payments.filter(p=>p.bill_id===b.id).reduce((n,p)=>n+Number(p.amount),0)>0).map(b=><option key={b.id} value={b.id}>{studentName(b.student_id)} · {b.title}</option>)}</SearchableSelect></label>{chooseAccount}<label className="field">Nominal dibayar<input type="number" min={1} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field">Metode<SearchableSelect label="Metode" allowCustom value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)}><option>Tunai</option><option>Transfer Bank</option><option>E-Wallet</option><option>QRIS</option><option>Lainnya</option></SearchableSelect></label><label className="field">Nomor kuitansi<input value={receipt} onChange={e=>setReceipt(e.target.value)} placeholder="KW-2026-0001"/></label><label className="field">Bukti pembayaran<input type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" onChange={e=>setProofFile(e.target.files?.[0]||null)}/></label></div>{bill&&<div className="banner">Sisa tagihan: <strong>{money(Number(bill.amount_due)-paid)}</strong></div>}<div className="modal-actions"><button className="button secondary" onClick={()=>setModal(null)}>Batal</button><button className="button" disabled={busy||!billId||!accountId||Number(amount)<=0||Number(amount)>Number(bill?.amount_due||0)-paid||receipt.trim().length<4} onClick={()=>void run(async()=>{const proof=await uploadProof("payment");await rpc("sc_record_bill_payment_v2",{p_school:schoolId,p_bill:billId,p_account:accountId,p_amount:Number(amount),p_receipt:receipt.trim(),p_method:paymentMethod,p_proof:proof});setModal(null)})}>Catat Pembayaran</button></div></DataEntryModal>
  {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}
 </>;
}
