"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {csvExport,saveCsv} from "@/lib/csv";
import {downloadExcel,readExcel} from "@/lib/excel";
type Account={id:string;name:string;kind:string;opening_balance:number};
type Tx={id:string;occurred_at:string;kind:string;category:string;amount:number;account_id:string|null;description:string|null};
type Budget={id:string;fiscal_year:number;category:string;amount:number;notes:string|null};
type Student={id:string;name:string;nis:string|null};
type Bill={id:string;student_id:string;title:string;amount_due:number;due_on:string};
type Payment={id:string;bill_id:string;amount:number;receipt_no:string;paid_at:string};
type Totals={income:number;expense:number;opening:number;budget:number;billed:number;paid:number};
type Balance={account_id:string;account_name:string;kind:string;balance:number};
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const localDay=()=>{const p=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Jakarta",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const v=(x:string)=>p.find(y=>y.type===x)?.value||"";return v("year")+"-"+v("month")+"-"+v("day")};
export default function FinancePanel({schoolId,userId,focus}:{schoolId:string;userId:string;focus?:string}){
 const db=useMemo(()=>browserDb(),[]);
 const [accounts,setAccounts]=useState<Account[]>([]),[tx,setTx]=useState<Tx[]>([]),[budgets,setBudgets]=useState<Budget[]>([]),[students,setStudents]=useState<Student[]>([]),[bills,setBills]=useState<Bill[]>([]),[payments,setPayments]=useState<Payment[]>([]),[totals,setTotals]=useState<Totals|null>(null),[balances,setBalances]=useState<Balance[]>([]);
 const [tab,setTab]=useState("overview"),[name,setName]=useState(""),[kind,setKind]=useState("cash"),[opening,setOpening]=useState("0"),[accountId,setAccountId]=useState(""),[category,setCategory]=useState(""),[amount,setAmount]=useState(""),[description,setDescription]=useState(""),[date,setDate]=useState(localDay()),[year,setYear]=useState(String(new Date().getFullYear())),[studentId,setStudentId]=useState(""),[billTitle,setBillTitle]=useState(""),[billId,setBillId]=useState(""),[receipt,setReceipt]=useState("");
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState(""),[financePreview,setFinancePreview]=useState<Record<string,unknown>[]>([]),[importFile,setImportFile]=useState("");
 async function load(){if(!db)return;const r=await Promise.all([
 db.from("sc_finance_accounts").select("id,name,kind,opening_balance").eq("school_id",schoolId).order("name"),
 db.from("sc_finance_transactions").select("id,occurred_at,kind,category,amount,account_id,description").eq("school_id",schoolId).order("occurred_at",{ascending:false}).limit(250),
 db.from("sc_budget_lines").select("id,fiscal_year,category,amount,notes").eq("school_id",schoolId).order("fiscal_year",{ascending:false}),
 db.from("sc_students").select("id,name,nis").eq("school_id",schoolId).eq("status","active").order("name"),
 db.from("sc_student_bills").select("id,student_id,title,amount_due,due_on").eq("school_id",schoolId).order("due_on",{ascending:false}),
 db.from("sc_bill_payments").select("id,bill_id,amount,receipt_no,paid_at").eq("school_id",schoolId).order("paid_at",{ascending:false}),
 db.rpc("sc_finance_summary",{p_school:schoolId}),
 db.rpc("sc_account_balances",{p_school:schoolId})
 ]);setAccounts((r[0].data||[]) as Account[]);setTx((r[1].data||[]) as Tx[]);setBudgets((r[2].data||[]) as Budget[]);setStudents((r[3].data||[]) as Student[]);setBills((r[4].data||[]) as Bill[]);setPayments((r[5].data||[]) as Payment[]);setTotals((r[6].data||null) as Totals|null);setBalances((r[7].data||[]) as Balance[]);for(const x of r){if(x.error){setError(x.error.message);break}}}
 useEffect(()=>{void load()},[db,schoolId]);
 useEffect(()=>{const f=(focus||"").toLowerCase();if(f.includes("kas")||f.includes("rekening"))setTab("overview");else if(f.includes("pemasukan")||f.includes("pengeluaran"))setTab("transaction");else if(f.includes("anggaran"))setTab("budget");else if(f.includes("tagihan"))setTab("bill");else if(f.includes("pembayaran")||f.includes("kuitansi"))setTab("payment");else if(f.includes("laporan")||f.includes("ekspor"))setTab("report")},[focus]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Data keuangan berhasil tersimpan.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function insert(table:string,row:Record<string,unknown>){if(!db)throw Error("Database belum terhubung");const {error}=await db.from(table).insert({...row,school_id:schoolId});if(error)throw error}
 async function rpc(fn:string,row:Record<string,unknown>){if(!db)throw Error("Database belum terhubung");const {data,error}=await db.rpc(fn,row);if(error)throw error;return data}
 async function editEntity(entity:string,id:string,patch:Record<string,unknown>){await run(()=>rpc("sc_update_operational",{p_school:schoolId,p_entity:entity,p_id:id,p_patch:patch}).then(()=>{}))}
 async function deleteEntity(entity:string,id:string){if(!confirm("Hapus data ini? Data bersejarah/terkait pembayaran akan ditolak."))return;await run(()=>rpc("sc_delete_operational",{p_school:schoolId,p_entity:entity,p_id:id}).then(()=>{}))}
 async function reverseTx(id:string){const reason=prompt("Alasan koreksi transaksi");if(!reason)return;await run(()=>rpc("sc_reverse_finance_transaction",{p_school:schoolId,p_tx:id,p_reason:reason}).then(()=>{}))}
 async function financeTemplate(){await downloadExcel("template-transaksi-keuangan-school-control.xlsx",[{name:"Transaksi",rows:[{Tanggal:"2026-09-30",Kas_Rekening:"Kas Tunai",Jenis:"income",Kategori:"Dana Kegiatan",Nominal:1000000,Uraian:"Contoh baris - hapus sebelum import"}]},{name:"Panduan",rows:[{Kolom:"Jenis",Keterangan:"Isi income untuk pemasukan atau expense untuk pengeluaran"},{Kolom:"Kas_Rekening",Keterangan:"Harus sama persis dengan nama kas/rekening yang sudah dibuat"}]}])}
 async function readFinance(file?:File){if(!file)return;try{const rows=await readExcel(file);if(rows.length>500)throw Error("Maksimal 500 transaksi");setFinancePreview(rows as Record<string,unknown>[]);setImportFile(file.name)}catch(e){setError(e instanceof Error?e.message:String(e))}}
 async function importFinance(){await run(async()=>{const rows=financePreview.map(x=>({occurred_at:String(x.Tanggal||""),account_name:String(x.Kas_Rekening||""),kind:String(x.Jenis||"").toLowerCase(),category:String(x.Kategori||""),amount:Number(x.Nominal||0),description:String(x.Uraian||"")}));await rpc("sc_import_finance_transactions",{p_school:schoolId,p_rows:rows});setFinancePreview([]);setImportFile("")})}
 const field=(text:string,value:string,set:(n:string)=>void,type="text")=><label className="field">{text}<input required value={value} type={type} onChange={e=>set(e.target.value)}/></label>;
 const chooseAccount=<label className="field">Kas / Rekening<select required value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Pilih kas</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.kind}</option>)}</select></label>;
 const bill= bills.find(b=>b.id===billId),paid=bill?payments.filter(p=>p.bill_id===bill.id).reduce((a,p)=>a+Number(p.amount),0):0;
 const studentName=(id:string)=>students.find(s=>s.id===id)?.name||"Siswa tidak aktif";
 const exportLedger=()=>saveCsv("laporan-kas-school-control.csv",csvExport(["Tanggal","Jenis","Kategori","Kas","Nominal","Keterangan"],tx.map(t=>[t.occurred_at,t.kind,t.category,accounts.find(a=>a.id===t.account_id)?.name,Number(t.amount),t.description])));
 return <><div className="grid"><div className="card"><label>Pemasukan tercatat</label><strong style={{fontSize:21}}>{money(totals?.income||0)}</strong></div><div className="card"><label>Pengeluaran</label><strong style={{fontSize:21}}>{money(totals?.expense||0)}</strong></div><div className="card"><label>Saldo kas keseluruhan</label><strong style={{fontSize:21}}>{money((totals?.opening||0)+(totals?.income||0)-(totals?.expense||0))}</strong></div><div className="card"><label>Tagihan belum dibayar</label><strong style={{fontSize:21}}>{money((totals?.billed||0)-(totals?.paid||0))}</strong></div></div>
 {tab==="overview"&&<section className="panel"><h2>Master Kas / Rekening</h2><p className="muted">Kas tunai, rekening, e-wallet dan akun khusus kegiatan; saldo setiap akun berasal dari saldo awal + pemasukan − pengeluaran.</p><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await insert("sc_finance_accounts",{name:name.trim(),kind,opening_balance:Number(opening)});setName("")})}}>{field("Nama Kas",name,setName)}<label className="field">Jenis<select value={kind} onChange={e=>setKind(e.target.value)}>{["cash","bank","ewallet","other"].map(k=><option key={k} value={k}>{k}</option>)}</select></label>{field("Saldo awal",opening,setOpening,"number")}<button className="button" disabled={busy||!name.trim()}>Tambah Kas</button></form>{accounts.map(a=>{const balance=Number(balances.find(b=>b.account_id===a.id)?.balance??a.opening_balance);return <div className="entry" key={a.id}><div><strong>{a.name}</strong><small>{a.kind} · Saldo awal {money(a.opening_balance)}</small></div><div className="flow"><span className="pill">{money(balance)}</span><button className="button secondary" onClick={()=>{const n=prompt("Nama kas/rekening",a.name);const k=prompt("Jenis: cash / bank / ewallet / other",a.kind);const o=prompt("Saldo awal",String(a.opening_balance));if(n&&k&&o!==null)void editEntity("finance_account",a.id,{name:n,kind:k,opening_balance:Number(o)})}}>Edit</button><button className="button danger" onClick={()=>void deleteEntity("finance_account",a.id)}>Hapus</button></div></div>})}</section>}
 {tab==="transaction"&&<section className="panel"><h2>Pemasukan & Pengeluaran Sekolah</h2><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await insert("sc_finance_transactions",{account_id:accountId,occurred_at:date,kind,category:category.trim(),amount:Number(amount),description:description.trim()||null,created_by:userId});setAmount("");setDescription("")})}}>{chooseAccount}<label className="field">Jenis<select value={kind} onChange={e=>setKind(e.target.value)}><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></select></label>{field("Tanggal",date,setDate,"date")}{field("Kategori",category,setCategory)}{field("Nominal",amount,setAmount,"number")}<label className="field full">Uraian<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="button" disabled={busy||!accountId||Number(amount)<=0||!category.trim()}>Simpan Transaksi</button></form>{tx.map(t=><div className="entry" key={t.id}><div><strong>{t.category}</strong><small>{t.occurred_at} · {accounts.find(a=>a.id===t.account_id)?.name||"Tanpa rekening"} · {t.description||""}</small></div><div className="flow"><b>{t.kind==="income"?"+":"−"}{money(t.amount)}</b><button className="button secondary" onClick={()=>void reverseTx(t.id)}>Koreksi</button></div></div>)}</section>}
 {tab==="budget"&&<section className="panel"><h2>Rencana Anggaran</h2><p className="muted">Pagu dicatat per tahun dan kategori. Sebelum penggunaan dana BOSP, klasifikasi belanja harus diverifikasi terhadap ketentuan resmi yang berlaku.</p><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await insert("sc_budget_lines",{fiscal_year:Number(year),category:category.trim(),amount:Number(amount),notes:description.trim()||null});setAmount("")})}}>{field("Tahun",year,setYear,"number")}{field("Kategori / Kegiatan",category,setCategory)}{field("Pagu Anggaran",amount,setAmount,"number")}<label className="field full">Catatan<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="button" disabled={busy||!category.trim()||Number(amount)<0}>Simpan Pagu</button></form>{budgets.map(b=><div className="entry" key={b.id}><div><strong>{b.category} · {b.fiscal_year}</strong><small>{b.notes||"Tanpa rincian"}</small></div><div className="flow"><b>{money(b.amount)}</b><button className="button secondary" onClick={()=>{const c=prompt("Kategori / kegiatan",b.category);const a=prompt("Nominal",String(b.amount));const n=prompt("Catatan",b.notes||"")||"";if(c&&a!==null)void editEntity("budget",b.id,{category:c,amount:Number(a),notes:n})}}>Edit</button><button className="button danger" onClick={()=>void deleteEntity("budget",b.id)}>Hapus</button></div></div>)}</section>}
 {tab==="bill"&&<section className="panel"><h2>Tagihan Siswa</h2><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await insert("sc_student_bills",{student_id:studentId,title:billTitle.trim(),due_on:date,amount_due:Number(amount),created_by:userId});setBillTitle("");setAmount("")})}}><label className="field">Siswa<select required value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Pilih siswa</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} · {s.nis||"—"}</option>)}</select></label>{field("Nama Tagihan",billTitle,setBillTitle)}{field("Jatuh Tempo",date,setDate,"date")}{field("Nominal",amount,setAmount,"number")}<button className="button" disabled={busy||!studentId||!billTitle.trim()||Number(amount)<=0}>Terbitkan Tagihan</button></form>{bills.map(b=>{const got=payments.filter(p=>p.bill_id===b.id).reduce((v,p)=>v+Number(p.amount),0);return <div className="entry" key={b.id}><div><strong>{studentName(b.student_id)} · {b.title}</strong><small>Jatuh tempo {b.due_on} · Sudah diterima {money(got)}</small></div><div className="flow"><span className="pill">Sisa {money(Number(b.amount_due)-got)}</span><button className="button secondary" onClick={()=>{const title=prompt("Nama tagihan",b.title);const amount=prompt("Nominal",String(b.amount_due));const due=prompt("Jatuh tempo YYYY-MM-DD",b.due_on);if(title&&amount&&due)void editEntity("bill",b.id,{title,amount_due:Number(amount),due_on:due})}}>Edit</button>{got===0&&<button className="button danger" onClick={()=>void deleteEntity("bill",b.id)}>Hapus</button>}</div></div>})}</section>}
 {tab==="payment"&&<section className="panel"><h2>Terima Pembayaran & Kuitansi</h2><p className="muted">Pembayaran dan pemasukan buku kas diposting dalam satu transaksi database; tidak bisa membayar lebih besar daripada sisa tagihan.</p><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc("sc_record_bill_payment",{p_school:schoolId,p_bill:billId,p_account:accountId,p_amount:Number(amount),p_receipt:receipt.trim()});setAmount("");setReceipt("")})}}><label className="field">Pilih tagihan<select required value={billId} onChange={e=>setBillId(e.target.value)}><option value="">Pilih tagihan</option>{bills.map(b=><option key={b.id} value={b.id}>{studentName(b.student_id)} · {b.title}</option>)}</select></label>{chooseAccount}{field("Nominal dibayar",amount,setAmount,"number")}{field("Nomor kuitansi unik",receipt,setReceipt)}<button className="button" disabled={busy||!billId||!accountId||Number(amount)<=0||Number(amount)>Number(bill?.amount_due||0)-paid||receipt.trim().length<4}>Catat Pembayaran</button></form>{payments.map(p=><div className="entry" key={p.id}><div><strong>{p.receipt_no}</strong><small>{p.paid_at.slice(0,10)} · {bills.find(b=>b.id===p.bill_id)?.title||"Tagihan"}</small></div><b>{money(p.amount)}</b></div>)}</section>}
 {tab==="report"&&<section className="panel"><h2>Laporan & Import Keuangan</h2><p className="muted">Rekap memakai transaksi sebenarnya. Untuk import massal, unduh template Excel agar kolom dan nama kas dapat dibaca konsisten.</p><div className="flow"><button className="button" onClick={exportLedger}>Ekspor Buku Kas CSV</button><button className="button secondary" onClick={()=>void financeTemplate()}>Template Import Excel</button><label className="button secondary">Pilih Excel<input hidden type="file" accept=".xlsx,.xls" onChange={e=>void readFinance(e.currentTarget.files?.[0])}/></label></div>{financePreview.length>0&&<div className="banner"><strong>{importFile} · {financePreview.length} baris</strong><p className="hint">Periksa nama kas/rekening dan nominal sebelum import.</p><button className="button" onClick={()=>void importFinance()} disabled={busy}>Konfirmasi Import</button></div>}<div className="grid" style={{marginTop:18}}><div className="card"><label>Anggaran tercatat</label><strong style={{fontSize:18}}>{money(totals?.budget||0)}</strong></div><div className="card"><label>Total tagihan</label><strong style={{fontSize:18}}>{money(totals?.billed||0)}</strong></div><div className="card"><label>Total pembayaran</label><strong style={{fontSize:18}}>{money(totals?.paid||0)}</strong></div><div className="card"><label>Sisa piutang</label><strong style={{fontSize:18}}>{money((totals?.billed||0)-(totals?.paid||0))}</strong></div></div></section>}
 {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
}
