"use client";
import {useEffect,useMemo,useState} from "react";
import {Download,Eye,FileSpreadsheet,MessageCircle,Plus,Upload,Users} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import {downloadExcel} from "@/lib/excel";
import type {Role} from "@/lib/modules";

type Tx={id:string;occurred_at:string;kind:string;category:string;amount:number;description:string|null;account_id:string|null;number:string|null;activity_name:string|null;proof_path:string|null;status:string;void_reason:string|null};
type Budget={id:string;fiscal_year:number;category:string;amount:number;notes:string|null;source_fund:string|null;activity_name:string|null};
type Bill={id:string;student_id:string;title:string;amount_due:number;due_on:string;period:string|null;status:string};
type Payment={id:string;bill_id:string;amount:number;receipt_no:string;paid_at:string;payment_method:string|null;proof_path:string|null};
type Student={id:string;name:string;nis:string|null};
type Contact={student_id:string;guardian_name:string|null;guardian_phone:string|null};
type Account={id:string;name:string;kind:string};
const monthNow=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"}).slice(0,7);
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
function printHtml(title:string,html:string){const w=window.open("","_blank");if(!w)return;w.document.write("<!doctype html><html><head><meta charset='utf-8'><title>"+title+"</title><style>body{font:12px Arial;margin:24mm;color:#111}h1{font-size:20px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:6px;text-align:left}th{background:#eee}.summary{display:flex;gap:25px;margin:15px 0}@media print{body{margin:12mm}}</style></head><body>"+html+"</body></html>");w.document.close();w.focus();w.print()}

export default function FinanceLegacyParity({schoolId,userId,role,focus}:{schoolId:string;userId:string;role:Role;focus:string}){
 const db=useMemo(()=>browserDb(),[]),[tx,setTx]=useState<Tx[]>([]),[budgets,setBudgets]=useState<Budget[]>([]),[bills,setBills]=useState<Bill[]>([]),[payments,setPayments]=useState<Payment[]>([]),[students,setStudents]=useState<Student[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[team,setTeam]=useState<any[]>([]);
 const [month,setMonth]=useState(monthNow()),[selected,setSelected]=useState(""),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const manager=["owner","principal","treasurer"].includes(role);
 async function load(){if(!db)return;const [t,b,bi,p,s,c,a,tm]=await Promise.all([
  db.from("sc_finance_transactions").select("id,occurred_at,kind,category,amount,description,account_id,number,activity_name,proof_path,status,void_reason").eq("school_id",schoolId).order("occurred_at",{ascending:false}).limit(1000),
  db.from("sc_budget_lines").select("id,fiscal_year,category,amount,notes,source_fund,activity_name").eq("school_id",schoolId).order("fiscal_year",{ascending:false}),
  db.from("sc_student_bills").select("id,student_id,title,amount_due,due_on,period,status").eq("school_id",schoolId).order("due_on",{ascending:false}),
  db.from("sc_bill_payments").select("id,bill_id,amount,receipt_no,paid_at,payment_method,proof_path").eq("school_id",schoolId).order("paid_at",{ascending:false}).limit(1000),
  db.from("sc_students").select("id,name,nis").eq("school_id",schoolId),
  db.from("sc_student_contacts").select("student_id,guardian_name,guardian_phone").eq("school_id",schoolId),
  db.from("sc_finance_accounts").select("id,name,kind").eq("school_id",schoolId),
  db.rpc("sc_team_directory",{p_school:schoolId})
 ]);setTx((t.data||[]) as Tx[]);setBudgets((b.data||[]) as Budget[]);setBills((bi.data||[]) as Bill[]);setPayments((p.data||[]) as Payment[]);setStudents((s.data||[]) as Student[]);setContacts((c.data||[]) as Contact[]);setAccounts((a.data||[]) as Account[]);if(!tm.error)setTeam((tm.data||[]) as any[])}
 useEffect(()=>{void load()},[db,schoolId]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const studentName=(id:string)=>students.find(s=>s.id===id)?.name||"Siswa";
 const paid=(id:string)=>payments.filter(p=>p.bill_id===id).reduce((n,p)=>n+Number(p.amount),0);
 const balance=(b:Bill)=>Math.max(0,Number(b.amount_due)-paid(b.id));
 async function uploadProof(kind:"tx"|"payment"){if(!db||!file||!selected)return;await run(async()=>{if(file.size>6*1024*1024)throw Error("File maksimal 6 MB.");const path=schoolId+"/finance/"+crypto.randomUUID()+"-"+file.name.replace(/[^\w.\-]/g,"_").slice(0,90);const {error:u}=await db.storage.from("sc-evidence").upload(path,file,{upsert:false,contentType:file.type});if(u)throw u;const table=kind==="tx"?"sc_finance_transactions":"sc_bill_payments";const {error}=await db.from(table).update({proof_path:path}).eq("id",selected);if(error)throw error;setFile(null);setOk("Bukti tersimpan secara privat.")})}
 async function openProof(path:string|null){if(!db||!path)return;const {data,error}=await db.storage.from("sc-evidence").createSignedUrl(path,180);if(error){setError(error.message);return}window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 function wa(b:Bill){const c=contacts.find(x=>x.student_id===b.student_id),phone=(c?.guardian_phone||"").replace(/^0/,"62").replace(/\D/g,"");if(!phone){setError("Nomor WhatsApp wali belum tersedia.");return}const msg=encodeURIComponent("Yth. Bapak/Ibu "+(c?.guardian_name||"Wali Siswa")+", kami informasikan tagihan "+b.title+" atas nama "+studentName(b.student_id)+" dengan sisa "+money(balance(b))+" dan jatuh tempo "+b.due_on+". Terima kasih.");window.open("https://wa.me/"+phone+"?text="+msg,"_blank","noopener,noreferrer")}
 const rows=tx.filter(x=>x.occurred_at.startsWith(month)&&x.status!=="void"),income=rows.filter(x=>x.kind==="income").reduce((n,x)=>n+Number(x.amount),0),expense=rows.filter(x=>x.kind==="expense").reduce((n,x)=>n+Number(x.amount),0);
 async function exportBku(){await downloadExcel("BKU-"+month+".xlsx",[{name:"Buku Kas Umum",rows:rows.map(x=>({Tanggal:x.occurred_at,Nomor:x.number||"",Kas:accounts.find(a=>a.id===x.account_id)?.name||"",Jenis:x.kind==="income"?"Pemasukan":"Pengeluaran",Kegiatan:x.activity_name||"",Kategori:x.category,Keterangan:x.description||"",Pemasukan:x.kind==="income"?x.amount:0,Pengeluaran:x.kind==="expense"?x.amount:0}))},{name:"Ringkasan",rows:[{Periode:month,Pemasukan:income,Pengeluaran:expense,Surplus_Defisit:income-expense,Jumlah_Transaksi:rows.length}]}])}
 function printBku(){const tr=rows.map(x=>"<tr><td>"+x.occurred_at+"</td><td>"+(x.number||"-")+"</td><td>"+x.category+"</td><td>"+(x.description||"-")+"</td><td>"+(x.kind==="income"?money(x.amount):"-")+"</td><td>"+(x.kind==="expense"?money(x.amount):"-")+"</td></tr>").join("");printHtml("Buku Kas Umum","<h1>BUKU KAS UMUM</h1><p>Periode "+month+"</p><div class='summary'><b>Pemasukan "+money(income)+"</b><b>Pengeluaran "+money(expense)+"</b><b>Surplus/Defisit "+money(income-expense)+"</b></div><table><thead><tr><th>Tanggal</th><th>Nomor</th><th>Kategori</th><th>Keterangan</th><th>Pemasukan</th><th>Pengeluaran</th></tr></thead><tbody>"+tr+"</tbody></table>")}
 const realization=budgets.map(b=>{const spent=tx.filter(x=>x.kind==="expense"&&x.status!=="void"&&(b.activity_name?x.activity_name===b.activity_name:x.category===b.category)).reduce((n,x)=>n+Number(x.amount),0);return {...b,spent,remaining:Number(b.amount)-spent,percent:Number(b.amount)>0?Math.round(spent/Number(b.amount)*1000)/10:0}});

 if(focus==="Buku Kas Umum")return <section className="panel"><div className="sectionhead"><div><h2>Buku Kas Umum</h2><p className="muted">Preview dan ekspor berdasarkan transaksi aktual per periode.</p></div><FileSpreadsheet/></div><div className="fields"><label className="field">Periode<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div className="flow"><button className="button" onClick={()=>void exportBku()}><Download size={15}/> Excel</button><button className="button secondary" onClick={printBku}>PDF / Cetak</button></div></div><div className="grid"><div className="card"><label>Pemasukan</label><strong>{money(income)}</strong></div><div className="card"><label>Pengeluaran</label><strong>{money(expense)}</strong></div><div className="card"><label>Surplus / defisit</label><strong>{money(income-expense)}</strong></div><div className="card"><label>Transaksi</label><strong>{rows.length}</strong></div></div><div className="tablewrap"><table className="data-table"><thead><tr><th>Tanggal</th><th>Nomor</th><th>Kas</th><th>Kategori</th><th>Keterangan</th><th>Nominal</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.occurred_at}</td><td>{x.number||"—"}</td><td>{accounts.find(a=>a.id===x.account_id)?.name||"—"}</td><td>{x.category}</td><td>{x.description||"—"}</td><td>{x.kind==="income"?"+":"−"} {money(x.amount)}</td></tr>)}</tbody></table></div></section>;

 if(focus==="Bukti Transaksi")return <section className="panel"><div className="sectionhead"><div><h2>Bukti Transaksi</h2><p className="muted">Lampiran transaksi disimpan privat dan dibuka dengan tautan sementara.</p></div><Upload/></div>{manager&&<div className="fields"><label className="field full">Transaksi<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Pilih transaksi</option>{tx.slice(0,200).map(x=><option key={x.id} value={x.id}>{x.occurred_at} · {x.category} · {money(x.amount)}</option>)}</select></label><label className="field">File<input type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="button" disabled={!selected||!file||busy} onClick={()=>void uploadProof("tx")}><Upload size={15}/> Simpan Bukti</button></div>}{tx.filter(x=>x.proof_path).map(x=><div className="entry" key={x.id}><div><strong>{x.occurred_at} · {x.category}</strong><small>{x.description||""} · {money(x.amount)}</small></div><button className="button secondary" onClick={()=>void openProof(x.proof_path)}><Eye size={14}/> Lihat Bukti</button></div>)}{!tx.some(x=>x.proof_path)&&<div className="empty">Belum ada bukti transaksi.</div>}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;

 if(focus==="Riwayat Pembayaran")return <section className="panel"><div className="sectionhead"><div><h2>Riwayat Pembayaran Siswa</h2><p className="muted">Nomor kuitansi, metode, nominal dan bukti pembayaran.</p></div><Eye/></div>{payments.map(p=>{const b=bills.find(x=>x.id===p.bill_id);return <div className="entry" key={p.id}><div><strong>{p.receipt_no} · {studentName(b?.student_id||"")}</strong><small>{new Date(p.paid_at).toLocaleString("id-ID")} · {p.payment_method||"Metode belum dicatat"} · {money(p.amount)}</small></div><div className="flow">{p.proof_path&&<button className="button secondary" onClick={()=>void openProof(p.proof_path)}>Bukti</button>}{manager&&!p.proof_path&&<button className="button secondary" onClick={()=>setSelected(p.id)}>Pilih Upload</button>}</div></div>})}{manager&&selected&&payments.some(p=>p.id===selected&&!p.proof_path)&&<div className="fields"><label className="field">Bukti pembayaran<input type="file" accept=".jpg,.jpeg,.png,.webp,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="button" disabled={!file} onClick={()=>void uploadProof("payment")}>Upload</button></div>}{!payments.length&&<div className="empty">Belum ada pembayaran.</div>}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;

 if(focus==="WhatsApp Tagihan")return <section className="panel"><div className="sectionhead"><div><h2>WhatsApp Tagihan</h2><p className="muted">Pesan disiapkan otomatis tetapi tetap dikirim manual dari WhatsApp pengguna.</p></div><MessageCircle/></div>{bills.filter(b=>balance(b)>0).map(b=><div className="entry" key={b.id}><div><strong>{studentName(b.student_id)} · {b.title}</strong><small>Jatuh tempo {b.due_on} · sisa {money(balance(b))}</small></div><button className="button" onClick={()=>wa(b)}><MessageCircle size={14}/> Buka WhatsApp</button></div>)}{!bills.some(b=>balance(b)>0)&&<div className="empty">Tidak ada tagihan aktif.</div>}</section>;

 if(focus==="Realisasi Anggaran")return <section className="panel"><div className="sectionhead"><div><h2>Realisasi Anggaran</h2><p className="muted">Pagu dibandingkan dengan pengeluaran aktual berdasarkan kegiatan atau kategori.</p></div><FileSpreadsheet/></div><div className="tablewrap"><table className="data-table"><thead><tr><th>Tahun</th><th>Sumber Dana</th><th>Kegiatan</th><th>Pagu</th><th>Realisasi</th><th>Sisa</th><th>%</th></tr></thead><tbody>{realization.map(r=><tr key={r.id}><td>{r.fiscal_year}</td><td>{r.source_fund||"—"}</td><td>{r.activity_name||r.category}</td><td>{money(r.amount)}</td><td>{money(r.spent)}</td><td>{money(r.remaining)}</td><td>{r.percent}%</td></tr>)}</tbody></table></div></section>;

 return <section className="panel"><div className="sectionhead"><div><h2>Tim Keuangan</h2><p className="muted">Akses bendahara/staf keuangan dapat dibuat dan dipantau tanpa membagikan akun utama.</p></div><Users/></div>{manager&&<button className="button" onClick={()=>void run(async()=>{const {data,error}=await db!.rpc("sc_create_invite",{p_school:schoolId,p_role:"treasurer"});if(error)throw error;setOk("Kode undangan bendahara: "+String(data||""))})}><Plus size={14}/> Undang Bendahara</button>}{team.filter(x=>["treasurer","staff"].includes(x.role)).map(x=><div className="entry" key={x.user_id}><div><strong>{x.staff_name||x.email||"Anggota"}</strong><small>{x.role} · {x.email||""}</small></div><span className="pill">aktif</span></div>)}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;
}
