"use client";
import {useEffect,useMemo,useState} from "react";
import {Check,Download,MapPin,Plus,Save,Trash2,Upload,Users} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import {downloadExcel} from "@/lib/excel";
import type {Role,Staff} from "@/lib/modules";

type Req={id:string;user_id:string;kind:string;from_at:string|null;to_at:string|null;amount:number;reason:string;status:string;decision_note:string|null;created_at:string};
type Schedule={id:string;name:string;weekday:number[];start_time:string;end_time:string;late_tolerance_minutes:number;active:boolean};
type Location={id:string;name:string;address:string|null;latitude:number|null;longitude:number|null;radius_meters:number;active:boolean};
type Assignment={id:string;staff_id:string;schedule_id:string|null;location_id:string|null;effective_from:string};
type Comp={id:string;name:string;kind:string;taxable:boolean;default_amount:number;active:boolean};
type StaffComp={id:string;staff_id:string;component_id:string;amount:number;active:boolean};
type Opening={id:string;title:string;department:string|null;description:string|null;status:string;created_at:string};
type Candidate={id:string;opening_id:string|null;name:string;phone:string|null;email:string|null;source:string|null;stage:string;interview_at:string|null;notes:string|null};
type Visit={id:string;user_id:string;title:string;place_name:string|null;address:string|null;scheduled_at:string;check_in_at:string|null;check_out_at:string|null;status:string;notes:string|null};
type Track={id:string;user_id:string;purpose:string;started_at:string;ended_at:string|null;status:string};
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"});
const nowLocal=()=>{const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000);return d.toISOString().slice(0,16)};
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const requestLabels:Record<string,string>={permission:"Izin",sick:"Sakit",annual_leave:"Cuti tahunan",other_leave:"Cuti lainnya",overtime:"Lembur",cash_advance:"Kasbon",reimbursement:"Reimburse"};
function position(){return new Promise<{lat:number;lng:number;accuracy:number}|null>(resolve=>{if(!navigator.geolocation)return resolve(null);navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),()=>resolve(null),{enableHighAccuracy:true,timeout:8000,maximumAge:15000})})}

export default function HRLegacyParity({schoolId,userId,role,staff,focus}:{schoolId:string;userId:string;role:Role;staff:Staff[];focus:string}){
 const db=useMemo(()=>browserDb(),[]),manager=["owner","principal","vice_principal","hr"].includes(role);
 const [requests,setRequests]=useState<Req[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]),[locations,setLocations]=useState<Location[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[components,setComponents]=useState<Comp[]>([]),[staffComponents,setStaffComponents]=useState<StaffComp[]>([]),[openings,setOpenings]=useState<Opening[]>([]),[candidates,setCandidates]=useState<Candidate[]>([]),[visits,setVisits]=useState<Visit[]>([]),[tracks,setTracks]=useState<Track[]>([]);
 const [kind,setKind]=useState("overtime"),[from,setFrom]=useState(nowLocal()),[to,setTo]=useState(nowLocal()),[amount,setAmount]=useState("0"),[reason,setReason]=useState(""),[name,setName]=useState(""),[start,setStart]=useState("07:00"),[end,setEnd]=useState("16:00"),[tolerance,setTolerance]=useState("15"),[address,setAddress]=useState(""),[lat,setLat]=useState(""),[lng,setLng]=useState(""),[radius,setRadius]=useState("150"),[staffId,setStaffId]=useState(""),[scheduleId,setScheduleId]=useState(""),[locationId,setLocationId]=useState(""),[compKind,setCompKind]=useState("earning"),[taxable,setTaxable]=useState(false),[openingId,setOpeningId]=useState(""),[stage,setStage]=useState("new"),[contact,setContact]=useState(""),[notes,setNotes]=useState(""),[scheduledAt,setScheduledAt]=useState(nowLocal()),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 async function load(){if(!db)return;const reads=await Promise.all([
  db.from("sc_hr_requests").select("id,user_id,kind,from_at,to_at,amount,reason,status,decision_note,created_at").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(300),
  db.from("sc_hr_work_schedules").select("id,name,weekday,start_time,end_time,late_tolerance_minutes,active").eq("school_id",schoolId).order("name"),
  db.from("sc_hr_locations").select("id,name,address,latitude,longitude,radius_meters,active").eq("school_id",schoolId).order("name"),
  db.from("sc_hr_assignments").select("id,staff_id,schedule_id,location_id,effective_from").eq("school_id",schoolId).order("effective_from",{ascending:false}),
  db.from("sc_payroll_component_catalog").select("id,name,kind,taxable,default_amount,active").eq("school_id",schoolId).order("name"),
  db.from("sc_payroll_staff_components").select("id,staff_id,component_id,amount,active").eq("school_id",schoolId),
  db.from("sc_recruitment_openings").select("id,title,department,description,status,created_at").eq("school_id",schoolId).order("created_at",{ascending:false}),
  db.from("sc_recruitment_candidates").select("id,opening_id,name,phone,email,source,stage,interview_at,notes").eq("school_id",schoolId).order("created_at",{ascending:false}),
  db.from("sc_field_visits").select("id,user_id,title,place_name,address,scheduled_at,check_in_at,check_out_at,status,notes").eq("school_id",schoolId).order("scheduled_at",{ascending:false}).limit(200),
  db.from("sc_tracking_sessions").select("id,user_id,purpose,started_at,ended_at,status").eq("school_id",schoolId).order("started_at",{ascending:false}).limit(100)
 ]);setRequests((reads[0].data||[]) as Req[]);setSchedules((reads[1].data||[]) as Schedule[]);setLocations((reads[2].data||[]) as Location[]);setAssignments((reads[3].data||[]) as Assignment[]);setComponents((reads[4].data||[]) as Comp[]);setStaffComponents((reads[5].data||[]) as StaffComp[]);setOpenings((reads[6].data||[]) as Opening[]);setCandidates((reads[7].data||[]) as Candidate[]);setVisits((reads[8].data||[]) as Visit[]);setTracks((reads[9].data||[]) as Track[])}
 useEffect(()=>{void load()},[db,schoolId]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 const staffName=(uid:string)=>staff.find(s=>s.user_id===uid)?.name||"Pengguna";
 async function request(){if(!db||!reason.trim())return;await run(async()=>{const {error}=await db.from("sc_hr_requests").insert({school_id:schoolId,user_id:userId,kind,from_at:from||null,to_at:to||null,amount:Number(amount||0),reason:reason.trim()});if(error)throw error;setReason("");setAmount("0");setOk("Pengajuan dikirim.")})}
 async function decide(id:string,status:string){if(!db)return;await run(async()=>{const note=prompt("Catatan keputusan (opsional)")||null;const {error}=await db.rpc("sc_decide_hr_request",{p_school:schoolId,p_request:id,p_status:status,p_note:note});if(error)throw error;setOk("Status pengajuan diperbarui.")})}
 async function addSchedule(){if(!db||name.trim().length<2||start>=end)return;await run(async()=>{const {error}=await db.from("sc_hr_work_schedules").insert({school_id:schoolId,name:name.trim(),start_time:start,end_time:end,late_tolerance_minutes:Number(tolerance),weekday:[1,2,3,4,5]});if(error)throw error;setName("");setOk("Jadwal kerja dibuat.")})}
 async function capture(){const p=await position();if(!p){setError("GPS belum tersedia atau izin lokasi ditolak.");return}setLat(String(p.lat));setLng(String(p.lng));setOk("Titik GPS diambil.") }
 async function addLocation(){if(!db||name.trim().length<2)return;await run(async()=>{const {error}=await db.from("sc_hr_locations").insert({school_id:schoolId,name:name.trim(),address:address.trim()||null,latitude:lat?Number(lat):null,longitude:lng?Number(lng):null,radius_meters:Number(radius)});if(error)throw error;setName("");setAddress("");setOk("Lokasi presensi dibuat.")})}
 async function assign(){if(!db||!staffId)return;await run(async()=>{const {error}=await db.from("sc_hr_assignments").insert({school_id:schoolId,staff_id:staffId,schedule_id:scheduleId||null,location_id:locationId||null,effective_from:today()});if(error)throw error;setOk("Jadwal/lokasi dipasang ke pegawai.")})}
 async function addComponent(){if(!db||name.trim().length<2)return;await run(async()=>{const {error}=await db.from("sc_payroll_component_catalog").insert({school_id:schoolId,name:name.trim(),kind:compKind,taxable,default_amount:Number(amount||0)});if(error)throw error;setName("");setAmount("0");setOk("Komponen payroll dibuat.")})}
 async function assignComponent(){if(!db||!staffId||!scheduleId)return;await run(async()=>{const c=components.find(x=>x.id===scheduleId);const {error}=await db.from("sc_payroll_staff_components").upsert({school_id:schoolId,staff_id:staffId,component_id:scheduleId,amount:Number(amount||c?.default_amount||0),active:true},{onConflict:"staff_id,component_id"});if(error)throw error;setOk("Komponen dipasang ke pegawai.")})}
 async function addOpening(){if(!db||name.trim().length<3)return;await run(async()=>{const {error}=await db.from("sc_recruitment_openings").insert({school_id:schoolId,title:name.trim(),department:address.trim()||null,description:notes.trim()||null,created_by:userId});if(error)throw error;setName("");setNotes("");setOk("Lowongan dibuat.")})}
 async function addCandidate(){if(!db||name.trim().length<2)return;await run(async()=>{const [email,phone]=contact.split("|").map(x=>x.trim());const {error}=await db.from("sc_recruitment_candidates").insert({school_id:schoolId,opening_id:openingId||null,name:name.trim(),email:email||null,phone:phone||null,source:address.trim()||null,stage,interview_at:scheduledAt||null,notes:notes.trim()||null});if(error)throw error;setName("");setContact("");setNotes("");setOk("Kandidat disimpan.")})}
 async function addVisit(){if(!db||name.trim().length<3)return;await run(async()=>{const {error}=await db.from("sc_field_visits").insert({school_id:schoolId,user_id:userId,title:name.trim(),place_name:address.trim()||null,address:notes.trim()||null,scheduled_at:new Date(scheduledAt).toISOString()});if(error)throw error;setName("");setNotes("");setOk("Kunjungan dijadwalkan.")})}
 async function visitAction(v:Visit,action:"in"|"out"){if(!db)return;await run(async()=>{const p=await position();if(!p)throw Error("GPS tidak tersedia.");const patch=action==="in"?{check_in_at:new Date().toISOString(),check_in_lat:p.lat,check_in_lng:p.lng,status:"in_progress"}:{check_out_at:new Date().toISOString(),check_out_lat:p.lat,check_out_lng:p.lng,status:"done"};const {error}=await db.from("sc_field_visits").update(patch).eq("id",v.id);if(error)throw error;setOk(action==="in"?"Check-in kunjungan tercatat.":"Kunjungan selesai.")})}
 async function startTrack(){if(!db||name.trim().length<3)return;await run(async()=>{const {error}=await db.from("sc_tracking_sessions").insert({school_id:schoolId,user_id:userId,purpose:name.trim()});if(error)throw error;setName("");setOk("Tracking dimulai.")})}
 async function sendPoint(t:Track){if(!db)return;await run(async()=>{const p=await position();if(!p)throw Error("GPS tidak tersedia.");const {error}=await db.from("sc_tracking_points").insert({school_id:schoolId,session_id:t.id,user_id:userId,latitude:p.lat,longitude:p.lng,accuracy:p.accuracy});if(error)throw error;setOk("Titik lokasi tersimpan.")})}
 async function stopTrack(t:Track){if(!db)return;await run(async()=>{const {error}=await db.from("sc_tracking_sessions").update({status:"completed",ended_at:new Date().toISOString()}).eq("id",t.id);if(error)throw error;setOk("Tracking selesai.")})}
 async function report(){await downloadExcel("laporan-hr-school-control.xlsx",[{name:"Pengajuan",rows:requests.map(r=>({Nama:staffName(r.user_id),Jenis:requestLabels[r.kind]||r.kind,Mulai:r.from_at,Selesai:r.to_at,Nominal:r.amount,Alasan:r.reason,Status:r.status}))},{name:"Jadwal",rows:schedules.map(s=>({Nama:s.name,Mulai:s.start_time,Selesai:s.end_time,Toleransi:s.late_tolerance_minutes}))},{name:"Lokasi",rows:locations.map(l=>({Nama:l.name,Alamat:l.address,Latitude:l.latitude,Longitude:l.longitude,Radius:l.radius_meters}))},{name:"Rekrutmen",rows:candidates.map(c=>({Nama:c.name,Lowongan:openings.find(o=>o.id===c.opening_id)?.title||"",Tahap:c.stage,Email:c.email,Telepon:c.phone,Sumber:c.source}))},{name:"Kunjungan",rows:visits.map(v=>({Judul:v.title,Tempat:v.place_name,Jadwal:v.scheduled_at,Status:v.status}))}])}
 const feedback=<>{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</>;
 const visibleReq=manager?requests:requests.filter(r=>r.user_id===userId);

 if(["Pengajuan SDM","Lembur","Kasbon","Reimburse"].includes(focus))return <section className="panel"><div className="sectionhead"><div><h2>Pengajuan SDM</h2><p className="muted">Izin, cuti, lembur, kasbon dan reimburse dalam satu alur approval.</p></div><Save/></div><div className="fields"><label className="field">Jenis<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(requestLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field">Mulai<input type="datetime-local" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="field">Selesai<input type="datetime-local" value={to} onChange={e=>setTo(e.target.value)}/></label>{["cash_advance","reimbursement"].includes(kind)&&<label className="field">Nominal<input type="number" min={0} value={amount} onChange={e=>setAmount(e.target.value)}/></label>}<label className="field full">Alasan / keterangan<textarea rows={4} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button" disabled={busy||!reason.trim()} onClick={()=>void request()}><Plus size={15}/> Kirim Pengajuan</button></div>{visibleReq.map(r=><div className="entry" key={r.id}><div><strong>{staffName(r.user_id)} · {requestLabels[r.kind]||r.kind}</strong><small>{r.from_at?new Date(r.from_at).toLocaleString("id-ID"):"—"} · {r.status}{r.amount? " · "+money(r.amount):""}</small><p>{r.reason}</p></div><div className="flow"><span className="pill">{r.status}</span>{manager&&r.status==="pending"&&<><button className="button" onClick={()=>void decide(r.id,"approved")}><Check size={14}/> Setujui</button><button className="button danger" onClick={()=>void decide(r.id,"rejected")}>Tolak</button></>}</div></div>)}{feedback}</section>;

 if(focus==="Jadwal Kerja")return <section className="panel"><div className="sectionhead"><div><h2>Jadwal Kerja & Penempatan</h2><p className="muted">Buat master jadwal lalu pasang ke pegawai; tidak lagi hanya satu jam masuk global.</p></div><Users/></div>{manager&&<><div className="fields"><label className="field">Nama jadwal<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Mulai<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field">Selesai<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label className="field">Toleransi menit<input type="number" value={tolerance} onChange={e=>setTolerance(e.target.value)}/></label><button className="button" onClick={()=>void addSchedule()}><Plus size={15}/> Tambah Jadwal</button></div><div className="fields" style={{marginTop:18}}><label className="field">Pegawai<select value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Pilih pegawai</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field">Jadwal<select value={scheduleId} onChange={e=>setScheduleId(e.target.value)}><option value="">Tanpa jadwal</option>{schedules.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field">Lokasi<select value={locationId} onChange={e=>setLocationId(e.target.value)}><option value="">Tanpa lokasi</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><button className="button secondary" onClick={()=>void assign()}>Pasang ke Pegawai</button></div></>}{schedules.map(s=><div className="entry" key={s.id}><div><strong>{s.name}</strong><small>{s.start_time.slice(0,5)}–{s.end_time.slice(0,5)} · toleransi {s.late_tolerance_minutes} menit</small></div></div>)}{feedback}</section>;

 if(focus==="Lokasi Presensi")return <section className="panel"><div className="sectionhead"><div><h2>Lokasi Presensi</h2><p className="muted">Master lokasi dan radius dapat dipakai sebagai basis validasi presensi GPS.</p></div><MapPin/></div>{manager&&<div className="fields"><label className="field">Nama lokasi<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field full">Alamat<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="field">Latitude<input value={lat} onChange={e=>setLat(e.target.value)}/></label><label className="field">Longitude<input value={lng} onChange={e=>setLng(e.target.value)}/></label><label className="field">Radius meter<input type="number" value={radius} onChange={e=>setRadius(e.target.value)}/></label><div className="flow"><button className="button secondary" onClick={()=>void capture()}><MapPin size={14}/> Ambil GPS Saya</button><button className="button" onClick={()=>void addLocation()}><Plus size={14}/> Tambah Lokasi</button></div></div>}{locations.map(l=><div className="entry" key={l.id}><div><strong>{l.name}</strong><small>{l.address||"Tanpa alamat"} · radius {l.radius_meters}m · {l.latitude??"—"}, {l.longitude??"—"}</small></div></div>)}{feedback}</section>;

 if(focus==="Komponen Dinamis")return <section className="panel"><div className="sectionhead"><div><h2>Master Komponen Payroll</h2><p className="muted">Tunjangan/penghasilan dan potongan dapat dibuat sendiri, ditandai kena pajak, lalu dipasang ke pegawai.</p></div><Save/></div>{manager&&<><div className="fields"><label className="field">Nama komponen<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Jenis<select value={compKind} onChange={e=>setCompKind(e.target.value)}><option value="earning">Pendapatan / Tunjangan</option><option value="deduction">Potongan</option></select></label><label className="field">Nominal default<input type="number" min={0} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label className="field">Kena pajak<input type="checkbox" checked={taxable} onChange={e=>setTaxable(e.target.checked)}/></label><button className="button" onClick={()=>void addComponent()}><Plus size={15}/> Tambah Komponen</button></div><div className="fields" style={{marginTop:18}}><label className="field">Pegawai<select value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Pilih</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field">Komponen<select value={scheduleId} onChange={e=>{setScheduleId(e.target.value);const c=components.find(x=>x.id===e.target.value);if(c)setAmount(String(c.default_amount))}}><option value="">Pilih</option>{components.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field">Nominal<input type="number" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="button secondary" onClick={()=>void assignComponent()}>Pasang</button></div></>}{components.map(c=><div className="entry" key={c.id}><div><strong>{c.name}</strong><small>{c.kind==="earning"?"Pendapatan":"Potongan"} · {money(c.default_amount)} · {c.taxable?"kena pajak":"non pajak"}</small></div><span className="pill">{staffComponents.filter(x=>x.component_id===c.id&&x.active).length} pegawai</span></div>)}{feedback}</section>;

 if(focus==="Rekrutmen")return <section className="panel"><div className="sectionhead"><div><h2>Rekrutmen</h2><p className="muted">Lowongan, kandidat, sumber kandidat, interview dan tahap seleksi.</p></div><Users/></div>{manager&&<><h3>Tambah lowongan</h3><div className="fields"><label className="field">Nama lowongan<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Departemen<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="field full">Deskripsi<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="button" onClick={()=>void addOpening()}>Simpan Lowongan</button></div><h3 style={{marginTop:20}}>Tambah kandidat</h3><div className="fields"><label className="field">Lowongan<select value={openingId} onChange={e=>setOpeningId(e.target.value)}><option value="">Umum</option>{openings.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select></label><label className="field">Nama kandidat<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Email | Telepon<input value={contact} onChange={e=>setContact(e.target.value)} placeholder="email | 08xxxx"/></label><label className="field">Sumber kandidat<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="field">Tahap<select value={stage} onChange={e=>setStage(e.target.value)}>{["new","screening","interview","offer","hired","rejected"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Interview<input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/></label><label className="field full">Catatan<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="button" onClick={()=>void addCandidate()}>Simpan Kandidat</button></div></>}{candidates.map(c=><div className="entry" key={c.id}><div><strong>{c.name}</strong><small>{openings.find(o=>o.id===c.opening_id)?.title||"Kandidat umum"} · {c.stage} · {c.source||"Sumber belum diisi"}</small></div><span className="pill">{c.interview_at?new Date(c.interview_at).toLocaleString("id-ID"):"Belum interview"}</span></div>)}{feedback}</section>;

 if(focus==="Kunjungan Lapangan")return <section className="panel"><div className="sectionhead"><div><h2>Kunjungan Lapangan</h2><p className="muted">Jadwalkan tugas luar dan catat check-in/check-out berbasis GPS.</p></div><MapPin/></div><div className="fields"><label className="field full">Nama kegiatan / tujuan<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="field">Tempat<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label className="field">Jadwal<input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/></label><label className="field full">Alamat / catatan<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="button" onClick={()=>void addVisit()}><Plus size={14}/> Jadwalkan</button></div>{visits.filter(v=>manager||v.user_id===userId).map(v=><div className="entry" key={v.id}><div><strong>{v.title}</strong><small>{v.place_name||"—"} · {new Date(v.scheduled_at).toLocaleString("id-ID")} · {v.status}</small></div><div className="flow">{v.status==="scheduled"&&v.user_id===userId&&<button className="button" onClick={()=>void visitAction(v,"in")}>Check-in</button>}{v.status==="in_progress"&&v.user_id===userId&&<button className="button" onClick={()=>void visitAction(v,"out")}>Selesai</button>}</div></div>)}{feedback}</section>;

 if(focus==="Pelacakan Lokasi")return <section className="panel"><div className="sectionhead"><div><h2>Pelacakan Lokasi Tugas</h2><p className="muted">Tracking hanya dimulai secara eksplisit oleh pengguna dan dihentikan saat tugas selesai.</p></div><MapPin/></div><div className="fields"><label className="field full">Tujuan tracking<input value={name} onChange={e=>setName(e.target.value)} placeholder="Contoh: Kunjungan dinas luar"/></label><button className="button" onClick={()=>void startTrack()}>Mulai Tracking</button></div>{tracks.filter(t=>manager||t.user_id===userId).map(t=><div className="entry" key={t.id}><div><strong>{t.purpose}</strong><small>{new Date(t.started_at).toLocaleString("id-ID")} · {t.status}</small></div>{t.user_id===userId&&t.status==="active"&&<div className="flow"><button className="button secondary" onClick={()=>void sendPoint(t)}>Kirim Titik</button><button className="button" onClick={()=>void stopTrack(t)}>Selesaikan</button></div>}</div>)}{feedback}</section>;

 return <section className="panel"><div className="sectionhead"><div><h2>Laporan HR & Payroll</h2><p className="muted">Gabungkan pengajuan, jadwal, lokasi, rekrutmen dan kunjungan dalam satu workbook.</p></div><Download/></div><button className="button" onClick={()=>void report()}><Download size={15}/> Export Excel Lengkap</button><div className="grid" style={{marginTop:18}}><div className="card"><label>Pengajuan</label><strong>{requests.length}</strong></div><div className="card"><label>Jadwal</label><strong>{schedules.length}</strong></div><div className="card"><label>Lokasi</label><strong>{locations.length}</strong></div><div className="card"><label>Kandidat</label><strong>{candidates.length}</strong></div></div>{feedback}</section>;
}
