"use client";
import {useEffect,useMemo,useState} from "react";
import {BookOpen,Download,FileText,Plus,Save,Trash2,Upload} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import type {Role,Staff} from "@/lib/modules";

type Template={id:string;scope:string;category:string;title:string;description:string|null;storage_path:string|null;url:string|null};
type Doc={id:string;kind:string;title:string;status:string;revision:number;source_notes:string|null;review_notes:string|null;readiness:string;assumptions:string|null};
type Source={id:string;document_id:string|null;title:string;source_type:string;storage_path:string|null;url:string|null;note:string|null;created_at:string};
type Perf={id:string;staff_user_id:string;event_type:string;title:string;occurred_at:string;verified_at:string|null;evidence_path?:string|null};
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"});

export default function ManagementLegacyParity({schoolId,userId,role,staff,focus}:{schoolId:string;userId:string;role:Role;staff:Staff[];focus:string}){
 const db=useMemo(()=>browserDb(),[]),manager=["owner","principal","vice_principal"].includes(role);
 const [templates,setTemplates]=useState<Template[]>([]),[docs,setDocs]=useState<Doc[]>([]),[sources,setSources]=useState<Source[]>([]),[perf,setPerf]=useState<Perf[]>([]);
 const [category,setCategory]=useState("Perencanaan & Laporan"),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[url,setUrl]=useState(""),[file,setFile]=useState<File|null>(null),[docId,setDocId]=useState(""),[sourceType,setSourceType]=useState("note"),[day,setDay]=useState(today()),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 async function load(){if(!db)return;const [t,d,s,p]=await Promise.all([
  db.from("sc_template_library").select("id,scope,category,title,description,storage_path,url").or("scope.eq.platform,school_id.eq."+schoolId).order("created_at",{ascending:false}),
  db.from("sc_documents").select("id,kind,title,status,revision,source_notes,review_notes,readiness,assumptions").eq("school_id",schoolId).order("updated_at",{ascending:false}).limit(100),
  db.from("sc_document_sources").select("id,document_id,title,source_type,storage_path,url,note,created_at").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(150),
  db.from("sc_staff_events").select("id,staff_user_id,event_type,title,occurred_at,verified_at,evidence_path").eq("school_id",schoolId).eq("event_type","head_performance").order("occurred_at",{ascending:false}).limit(100)
 ]);setTemplates((t.data||[]) as Template[]);setDocs((d.data||[]) as Doc[]);setSources((s.data||[]) as Source[]);setPerf((p.data||[]) as Perf[])}
 useEffect(()=>{void load()},[db,schoolId]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function upload(prefix:string){if(!db||!file)return null;if(file.size>15*1024*1024)throw Error("File maksimal 15 MB.");const path=schoolId+"/"+prefix+"/"+crypto.randomUUID()+"-"+file.name.replace(/[^\w.\-]/g,"_").slice(0,100);const {error}=await db.storage.from("sc-evidence").upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return path}
 async function addTemplate(){if(!db||title.trim().length<3)return;await run(async()=>{const path=await upload("templates");const {error}=await db.from("sc_template_library").insert({school_id:schoolId,scope:"school",category,title:title.trim(),description:description.trim()||null,storage_path:path,url:url.trim()||null,created_by:userId});if(error)throw error;setTitle("");setDescription("");setUrl("");setFile(null);setOk("Template masuk pustaka sekolah.")})}
 async function addSource(){if(!db||title.trim().length<3)return;await run(async()=>{const path=sourceType==="file"?await upload("document-sources"):null;const {error}=await db.from("sc_document_sources").insert({school_id:schoolId,document_id:docId||null,title:title.trim(),source_type:sourceType,storage_path:path,url:url.trim()||null,note:description.trim()||null,created_by:userId});if(error)throw error;setTitle("");setDescription("");setUrl("");setFile(null);setOk("Sumber dokumen tersimpan.")})}
 async function addPerformance(){if(!db||title.trim().length<3)return;await run(async()=>{const path=await upload("head-performance");const {error}=await db.from("sc_staff_events").insert({school_id:schoolId,staff_user_id:userId,event_type:"head_performance",title:title.trim(),occurred_at:day,evidence_path:path,created_by:userId});if(error)throw error;setTitle("");setFile(null);setOk("Bukti kinerja kepala sekolah tersimpan.")})}
 async function deleteTemplate(id:string){if(!db||!confirm("Hapus template sekolah ini?"))return;await run(async()=>{const {error}=await db.from("sc_template_library").delete().eq("id",id).eq("scope","school");if(error)throw error})}
 async function deleteSource(id:string){if(!db||!confirm("Hapus sumber ini?"))return;await run(async()=>{const {error}=await db.from("sc_document_sources").delete().eq("id",id);if(error)throw error})}
 async function openPath(path:string|null,urlValue:string|null){if(urlValue){window.open(urlValue,"_blank","noopener,noreferrer");return}if(!db||!path)return;const {data,error}=await db.storage.from("sc-evidence").createSignedUrl(path,120);if(error){setError(error.message);return}window.open(data.signedUrl,"_blank","noopener,noreferrer")}
 async function saveWorkflow(d:Doc,patch:Record<string,unknown>){if(!db)return;await run(async()=>{const {error}=await db.from("sc_documents").update({...patch,updated_at:new Date().toISOString()}).eq("id",d.id).eq("school_id",schoolId);if(error)throw error;setOk("Workflow dokumen diperbarui.")})}

 if(focus==="Pustaka Format")return <section className="panel"><div className="sectionhead"><div><h2>Pustaka Format</h2><p className="muted">Format SOP, supervisi, RKJM/RKT, PKKS, bukti dukung dan laporan dapat disimpan untuk seluruh tim sekolah.</p></div><BookOpen/></div>{manager&&<div className="fields"><label className="field">Kategori<select value={category} onChange={e=>setCategory(e.target.value)}>{["SOP Sekolah","Instrumen Supervisi","Perencanaan & Laporan","PKKS & Kinerja","Bonus Bukti Dukung","Buku Panduan"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field full">Nama format<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field full">Deskripsi<textarea rows={3} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="field">URL opsional<input value={url} onChange={e=>setUrl(e.target.value)}/></label><label className="field">File opsional<input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="button" disabled={busy||title.trim().length<3} onClick={()=>void addTemplate()}><Plus size={15}/> Tambah Format</button></div>}<div style={{marginTop:18}}>{templates.map(t=><div className="entry" key={t.id}><div><strong>{t.title}</strong><small>{t.category} · {t.scope==="platform"?"Pustaka Bantu Beres":"Sekolah"}</small><p>{t.description||""}</p></div><div className="flow">{(t.storage_path||t.url)&&<button className="button secondary" onClick={()=>void openPath(t.storage_path,t.url)}><Download size={14}/> Buka</button>}{manager&&t.scope==="school"&&<button className="button danger" onClick={()=>void deleteTemplate(t.id)}><Trash2 size={14}/></button>}</div></div>)}</div>{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;

 if(focus==="Sumber Dokumen")return <section className="panel"><div className="sectionhead"><div><h2>Dokumen Sumber</h2><p className="muted">Lampirkan file, catatan, tautan atau acuan resmi ke dokumen sekolah. Sumber tetap terpisah dari hasil AI.</p></div><FileText/></div>{manager&&<div className="fields"><label className="field">Dokumen terkait<select value={docId} onChange={e=>setDocId(e.target.value)}><option value="">Sumber umum sekolah</option>{docs.map(d=><option key={d.id} value={d.id}>{d.kind} · {d.title}</option>)}</select></label><label className="field">Jenis sumber<select value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="file">File</option><option value="url">URL</option><option value="note">Catatan</option><option value="official_reference">Acuan resmi</option></select></label><label className="field full">Judul sumber<input value={title} onChange={e=>setTitle(e.target.value)}/></label>{sourceType==="file"&&<label className="field">File<input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}{["url","official_reference"].includes(sourceType)&&<label className="field full">URL<input value={url} onChange={e=>setUrl(e.target.value)}/></label>}<label className="field full">Catatan<textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="button" disabled={busy||title.trim().length<3||(sourceType==="file"&&!file)} onClick={()=>void addSource()}><Upload size={15}/> Simpan Sumber</button></div>}<div style={{marginTop:18}}>{sources.map(s=><div className="entry" key={s.id}><div><strong>{s.title}</strong><small>{s.source_type} · {docs.find(d=>d.id===s.document_id)?.title||"Sumber umum"}</small><p>{s.note||""}</p></div><div className="flow">{(s.storage_path||s.url)&&<button className="button secondary" onClick={()=>void openPath(s.storage_path,s.url)}>Buka</button>}{manager&&<button className="button danger" onClick={()=>void deleteSource(s.id)}><Trash2 size={14}/></button>}</div></div>)}</div></section>;

 if(focus==="Kinerja Kepala Sekolah")return <section className="panel"><div className="sectionhead"><div><h2>Kinerja Kepala Sekolah</h2><p className="muted">Bukti, capaian dan refleksi kepala sekolah dipisahkan dari evaluasi guru.</p></div><FileText/></div>{manager&&<div className="fields"><label className="field">Tanggal<input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><label className="field full">Bukti / capaian / refleksi<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Contoh: Tindak lanjut hasil PBD semester ganjil"/></label><label className="field">Lampiran bukti<input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="button" disabled={busy||title.trim().length<3} onClick={()=>void addPerformance()}><Plus size={15}/> Simpan Bukti</button></div>}{perf.map(p=><div className="entry" key={p.id}><div><strong>{p.title}</strong><small>{p.occurred_at} · {p.verified_at?"Terverifikasi":"Tercatat"}</small></div></div>)}{!perf.length&&<div className="empty">Belum ada bukti kinerja kepala sekolah.</div>}</section>;

 return <section className="panel"><div className="sectionhead"><div><h2>Workflow & Kesiapan Dokumen</h2><p className="muted">Dokumen dapat diberi catatan sumber, asumsi kerja, catatan review dan status kesiapan sebelum disetujui.</p></div><Save/></div>{docs.map(d=><article className="panel" key={d.id} style={{marginTop:12}}><div className="sectionhead"><div><strong>{d.kind} · {d.title}</strong><small>Revisi {d.revision} · status {d.status}</small></div><span className="pill">{d.readiness}</span></div><div className="fields"><label className="field">Kesiapan<select defaultValue={d.readiness} onChange={e=>void saveWorkflow(d,{readiness:e.target.value})}><option value="draft">Draft</option><option value="needs_data">Perlu data</option><option value="review">Siap review</option><option value="ready">Siap disahkan</option></select></label><label className="field full">Catatan sumber<textarea defaultValue={d.source_notes||""} onBlur={e=>void saveWorkflow(d,{source_notes:e.target.value})}/></label><label className="field full">Asumsi kerja<textarea defaultValue={d.assumptions||""} onBlur={e=>void saveWorkflow(d,{assumptions:e.target.value})}/></label><label className="field full">Catatan peninjauan<textarea defaultValue={d.review_notes||""} onBlur={e=>void saveWorkflow(d,{review_notes:e.target.value})}/></label></div></article>)}{!docs.length&&<div className="empty">Belum ada dokumen.</div>}{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</section>;
}
