"use client";
import {useEffect,useMemo,useState} from "react";
import {Download,FileSpreadsheet,Plus,Upload} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import {downloadExcel,readExcel,readWorkbook,type SheetRows} from "@/lib/excel";
import {isAdmin,type Role} from "@/lib/modules";

type C={id:string;name:string;grade:string|null;academic_year:string};
type S={id:string;name:string;nis:string|null;nisn:string|null;gender:string|null;class_id:string|null;status:string};
type Staff={id:string;user_id:string|null;name:string;position:string|null;shift_start:string;late_tolerance_minutes:number;staff_type:string};
type Subject={id:string;name:string;code:string|null};
type Member={user_id:string;role:string;email?:string|null;staff_name?:string|null};
type A={id:string;teacher_id:string;class_id:string;subject_id:string|null;mode:string};
type View="students"|"classes"|"teachers"|"staff"|"subjects"|"assignments"|"all";
const clean=(v:unknown)=>String(v??"").trim();

export default function MasterHubV2({schoolId,role,focus}:{schoolId:string;role:Role;focus?:string}){
 const db=useMemo(()=>browserDb(),[]),admin=isAdmin(role);
 const [classes,setClasses]=useState<C[]>([]),[students,setStudents]=useState<S[]>([]),[staff,setStaff]=useState<Staff[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[members,setMembers]=useState<Member[]>([]),[assignments,setAssignments]=useState<A[]>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const [sid,setSid]=useState<string|null>(null),[sName,setSName]=useState(""),[nis,setNis]=useState(""),[nisn,setNisn]=useState(""),[gender,setGender]=useState(""),[sClass,setSClass]=useState(""),[sStatus,setSStatus]=useState("active");
 const [cid,setCid]=useState<string|null>(null),[cName,setCName]=useState(""),[grade,setGrade]=useState(""),[year,setYear]=useState("2026/2027");
 const [staffId,setStaffId]=useState<string|null>(null),[staffName,setStaffName]=useState(""),[position,setPosition]=useState(""),[shift,setShift]=useState("07:00"),[tolerance,setTolerance]=useState("15");
 const [subId,setSubId]=useState<string|null>(null),[subName,setSubName]=useState(""),[subCode,setSubCode]=useState("");
 const [assignId,setAssignId]=useState<string|null>(null),[teacher,setTeacher]=useState(""),[classId,setClassId]=useState(""),[subjectId,setSubjectId]=useState(""),[mode,setMode]=useState("subject");
 const [importRows,setImportRows]=useState<SheetRows>([]),[importFile,setImportFile]=useState(""),[workbook,setWorkbook]=useState<Record<string,SheetRows>>({});
 const f=(focus||"Siswa").toLowerCase();
 const view:View=f.includes("import excel keseluruhan")?"all":f.includes("penugasan")?"assignments":f.includes("mata")?"subjects":f.includes("tenaga")?"staff":f==="guru"||f.includes("guru")?"teachers":f.includes("kelas")?"classes":"students";
 async function load(){if(!db)return;const r=await Promise.all([
  db.from("sc_classes").select("id,name,grade,academic_year").eq("school_id",schoolId).order("name"),
  db.from("sc_students").select("id,name,nis,nisn,gender,class_id,status").eq("school_id",schoolId).order("name"),
  db.from("sc_staff").select("id,user_id,name,position,shift_start,late_tolerance_minutes,staff_type").eq("school_id",schoolId).order("name"),
  db.from("sc_subjects").select("id,name,code").eq("school_id",schoolId).order("name"),
  db.from("sc_members").select("user_id,role").eq("school_id",schoolId),
  db.from("sc_teacher_assignments").select("id,teacher_id,class_id,subject_id,mode").eq("school_id",schoolId)
 ]);setClasses((r[0].data||[]) as C[]);setStudents((r[1].data||[]) as S[]);setStaff((r[2].data||[]) as Staff[]);setSubjects((r[3].data||[]) as Subject[]);setMembers((r[4].data||[]) as Member[]);setAssignments((r[5].data||[]) as A[]);
 if(admin){const d=await db.rpc("sc_team_directory",{p_school:schoolId});if(!d.error&&d.data)setMembers(d.data as Member[])}
 const first=r.find(x=>x.error);if(first?.error)setError(first.error.message)}
 useEffect(()=>{void load();setImportRows([]);setWorkbook({});setImportFile("")},[db,schoolId,focus]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Perubahan tersimpan dan langsung dipakai modul lain.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function rpc(name:string,args:Record<string,unknown>){if(!db)throw Error("Database belum terhubung");const {data,error}=await db.rpc(name,args);if(error)throw error;return data}
 async function remove(entity:string,id:string){if(!confirm("Hapus data ini? Data yang sudah dipakai pada riwayat lain dapat ditolak sistem."))return;await run(async()=>{await rpc("sc_master_delete",{p_school:schoolId,p_entity:entity,p_id:id})})}
 const className=(id:string|null)=>classes.find(c=>c.id===id)?.name||"—";
 const subjectName=(id:string|null)=>subjects.find(s=>s.id===id)?.name||"Umum";
 const memberName=(id:string)=>staff.find(s=>s.user_id===id)?.name||members.find(m=>m.user_id===id)?.staff_name||members.find(m=>m.user_id===id)?.email||id.slice(0,8);
 const visibleStaff=staff.filter(x=>view==="teachers"?x.staff_type==="teacher":view==="staff"?x.staff_type!=="teacher":true);
 function resetStudent(){setSid(null);setSName("");setNis("");setNisn("");setGender("");setSClass("");setSStatus("active")}
 function resetClass(){setCid(null);setCName("");setGrade("");setYear("2026/2027")}
 function resetStaff(){setStaffId(null);setStaffName("");setPosition("");setShift("07:00");setTolerance("15")}
 function resetSubject(){setSubId(null);setSubName("");setSubCode("")}
 function resetAssignment(){setAssignId(null);setTeacher("");setClassId("");setSubjectId("");setMode("subject")}
 function pickStudent(s:S){setSid(s.id);setSName(s.name);setNis(s.nis||"");setNisn(s.nisn||"");setGender(s.gender||"");setSClass(s.class_id||"");setSStatus(s.status)}
 function pickClass(x:C){setCid(x.id);setCName(x.name);setGrade(x.grade||"");setYear(x.academic_year)}
 function pickStaff(x:Staff){setStaffId(x.id);setStaffName(x.name);setPosition(x.position||"");setShift((x.shift_start||"07:00").slice(0,5));setTolerance(String(x.late_tolerance_minutes??15))}
 function pickSubject(x:Subject){setSubId(x.id);setSubName(x.name);setSubCode(x.code||"")}
 function pickAssignment(x:A){setAssignId(x.id);setTeacher(x.teacher_id);setClassId(x.class_id);setSubjectId(x.subject_id||"");setMode(x.mode)}
 function importType(){return view==="students"?"students":view==="classes"?"classes":view==="teachers"?"teachers":view==="staff"?"staff":view==="subjects"?"subjects":"assignments"}
 async function template(){
  const type=importType(),guide=[{Kolom:"Panduan",Keterangan:"Jangan ubah nama kolom. Hapus baris contoh sebelum import data nyata. Maksimal 500 baris per sheet."}];
  const rows=type==="students"?[{NIS:"1001",NISN:"0098765432",Nama:"Alya Putri",Jenis_Kelamin:"Perempuan",Kelas:"VIII A",Tahun_Ajaran:"2026/2027"}]:
   type==="classes"?[{Nama_Kelas:"VIII A",Jenjang:"SMP 8",Tahun_Ajaran:"2026/2027"}]:
   type==="teachers"?[{Nama:"Budi Santoso",Jabatan:"Guru Matematika",Jam_Masuk:"07:00",Toleransi_Terlambat_Menit:15}]:
   type==="staff"?[{Nama:"Rina Setiawati",Jabatan:"Tenaga Administrasi",Jam_Masuk:"07:00",Toleransi_Terlambat_Menit:15}]:
   type==="subjects"?[{Kode:"MTK",Nama:"Matematika"}]:
   [{Email_Akun:"guru@sekolah.id",Kelas:"VIII A",Mata_Pelajaran:"Matematika",Jenis:"subject"}];
  await downloadExcel("template-"+type+"-school-control.xlsx",[{name:"Data",rows},{name:"Panduan",rows:guide}])
 }
 async function allTemplate(){const guide=[{Bagian:"Cara pakai",Keterangan:"Isi sheet yang diperlukan saja. Sheet kosong akan dilewati. Nama sheet dan kolom jangan diubah."}];await downloadExcel("template-data-induk-lengkap-school-control.xlsx",[
  {name:"Siswa",rows:[{NIS:"1001",NISN:"0098765432",Nama:"Alya Putri",Jenis_Kelamin:"Perempuan",Kelas:"VIII A",Tahun_Ajaran:"2026/2027"}]},
  {name:"Kelas",rows:[{Nama_Kelas:"VIII A",Jenjang:"SMP 8",Tahun_Ajaran:"2026/2027"}]},
  {name:"Guru",rows:[{Nama:"Budi Santoso",Jabatan:"Guru Matematika",Jam_Masuk:"07:00",Toleransi_Terlambat_Menit:15}]},
  {name:"Tenaga_Pendidik",rows:[{Nama:"Rina Setiawati",Jabatan:"Tenaga Administrasi",Jam_Masuk:"07:00",Toleransi_Terlambat_Menit:15}]},
  {name:"Mata_Pelajaran",rows:[{Kode:"MTK",Nama:"Matematika"}]},
  {name:"Penugasan_Guru",rows:[{Email_Akun:"guru@sekolah.id",Kelas:"VIII A",Mata_Pelajaran:"Matematika",Jenis:"subject"}]},
  {name:"Panduan",rows:guide}
 ])}
 async function readOne(file?:File){if(!file)return;setError("");try{if(file.size>8_000_000)throw Error("File maksimal 8 MB");const rows=await readExcel(file);if(rows.length>500)throw Error("Maksimal 500 baris");setImportRows(rows);setImportFile(file.name)}catch(e){setError(e instanceof Error?e.message:String(e));setImportRows([])}}
 async function readAll(file?:File){if(!file)return;setError("");try{if(file.size>12_000_000)throw Error("File maksimal 12 MB");const wb=await readWorkbook(file);for(const rows of Object.values(wb))if(rows.length>500)throw Error("Maksimal 500 baris per sheet");setWorkbook(wb);setImportFile(file.name)}catch(e){setError(e instanceof Error?e.message:String(e));setWorkbook({})}}
 async function importAssignments(rows:SheetRows){
  if(!db)return;const dir=await db.rpc("sc_team_directory",{p_school:schoolId});if(dir.error)throw dir.error;const people=(dir.data||[]) as Member[];
  const cl=await db.from("sc_classes").select("id,name").eq("school_id",schoolId);const su=await db.from("sc_subjects").select("id,name").eq("school_id",schoolId);
  for(const r of rows){const email=clean(r.Email_Akun).toLowerCase(),cn=clean(r.Kelas).toLowerCase(),sn=clean(r.Mata_Pelajaran).toLowerCase(),m=clean(r.Jenis)||"subject";if(!email||!cn)continue;
   const person=people.find(x=>(x.email||"").toLowerCase()===email),klass=(cl.data||[]).find(x=>x.name.toLowerCase()===cn),subject=(su.data||[]).find(x=>x.name.toLowerCase()===sn);
   if(person&&klass)await rpc("sc_master_save_assignment",{p_school:schoolId,p_id:null,p_teacher:person.user_id,p_class:klass.id,p_subject:subject?.id||null,p_mode:m});
  }
 }
 async function commitOne(){const type=importType();await run(async()=>{if(!importRows.length)return;
  if(type==="students")await rpc("sc_import_students",{p_school:schoolId,p_rows:importRows.map(r=>({nis:clean(r.NIS),nisn:clean(r.NISN),name:clean(r.Nama),gender:clean(r.Jenis_Kelamin),class_name:clean(r.Kelas),academic_year:clean(r.Tahun_Ajaran)}))});
  else if(type==="classes")await rpc("sc_import_classes",{p_school:schoolId,p_rows:importRows.map(r=>({name:clean(r.Nama_Kelas),grade:clean(r.Jenjang),academic_year:clean(r.Tahun_Ajaran)}))});
  else if(type==="teachers"||type==="staff")await rpc("sc_import_staff_v2",{p_school:schoolId,p_rows:importRows.map(r=>({name:clean(r.Nama),position:clean(r.Jabatan),shift_start:clean(r.Jam_Masuk),late_tolerance_minutes:Number(r.Toleransi_Terlambat_Menit||15)})),p_staff_type:type==="teachers"?"teacher":"education_staff"});
  else if(type==="subjects")await rpc("sc_import_subjects",{p_school:schoolId,p_rows:importRows.map(r=>({code:clean(r.Kode),name:clean(r.Nama)}))});
  else await importAssignments(importRows);
  setImportRows([]);setImportFile("");
 })}
 async function commitAll(){await run(async()=>{
  const by=(...names:string[])=>{for(const n of names)if(workbook[n])return workbook[n];return [] as SheetRows};
  const classRows=by("Kelas"),teacherRows=by("Guru"),staffRows=by("Tenaga_Pendidik","Tenaga Pendidik"),subjectRows=by("Mata_Pelajaran","Mata Pelajaran"),studentRows=by("Siswa"),assignmentRows=by("Penugasan_Guru","Penugasan Guru");
  if(classRows.length)await rpc("sc_import_classes",{p_school:schoolId,p_rows:classRows.map(r=>({name:clean(r.Nama_Kelas),grade:clean(r.Jenjang),academic_year:clean(r.Tahun_Ajaran)}))});
  if(teacherRows.length)await rpc("sc_import_staff_v2",{p_school:schoolId,p_rows:teacherRows.map(r=>({name:clean(r.Nama),position:clean(r.Jabatan),shift_start:clean(r.Jam_Masuk),late_tolerance_minutes:Number(r.Toleransi_Terlambat_Menit||15)})),p_staff_type:"teacher"});
  if(staffRows.length)await rpc("sc_import_staff_v2",{p_school:schoolId,p_rows:staffRows.map(r=>({name:clean(r.Nama),position:clean(r.Jabatan),shift_start:clean(r.Jam_Masuk),late_tolerance_minutes:Number(r.Toleransi_Terlambat_Menit||15)})),p_staff_type:"education_staff"});
  if(subjectRows.length)await rpc("sc_import_subjects",{p_school:schoolId,p_rows:subjectRows.map(r=>({code:clean(r.Kode),name:clean(r.Nama)}))});
  if(studentRows.length)await rpc("sc_import_students",{p_school:schoolId,p_rows:studentRows.map(r=>({nis:clean(r.NIS),nisn:clean(r.NISN),name:clean(r.Nama),gender:clean(r.Jenis_Kelamin),class_name:clean(r.Kelas),academic_year:clean(r.Tahun_Ajaran)}))});
  if(assignmentRows.length)await importAssignments(assignmentRows);
  setWorkbook({});setImportFile("");
 })}
 async function exportCurrent(){
  if(view==="students")return downloadExcel("siswa-school-control.xlsx",[{name:"Siswa",rows:students.map(s=>({NIS:s.nis||"",NISN:s.nisn||"",Nama:s.name,Jenis_Kelamin:s.gender||"",Kelas:className(s.class_id),Status:s.status}))}]);
  if(view==="classes")return downloadExcel("kelas-school-control.xlsx",[{name:"Kelas",rows:classes.map(c=>({Nama_Kelas:c.name,Jenjang:c.grade||"",Tahun_Ajaran:c.academic_year}))}]);
  if(view==="teachers"||view==="staff")return downloadExcel((view==="teachers"?"guru":"tenaga-pendidik")+"-school-control.xlsx",[{name:view==="teachers"?"Guru":"Tenaga_Pendidik",rows:visibleStaff.map(s=>({Nama:s.name,Jabatan:s.position||"",Jam_Masuk:s.shift_start,Toleransi_Terlambat_Menit:s.late_tolerance_minutes,Akun:s.user_id?"Terhubung":"Belum"}))}]);
  if(view==="subjects")return downloadExcel("mata-pelajaran-school-control.xlsx",[{name:"Mata_Pelajaran",rows:subjects.map(s=>({Kode:s.code||"",Nama:s.name}))}]);
  if(view==="assignments")return downloadExcel("penugasan-guru-school-control.xlsx",[{name:"Penugasan_Guru",rows:assignments.map(a=>({Guru:memberName(a.teacher_id),Kelas:className(a.class_id),Mata_Pelajaran:subjectName(a.subject_id),Jenis:a.mode}))}]);
 }
 const ImportBox=()=>view==="all"?<section className="panel"><div className="sectionhead"><div><h2>Import Excel Keseluruhan</h2><p className="muted">Satu workbook untuk semua Data Induk. Sheet yang kosong akan dilewati tanpa error.</p></div><FileSpreadsheet size={22}/></div><div className="flow"><button className="button secondary" onClick={()=>void allTemplate()}><Download size={15}/> Unduh Template Lengkap</button><label className="button secondary"><Upload size={15}/> Pilih Workbook<input hidden type="file" accept=".xlsx,.xls" onChange={e=>void readAll(e.currentTarget.files?.[0])}/></label></div>{Object.keys(workbook).length>0&&<div className="import-summary"><strong>{importFile}</strong>{Object.entries(workbook).filter(([n])=>n!=="Panduan").map(([n,r])=><span key={n}>{n}: {r.length} baris</span>)}<button className="button" disabled={busy} onClick={()=>void commitAll()}>Import Semua Sheet Berisi Data</button></div>}</section>:
 <section className="panel import-panel"><div className="sectionhead"><div><h2>Import / Export {view==="teachers"?"Guru":view==="staff"?"Tenaga Kependidikan":view==="assignments"?"Penugasan Guru":view==="subjects"?"Mata Pelajaran":view==="classes"?"Kelas":"Siswa"}</h2><p className="muted">Gunakan template agar data dapat divalidasi sebelum masuk ke sistem.</p></div></div><div className="flow"><button className="button secondary" onClick={()=>void template()}><Download size={15}/> Template Excel</button><label className="button secondary"><Upload size={15}/> Pilih Excel<input hidden type="file" accept=".xlsx,.xls" onChange={e=>void readOne(e.currentTarget.files?.[0])}/></label><button className="button secondary" onClick={()=>void exportCurrent()}><Download size={15}/> Export Data</button></div>{importRows.length>0&&<div className="import-summary"><strong>{importFile} · {importRows.length} baris</strong><small>{importRows.slice(0,3).map(x=>Object.values(x).slice(0,5).join(" | ")).join(" / ")}</small><button className="button" disabled={busy} onClick={()=>void commitOne()}>Konfirmasi Import</button></div>}</section>;
 if(!admin)return <section className="panel"><h2>Data Induk</h2><p className="muted">Peran Anda hanya dapat membaca data yang diperlukan. Perubahan Data Induk dilakukan manajemen sekolah.</p></section>;
 return <>
  {view==="students"&&<><section className="panel"><div className="sectionhead"><div><h2>Data Siswa</h2><p className="muted">Kelola siswa aktif dan arsip. Data ini dipakai penilaian, disiplin, BK dan tagihan.</p></div><button className="button secondary" onClick={resetStudent}><Plus size={15}/> Siswa Baru</button></div><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc("sc_master_save_student",{p_school:schoolId,p_id:sid,p_name:sName,p_nis:nis,p_nisn:nisn,p_gender:gender,p_class:sClass||null,p_status:sStatus});resetStudent()})}}><label className="field">Nama<input value={sName} onChange={e=>setSName(e.target.value)} required/></label><label className="field">NIS<input value={nis} onChange={e=>setNis(e.target.value)}/></label><label className="field">NISN<input value={nisn} onChange={e=>setNisn(e.target.value)}/></label><label className="field">Jenis Kelamin<select value={gender} onChange={e=>setGender(e.target.value)}><option value="">Belum diisi</option><option>Laki-laki</option><option>Perempuan</option></select></label><label className="field">Kelas<select value={sClass} onChange={e=>setSClass(e.target.value)}><option value="">Tanpa kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field">Status<select value={sStatus} onChange={e=>setSStatus(e.target.value)}><option value="active">Aktif</option><option value="archived">Arsip</option></select></label><button className="button" disabled={busy||sName.trim().length<2}>{sid?"Simpan Perubahan":"Tambah Siswa"}</button>{sid&&<button type="button" className="button secondary" onClick={resetStudent}>Batal</button>}</form><div className="tablewrap"><table className="data-table"><thead><tr><th>Nama</th><th>NIS/NISN</th><th>Kelas</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.nis||"—"} / {s.nisn||"—"}</td><td>{className(s.class_id)}</td><td><span className="pill">{s.status}</span></td><td><div className="flow"><button className="button secondary" onClick={()=>pickStudent(s)}>Edit</button>{s.status==="active"?<button className="button secondary" onClick={()=>void run(()=>rpc("sc_master_save_student",{p_school:schoolId,p_id:s.id,p_name:s.name,p_nis:s.nis||"",p_nisn:s.nisn||"",p_gender:s.gender||"",p_class:s.class_id,p_status:"archived"}).then(()=>{}))}>Arsipkan</button>:<><button className="button secondary" onClick={()=>void run(()=>rpc("sc_master_save_student",{p_school:schoolId,p_id:s.id,p_name:s.name,p_nis:s.nis||"",p_nisn:s.nisn||"",p_gender:s.gender||"",p_class:s.class_id,p_status:"active"}).then(()=>{}))}>Pulihkan</button><button className="button danger" onClick={()=>void remove("student",s.id)}>Hapus Permanen</button></>}</div></td></tr>)}</tbody></table></div></section><ImportBox/></>}
  {view==="classes"&&<><section className="panel"><div className="sectionhead"><div><h2>Kelas</h2><p className="muted">Kelas terhubung ke siswa, penugasan guru, presensi, nilai dan laporan.</p></div><button className="button secondary" onClick={resetClass}><Plus size={15}/> Kelas Baru</button></div><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc("sc_master_save_class",{p_school:schoolId,p_id:cid,p_name:cName,p_grade:grade,p_year:year});resetClass()})}}><label className="field">Nama Kelas<input value={cName} onChange={e=>setCName(e.target.value)} required/></label><label className="field">Jenjang<input value={grade} onChange={e=>setGrade(e.target.value)}/></label><label className="field">Tahun Ajaran<input value={year} onChange={e=>setYear(e.target.value)} required/></label><button className="button" disabled={busy||!cName.trim()}>{cid?"Simpan Perubahan":"Tambah Kelas"}</button></form>{classes.map(x=><div className="entry" key={x.id}><div><strong>{x.name}</strong><small>{x.grade||"—"} · {x.academic_year}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickClass(x)}>Edit</button><button className="button danger" onClick={()=>void remove("class",x.id)}>Hapus</button></div></div>)}</section><ImportBox/></>}
  {(view==="teachers"||view==="staff")&&<><section className="panel"><div className="sectionhead"><div><h2>{view==="teachers"?"Guru":"Tenaga Kependidikan"}</h2><p className="muted">{view==="teachers"?"Data guru untuk penugasan kelas, perangkat ajar, penilaian, presensi dan payroll.":"Data tenaga kependidikan untuk presensi, tugas, akses dan payroll."}</p></div><button className="button secondary" onClick={resetStaff}><Plus size={15}/> Tambah</button></div><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc("sc_master_save_staff_v2",{p_school:schoolId,p_id:staffId,p_name:staffName,p_position:position,p_shift:shift,p_tolerance:Number(tolerance),p_staff_type:view==="teachers"?"teacher":"education_staff"});resetStaff()})}}><label className="field">Nama<input value={staffName} onChange={e=>setStaffName(e.target.value)} required/></label><label className="field">Jabatan<input value={position} onChange={e=>setPosition(e.target.value)}/></label><label className="field">Jam Masuk<input type="time" value={shift} onChange={e=>setShift(e.target.value)}/></label><label className="field">Toleransi Terlambat<input type="number" min={0} max={240} value={tolerance} onChange={e=>setTolerance(e.target.value)}/></label><button className="button" disabled={busy||staffName.trim().length<2}>{staffId?"Simpan Perubahan":"Tambah Data"}</button></form>{visibleStaff.map(x=><div className="entry" key={x.id}><div><strong>{x.name}</strong><small>{x.position||"Tanpa jabatan"} · {x.shift_start?.slice(0,5)} · {x.user_id?"Akun terhubung":"Belum terkait akun"}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickStaff(x)}>Edit</button>{!x.user_id&&<button className="button danger" onClick={()=>void remove("staff",x.id)}>Hapus</button>}</div></div>)}</section><ImportBox/></>}
  {view==="subjects"&&<><section className="panel"><div className="sectionhead"><div><h2>Mata Pelajaran</h2><p className="muted">Master mapel dipakai penugasan, jurnal, nilai dan Perangkat Ajar AI.</p></div><button className="button secondary" onClick={resetSubject}><Plus size={15}/> Mapel Baru</button></div><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc("sc_master_save_subject",{p_school:schoolId,p_id:subId,p_name:subName,p_code:subCode});resetSubject()})}}><label className="field">Kode<input value={subCode} onChange={e=>setSubCode(e.target.value)}/></label><label className="field">Nama Mata Pelajaran<input value={subName} onChange={e=>setSubName(e.target.value)} required/></label><button className="button" disabled={busy||subName.trim().length<2}>{subId?"Simpan Perubahan":"Tambah Mapel"}</button></form>{subjects.map(x=><div className="entry" key={x.id}><div><strong>{x.name}</strong><small>{x.code||"Tanpa kode"}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickSubject(x)}>Edit</button><button className="button danger" onClick={()=>void remove("subject",x.id)}>Hapus</button></div></div>)}</section><ImportBox/></>}
  {view==="assignments"&&<><section className="panel"><div className="sectionhead"><div><h2>Penugasan Guru</h2><p className="muted">Hubungkan akun guru dengan kelas dan mata pelajaran. Hak input akademik mengikuti penugasan ini.</p></div><button className="button secondary" onClick={resetAssignment}><Plus size={15}/> Penugasan</button></div><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc("sc_master_save_assignment",{p_school:schoolId,p_id:assignId,p_teacher:teacher,p_class:classId,p_subject:subjectId||null,p_mode:mode});resetAssignment()})}}><label className="field">Guru<select value={teacher} onChange={e=>setTeacher(e.target.value)} required><option value="">Pilih guru</option>{members.filter(m=>["owner","principal","vice_principal","teacher"].includes(m.role)).map(m=><option key={m.user_id} value={m.user_id}>{memberName(m.user_id)}</option>)}</select></label><label className="field">Kelas<select value={classId} onChange={e=>setClassId(e.target.value)} required><option value="">Pilih kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field">Mata Pelajaran<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Tanpa mapel</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field">Jenis<select value={mode} onChange={e=>setMode(e.target.value)}><option value="homeroom">Wali Kelas</option><option value="subject">Guru Mapel</option><option value="combined">Gabungan</option></select></label><button className="button" disabled={busy||!teacher||!classId}>{assignId?"Simpan Perubahan":"Tetapkan Guru"}</button></form>{assignments.map(x=><div className="entry" key={x.id}><div><strong>{memberName(x.teacher_id)} · {className(x.class_id)}</strong><small>{x.mode} · {subjectName(x.subject_id)}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickAssignment(x)}>Edit</button><button className="button danger" onClick={()=>void remove("assignment",x.id)}>Hapus</button></div></div>)}</section><ImportBox/></>}
  {view==="all"&&<ImportBox/>}
  {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}
 </>;
}
