"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {downloadExcel,readExcel} from "@/lib/excel";
import {isAdmin,type Role} from "@/lib/modules";
type C={id:string;name:string;grade:string|null;academic_year:string};
type S={id:string;name:string;nis:string|null;nisn:string|null;gender:string|null;class_id:string|null;status:string};
type Staff={id:string;user_id:string|null;name:string;position:string|null;shift_start:string;late_tolerance_minutes:number};
type Subject={id:string;name:string;code:string|null};
type Member={user_id:string;role:string};
type A={id:string;teacher_id:string;class_id:string;subject_id:string|null;mode:string};
type Tab="students"|"classes"|"staff"|"subjects"|"assignments"|"import";
const tabs:[Tab,string][]=[["students","Siswa"],["classes","Kelas"],["staff","Guru & Staf"],["subjects","Mata Pelajaran"],["assignments","Penugasan Guru"],["import","Import / Export"]];
const clean=(v:unknown)=>String(v??"").trim();
export default function MasterHub({schoolId,role,focus}:{schoolId:string;role:Role;focus?:string}){
 const db=useMemo(()=>browserDb(),[]),admin=isAdmin(role);
 const [tab,setTab]=useState<Tab>("students"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 const [classes,setClasses]=useState<C[]>([]),[students,setStudents]=useState<S[]>([]),[staff,setStaff]=useState<Staff[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[members,setMembers]=useState<Member[]>([]),[assignments,setAssignments]=useState<A[]>([]);
 const [sid,setSid]=useState<string|null>(null),[sName,setSName]=useState(""),[nis,setNis]=useState(""),[nisn,setNisn]=useState(""),[gender,setGender]=useState(""),[sClass,setSClass]=useState(""),[sStatus,setSStatus]=useState("active");
 const [cid,setCid]=useState<string|null>(null),[cName,setCName]=useState(""),[grade,setGrade]=useState(""),[year,setYear]=useState("2026/2027");
 const [staffId,setStaffId]=useState<string|null>(null),[staffName,setStaffName]=useState(""),[position,setPosition]=useState(""),[shift,setShift]=useState("07:00"),[tolerance,setTolerance]=useState("15");
 const [subId,setSubId]=useState<string|null>(null),[subName,setSubName]=useState(""),[subCode,setSubCode]=useState("");
 const [assignId,setAssignId]=useState<string|null>(null),[teacher,setTeacher]=useState(""),[classId,setClassId]=useState(""),[subjectId,setSubjectId]=useState(""),[mode,setMode]=useState("subject");
 const [importKind,setImportKind]=useState<"students"|"classes"|"staff"|"subjects">("students"),[preview,setPreview]=useState<Record<string,unknown>[]>([]),[filename,setFilename]=useState("");
 async function load(){if(!db)return;const r=await Promise.all([
  db.from("sc_classes").select("id,name,grade,academic_year").eq("school_id",schoolId).order("name"),
  db.from("sc_students").select("id,name,nis,nisn,gender,class_id,status").eq("school_id",schoolId).order("name"),
  db.from("sc_staff").select("id,user_id,name,position,shift_start,late_tolerance_minutes").eq("school_id",schoolId).order("name"),
  db.from("sc_subjects").select("id,name,code").eq("school_id",schoolId).order("name"),
  db.from("sc_members").select("user_id,role").eq("school_id",schoolId),
  db.from("sc_teacher_assignments").select("id,teacher_id,class_id,subject_id,mode").eq("school_id",schoolId)
 ]);setClasses((r[0].data||[]) as C[]);setStudents((r[1].data||[]) as S[]);setStaff((r[2].data||[]) as Staff[]);setSubjects((r[3].data||[]) as Subject[]);setMembers((r[4].data||[]) as Member[]);setAssignments((r[5].data||[]) as A[]);for(const x of r)if(x.error){setError(x.error.message);break}}
 useEffect(()=>{void load()},[db,schoolId]);
 useEffect(()=>{const f=(focus||"").toLowerCase();if(f.includes("siswa"))setTab("students");else if(f.includes("kelas"))setTab("classes");else if(f.includes("guru")||f.includes("tenaga"))setTab("staff");else if(f.includes("mata"))setTab("subjects");else if(f.includes("penugasan"))setTab("assignments");else if(f.includes("import")||f.includes("export"))setTab("import")},[focus]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Perubahan tersimpan dan langsung dipakai fitur lain.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function rpc(name:string,args:Record<string,unknown>){if(!db)throw Error("Database belum terhubung");const {data,error}=await db.rpc(name,args);if(error)throw error;return data}
 function resetStudent(){setSid(null);setSName("");setNis("");setNisn("");setGender("");setSClass("");setSStatus("active")}
 function pickStudent(s:S){setSid(s.id);setSName(s.name);setNis(s.nis||"");setNisn(s.nisn||"");setGender(s.gender||"");setSClass(s.class_id||"");setSStatus(s.status)}
 function resetClass(){setCid(null);setCName("");setGrade("");setYear("2026/2027")}
 function pickClass(c:C){setCid(c.id);setCName(c.name);setGrade(c.grade||"");setYear(c.academic_year)}
 function resetStaff(){setStaffId(null);setStaffName("");setPosition("");setShift("07:00");setTolerance("15")}
 function pickStaff(x:Staff){setStaffId(x.id);setStaffName(x.name);setPosition(x.position||"");setShift((x.shift_start||"07:00").slice(0,5));setTolerance(String(x.late_tolerance_minutes??15))}
 function resetSubject(){setSubId(null);setSubName("");setSubCode("")}
 function pickSubject(x:Subject){setSubId(x.id);setSubName(x.name);setSubCode(x.code||"")}
 function resetAssignment(){setAssignId(null);setTeacher("");setClassId("");setSubjectId("");setMode("subject")}
 function pickAssignment(x:A){setAssignId(x.id);setTeacher(x.teacher_id);setClassId(x.class_id);setSubjectId(x.subject_id||"");setMode(x.mode)}
 async function remove(entity:string,id:string){if(!confirm("Hapus data ini? Data yang sudah dipakai riwayat lain akan ditolak oleh sistem."))return;await run(async()=>{await rpc("sc_master_delete",{p_school:schoolId,p_entity:entity,p_id:id})})}
 const teacherName=(id:string)=>staff.find(s=>s.user_id===id)?.name||members.find(m=>m.user_id===id)?.role+" · "+id.slice(0,8);
 async function template(){
  const guide=[{Kolom:"Wajib",Keterangan:"Jangan mengubah nama kolom pada baris pertama. Baris contoh boleh dihapus sebelum import."},{Kolom:"Batas",Keterangan:"Maksimal 500 baris per file."}];
  const rows=importKind==="students"?[{NIS:"1001",Nama:"Alya Putri",Kelas:"VIII A",Tahun_Ajaran:"2026/2027"}]:
   importKind==="classes"?[{Nama_Kelas:"VIII A",Jenjang:"SMP 8",Tahun_Ajaran:"2026/2027"}]:
   importKind==="staff"?[{Nama:"Budi Santoso",Jabatan:"Guru Matematika",Jam_Masuk:"07:00",Toleransi_Terlambat_Menit:15}]:
   [{Kode:"MTK",Nama:"Matematika"}];
  await downloadExcel("template-"+importKind+"-school-control.xlsx",[{name:"Data",rows},{name:"Panduan",rows:guide}]);
 }
 async function read(file?:File){if(!file)return;setError("");try{if(file.size>5_000_000)throw Error("File maksimal 5 MB");const rows=await readExcel(file);if(rows.length>500)throw Error("Maksimal 500 baris");setPreview(rows as Record<string,unknown>[]);setFilename(file.name)}catch(e){setError(e instanceof Error?e.message:String(e));setPreview([])}}
 async function commitImport(){if(!preview.length)return;await run(async()=>{
  if(importKind==="students"){
   const rows=preview.map(r=>({nis:clean(r.NIS),name:clean(r.Nama),class_name:clean(r.Kelas),academic_year:clean(r.Tahun_Ajaran)}));
   const res=await rpc("sc_import_students",{p_school:schoolId,p_rows:rows});setOk("Import siswa selesai: "+JSON.stringify(res));
  }else if(importKind==="classes"){
   const rows=preview.map(r=>({name:clean(r.Nama_Kelas),grade:clean(r.Jenjang),academic_year:clean(r.Tahun_Ajaran)}));await rpc("sc_import_classes",{p_school:schoolId,p_rows:rows});
  }else if(importKind==="staff"){
   const rows=preview.map(r=>({name:clean(r.Nama),position:clean(r.Jabatan),shift_start:clean(r.Jam_Masuk),late_tolerance_minutes:Number(r.Toleransi_Terlambat_Menit||15)}));await rpc("sc_import_staff",{p_school:schoolId,p_rows:rows});
  }else{
   const rows=preview.map(r=>({code:clean(r.Kode),name:clean(r.Nama)}));await rpc("sc_import_subjects",{p_school:schoolId,p_rows:rows});
  } setPreview([]);setFilename("");
 })}
 async function exportAll(){await downloadExcel("data-induk-school-control.xlsx",[
  {name:"Siswa",rows:students.map(s=>({NIS:s.nis||"",NISN:s.nisn||"",Nama:s.name,Jenis_Kelamin:s.gender||"",Kelas:classes.find(c=>c.id===s.class_id)?.name||"",Status:s.status}))},
  {name:"Kelas",rows:classes.map(c=>({Nama_Kelas:c.name,Jenjang:c.grade||"",Tahun_Ajaran:c.academic_year}))},
  {name:"Guru_Staf",rows:staff.map(s=>({Nama:s.name,Jabatan:s.position||"",Jam_Masuk:s.shift_start,Toleransi:s.late_tolerance_minutes,Terkait_Akun:s.user_id?"Ya":"Belum"}))},
  {name:"Mata_Pelajaran",rows:subjects.map(s=>({Kode:s.code||"",Nama:s.name}))}
 ])}
 if(!admin)return <section className="panel"><h2>Data Induk</h2><p className="muted">Peran Anda hanya dapat membaca data yang diperlukan. Pengubahan Data Induk dilakukan manajemen sekolah.</p></section>;
 return <><div className="subtabs">{tabs.map(([k,n])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{n}</button>)}</div>
 {tab==="students"&&<section className="panel"><div className="sectionhead"><div><h2>Data Siswa</h2><p className="muted">Tambah, edit, arsipkan, pulihkan, dan hapus permanen jika tidak memiliki riwayat terikat.</p></div><button className="button secondary" onClick={resetStudent}>+ Siswa Baru</button></div><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc("sc_master_save_student",{p_school:schoolId,p_id:sid,p_name:sName,p_nis:nis,p_nisn:nisn,p_gender:gender,p_class:sClass||null,p_status:sStatus});resetStudent()})}}><label className="field">Nama<input value={sName} onChange={e=>setSName(e.target.value)} required/></label><label className="field">NIS<input value={nis} onChange={e=>setNis(e.target.value)}/></label><label className="field">NISN<input value={nisn} onChange={e=>setNisn(e.target.value)}/></label><label className="field">Jenis Kelamin<select value={gender} onChange={e=>setGender(e.target.value)}><option value="">Belum diisi</option><option>Laki-laki</option><option>Perempuan</option></select></label><label className="field">Kelas<select value={sClass} onChange={e=>setSClass(e.target.value)}><option value="">Tanpa kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.academic_year}</option>)}</select></label><label className="field">Status<select value={sStatus} onChange={e=>setSStatus(e.target.value)}><option value="active">Aktif</option><option value="archived">Arsip</option></select></label><button className="button" disabled={busy||sName.trim().length<2}>{sid?"Simpan Perubahan":"Tambah Siswa"}</button>{sid&&<button type="button" className="button secondary" onClick={resetStudent}>Batal</button>}</form><div className="tablewrap"><table className="data-table"><thead><tr><th>Nama</th><th>NIS/NISN</th><th>Kelas</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.nis||"—"} / {s.nisn||"—"}</td><td>{classes.find(c=>c.id===s.class_id)?.name||"—"}</td><td><span className="pill">{s.status}</span></td><td><div className="flow"><button className="button secondary" onClick={()=>pickStudent(s)}>Edit</button>{s.status==="active"?<button className="button secondary" onClick={()=>void run(()=>rpc("sc_master_save_student",{p_school:schoolId,p_id:s.id,p_name:s.name,p_nis:s.nis||"",p_nisn:s.nisn||"",p_gender:s.gender||"",p_class:s.class_id,p_status:"archived"}))}>Arsipkan</button>:<><button className="button secondary" onClick={()=>void run(()=>rpc("sc_master_save_student",{p_school:schoolId,p_id:s.id,p_name:s.name,p_nis:s.nis||"",p_nisn:s.nisn||"",p_gender:s.gender||"",p_class:s.class_id,p_status:"active"}))}>Pulihkan</button><button className="button danger" onClick={()=>void remove("student",s.id)}>Hapus Permanen</button></>}</div></td></tr>)}</tbody></table></div></section>}
 {tab==="classes"&&<section className="panel"><div className="sectionhead"><div><h2>Kelas & Tahun Ajaran</h2><p className="muted">Kelas dipakai oleh siswa, presensi, nilai, penugasan guru dan laporan.</p></div><button className="button secondary" onClick={resetClass}>+ Kelas Baru</button></div><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc("sc_master_save_class",{p_school:schoolId,p_id:cid,p_name:cName,p_grade:grade,p_year:year});resetClass()})}}><label className="field">Nama Kelas<input value={cName} onChange={e=>setCName(e.target.value)} required/></label><label className="field">Jenjang<input value={grade} onChange={e=>setGrade(e.target.value)}/></label><label className="field">Tahun Ajaran<input value={year} onChange={e=>setYear(e.target.value)} required/></label><button className="button" disabled={busy||!cName.trim()}>{cid?"Simpan Perubahan":"Tambah Kelas"}</button></form>{classes.map(c=><div className="entry" key={c.id}><div><strong>{c.name}</strong><small>{c.grade||"—"} · {c.academic_year}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickClass(c)}>Edit</button><button className="button danger" onClick={()=>void remove("class",c.id)}>Hapus</button></div></div>)}</section>}
 {tab==="staff"&&<section className="panel"><div className="sectionhead"><div><h2>Guru & Tenaga Kependidikan</h2><p className="muted">Data SDM ini menjadi sumber presensi, kinerja, program, payroll dan slip gaji.</p></div><button className="button secondary" onClick={resetStaff}>+ SDM Baru</button></div><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc("sc_master_save_staff",{p_school:schoolId,p_id:staffId,p_name:staffName,p_position:position,p_shift:shift,p_tolerance:Number(tolerance)});resetStaff()})}}><label className="field">Nama<input value={staffName} onChange={e=>setStaffName(e.target.value)} required/></label><label className="field">Jabatan<input value={position} onChange={e=>setPosition(e.target.value)}/></label><label className="field">Jam Masuk<input type="time" value={shift} onChange={e=>setShift(e.target.value)}/></label><label className="field">Toleransi Terlambat (menit)<input type="number" min={0} max={240} value={tolerance} onChange={e=>setTolerance(e.target.value)}/></label><button className="button" disabled={busy||staffName.trim().length<2}>{staffId?"Simpan Perubahan":"Tambah SDM"}</button></form>{staff.map(x=><div className="entry" key={x.id}><div><strong>{x.name}</strong><small>{x.position||"Tanpa jabatan"} · {x.shift_start?.slice(0,5)} · {x.user_id?"Akun terhubung":"Belum terkait akun"}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickStaff(x)}>Edit</button>{!x.user_id&&<button className="button danger" onClick={()=>void remove("staff",x.id)}>Hapus</button>}</div></div>)}</section>}
 {tab==="subjects"&&<section className="panel"><div className="sectionhead"><div><h2>Mata Pelajaran</h2><p className="muted">Master mapel dipakai penugasan guru, jurnal, nilai dan perangkat ajar.</p></div><button className="button secondary" onClick={resetSubject}>+ Mapel Baru</button></div><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc("sc_master_save_subject",{p_school:schoolId,p_id:subId,p_name:subName,p_code:subCode});resetSubject()})}}><label className="field">Kode<input value={subCode} onChange={e=>setSubCode(e.target.value)}/></label><label className="field">Nama Mata Pelajaran<input value={subName} onChange={e=>setSubName(e.target.value)} required/></label><button className="button" disabled={busy||subName.trim().length<2}>{subId?"Simpan Perubahan":"Tambah Mapel"}</button></form>{subjects.map(x=><div className="entry" key={x.id}><div><strong>{x.name}</strong><small>{x.code||"Tanpa kode"}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickSubject(x)}>Edit</button><button className="button danger" onClick={()=>void remove("subject",x.id)}>Hapus</button></div></div>)}</section>}
 {tab==="assignments"&&<section className="panel"><div className="sectionhead"><div><h2>Penugasan Guru</h2><p className="muted">Tetapkan wali kelas, guru mapel, atau gabungan. Hak input akademik mengikuti penugasan ini.</p></div><button className="button secondary" onClick={resetAssignment}>+ Penugasan</button></div><form className="fields" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc("sc_master_save_assignment",{p_school:schoolId,p_id:assignId,p_teacher:teacher,p_class:classId,p_subject:subjectId||null,p_mode:mode});resetAssignment()})}}><label className="field">Guru<select value={teacher} onChange={e=>setTeacher(e.target.value)} required><option value="">Pilih guru</option>{members.filter(m=>["owner","principal","vice_principal","teacher"].includes(m.role)).map(m=><option key={m.user_id} value={m.user_id}>{teacherName(m.user_id)}</option>)}</select></label><label className="field">Kelas<select value={classId} onChange={e=>setClassId(e.target.value)} required><option value="">Pilih kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field">Mata Pelajaran<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Tanpa mapel</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field">Jenis<select value={mode} onChange={e=>setMode(e.target.value)}><option value="homeroom">Wali Kelas</option><option value="subject">Guru Mapel</option><option value="combined">Gabungan</option></select></label><button className="button" disabled={busy||!teacher||!classId}>{assignId?"Simpan Perubahan":"Tetapkan Guru"}</button></form>{assignments.map(x=><div className="entry" key={x.id}><div><strong>{teacherName(x.teacher_id)} · {classes.find(c=>c.id===x.class_id)?.name}</strong><small>{x.mode} · {subjects.find(s=>s.id===x.subject_id)?.name||"Umum"}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickAssignment(x)}>Edit</button><button className="button danger" onClick={()=>void remove("assignment",x.id)}>Hapus</button></div></div>)}</section>}
 {tab==="import"&&<section className="panel"><h2>Import / Export Excel</h2><p className="muted">Gunakan template resmi agar nama kolom terbaca konsisten. Setiap template memiliki sheet Panduan dan satu baris contoh.</p><div className="fields"><label className="field">Jenis Data<select value={importKind} onChange={e=>{setImportKind(e.target.value as typeof importKind);setPreview([])}}><option value="students">Siswa</option><option value="classes">Kelas</option><option value="staff">Guru & Staf</option><option value="subjects">Mata Pelajaran</option></select></label><div className="flow"><button className="button secondary" onClick={()=>void template()}>Unduh Template Excel</button><label className="button secondary">Pilih File Excel<input hidden type="file" accept=".xlsx,.xls" onChange={e=>void read(e.currentTarget.files?.[0])}/></label><button className="button secondary" onClick={()=>void exportAll()}>Export Semua Data Induk</button></div></div>{preview.length>0&&<div className="banner"><strong>{filename} · {preview.length} baris</strong><p className="hint">Pratinjau: {preview.slice(0,3).map(x=>Object.values(x).slice(0,4).join(" | ")).join(" / ")}</p><button className="button" disabled={busy} onClick={()=>void commitImport()}>Konfirmasi Import</button></div>}</section>}
 {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
}
