"use client";
import {useEffect,useMemo,useState} from "react";
import {Download,FileSpreadsheet,Plus,Upload} from "lucide-react";
import DataEntryModal from "@/components/DataEntryModal";
import {browserDb} from "@/lib/supabase";
import {downloadExcel,readExcel,readWorkbook,type SheetRows} from "@/lib/excel";
import {isAdmin,type Role} from "@/lib/modules";

type C={id:string;name:string;grade:string|null;academic_year:string};
type Contact={student_id:string;guardian_name:string|null;guardian_phone:string|null};
type S={id:string;name:string;nis:string|null;nisn:string|null;gender:string|null;class_id:string|null;status:string;nickname:string|null;birth_date:string|null;address:string|null;phone:string|null;parent_phone:string|null};
type Staff={id:string;user_id:string|null;name:string;position:string|null;shift_start:string;late_tolerance_minutes:number;staff_type:string;employee_code:string|null;email:string|null;phone:string|null;department:string|null;rank_name:string|null;employment_type:string|null;hire_date:string|null;contract_end:string|null;personal_data:Record<string,unknown>|null;bank_name:string|null;bank_account_name:string|null;bank_account_number:string|null;payroll_data:Record<string,unknown>|null};
type Subject={id:string;name:string;code:string|null};
type Member={user_id:string;role:string;email?:string|null;staff_name?:string|null};
type A={id:string;teacher_id:string;class_id:string;subject_id:string|null;mode:string};
type View="students"|"classes"|"teachers"|"staff"|"subjects"|"assignments"|"all";
const clean=(v:unknown)=>String(v??"").trim();
const blankExtra=()=>({employee_code:"",email:"",phone:"",department:"",rank_name:"",employment_type:"Tetap",hire_date:"",contract_end:"",birth_place:"",birth_date:"",marital_status:"",blood_type:"",religion:"",identity_number:"",address:"",emergency_name:"",emergency_phone:"",education_level:"",institution:"",study_program:"",bank_name:"",bank_account_name:"",bank_account_number:"",npwp:"",tax_status:"",bpjs_health:"",bpjs_employment:""});

export default function MasterHubV2({schoolId,role,focus}:{schoolId:string;role:Role;focus?:string}){
 const db=useMemo(()=>browserDb(),[]),admin=isAdmin(role);
 const [classes,setClasses]=useState<C[]>([]),[students,setStudents]=useState<S[]>([]),[contacts,setContacts]=useState<Contact[]>([]),[staff,setStaff]=useState<Staff[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[members,setMembers]=useState<Member[]>([]),[assignments,setAssignments]=useState<A[]>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState(""),[modal,setModal]=useState(false);
 const [sid,setSid]=useState<string|null>(null),[sName,setSName]=useState(""),[nickname,setNickname]=useState(""),[nis,setNis]=useState(""),[nisn,setNisn]=useState(""),[gender,setGender]=useState(""),[birthDate,setBirthDate]=useState(""),[studentAddress,setStudentAddress]=useState(""),[studentPhone,setStudentPhone]=useState(""),[parentPhone,setParentPhone]=useState(""),[sClass,setSClass]=useState(""),[sStatus,setSStatus]=useState("active"),[guardian,setGuardian]=useState(""),[guardianPhone,setGuardianPhone]=useState("");
 const [cid,setCid]=useState<string|null>(null),[cName,setCName]=useState(""),[grade,setGrade]=useState(""),[year,setYear]=useState("2026/2027");
 const [staffId,setStaffId]=useState<string|null>(null),[staffName,setStaffName]=useState(""),[position,setPosition]=useState(""),[shift,setShift]=useState("07:00"),[tolerance,setTolerance]=useState("15"),[staffExtra,setStaffExtra]=useState(blankExtra());
 const [subId,setSubId]=useState<string|null>(null),[subName,setSubName]=useState(""),[subCode,setSubCode]=useState("");
 const [assignId,setAssignId]=useState<string|null>(null),[teacher,setTeacher]=useState(""),[classId,setClassId]=useState(""),[subjectId,setSubjectId]=useState(""),[mode,setMode]=useState("subject");
 const [importRows,setImportRows]=useState<SheetRows>([]),[importFile,setImportFile]=useState(""),[workbook,setWorkbook]=useState<Record<string,SheetRows>>({});
 const f=(focus||"Siswa").toLowerCase();
 const view:View=f.includes("import excel keseluruhan")?"all":f.includes("penugasan")?"assignments":f.includes("mata")?"subjects":f.includes("tenaga")?"staff":f==="guru"||f.includes("guru")?"teachers":f.includes("kelas")?"classes":"students";

 async function load(){if(!db)return;const r=await Promise.all([
  db.from("sc_classes").select("id,name,grade,academic_year").eq("school_id",schoolId).order("name"),
  db.from("sc_students").select("id,name,nis,nisn,gender,class_id,status,nickname,birth_date,address,phone,parent_phone").eq("school_id",schoolId).neq("status","deleted").order("name"),
  db.from("sc_student_contacts").select("student_id,guardian_name,guardian_phone").eq("school_id",schoolId),
  db.from("sc_staff").select("id,user_id,name,position,shift_start,late_tolerance_minutes,staff_type,employee_code,email,phone,department,rank_name,employment_type,hire_date,contract_end,personal_data,bank_name,bank_account_name,bank_account_number,payroll_data").eq("school_id",schoolId).order("name"),
  db.from("sc_subjects").select("id,name,code").eq("school_id",schoolId).order("name"),
  db.from("sc_members").select("user_id,role").eq("school_id",schoolId),
  db.from("sc_teacher_assignments").select("id,teacher_id,class_id,subject_id,mode").eq("school_id",schoolId)
 ]);setClasses((r[0].data||[]) as C[]);setStudents((r[1].data||[]) as S[]);setContacts((r[2].data||[]) as Contact[]);setStaff((r[3].data||[]) as Staff[]);setSubjects((r[4].data||[]) as Subject[]);setMembers((r[5].data||[]) as Member[]);setAssignments((r[6].data||[]) as A[]);
 if(admin){const d=await db.rpc("sc_team_directory",{p_school:schoolId});if(!d.error&&d.data)setMembers(d.data as Member[])}
 const first=r.find(x=>x.error);if(first?.error)setError(first.error.message)}
 useEffect(()=>{void load();setImportRows([]);setWorkbook({});setImportFile("");setModal(false)},[db,schoolId,focus]);

 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Perubahan tersimpan dan langsung dipakai modul lain.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function rpc(name:string,args:Record<string,unknown>){if(!db)throw Error("Database belum terhubung");const {data,error}=await db.rpc(name,args);if(error)throw error;return data}
 async function remove(entity:string,id:string){if(!confirm("Hapus data ini? Data yang sudah dipakai pada riwayat lain dapat ditolak sistem."))return;await run(async()=>{await rpc("sc_master_delete",{p_school:schoolId,p_entity:entity,p_id:id})})}
 const className=(id:string|null)=>classes.find(c=>c.id===id)?.name||"—";
 const subjectName=(id:string|null)=>subjects.find(s=>s.id===id)?.name||"Umum";
 const memberName=(id:string)=>staff.find(s=>s.user_id===id)?.name||members.find(m=>m.user_id===id)?.staff_name||members.find(m=>m.user_id===id)?.email||id.slice(0,8);
 const contact=(id:string)=>contacts.find(x=>x.student_id===id);
 const visibleStaff=staff.filter(x=>view==="teachers"?x.staff_type==="teacher":view==="staff"?x.staff_type!=="teacher":true);
 const setExtra=(key:string,value:string)=>setStaffExtra(x=>({...x,[key]:value}));

 function resetStudent(){setSid(null);setSName("");setNickname("");setNis("");setNisn("");setGender("");setBirthDate("");setStudentAddress("");setStudentPhone("");setParentPhone("");setSClass("");setSStatus("active");setGuardian("");setGuardianPhone("")}
 function resetClass(){setCid(null);setCName("");setGrade("");setYear("2026/2027")}
 function resetStaff(){setStaffId(null);setStaffName("");setPosition("");setShift("07:00");setTolerance("15");setStaffExtra(blankExtra())}
 function resetSubject(){setSubId(null);setSubName("");setSubCode("")}
 function resetAssignment(){setAssignId(null);setTeacher("");setClassId("");setSubjectId("");setMode("subject")}
 function openNew(){if(view==="students")resetStudent();if(view==="classes")resetClass();if(view==="teachers"||view==="staff")resetStaff();if(view==="subjects")resetSubject();if(view==="assignments")resetAssignment();setModal(true)}
 function pickStudent(s:S){const ct=contact(s.id);setSid(s.id);setSName(s.name);setNickname(s.nickname||"");setNis(s.nis||"");setNisn(s.nisn||"");setGender(s.gender||"");setBirthDate(s.birth_date||"");setStudentAddress(s.address||"");setStudentPhone(s.phone||"");setParentPhone(s.parent_phone||"");setSClass(s.class_id||"");setSStatus(s.status);setGuardian(ct?.guardian_name||"");setGuardianPhone(ct?.guardian_phone||"");setModal(true)}
 function pickClass(x:C){setCid(x.id);setCName(x.name);setGrade(x.grade||"");setYear(x.academic_year);setModal(true)}
 function pickStaff(x:Staff){const p=(x.personal_data||{}) as Record<string,unknown>,pay=(x.payroll_data||{}) as Record<string,unknown>;setStaffId(x.id);setStaffName(x.name);setPosition(x.position||"");setShift((x.shift_start||"07:00").slice(0,5));setTolerance(String(x.late_tolerance_minutes??15));setStaffExtra({...blankExtra(),employee_code:x.employee_code||"",email:x.email||"",phone:x.phone||"",department:x.department||"",rank_name:x.rank_name||"",employment_type:x.employment_type||"Tetap",hire_date:x.hire_date||"",contract_end:x.contract_end||"",birth_place:clean(p.birth_place),birth_date:clean(p.birth_date),marital_status:clean(p.marital_status),blood_type:clean(p.blood_type),religion:clean(p.religion),identity_number:clean(p.identity_number),address:clean(p.address),emergency_name:clean(p.emergency_name),emergency_phone:clean(p.emergency_phone),education_level:clean(p.education_level),institution:clean(p.institution),study_program:clean(p.study_program),bank_name:x.bank_name||"",bank_account_name:x.bank_account_name||"",bank_account_number:x.bank_account_number||"",npwp:clean(pay.npwp),tax_status:clean(pay.tax_status),bpjs_health:clean(pay.bpjs_health),bpjs_employment:clean(pay.bpjs_employment)});setModal(true)}
 function pickSubject(x:Subject){setSubId(x.id);setSubName(x.name);setSubCode(x.code||"");setModal(true)}
 function pickAssignment(x:A){setAssignId(x.id);setTeacher(x.teacher_id);setClassId(x.class_id);setSubjectId(x.subject_id||"");setMode(x.mode);setModal(true)}
 function importType(){return view==="students"?"students":view==="classes"?"classes":view==="teachers"?"teachers":view==="staff"?"staff":view==="subjects"?"subjects":"assignments"}

 async function saveCurrent(){
  if(view==="students")return run(async()=>{await rpc("sc_master_save_student_profile",{p_school:schoolId,p_id:sid,p_payload:{name:sName,nickname,nis,nisn,gender,birth_date:birthDate,address:studentAddress,phone:studentPhone,parent_phone:parentPhone,class_id:sClass,status:sStatus,guardian_name:guardian,guardian_phone:guardianPhone}});resetStudent();setModal(false)});
  if(view==="classes")return run(async()=>{await rpc("sc_master_save_class",{p_school:schoolId,p_id:cid,p_name:cName,p_grade:grade,p_year:year});resetClass();setModal(false)});
  if(view==="teachers"||view==="staff")return run(async()=>{await rpc("sc_master_save_staff_full",{p_school:schoolId,p_id:staffId,p_name:staffName,p_position:position,p_shift:shift,p_tolerance:Number(tolerance),p_staff_type:view==="teachers"?"teacher":"education_staff",p_profile:{employee_code:staffExtra.employee_code,email:staffExtra.email,phone:staffExtra.phone,department:staffExtra.department,rank_name:staffExtra.rank_name,employment_type:staffExtra.employment_type,hire_date:staffExtra.hire_date,contract_end:staffExtra.contract_end,personal_data:{birth_place:staffExtra.birth_place,birth_date:staffExtra.birth_date,marital_status:staffExtra.marital_status,blood_type:staffExtra.blood_type,religion:staffExtra.religion,identity_number:staffExtra.identity_number,address:staffExtra.address,emergency_name:staffExtra.emergency_name,emergency_phone:staffExtra.emergency_phone,education_level:staffExtra.education_level,institution:staffExtra.institution,study_program:staffExtra.study_program},bank_name:staffExtra.bank_name,bank_account_name:staffExtra.bank_account_name,bank_account_number:staffExtra.bank_account_number,payroll_data:{npwp:staffExtra.npwp,tax_status:staffExtra.tax_status,bpjs_health:staffExtra.bpjs_health,bpjs_employment:staffExtra.bpjs_employment}}});resetStaff();setModal(false)});
  if(view==="subjects")return run(async()=>{await rpc("sc_master_save_subject",{p_school:schoolId,p_id:subId,p_name:subName,p_code:subCode});resetSubject();setModal(false)});
  if(view==="assignments")return run(async()=>{await rpc("sc_master_save_assignment",{p_school:schoolId,p_id:assignId,p_teacher:teacher,p_class:classId,p_subject:subjectId||null,p_mode:mode});resetAssignment();setModal(false)});
 }

 async function template(){
  const type=importType(),guide=[{Kolom:"Panduan",Keterangan:"Jangan ubah nama kolom. Hapus baris contoh sebelum import data nyata. File Excel atau CSV dapat dibaca. Maksimal 500 baris."}];
  const rows=type==="students"?[{NIS:"1001",NISN:"0098765432",Nama:"Alya Putri",Nama_Panggilan:"Alya",Jenis_Kelamin:"P",Tanggal_Lahir:"2012-05-14",Alamat:"Malang",HP_Siswa:"081234567800",HP_Orang_Tua:"081234567890",Kelas:"VIII A",Tahun_Ajaran:"2026/2027",Nama_Wali:"Siti Aminah",WhatsApp_Wali:"081234567890"}]:
   type==="classes"?[{Nama_Kelas:"VIII A",Jenjang:"SMP 8",Tahun_Ajaran:"2026/2027"}]:
   type==="teachers"||type==="staff"?[{ID_Pegawai:type==="teachers"?"G-001":"T-001",Nama:type==="teachers"?"Budi Santoso":"Rina Setiawati",Email:"nama@sekolah.id",Telepon:"081234567890",Organisasi:"Kurikulum",Jabatan:type==="teachers"?"Guru Matematika":"Tenaga Administrasi",Pangkat:"",Status_Kerja:"Tetap",Tanggal_Bergabung:"2026-07-01",Jam_Masuk:"07:00",Toleransi_Terlambat_Menit:15,Tempat_Lahir:"Malang",Tanggal_Lahir:"1990-01-01",Jenis_Kelamin:"Laki-laki",Agama:"Islam",Pendidikan:"S1",Institusi:"Universitas",Program_Studi:"Pendidikan",Bank:"BRI",Nama_Rekening:"Budi Santoso",Nomor_Rekening:"1234567890"}]:
   type==="subjects"?[{Kode:"MTK",Nama:"Matematika"}]:
   [{Email_Akun:"guru@sekolah.id",Kelas:"VIII A",Mata_Pelajaran:"Matematika",Jenis:"subject"}];
  await downloadExcel("template-"+type+"-school-control.xlsx",[{name:"Data",rows},{name:"Panduan",rows:guide}])
 }
 async function allTemplate(){const guide=[{Bagian:"Cara pakai",Keterangan:"Isi sheet yang diperlukan saja. Sheet kosong dilewati. Bisa memakai workbook Excel; untuk satu jenis data juga dapat CSV."}];await downloadExcel("template-data-induk-lengkap-school-control.xlsx",[
  {name:"Siswa",rows:[{NIS:"1001",NISN:"0098765432",Nama:"Alya Putri",Nama_Panggilan:"Alya",Jenis_Kelamin:"P",Tanggal_Lahir:"2012-05-14",Alamat:"Malang",HP_Siswa:"081234567800",HP_Orang_Tua:"081234567890",Kelas:"VIII A",Tahun_Ajaran:"2026/2027",Nama_Wali:"Siti Aminah",WhatsApp_Wali:"081234567890"}]},
  {name:"Kelas",rows:[{Nama_Kelas:"VIII A",Jenjang:"SMP 8",Tahun_Ajaran:"2026/2027"}]},
  {name:"Guru",rows:[{ID_Pegawai:"G-001",Nama:"Budi Santoso",Email:"guru@sekolah.id",Telepon:"081234567890",Organisasi:"Kurikulum",Jabatan:"Guru Matematika",Status_Kerja:"Tetap",Tanggal_Bergabung:"2026-07-01",Jam_Masuk:"07:00",Toleransi_Terlambat_Menit:15}]},
  {name:"Tenaga_Pendidik",rows:[{ID_Pegawai:"T-001",Nama:"Rina Setiawati",Email:"staf@sekolah.id",Telepon:"081234567890",Organisasi:"Tata Usaha",Jabatan:"Tenaga Administrasi",Status_Kerja:"Tetap",Tanggal_Bergabung:"2026-07-01",Jam_Masuk:"07:00",Toleransi_Terlambat_Menit:15}]},
  {name:"Mata_Pelajaran",rows:[{Kode:"MTK",Nama:"Matematika"}]},
  {name:"Penugasan_Guru",rows:[{Email_Akun:"guru@sekolah.id",Kelas:"VIII A",Mata_Pelajaran:"Matematika",Jenis:"subject"}]},
  {name:"Panduan",rows:guide}
 ])}
 async function readOne(file?:File){if(!file)return;setError("");try{if(file.size>8_000_000)throw Error("File maksimal 8 MB");const rows=await readExcel(file);if(rows.length>500)throw Error("Maksimal 500 baris");setImportRows(rows);setImportFile(file.name)}catch(e){setError(e instanceof Error?e.message:String(e));setImportRows([])}}
 async function readAll(file?:File){if(!file)return;setError("");try{if(file.size>12_000_000)throw Error("File maksimal 12 MB");const wb=await readWorkbook(file);for(const rows of Object.values(wb))if(rows.length>500)throw Error("Maksimal 500 baris per sheet");setWorkbook(wb);setImportFile(file.name)}catch(e){setError(e instanceof Error?e.message:String(e));setWorkbook({})}}
 async function importAssignments(rows:SheetRows){if(!db)return;const dir=await db.rpc("sc_team_directory",{p_school:schoolId});if(dir.error)throw dir.error;const people=(dir.data||[]) as Member[];const cl=await db.from("sc_classes").select("id,name").eq("school_id",schoolId);const su=await db.from("sc_subjects").select("id,name").eq("school_id",schoolId);for(const r of rows){const email=clean(r.Email_Akun).toLowerCase(),cn=clean(r.Kelas).toLowerCase(),sn=clean(r.Mata_Pelajaran).toLowerCase(),m=clean(r.Jenis)||"subject";if(!email||!cn)continue;const person=people.find(x=>(x.email||"").toLowerCase()===email),klass=(cl.data||[]).find(x=>x.name.toLowerCase()===cn),subject=(su.data||[]).find(x=>x.name.toLowerCase()===sn);if(person&&klass)await rpc("sc_master_save_assignment",{p_school:schoolId,p_id:null,p_teacher:person.user_id,p_class:klass.id,p_subject:subject?.id||null,p_mode:m})}}
 const staffRows=(rows:SheetRows)=>rows.map(r=>({name:clean(r.Nama),employee_code:clean(r.ID_Pegawai),email:clean(r.Email),phone:clean(r.Telepon),department:clean(r.Organisasi),position:clean(r.Jabatan),rank_name:clean(r.Pangkat),employment_type:clean(r.Status_Kerja),hire_date:clean(r.Tanggal_Bergabung),contract_end:clean(r.Tanggal_Akhir_Kerja),shift_start:clean(r.Jam_Masuk),late_tolerance_minutes:Number(r.Toleransi_Terlambat_Menit||15),bank_name:clean(r.Bank),bank_account_name:clean(r.Nama_Rekening),bank_account_number:clean(r.Nomor_Rekening),personal_data:{birth_place:clean(r.Tempat_Lahir),birth_date:clean(r.Tanggal_Lahir),gender:clean(r.Jenis_Kelamin),religion:clean(r.Agama),education_level:clean(r.Pendidikan),institution:clean(r.Institusi),study_program:clean(r.Program_Studi)}}));
 const studentRows=(rows:SheetRows)=>rows.map(r=>({nis:clean(r.NIS),nisn:clean(r.NISN),name:clean(r.Nama),nickname:clean(r.Nama_Panggilan),gender:clean(r.Jenis_Kelamin),birth_date:clean(r.Tanggal_Lahir),address:clean(r.Alamat),phone:clean(r.HP_Siswa),parent_phone:clean(r.HP_Orang_Tua),class_name:clean(r.Kelas),academic_year:clean(r.Tahun_Ajaran),guardian_name:clean(r.Nama_Wali),guardian_phone:clean(r.WhatsApp_Wali)}));
 async function commitOne(){const type=importType();await run(async()=>{if(!importRows.length)return;if(type==="students")await rpc("sc_import_students_profile",{p_school:schoolId,p_rows:studentRows(importRows)});else if(type==="classes")await rpc("sc_import_classes",{p_school:schoolId,p_rows:importRows.map(r=>({name:clean(r.Nama_Kelas),grade:clean(r.Jenjang),academic_year:clean(r.Tahun_Ajaran)}))});else if(type==="teachers"||type==="staff")await rpc("sc_import_staff_full",{p_school:schoolId,p_rows:staffRows(importRows),p_staff_type:type==="teachers"?"teacher":"education_staff"});else if(type==="subjects")await rpc("sc_import_subjects",{p_school:schoolId,p_rows:importRows.map(r=>({code:clean(r.Kode),name:clean(r.Nama)}))});else await importAssignments(importRows);setImportRows([]);setImportFile("")})}
 async function commitAll(){await run(async()=>{const by=(...names:string[])=>{for(const n of names)if(workbook[n])return workbook[n];return [] as SheetRows};const classRows=by("Kelas"),teacherRows=by("Guru"),otherStaffRows=by("Tenaga_Pendidik","Tenaga Pendidik"),subjectRows=by("Mata_Pelajaran","Mata Pelajaran"),studentData=by("Siswa"),assignmentRows=by("Penugasan_Guru","Penugasan Guru");if(classRows.length)await rpc("sc_import_classes",{p_school:schoolId,p_rows:classRows.map(r=>({name:clean(r.Nama_Kelas),grade:clean(r.Jenjang),academic_year:clean(r.Tahun_Ajaran)}))});if(teacherRows.length)await rpc("sc_import_staff_full",{p_school:schoolId,p_rows:staffRows(teacherRows),p_staff_type:"teacher"});if(otherStaffRows.length)await rpc("sc_import_staff_full",{p_school:schoolId,p_rows:staffRows(otherStaffRows),p_staff_type:"education_staff"});if(subjectRows.length)await rpc("sc_import_subjects",{p_school:schoolId,p_rows:subjectRows.map(r=>({code:clean(r.Kode),name:clean(r.Nama)}))});if(studentData.length)await rpc("sc_import_students_profile",{p_school:schoolId,p_rows:studentRows(studentData)});if(assignmentRows.length)await importAssignments(assignmentRows);setWorkbook({});setImportFile("")})}
 async function exportCurrent(){if(view==="students")return downloadExcel("siswa-school-control.xlsx",[{name:"Siswa",rows:students.map(s=>({NIS:s.nis||"",NISN:s.nisn||"",Nama:s.name,Nama_Panggilan:s.nickname||"",Jenis_Kelamin:s.gender||"",Tanggal_Lahir:s.birth_date||"",Alamat:s.address||"",HP_Siswa:s.phone||"",HP_Orang_Tua:s.parent_phone||"",Kelas:className(s.class_id),Nama_Wali:contact(s.id)?.guardian_name||"",WhatsApp_Wali:contact(s.id)?.guardian_phone||"",Status:s.status}))}]);if(view==="classes")return downloadExcel("kelas-school-control.xlsx",[{name:"Kelas",rows:classes.map(c=>({Nama_Kelas:c.name,Jenjang:c.grade||"",Tahun_Ajaran:c.academic_year}))}]);if(view==="teachers"||view==="staff")return downloadExcel((view==="teachers"?"guru":"tenaga-pendidik")+"-school-control.xlsx",[{name:view==="teachers"?"Guru":"Tenaga_Pendidik",rows:visibleStaff.map(s=>({ID_Pegawai:s.employee_code||"",Nama:s.name,Email:s.email||"",Telepon:s.phone||"",Organisasi:s.department||"",Jabatan:s.position||"",Pangkat:s.rank_name||"",Status_Kerja:s.employment_type||"",Tanggal_Bergabung:s.hire_date||"",Jam_Masuk:s.shift_start,Toleransi_Terlambat_Menit:s.late_tolerance_minutes}))}]);if(view==="subjects")return downloadExcel("mata-pelajaran-school-control.xlsx",[{name:"Mata_Pelajaran",rows:subjects.map(s=>({Kode:s.code||"",Nama:s.name}))}]);if(view==="assignments")return downloadExcel("penugasan-guru-school-control.xlsx",[{name:"Penugasan_Guru",rows:assignments.map(a=>({Guru:memberName(a.teacher_id),Kelas:className(a.class_id),Mata_Pelajaran:subjectName(a.subject_id),Jenis:a.mode}))}])}

 const title=view==="students"?"Siswa":view==="classes"?"Kelas":view==="teachers"?"Guru":view==="staff"?"Tenaga Kependidikan":view==="subjects"?"Mata Pelajaran":"Penugasan Guru";
 const ImportBox=()=>view==="all"?<section className="panel"><div className="sectionhead"><div><h2>Import Excel Keseluruhan</h2><p className="muted">Satu workbook untuk semua Data Induk. Sheet kosong dilewati.</p></div><FileSpreadsheet size={22}/></div><div className="flow"><button className="button secondary" onClick={()=>void allTemplate()}><Download size={15}/> Template Lengkap</button><label className="button secondary"><Upload size={15}/> Pilih Workbook<input hidden type="file" accept=".xlsx,.xls" onChange={e=>void readAll(e.currentTarget.files?.[0])}/></label></div>{Object.keys(workbook).length>0&&<div className="import-summary"><strong>{importFile}</strong>{Object.entries(workbook).filter(([n])=>n!=="Panduan").map(([n,r])=><span key={n}>{n}: {r.length} baris</span>)}<button className="button" disabled={busy} onClick={()=>void commitAll()}>Import Semua Sheet Berisi Data</button></div>}</section>:<section className="panel import-panel"><div className="sectionhead"><div><h2>Import / Export {title}</h2><p className="muted">Template mengikuti struktur data aplikasi asal. Excel dan CSV diterima untuk import per bagian.</p></div></div><div className="flow"><button className="button secondary" onClick={()=>void template()}><Download size={15}/> Template Excel</button><label className="button secondary"><Upload size={15}/> Pilih Excel / CSV<input hidden type="file" accept=".xlsx,.xls,.csv,text/csv" onChange={e=>void readOne(e.currentTarget.files?.[0])}/></label><button className="button secondary" onClick={()=>void exportCurrent()}><Download size={15}/> Export Data</button></div>{importRows.length>0&&<div className="import-summary"><strong>{importFile} · {importRows.length} baris</strong><small>{importRows.slice(0,3).map(x=>Object.values(x).slice(0,6).join(" | ")).join(" / ")}</small><button className="button" disabled={busy} onClick={()=>void commitOne()}>Konfirmasi Import</button></div>}</section>;

 if(!admin)return <section className="panel"><h2>Data Induk</h2><p className="muted">Peran Anda hanya dapat membaca data yang diperlukan. Perubahan dilakukan manajemen sekolah.</p></section>;
 return <>
  {view!=="all"&&<section className="panel"><div className="sectionhead"><div><h2>Data {title}</h2><p className="muted">Form tambah/edit dipindahkan ke popup supaya daftar data tetap bersih dan mudah dibaca.</p></div><button className="button" onClick={openNew}><Plus size={15}/> Tambah {title}</button></div>
   {view==="students"&&<div className="tablewrap"><table className="data-table"><thead><tr><th>Nama</th><th>NIS/NISN</th><th>Kelas</th><th>Wali</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.nis||"—"} / {s.nisn||"—"}</td><td>{className(s.class_id)}</td><td>{contact(s.id)?.guardian_name||"—"}<small>{contact(s.id)?.guardian_phone?" · "+contact(s.id)?.guardian_phone:""}</small></td><td><span className="pill">{s.status}</span></td><td><div className="flow"><button className="button secondary" onClick={()=>pickStudent(s)}>Edit</button>{s.status==="active"?<button className="button secondary" onClick={()=>void run(()=>rpc("sc_master_save_student_full",{p_school:schoolId,p_id:s.id,p_name:s.name,p_nis:s.nis||"",p_nisn:s.nisn||"",p_gender:s.gender||"",p_class:s.class_id,p_status:"archived",p_guardian_name:contact(s.id)?.guardian_name||"",p_guardian_phone:contact(s.id)?.guardian_phone||""}).then(()=>{}))}>Arsipkan</button>:<><button className="button secondary" onClick={()=>void run(()=>rpc("sc_master_save_student_full",{p_school:schoolId,p_id:s.id,p_name:s.name,p_nis:s.nis||"",p_nisn:s.nisn||"",p_gender:s.gender||"",p_class:s.class_id,p_status:"active",p_guardian_name:contact(s.id)?.guardian_name||"",p_guardian_phone:contact(s.id)?.guardian_phone||""}).then(()=>{}))}>Pulihkan</button><button className="button danger" onClick={()=>void remove("student",s.id)}>Hapus Permanen</button></>}</div></td></tr>)}</tbody></table></div>}
   {view==="classes"&&classes.map(x=><div className="entry" key={x.id}><div><strong>{x.name}</strong><small>{x.grade||"—"} · {x.academic_year}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickClass(x)}>Edit</button><button className="button danger" onClick={()=>void remove("class",x.id)}>Hapus</button></div></div>)}
   {(view==="teachers"||view==="staff")&&visibleStaff.map(x=><div className="entry" key={x.id}><div><strong>{x.name}</strong><small>{[x.employee_code,x.department,x.position].filter(Boolean).join(" · ")||"Data kepegawaian belum lengkap"}</small><small>{x.email||x.phone||""}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickStaff(x)}>Edit</button>{!x.user_id&&<button className="button danger" onClick={()=>void remove("staff",x.id)}>Hapus</button>}</div></div>)}
   {view==="subjects"&&subjects.map(x=><div className="entry" key={x.id}><div><strong>{x.name}</strong><small>{x.code||"Tanpa kode"}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickSubject(x)}>Edit</button><button className="button danger" onClick={()=>void remove("subject",x.id)}>Hapus</button></div></div>)}
   {view==="assignments"&&assignments.map(x=><div className="entry" key={x.id}><div><strong>{memberName(x.teacher_id)} · {className(x.class_id)}</strong><small>{x.mode} · {subjectName(x.subject_id)}</small></div><div className="flow"><button className="button secondary" onClick={()=>pickAssignment(x)}>Edit</button><button className="button danger" onClick={()=>void remove("assignment",x.id)}>Hapus</button></div></div>)}
  </section>}
  <ImportBox/>
  <DataEntryModal open={modal} onClose={()=>setModal(false)} title={(sid||cid||staffId||subId||assignId?"Edit ":"Tambah ")+title} subtitle="Isi data selengkap mungkin. Field yang relevan akan dipakai lintas modul School Control." wide={view==="teachers"||view==="staff"}>
   {view==="students"&&<div className="fields"><label className="field">Nama lengkap<input value={sName} onChange={e=>setSName(e.target.value)} autoFocus required/></label><label className="field">Nama panggilan<input value={nickname} onChange={e=>setNickname(e.target.value)}/></label><label className="field">NIS<input value={nis} onChange={e=>setNis(e.target.value)}/></label><label className="field">NISN<input value={nisn} onChange={e=>setNisn(e.target.value)}/></label><label className="field">Jenis Kelamin<select value={gender} onChange={e=>setGender(e.target.value)}><option value="">Pilih</option><option value="L">Laki-laki</option><option value="P">Perempuan</option></select></label><label className="field">Tanggal lahir<input type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)}/></label><label className="field full">Alamat<input value={studentAddress} onChange={e=>setStudentAddress(e.target.value)}/></label><label className="field">HP siswa<input value={studentPhone} onChange={e=>setStudentPhone(e.target.value)}/></label><label className="field">HP orang tua<input value={parentPhone} onChange={e=>setParentPhone(e.target.value)}/></label><label className="field">Kelas<select value={sClass} onChange={e=>setSClass(e.target.value)}><option value="">Tanpa kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field">Status<select value={sStatus} onChange={e=>setSStatus(e.target.value)}><option value="active">Aktif</option><option value="archived">Arsip</option></select></label><label className="field">Nama orang tua / wali<input value={guardian} onChange={e=>setGuardian(e.target.value)}/></label><label className="field">WhatsApp wali<input value={guardianPhone} onChange={e=>setGuardianPhone(e.target.value)} placeholder="081234567890"/></label></div>}
   {view==="classes"&&<div className="fields"><label className="field">Nama Kelas<input value={cName} onChange={e=>setCName(e.target.value)} autoFocus/></label><label className="field">Jenjang<input value={grade} onChange={e=>setGrade(e.target.value)} placeholder="SD 6 / SMP 8 / SMA 11"/></label><label className="field">Tahun Ajaran<input value={year} onChange={e=>setYear(e.target.value)}/></label></div>}
   {(view==="teachers"||view==="staff")&&<><div className="modal-section"><h3>Identitas & Kontak</h3><div className="fields"><label className="field">ID Pegawai<input value={staffExtra.employee_code} onChange={e=>setExtra("employee_code",e.target.value)}/></label><label className="field">Nama lengkap<input value={staffName} onChange={e=>setStaffName(e.target.value)} autoFocus/></label><label className="field">Email<input type="email" value={staffExtra.email} onChange={e=>setExtra("email",e.target.value)}/></label><label className="field">Nomor ponsel<input value={staffExtra.phone} onChange={e=>setExtra("phone",e.target.value)}/></label></div></div>
    <div className="modal-section"><h3>Kepegawaian</h3><div className="fields"><label className="field">Organisasi / Unit<input value={staffExtra.department} onChange={e=>setExtra("department",e.target.value)}/></label><label className="field">Jabatan<input value={position} onChange={e=>setPosition(e.target.value)}/></label><label className="field">Pangkat<input value={staffExtra.rank_name} onChange={e=>setExtra("rank_name",e.target.value)}/></label><label className="field">Status kerja<select value={staffExtra.employment_type} onChange={e=>setExtra("employment_type",e.target.value)}>{["Tetap","Kontrak","PKWT","Harian","Magang","Mitra"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Tanggal bergabung<input type="date" value={staffExtra.hire_date} onChange={e=>setExtra("hire_date",e.target.value)}/></label><label className="field">Tanggal akhir kerja<input type="date" value={staffExtra.contract_end} onChange={e=>setExtra("contract_end",e.target.value)}/></label><label className="field">Jam masuk<input type="time" value={shift} onChange={e=>setShift(e.target.value)}/></label><label className="field">Toleransi terlambat (menit)<input type="number" min={0} max={240} value={tolerance} onChange={e=>setTolerance(e.target.value)}/></label></div></div>
    <div className="modal-section"><h3>Data Personal</h3><div className="fields"><label className="field">Tempat lahir<input value={staffExtra.birth_place} onChange={e=>setExtra("birth_place",e.target.value)}/></label><label className="field">Tanggal lahir<input type="date" value={staffExtra.birth_date} onChange={e=>setExtra("birth_date",e.target.value)}/></label><label className="field">Status perkawinan<input value={staffExtra.marital_status} onChange={e=>setExtra("marital_status",e.target.value)}/></label><label className="field">Golongan darah<input value={staffExtra.blood_type} onChange={e=>setExtra("blood_type",e.target.value)}/></label><label className="field">Agama<input value={staffExtra.religion} onChange={e=>setExtra("religion",e.target.value)}/></label><label className="field">Nomor identitas<input value={staffExtra.identity_number} onChange={e=>setExtra("identity_number",e.target.value)}/></label><label className="field full">Alamat<textarea value={staffExtra.address} onChange={e=>setExtra("address",e.target.value)}/></label><label className="field">Kontak darurat<input value={staffExtra.emergency_name} onChange={e=>setExtra("emergency_name",e.target.value)}/></label><label className="field">Nomor kontak darurat<input value={staffExtra.emergency_phone} onChange={e=>setExtra("emergency_phone",e.target.value)}/></label><label className="field">Pendidikan terakhir<input value={staffExtra.education_level} onChange={e=>setExtra("education_level",e.target.value)}/></label><label className="field">Institusi pendidikan<input value={staffExtra.institution} onChange={e=>setExtra("institution",e.target.value)}/></label><label className="field">Program studi<input value={staffExtra.study_program} onChange={e=>setExtra("study_program",e.target.value)}/></label></div></div>
    <div className="modal-section"><h3>Payroll & Rekening</h3><div className="fields"><label className="field">Bank<input value={staffExtra.bank_name} onChange={e=>setExtra("bank_name",e.target.value)}/></label><label className="field">Nama pemilik rekening<input value={staffExtra.bank_account_name} onChange={e=>setExtra("bank_account_name",e.target.value)}/></label><label className="field">Nomor rekening<input value={staffExtra.bank_account_number} onChange={e=>setExtra("bank_account_number",e.target.value)}/></label><label className="field">NPWP<input value={staffExtra.npwp} onChange={e=>setExtra("npwp",e.target.value)}/></label><label className="field">Status pajak<input value={staffExtra.tax_status} onChange={e=>setExtra("tax_status",e.target.value)}/></label><label className="field">BPJS Kesehatan<input value={staffExtra.bpjs_health} onChange={e=>setExtra("bpjs_health",e.target.value)}/></label><label className="field">BPJS Ketenagakerjaan<input value={staffExtra.bpjs_employment} onChange={e=>setExtra("bpjs_employment",e.target.value)}/></label></div></div></>}
   {view==="subjects"&&<div className="fields"><label className="field">Kode<input value={subCode} onChange={e=>setSubCode(e.target.value)}/></label><label className="field">Nama Mata Pelajaran<input value={subName} onChange={e=>setSubName(e.target.value)} autoFocus/></label></div>}
   {view==="assignments"&&<div className="fields"><label className="field">Guru<select value={teacher} onChange={e=>setTeacher(e.target.value)}><option value="">Pilih guru</option>{members.filter(m=>["owner","principal","vice_principal","teacher"].includes(m.role)).map(m=><option key={m.user_id} value={m.user_id}>{memberName(m.user_id)}</option>)}</select></label><label className="field">Kelas<select value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Pilih kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field">Mata Pelajaran<select value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Tanpa mapel</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field">Jenis<select value={mode} onChange={e=>setMode(e.target.value)}><option value="homeroom">Wali Kelas</option><option value="subject">Guru Mapel</option><option value="combined">Gabungan</option></select></label></div>}
   <div className="modal-actions"><button className="button secondary" type="button" onClick={()=>setModal(false)}>Batal</button><button className="button" type="button" disabled={busy||(view==="students"?!sName.trim():view==="classes"?!cName.trim():(view==="teachers"||view==="staff")?!staffName.trim():view==="subjects"?!subName.trim():!teacher||!classId)} onClick={()=>void saveCurrent()}>{busy?"Menyimpan…":"Simpan Data"}</button></div>
  </DataEntryModal>
  {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}
 </>;
}
