"use client";
import {useRealtimeRefresh} from "@/lib/school-realtime";
import SearchableSelect from "@/components/SearchableSelect";
import {errorMessage} from "@/lib/error-message";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {parseCsv,csvExport,saveCsv} from "@/lib/csv";
import {isAdmin,type Role} from "@/lib/modules";
type C={id:string;name:string;grade:string|null;academic_year:string};
type S={id:string;name:string;nis:string|null;class_id:string|null;status:string};
type M={user_id:string;role:string};
type Assignment={id:string;teacher_id:string;class_id:string;subject_id:string|null;mode:string};
type Subject={id:string;name:string};
export default function MasterAdvanced({schoolId,role}:{schoolId:string;role:Role}){
 const db=useMemo(()=>browserDb(),[]),admin=isAdmin(role);
 const [classes,setClasses]=useState<C[]>([]),[students,setStudents]=useState<S[]>([]),[members,setMembers]=useState<M[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]);
 const [selected,setSelected]=useState(""),[studentSelected,setStudentSelected]=useState(""),[name,setName]=useState(""),[studentName,setStudentName]=useState(""),[studentClass,setStudentClass]=useState(""),[studentStatus,setStudentStatus]=useState("active");
 const [preview,setPreview]=useState<{nis:string;name:string;class_name:string;academic_year:string}[]>([]),[fileName,setFileName]=useState("");
 const [subject,setSubject]=useState(""),[teacher,setTeacher]=useState(""),[classId,setClassId]=useState(""),[subjectId,setSubjectId]=useState(""),[assignMode,setAssignMode]=useState("subject");
 const [err,setErr]=useState(""),[ok,setOk]=useState(""),[busy,setBusy]=useState(false);
 useRealtimeRefresh(schoolId,()=>load());
 async function load(){if(!db)return;const [{data:c},{data:s},{data:m},{data:su},{data:a}]=await Promise.all([
 db.from("sc_classes").select("id,name,grade,academic_year").eq("school_id",schoolId).order("name"),
 db.from("sc_students").select("id,name,nis,class_id,status").eq("school_id",schoolId).order("name"),
 db.from("sc_members").select("user_id,role").eq("school_id",schoolId),
 db.from("sc_subjects").select("id,name").eq("school_id",schoolId).order("name"),
 db.from("sc_teacher_assignments").select("id,teacher_id,class_id,subject_id,mode").eq("school_id",schoolId)
 ]);setClasses((c||[]) as C[]);setStudents((s||[]) as S[]);setMembers((m||[]) as M[]);setSubjects((su||[]) as Subject[]);setAssignments((a||[]) as Assignment[])}
 useEffect(()=>{void load()},[db,schoolId]);
 async function job(fn:()=>Promise<void>){setBusy(true);setErr("");setOk("");try{await fn();await load();setOk("Perubahan berhasil tersimpan.")}catch(e){setErr(errorMessage(e))}finally{setBusy(false)}}
 async function call(name:string,params:Record<string,unknown>){if(!db)throw Error("Database belum terhubung.");const {data,error}=await db.rpc(name,params);if(error)throw error;return data}
 async function insert(table:string,row:Record<string,unknown>){if(!db)throw Error("Database belum terhubung.");const {error}=await db.from(table).insert({...row,school_id:schoolId});if(error)throw error}
 function pickClass(id:string){setSelected(id);setName(classes.find(c=>c.id===id)?.name||"")}
 function pickStudent(id:string){setStudentSelected(id);const s=students.find(s=>s.id===id);setStudentName(s?.name||"");setStudentClass(s?.class_id||"");setStudentStatus(s?.status||"active")}
 async function readFile(file?:File){if(!file)return;setErr("");try{if(file.size>2_000_000)throw Error("Ukuran CSV maksimal 2 MB.");const all=parseCsv(await file.text());const heads=(all.shift()||[]).map(s=>s.trim().toLowerCase());const required=["nis","nama","kelas","tahun_ajaran"];if(required.some(h=>!heads.includes(h)))throw Error("Header wajib: NIS,Nama,Kelas,Tahun_Ajaran");const rows=all.map(r=>({nis:r[heads.indexOf("nis")]?.trim()||"",name:r[heads.indexOf("nama")]?.trim()||"",class_name:r[heads.indexOf("kelas")]?.trim()||"",academic_year:r[heads.indexOf("tahun_ajaran")]?.trim()||""}));if(rows.length>500)throw Error("Maksimal 500 siswa per berkas.");if(rows.some(r=>!r.nis||!r.name||!r.class_name||!r.academic_year))throw Error("Ada kolom wajib yang belum diisi.");setPreview(rows);setFileName(file.name)}catch(e){setErr(errorMessage(e));setPreview([])}}
 const template=()=>saveCsv("template-import-siswa-sekolapro.csv",csvExport(["NIS","Nama","Kelas","Tahun_Ajaran"],[]));
 const exportData=()=>saveCsv("data-siswa-sekolapro.csv",csvExport(["NIS","Nama","Kelas","Tahun_Ajaran","Status"],students.map(s=>{const c=classes.find(c=>c.id===s.class_id);return[s.nis,s.name,c?.name,c?.academic_year,s.status]})));
 const notice=<>{err&&<p role="alert" className="banner error">{err}</p>}{ok&&<p role="status" className="banner success">{ok}</p>}</>;
 return <><section className="panel"><h2>Pembaruan kelas dan siswa</h2><p className="muted">Penggantian nama mempertahankan ID dan seluruh riwayat terkait. Arsip tidak menghapus data nilai, presensi, disiplin maupun BK.</p>{admin&&<div className="fields"><label className="field">Pilih kelas<SearchableSelect label="Pilih kelas" value={selected} onChange={e=>pickClass(e.target.value)}><option value="">Pilih</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.academic_year}</option>)}</SearchableSelect></label><label className="field">Nama kelas baru<input value={name} onChange={e=>setName(e.target.value)}/></label><button className="button secondary" disabled={busy||!selected||!name.trim()} onClick={()=>void job(async()=>{await call("sc_rename_class",{p_school:schoolId,p_class:selected,p_name:name.trim()});setSelected("")})}>Perbarui Kelas</button><div/><label className="field">Pilih siswa<SearchableSelect label="Pilih siswa" value={studentSelected} onChange={e=>pickStudent(e.target.value)}><option value="">Pilih</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} {s.status==="archived"?"(Arsip)":""}</option>)}</SearchableSelect></label><label className="field">Nama siswa<input value={studentName} onChange={e=>setStudentName(e.target.value)}/></label><label className="field">Kelas<SearchableSelect label="Kelas" value={studentClass} onChange={e=>setStudentClass(e.target.value)}><option value="">Tanpa kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.academic_year}</option>)}</SearchableSelect></label><label className="field">Status<SearchableSelect label="Status" value={studentStatus} onChange={e=>setStudentStatus(e.target.value)}><option value="active">Aktif</option><option value="archived">Arsip</option></SearchableSelect></label><button className="button secondary" disabled={busy||!studentSelected||studentName.trim().length<2} onClick={()=>void job(async()=>{await call("sc_update_student",{p_school:schoolId,p_student:studentSelected,p_name:studentName,p_class:studentClass||null,p_status:studentStatus});setStudentSelected("")})}>Simpan Perubahan Siswa</button></div>}{notice}</section>
 <section className="panel"><h2>Impor / ekspor data siswa</h2><p className="muted">Template CSV kompatibel Excel. Data yang diimpor adalah milik sekolah baru; tidak ada koneksi dengan database aplikasi lama. Pratinjau dilakukan sebelum disimpan.</p><div className="flow"><button className="button secondary" onClick={template}>Unduh Template</button><button className="button secondary" onClick={exportData}>Ekspor CSV</button>{admin&&<label className="button secondary" style={{display:"inline-block"}}>Pilih CSV<input type="file" accept=".csv,text/csv" onChange={e=>void readFile(e.currentTarget.files?.[0])} style={{display:"none"}}/></label>}</div>{preview.length>0&&<div className="banner"><strong>{fileName}: {preview.length} siswa</strong><p className="hint">Contoh: {preview.slice(0,3).map(x=>x.nis+" · "+x.name+" · "+x.class_name).join(" / ")}</p><button className="button" disabled={busy} onClick={()=>void job(async()=>{const result=await call("sc_import_students",{p_school:schoolId,p_rows:preview});setPreview([]);setOk("Impor selesai: "+result.added+" ditambahkan, "+result.skipped+" dilewati.")})}>Konfirmasi Impor</button></div>}</section>
 <section className="panel"><h2>Mapel & penugasan guru</h2><p className="muted">Satu guru dapat menjadi wali kelas, guru mapel, atau gabungan sesuai penugasan sekolah.</p>{admin&&<><div className="fields"><label className="field">Nama mata pelajaran<input value={subject} onChange={e=>setSubject(e.target.value)}/></label><button className="button secondary" disabled={busy||!subject.trim()} onClick={()=>void job(async()=>{await insert("sc_subjects",{name:subject.trim()});setSubject("")})}>Tambah Mapel</button></div><div className="fields" style={{marginTop:15}}><label className="field">Guru terdaftar<SearchableSelect label="Guru terdaftar" value={teacher} onChange={e=>setTeacher(e.target.value)}><option value="">Pilih guru</option>{members.filter(m=>["teacher","principal","vice_principal","owner"].includes(m.role)).map(m=><option key={m.user_id} value={m.user_id}>{m.user_id.slice(0,8)} · {m.role}</option>)}</SearchableSelect></label><label className="field">Kelas<SearchableSelect label="Kelas" value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Pilih kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} ({c.academic_year})</option>)}</SearchableSelect></label><label className="field">Mapel<SearchableSelect label="Mapel" value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Tanpa mapel</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</SearchableSelect></label><label className="field">Peran penugasan<SearchableSelect label="Peran penugasan" value={assignMode} onChange={e=>setAssignMode(e.target.value)}><option value="homeroom">Wali Kelas</option><option value="subject">Guru Mapel</option><option value="combined">Gabungan</option></SearchableSelect></label><button className="button" disabled={busy||!teacher||!classId} onClick={()=>void job(()=>insert("sc_teacher_assignments",{teacher_id:teacher,class_id:classId,subject_id:subjectId||null,mode:assignMode}))}>Tetapkan Guru</button></div></>}{assignments.map(a=><div className="entry" key={a.id}><div><strong>{classes.find(c=>c.id===a.class_id)?.name} · {a.mode}</strong><small>{members.find(m=>m.user_id===a.teacher_id)?.role||"guru"} · {subjects.find(s=>s.id===a.subject_id)?.name||"Umum"}</small></div></div>)}{!assignments.length&&<div className="empty">Belum ada penugasan.</div>}</section></>;
}
