"use client";
import {useEffect,useState} from "react";
import "./paywall.css";
import {LockKeyhole,CheckCircle2,ShieldCheck,RefreshCw,ArrowRight,CalendarClock} from "lucide-react";
type Plan={key:"monthly"|"yearly";label:string;price:number;days:number;caption:string};
type Plans={monthly:Plan;yearly:Plan};
const rupiah=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(v);
export default function PaymentWall({schoolName,trialEnd,status,owner,onCheckout,busy,onRefresh}:{schoolName:string;trialEnd:string;status:string;owner:boolean;onCheckout:(p:"monthly"|"yearly")=>void;busy:boolean;onRefresh:()=>void}){
 const [plans,setPlans]=useState<Plans|null>(null),[chosen,setChosen]=useState<"monthly"|"yearly">("monthly");
 useEffect(()=>{void fetch("/api/plans",{cache:"no-store"}).then(r=>r.json()).then(setPlans).catch(()=>{})},[]);
 return <main className="paywall"><div className="paywall-mark"><LockKeyhole size={28}/></div><span className="paywall-kicker">LANGGANAN SEKOLAPRO</span><h1>Masa akses sekolah<br/>telah berakhir.</h1><p>Uji coba 7 hari untuk <b>{schoolName}</b> selesai pada {new Date(trialEnd).toLocaleString("id-ID",{dateStyle:"long",timeStyle:"short"})}. Seluruh data tetap tersimpan. Aktifkan paket untuk melanjutkan pekerjaan.</p><div className="paywall-grid">{plans&&(["monthly","yearly"] as const).map(k=><button type="button" key={k} className={"paywall-option "+(chosen===k?"active":"")} onClick={()=>setChosen(k)}><div><b>{plans[k].label}</b><span>{plans[k].caption}</span></div><strong>{rupiah(plans[k].price)}</strong><span className="paywall-radio">{chosen===k?"●":"○"}</span></button>)}</div><div className="paywall-perks"><span><CheckCircle2 size={17}/> Semua modul dalam satu sekolah</span><span><ShieldCheck size={17}/> Data lama tidak dihapus</span><span><CalendarClock size={17}/> Masa aktif setelah pembayaran terverifikasi</span></div>{owner?<button className="paywall-pay" disabled={busy||!plans} onClick={()=>onCheckout(chosen)}>{busy?"Menghubungkan pembayaran…":"Lanjut ke Pembayaran"} <ArrowRight size={18}/></button>:<div className="paywall-info">Hanya pemilik akun utama sekolah yang dapat memperpanjang langganan. Hubungi pemilik workspace sekolah Anda.</div>}<button className="paywall-refresh" onClick={onRefresh}><RefreshCw size={16}/> Saya sudah membayar — cek status</button><small className="paywall-note">Status langganan ditentukan oleh database, bukan tanggal perangkat Anda. Pembayaran hanya aktif setelah konfirmasi aman dari penyedia pembayaran.</small></main>;
}
