"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {isAdmin,type Role,type Staff} from "@/lib/modules";
type Review={id:string;user_id:string;period:string;summary:string;status:string;response:string|null;created_at:string;updated_at:string};
const periodNow=()=>{const d=new Date();return d.toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"}).slice(0,7)};
export default function PerformanceReviews({schoolId,userId,role,staff,focus}:{schoolId:string;userId:string;role:Role;staff:Staff[];focus?:string}){
 const db=useMemo(()=>browserDb(),[]),manager=isAdmin(role)||role==="hr";
 const [rows,setRows]=useState<Review[]>([]),[selected,setSelected]=useState(""),[target,setTarget]=useState(""),[period,setPeriod]=useState(periodNow()),[summary,setSummary]=useState(""),[response,setResponse]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 async function load(){if(!db)return;const {data,error}=await db.from("sc_performance_reviews").select("id,user_id,period,summary,status,response,created_at,updated_at").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(100);if(error)setError(error.message);else setRows((data||[]) as Review[])}
 useEffect(()=>{void load()},[db,schoolId]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Evaluasi kinerja tersimpan.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function rpc(name:string,args:Record<string,unknown>){if(!db)throw Error("Database belum siap");const {data,error}=await db.rpc(name,args);if(error)throw error;return data}
 function pick(r:Review){setSelected(r.id);setTarget(r.user_id);setPeriod(r.period);setSummary(r.summary);setResponse(r.response||"")}
 function reset(){setSelected("");setTarget("");setPeriod(periodNow());setSummary("");setResponse("")}
 const name=(id:string)=>staff.find(s=>s.user_id===id)?.name||"Pegawai";
 const onlyResponses=(focus||"").toLowerCase().includes("tanggapan");
 return <>{manager&&!onlyResponses&&<section className="panel"><div className="sectionhead"><div><h2>Evaluasi Kinerja</h2><p className="muted">Evaluasi berbasis bukti. Guru mendapat ruang membaca dan memberi tanggapan sebelum finalisasi.</p></div><button className="button secondary" onClick={reset}>+ Evaluasi Baru</button></div><div className="fields"><label className="field">Pegawai<select value={target} onChange={e=>setTarget(e.target.value)} disabled={!!selected&&rows.find(x=>x.id===selected)?.status!=="draft"}><option value="">Pilih pegawai</option>{staff.filter(s=>s.user_id).map(s=><option key={s.id} value={s.user_id!}>{s.name}</option>)}</select></label><label className="field">Periode<input value={period} onChange={e=>setPeriod(e.target.value)} placeholder="2026-09"/></label><label className="field full">Ringkasan evaluasi<textarea rows={7} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Tuliskan bukti, capaian, area pengembangan, dan tindak lanjut tanpa penilaian otomatis."/></label></div><div className="flow" style={{marginTop:12}}><button className="button secondary" disabled={busy||!target||summary.trim().length<10} onClick={()=>void run(async()=>{const id=await rpc("sc_save_performance_review",{p_school:schoolId,p_id:selected||null,p_user:target,p_period:period,p_summary:summary,p_submit:false});setSelected(String(id))})}>Simpan Draft</button><button className="button" disabled={busy||!target||summary.trim().length<10} onClick={()=>void run(async()=>{await rpc("sc_save_performance_review",{p_school:schoolId,p_id:selected||null,p_user:target,p_period:period,p_summary:summary,p_submit:true});reset()})}>Ajukan ke Pegawai</button></div></section>}
 <section className="panel"><h2>{onlyResponses?"Tanggapan Guru":"Riwayat Evaluasi"}</h2>{rows.filter(r=>!onlyResponses||r.user_id===userId).map(r=><div className="entry" key={r.id}><div style={{flex:1}}><strong>{name(r.user_id)} · {r.period}</strong><small>Status {r.status}</small><p style={{margin:"7px 0",whiteSpace:"pre-wrap"}}>{r.summary}</p>{r.response&&<div className="banner"><b>Tanggapan:</b> {r.response}</div>}</div><div className="flow">{manager&&r.status==="draft"&&<><button className="button secondary" onClick={()=>pick(r)}>Edit</button><button className="button danger" onClick={()=>{if(confirm("Hapus draft evaluasi?"))void run(()=>rpc("sc_delete_performance_review",{p_school:schoolId,p_id:r.id}).then(()=>{}))}}>Hapus</button></>}{r.user_id===userId&&r.status==="review"&&<button className="button" onClick={()=>{const text=prompt("Tanggapan Anda terhadap evaluasi",r.response||"");if(text)void run(()=>rpc("sc_respond_performance_review",{p_school:schoolId,p_id:r.id,p_response:text}).then(()=>{}))}}>Beri Tanggapan</button>}{manager&&["review","responded"].includes(r.status)&&<button className="button" onClick={()=>void run(()=>rpc("sc_finalize_performance_review",{p_school:schoolId,p_id:r.id}).then(()=>{}))}>Finalkan</button>}</div></div>)}{!rows.length&&<div className="empty">Belum ada evaluasi kinerja.</div>}</section>
 {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
}
