"use client";
import SearchableSelect from "@/components/SearchableSelect";
import {downloadExcel,readExcel,type SheetRows} from "@/lib/excel";
import {errorMessage} from "@/lib/error-message";
import {useEffect,useMemo,useState} from "react";
import {Plus,Download,Upload} from "lucide-react";
import DataEntryModal from "@/components/DataEntryModal";
import {browserDb} from "@/lib/supabase";
import {isAdmin,type Role,type Staff} from "@/lib/modules";
type Review={id:string;user_id:string;period:string;summary:string;status:string;response:string|null;created_at:string;updated_at:string};
const periodNow=()=>{const d=new Date();return d.toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"}).slice(0,7)};
export default function PerformanceReviews({schoolId,userId,role,staff,focus}:{schoolId:string;userId:string;role:Role;staff:Staff[];focus?:string}){
 const db=useMemo(()=>browserDb(),[]),manager=isAdmin(role)||role==="hr";
 const [rows,setRows]=useState<Review[]>([]),[selected,setSelected]=useState(""),[target,setTarget]=useState(""),[period,setPeriod]=useState(periodNow()),[summary,setSummary]=useState(""),[response,setResponse]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState(""),[modal,setModal]=useState(false);
 async function load(){if(!db)return;const {data,error}=await db.from("sc_performance_reviews").select("id,user_id,period,summary,status,response,created_at,updated_at").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(100);if(error)setError(error.message);else setRows((data||[]) as Review[])}
 useEffect(()=>{void load()},[db,schoolId]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load();setOk("Evaluasi kinerja tersimpan.")}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function rpc(name:string,args:Record<string,unknown>){if(!db)throw Error("Database belum siap");const {data,error}=await db.rpc(name,args);if(error)throw error;return data}
 function pick(r:Review){setSelected(r.id);setTarget(r.user_id);setPeriod(r.period);setSummary(r.summary);setResponse(r.response||"");setModal(true)}
 function reset(open=false){setSelected("");setTarget("");setPeriod(periodNow());setSummary("");setResponse("");if(open)setModal(true)}
 const [responseFor,setResponseFor]=useState<Review|null>(null),[importRows,setImportRows]=useState<SheetRows>([]),[importFile,setImportFile]=useState(""),[importIssues,setImportIssues]=useState<{Baris:number;Kesalahan:string}[]>([]);
 useEffect(()=>{setImportRows([]);setImportIssues([]);setResponseFor(null)},[focus,schoolId]);
 const name=(id:string)=>staff.find(s=>s.user_id===id)?.name||"Pegawai";
 const onlyResponses=(focus||"").toLowerCase().includes("tanggapan");
 async function template(){await downloadExcel(onlyResponses?"template-tanggapan-evaluasi.xlsx":"template-evaluasi-draft.xlsx",[{name:"DATA",rows:onlyResponses?[{Evaluasi_ID:rows.find(r=>r.user_id===userId&&r.status==="review")?.id||"",Tanggapan:"Tanggapan berbasis bukti"}]:[{Evaluasi_ID:"",Pegawai_ID:staff.find(s=>s.user_id)?.id||"",Pegawai:"Nama pegawai",Periode:periodNow(),Ringkasan:"Capaian, bukti, pengembangan dan tindak lanjut"}]},{name:"Panduan",rows:[{Ketentuan:onlyResponses?"Isi Evaluasi_ID dari export. Hanya evaluasi milik Anda dengan status review dapat ditanggapi. Tanggapan minimal 3 karakter.":"Import hanya menyimpan draft; pengajuan dan finalisasi tetap melalui tombol aplikasi. Evaluasi_ID kosong untuk draft baru atau isi ID draft dari export untuk edit. Pegawai_ID dari Data Induk; nama harus unik bila ID kosong. Periode minimal 4 karakter; ringkasan minimal 10 karakter."}]}])}
 async function readImport(file?:File){if(!file)return;setError("");try{if(file.size>8000000)throw Error("File maksimal 8 MB.");const data=await readExcel(file);if(!data.length||data.length>2000)throw Error("Isi 1–2.000 baris data.");setImportRows(data);setImportFile(file.name);setImportIssues([])}catch(e){setError(errorMessage(e))}}
 async function commitImport(){if(!db||!importRows.length||(!manager&&!onlyResponses))return;setBusy(true);setError("");const issues:{Baris:number;Kesalahan:string}[]=[];let imported=0;try{for(const [index,row] of importRows.entries()){try{const id=String(row.Evaluasi_ID||"").trim();if(onlyResponses){const own=rows.find(r=>r.id===id&&r.user_id===userId&&r.status==="review");if(!own)throw Error("Evaluasi tidak tersedia untuk ditanggapi.");const text=String(row.Tanggapan||"").trim();if(text.length<3)throw Error("Tanggapan minimal 3 karakter.");await rpc("sc_respond_performance_review",{p_school:schoolId,p_id:id,p_response:text})}else {const staffId=String(row.Pegawai_ID||"").trim(),staffName=String(row.Pegawai||"").trim(),people=staff.filter(s=>s.user_id&&(staffId?s.id===staffId:s.name.trim().toLowerCase()===staffName.toLowerCase()));if(people.length!==1)throw Error("Pegawai tidak ditemukan atau nama ganda.");if(id&&!rows.some(r=>r.id===id&&r.status==="draft"))throw Error("ID harus menunjuk draft yang dapat diedit.");const period=String(row.Periode||"").trim(),summary=String(row.Ringkasan||"").trim();if(period.length<4||summary.length<10)throw Error("Periode atau ringkasan evaluasi belum lengkap.");await rpc("sc_save_performance_review",{p_school:schoolId,p_id:id||null,p_user:people[0].user_id,p_period:period,p_summary:summary,p_submit:false})}imported++}catch(e){issues.push({Baris:index+2,Kesalahan:errorMessage(e)})}}setImportIssues(issues);setImportRows([]);await load();setOk(imported+" baris tersimpan, "+issues.length+" gagal.")}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 const excelTools=<section className="panel"><div className="flow"><button className="button secondary" disabled={busy} onClick={()=>void template()}><Download size={14}/> Template Excel</button>{(manager||onlyResponses)&&role!=="viewer"&&<label className="button secondary"><Upload size={14}/> Import Excel<input type="file" hidden accept=".xlsx,.xls,.csv" onChange={e=>void readImport(e.target.files?.[0])}/></label>}<button className="button secondary" disabled={busy} onClick={()=>downloadExcel("evaluasi-kinerja.xlsx",[{name:"DATA",rows:rows.filter(r=>!onlyResponses||r.user_id===userId).map(r=>({Evaluasi_ID:r.id,Pegawai_ID:staff.find(s=>s.user_id===r.user_id)?.id||"",Pegawai:name(r.user_id),Periode:r.period,Ringkasan:r.summary,Status:r.status,Tanggapan:r.response||""}))}])}>Export data termuat</button>{importRows.length>0&&<><span>{importFile} · {importRows.length} baris</span><button className="button" disabled={busy} onClick={()=>void commitImport()}>Proses import</button><button className="button secondary" disabled={busy} onClick={()=>setImportRows([])}>Batal</button></>}{importIssues.length>0&&<button className="button secondary" onClick={()=>downloadExcel("kesalahan-import-evaluasi.xlsx",[{name:"Kesalahan",rows:importIssues}])}>Unduh {importIssues.length} kesalahan baris</button>}</div></section>;
 return <>{excelTools}{manager&&!onlyResponses&&<section className="panel"><div className="sectionhead"><div><h2>Evaluasi Kinerja</h2><p className="muted">Evaluasi berbasis bukti. Form evaluasi dibuka melalui popup agar daftar riwayat tetap fokus.</p></div><button className="button" onClick={()=>reset(true)}><Plus size={15}/> Evaluasi Baru</button></div></section>}
 <DataEntryModal open={modal} onClose={()=>setModal(false)} title={selected?"Edit Evaluasi Kinerja":"Evaluasi Kinerja Baru"} subtitle="Tuliskan bukti, capaian, area pengembangan, dan tindak lanjut tanpa penilaian otomatis." wide>
  <div className="fields"><label className="field">Pegawai<SearchableSelect label="Pegawai" value={target} onChange={e=>setTarget(e.target.value)} disabled={!!selected&&rows.find(x=>x.id===selected)?.status!=="draft"}><option value="">Pilih pegawai</option>{staff.filter(s=>s.user_id).map(s=><option key={s.id} value={s.user_id!}>{s.name}</option>)}</SearchableSelect></label><label className="field">Periode<input value={period} onChange={e=>setPeriod(e.target.value)} placeholder="2026-09"/></label><label className="field full">Ringkasan evaluasi<textarea rows={9} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Bukti, capaian, area pengembangan, dukungan yang dibutuhkan, dan rencana tindak lanjut."/></label></div>
  <div className="modal-actions"><button className="button secondary" onClick={()=>setModal(false)}>Batal</button><button className="button secondary" disabled={busy||!target||summary.trim().length<10} onClick={()=>void run(async()=>{const id=await rpc("sc_save_performance_review",{p_school:schoolId,p_id:selected||null,p_user:target,p_period:period,p_summary:summary,p_submit:false});setSelected(String(id));setModal(false)})}>Simpan Draft</button><button className="button" disabled={busy||!target||summary.trim().length<10} onClick={()=>void run(async()=>{await rpc("sc_save_performance_review",{p_school:schoolId,p_id:selected||null,p_user:target,p_period:period,p_summary:summary,p_submit:true});reset();setModal(false)})}>Ajukan ke Pegawai</button></div>
 </DataEntryModal> <section className="panel"><h2>{onlyResponses?"Tanggapan Guru":"Riwayat Evaluasi"}</h2>{rows.filter(r=>!onlyResponses||r.user_id===userId).map(r=><div className="entry" key={r.id}><div style={{flex:1}}><strong>{name(r.user_id)} · {r.period}</strong><small>Status {r.status}</small><p style={{margin:"7px 0",whiteSpace:"pre-wrap"}}>{r.summary}</p>{r.response&&<div className="banner"><b>Tanggapan:</b> {r.response}</div>}</div><div className="flow">{manager&&r.status==="draft"&&<><button className="button secondary" onClick={()=>pick(r)}>Edit</button><button className="button danger" onClick={()=>{if(confirm("Hapus draft evaluasi?"))void run(()=>rpc("sc_delete_performance_review",{p_school:schoolId,p_id:r.id}).then(()=>{}))}}>Hapus</button></>}{r.user_id===userId&&r.status==="review"&&<button className="button" onClick={()=>{setResponseFor(r);setResponse(r.response||"")}}>Beri Tanggapan</button>}{manager&&["review","responded"].includes(r.status)&&<button className="button" onClick={()=>void run(()=>rpc("sc_finalize_performance_review",{p_school:schoolId,p_id:r.id}).then(()=>{}))}>Finalkan</button>}</div></div>)}{!rows.length&&<div className="empty">Belum ada evaluasi kinerja.</div>}</section>
 <DataEntryModal open={Boolean(responseFor)} title="Tanggapan evaluasi" subtitle={responseFor?.period} onClose={()=>{if(!busy)setResponseFor(null)}}><label className="field full">Tanggapan Anda<textarea rows={6} value={response} onChange={e=>setResponse(e.target.value)}/></label><button className="button" disabled={busy||response.trim().length<3} onClick={()=>responseFor&&void run(async()=>{await rpc("sc_respond_performance_review",{p_school:schoolId,p_id:responseFor.id,p_response:response});setResponseFor(null)})}>Kirim tanggapan</button>{error&&<div className="banner error" role="alert">{error}</div>}</DataEntryModal>
 {error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
}
