"use client";
import {errorMessage} from "@/lib/error-message";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {browserDb} from "@/lib/supabase";
import {Activity,ArrowUpRight,Building2,CalendarClock,CheckCircle2,CreditCard,ExternalLink,LogOut,RefreshCw,Search,ShieldCheck,UsersRound,WalletCards} from "lucide-react";
import "./admin.css";
type Metrics={schools:number;test_schools:number;accounts:number;trial:number;active:number;expired:number;pending_orders:number;paid_orders:number;revenue_total:number;revenue_current_month:number;generated_at:string};
type SchoolRow={id:string;name:string;created_at:string;is_internal_test:boolean;subscription_status:string;trial_ends_at:string|null;current_period_end:string|null;member_count:number;student_count:number;paid_amount:number};
type Order={order_id:string;school_id:string;school_name:string;is_internal_test:boolean;gross_amount:number;period_days:number;status:string;created_at:string;paid_at:string|null};
type CountMap=Record<string,number>;
type SchoolDetail={
 school:Record<string,string|boolean|null>;subscription:Record<string,string|null>;owner:{email?:string;role?:string};
 roles:{role:string;count:number}[];core:CountMap;attendance:CountMap;academic:CountMap;student_affairs:CountMap;
 programs:CountMap;finance:CountMap;hr:CountMap;documents:CountMap;calendar:CountMap;ai:CountMap;payments:CountMap;
 recent_activity:{action:string;target_id:string|null;occurred_at:string}[];
};
const money=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v)||0);
const date=(s:string|null)=>s?new Date(s).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"}):"—";
const status=(s:SchoolRow)=>s.subscription_status==="trial"&&s.trial_ends_at&&Date.parse(s.trial_ends_at)<Date.now()?"expired":s.subscription_status==="active"&&s.current_period_end&&Date.parse(s.current_period_end)<Date.now()?"expired":s.subscription_status;
export default function PlatformAdmin(){
 const db=useMemo(()=>browserDb(),[]),router=useRouter();
 const [authorized,setAuthorized]=useState<boolean|null>(null),[metrics,setMetrics]=useState<Metrics|null>(null),[schools,setSchools]=useState<SchoolRow[]>([]),[orders,setOrders]=useState<Order[]>([]),[detail,setDetail]=useState<SchoolDetail|null>(null),[detailSchoolId,setDetailSchoolId]=useState(""),[detailLoading,setDetailLoading]=useState(false);
 const [tab,setTab]=useState<"overview"|"schools"|"orders">("overview"),[query,setQuery]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false),[email,setEmail]=useState("");
 useEffect(()=>{if(!db){setError("Konfigurasi database belum tersedia.");return}let active=true;(async()=>{const {data:{user}}=await db.auth.getUser();if(!active)return;if(!user){router.replace("/masuk");return}setEmail(user.email||"");const {data,error}=await db.rpc("sc_is_platform_admin");if(!active)return;if(error||data!==true){setAuthorized(false);return}setAuthorized(true)})();return()=>{active=false}},[db,router]);
 async function refresh(){if(!db||!authorized)return;setLoading(true);setError("");try{const [m,s,o]=await Promise.all([
 db.rpc("sc_platform_summary"),db.rpc("sc_platform_schools"),db.rpc("sc_platform_orders")
 ]);for(const r of [m,s,o])if(r.error)throw r.error;
 setMetrics(m.data as Metrics);setSchools((s.data||[]) as SchoolRow[]);setOrders((o.data||[]) as Order[]);
 }catch(e){setError(errorMessage(e))}finally{setLoading(false)}}
 useEffect(()=>{if(authorized)void refresh()},[authorized]);
 async function signOut(){await db?.auth.signOut();router.replace("/masuk")}
 async function openSchool(id:string){if(!db)return;setDetailSchoolId(id);setDetailLoading(true);setError("");try{const {data,error}=await db.rpc("sc_platform_school_detail",{p_school:id});if(error)throw error;setDetail(data as SchoolDetail)}catch(e){setError(errorMessage(e));setDetail(null)}finally{setDetailLoading(false)}}
 const filteredSchools=schools.filter(s=>(s.name+" "+s.id).toLowerCase().includes(query.toLowerCase()));
 const filteredOrders=orders.filter(o=>(o.order_id+" "+o.school_name).toLowerCase().includes(query.toLowerCase()));
 const labels:Record<string,string>={members:"Anggota",students:"Siswa",students_active:"Siswa aktif",students_archived:"Siswa arsip",classes:"Kelas",staff:"SDM",teachers:"Guru",today:"Presensi hari ini",present_30d:"Hadir 30 hari",late_30d:"Terlambat 30 hari",event_checkins_30d:"Check-in agenda 30 hari",grades:"Nilai",journals:"Jurnal mengajar",student_attendance:"Presensi siswa",ai_projects:"Proyek AI",ai_outputs:"Output AI",discipline_events:"Kejadian disiplin",discipline_open_actions:"Tindak lanjut disiplin terbuka",bk_cases:"Kasus BK",bk_records:"Catatan layanan BK",programs:"Program",tasks:"Tugas",tasks_open:"Tugas aktif",tasks_overdue:"Tugas terlambat",evidence:"Bukti kegiatan",transactions:"Transaksi",income:"Total pemasukan",expense:"Total pengeluaran",student_bills:"Tagihan siswa",bill_payments:"Pembayaran tagihan",requests:"Pengajuan SDM",requests_pending:"Pengajuan pending",payroll_records:"Record payroll",payroll_approved:"Payroll final",work_locations:"Lokasi kerja",documents:"Dokumen",reports:"Laporan terbit",imports:"Riwayat import",supervisions:"Supervisi",upcoming_31d:"Agenda 31 hari",attendance_required:"Agenda wajib presensi",total:"Total agenda",orders:"Order pembayaran",pending:"Order pending",paid:"Order lunas",paid_amount:"Nominal lunas"};
 const metricValue=(key:string,value:number)=>["income","expense","paid_amount"].includes(key)?money(value):new Intl.NumberFormat("id-ID").format(value);
 const DetailGroup=({title,data}:{title:string;data:CountMap})=><section className="platform-detail-group"><h3>{title}</h3><div className="platform-detail-grid">{Object.entries(data||{}).map(([k,v])=><div key={k}><small>{labels[k]||k.replaceAll("_"," ")}</small><strong>{metricValue(k,Number(v)||0)}</strong></div>)}</div></section>;
 if(authorized===null)return <main className="platform-loading">Memeriksa izin Super Admin…</main>;
 if(!authorized)return <main className="platform-loading"><ShieldCheck size={32}/><h2>Akses platform dibatasi</h2><p>Akun ini tidak mempunyai izin Super Admin.</p><Link href="/app">Kembali ke Workspace Sekolah</Link></main>;
 return <div className="platform-admin"><aside className="platform-aside"><Link href="/admin" className="platform-brand"><img src="/school-control-mark.svg" alt="" width={40} height={40}/><span><b>School Control</b><small>Platform Administration</small></span></Link><div className="platform-section-label">KONTROL PLATFORM</div><nav aria-label="Navigasi administrasi platform">{([["overview","Ringkasan",Activity],["schools","Sekolah & Langganan",Building2],["orders","Transaksi Pembayaran",CreditCard]] as const).map(([v,label,Icon])=><button key={v} className={tab===v?"selected":""} onClick={()=>{setTab(v);setQuery("")}}><Icon size={19}/>{label}</button>)}</nav><div className="platform-aside-bottom"><div className="platform-admin-pill"><ShieldCheck size={17}/><div><b>Super Admin</b><small>{email}</small></div></div><button className="platform-signout" onClick={()=>void signOut()}><LogOut size={17}/> Keluar</button></div></aside>
 <main className="platform-main"><header className="platform-head"><div><div className="platform-kicker">SUPER ADMIN / PLATFORM MONITORING</div><h1>{tab==="overview"?"Ringkasan Platform":tab==="schools"?"Sekolah & Langganan":"Riwayat Transaksi"}</h1><p>Monitoring menyeluruh tanpa membuka data konseling atau payroll pribadi pelanggan.</p></div><div className="platform-tools"><a href="https://vercel.com/hudbrother62-2859/school-control-pro" target="_blank" rel="noreferrer">Deployment <ExternalLink size={15}/></a><button onClick={()=>void refresh()} disabled={loading}><RefreshCw size={16}/> {loading?"Memperbarui…":"Segarkan"}</button></div></header>
 {error&&<div className="platform-error" role="alert">{error}</div>}
 {tab==="overview"&&<><div className="platform-metrics">{[
 ["Sekolah Terdaftar",metrics?.schools??"—",Building2],["Total Akun",metrics?.accounts??"—",UsersRound],["Trial Aktif",metrics?.trial??"—",CalendarClock],["Langganan Aktif",metrics?.active??"—",CheckCircle2],
 ["Trial/Langganan Berakhir",metrics?.expired??"—",Activity],["Menunggu Pembayaran",metrics?.pending_orders??"—",CreditCard]
 ].map(([title,value,Icon],index)=>{const I=Icon as typeof Building2;return <div className="platform-metric" key={String(title)}><div className="platform-metric-top"><small>{String(title)}</small><I size={19}/></div><strong>{String(value)}</strong><span>{index===0?"Tenant pelanggan aktif/nonaktif":index===1?"Akun platform dan sekolah":index===2?"Belum melewati 7 hari":index===3?"Pembayaran/masa aktif valid":index===4?"Berdasarkan masa berlaku server":"Pesanan berstatus pending"}</span></div>})}</div><div className="platform-revenue"><div><WalletCards size={25}/><span>Total pemasukan terverifikasi<strong>{money(metrics?.revenue_total||0)}</strong><small>Hanya transaksi gateway yang sudah terverifikasi dan berstatus paid.</small></span></div><div><span>PEMASUKAN BULAN INI</span><strong>{money(metrics?.revenue_current_month||0)}</strong><small>{metrics?.paid_orders||0} transaksi berhasil sepanjang waktu</small></div></div><div className="platform-panel"><div className="platform-panel-header"><div><h2>Sekolah Terbaru</h2><p>Status dan tanggal yang berasal dari database langsung.</p></div><button onClick={()=>setTab("schools")}>Lihat semua <ArrowUpRight size={16}/></button></div><div className="platform-table-wrap"><table><thead><tr><th>Sekolah</th><th>Anggota</th><th>Status</th><th>Masa Aktif</th></tr></thead><tbody>{schools.slice(0,7).map(s=><tr key={s.id}><td><b>{s.name}</b>{s.is_internal_test&&<small className="platform-demo">DEMO INTERNAL</small>}</td><td>{s.member_count}</td><td><span className={"platform-status "+status(s)}>{status(s)}</span></td><td>{date(s.current_period_end||s.trial_ends_at)}</td></tr>)}</tbody></table>{!schools.length&&<div className="platform-empty">Belum ada sekolah terdaftar.</div>}</div></div><p className="platform-updated">Data terakhir dimuat: {metrics?.generated_at?date(metrics.generated_at):"—"}. Angka berubah setelah halaman disegarkan.</p></>}
 {tab==="schools"&&<div className="platform-panel"><div className="platform-panel-header"><div><h2>Daftar Sekolah</h2><p>100 pendaftaran terbaru beserta status langganan dan ringkasan operasional.</p></div><div className="platform-search"><Search size={16}/><input aria-label="Cari sekolah" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari nama / ID sekolah"/></div></div><div className="platform-table-wrap"><table><thead><tr><th>Sekolah</th><th>Dibuat</th><th>Anggota</th><th>Siswa</th><th>Status</th><th>Berlaku Sampai</th><th>Pendapatan</th><th>Aksi</th></tr></thead><tbody>{filteredSchools.map(s=><tr key={s.id} className={detailSchoolId===s.id?"selected-row":""}><td><b>{s.name}</b>{s.is_internal_test&&<small className="platform-demo">INTERNAL</small>}<small>{s.id.slice(0,8)}</small></td><td>{date(s.created_at)}</td><td>{s.member_count}</td><td>{s.student_count}</td><td><span className={"platform-status "+status(s)}>{status(s)}</span></td><td>{date(s.current_period_end||s.trial_ends_at)}</td><td>{money(s.paid_amount)}</td><td><button onClick={()=>void openSchool(s.id)}>{detailLoading&&detailSchoolId===s.id?"Memuat…":"Detail"}</button></td></tr>)}</tbody></table>{!filteredSchools.length&&<div className="platform-empty">Tidak ada sekolah yang cocok.</div>}</div>
 {detail&&<div className="platform-school-detail">
  <div className="platform-panel-header"><div><div className="platform-kicker">DETAIL TENANT</div><h2>{String(detail.school?.name||"Sekolah")}</h2><p>{String(detail.school?.education_level||detail.school?.school_type||"Jenjang belum diisi")} · {String(detail.school?.city||"Lokasi belum diisi")} · Tahun {String(detail.school?.academic_year||"—")}</p></div><button onClick={()=>{setDetail(null);setDetailSchoolId("")}}>Tutup</button></div>
  <div className="platform-detail-identity"><div><small>Owner</small><strong>{detail.owner?.email||"—"}</strong></div><div><small>Langganan</small><strong>{String(detail.subscription?.status||"—")}</strong></div><div><small>Masa aktif</small><strong>{date(detail.subscription?.current_period_end||detail.subscription?.trial_ends_at||null)}</strong></div><div><small>Peran</small><strong>{(detail.roles||[]).map(x=>x.role+" "+x.count).join(" · ")||"—"}</strong></div></div>
  <DetailGroup title="Data inti" data={detail.core}/>
  <DetailGroup title="Presensi" data={detail.attendance}/>
  <DetailGroup title="Pembelajaran & AI" data={detail.academic}/>
  <DetailGroup title="Kesiswaan, Disiplin & BK" data={detail.student_affairs}/>
  <DetailGroup title="Program & Tugas" data={detail.programs}/>
  <DetailGroup title="Keuangan" data={detail.finance}/>
  <DetailGroup title="SDM & Payroll" data={detail.hr}/>
  <DetailGroup title="Dokumen, Laporan & Import" data={detail.documents}/>
  <DetailGroup title="Agenda" data={detail.calendar}/>
  <DetailGroup title="Pembayaran" data={detail.payments}/>
  <section className="platform-detail-group"><h3>Aktivitas audit terbaru</h3>{detail.recent_activity?.map((x,i)=><div className="platform-activity" key={i}><div><strong>{x.action}</strong><small>{x.target_id||"Tanpa target"}</small></div><time>{date(x.occurred_at)}</time></div>)}{!detail.recent_activity?.length&&<div className="platform-empty">Belum ada aktivitas audit pada sekolah ini.</div>}</section>
 </div>}
 </div>}
 {tab==="orders"&&<div className="platform-panel"><div className="platform-panel-header"><div><h2>Pesanan & Pembayaran</h2><p>Hanya callback terverifikasi dari gateway dapat mengubah status pembayaran.</p></div><div className="platform-search"><Search size={16}/><input aria-label="Cari pembayaran" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari order / sekolah"/></div></div><div className="platform-table-wrap"><table><thead><tr><th>Order ID</th><th>Sekolah</th><th>Waktu Pesan</th><th>Nominal</th><th>Durasi</th><th>Status</th><th>Waktu Lunas</th></tr></thead><tbody>{filteredOrders.map(o=><tr key={o.order_id}><td><b>{o.order_id}</b></td><td>{o.school_name}{o.is_internal_test&&<small className="platform-demo">DEMO</small>}</td><td>{date(o.created_at)}</td><td>{money(o.gross_amount)}</td><td>{o.period_days} hari</td><td><span className={"platform-status "+o.status}>{o.status}</span></td><td>{date(o.paid_at)}</td></tr>)}</tbody></table>{!filteredOrders.length&&<div className="platform-empty">Belum ada transaksi yang tercatat.</div>}</div></div>}
 </main></div>;
}
