"use client";
import DataEntryModal from "@/components/DataEntryModal";
import {ROLE_LABELS,type Role} from "@/lib/modules";
import SupportChat from "@/components/SupportChat";
import {useRealtimeRefresh} from "@/lib/school-realtime";
import {subscriptionTimeline} from "@/lib/subscription-timeline";
import {errorMessage} from "@/lib/error-message";
import {useEffect,useMemo,useRef,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {browserDb} from "@/lib/supabase";
import {Activity,ArrowUpRight,Building2,CalendarClock,CheckCircle2,CreditCard,ExternalLink,LogOut,RefreshCw,Search,ShieldCheck,MessageSquare,UsersRound,WalletCards} from "lucide-react";
import "./admin.css";
type Metrics={schools:number;test_schools:number;accounts:number;trial:number;active:number;expired:number;pending_orders:number;paid_orders:number;revenue_total:number;revenue_current_month:number;generated_at:string};
type SchoolRow={id:string;name:string;created_at:string;is_internal_test:boolean;subscription_status:string;trial_ends_at:string|null;current_period_end:string|null;member_count:number;student_count:number;paid_amount:number};
type Order={order_id:string;school_id:string;school_name:string;is_internal_test:boolean;gross_amount:number;period_days:number;status:string;created_at:string;paid_at:string|null};
type Account={school_id:string;user_id:string;school_name:string;account_name:string;email:string;role:string;registered_at:string;last_sign_in_at:string|null;email_confirmed_at:string|null;banned_until:string|null;member_since:string|null;unread:number;last_message_at:string|null};
type CountMap=Record<string,number>;
type SchoolDetail={
 school:Record<string,string|boolean|null>;subscription:Record<string,string|null>;owner:{email?:string;role?:string};
 roles:{role:string;count:number}[];core:CountMap;attendance:CountMap;academic:CountMap;student_affairs:CountMap;
 programs:CountMap;finance:CountMap;hr:CountMap;documents:CountMap;calendar:CountMap;ai:CountMap;payments:CountMap;
 recent_activity:{action:string;target_id:string|null;occurred_at:string}[];
};
const money=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v)||0);
const date=(s:string|null)=>s?new Date(s).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jakarta"}):"—";

const status=(s:SchoolRow)=>subscriptionTimeline(s).status;
export default function PlatformAdmin(){
 const db=useMemo(()=>browserDb(),[]),router=useRouter();
 const [authorized,setAuthorized]=useState<boolean|null>(null),[metrics,setMetrics]=useState<Metrics|null>(null),[schools,setSchools]=useState<SchoolRow[]>([]),[orders,setOrders]=useState<Order[]>([]),[detail,setDetail]=useState<SchoolDetail|null>(null),[detailSchoolId,setDetailSchoolId]=useState(""),[detailLoading,setDetailLoading]=useState(false);
 const [tab,setTab]=useState<"overview"|"schools"|"orders"|"support">("overview"),[query,setQuery]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(false),[email,setEmail]=useState("");
 useEffect(()=>{if(!db){setError("Konfigurasi database belum tersedia.");return}let active=true;(async()=>{const {data:{user}}=await db.auth.getUser();if(!active)return;if(!user){router.replace("/masuk");return}setEmail(user.email||"");const {data,error}=await db.rpc("sc_is_platform_admin");if(!active)return;if(error||data!==true){setAuthorized(false);return}setAuthorized(true)})();return()=>{active=false}},[db,router]);
 const detailRequest=useRef(0);
 const [customerStatus,setCustomerStatus]=useState("all"),[schoolPage,setSchoolPage]=useState(0);
 const [accounts,setAccounts]=useState<Account[]>([]),[now,setNow]=useState(Date.now());
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(t)},[]);
 useRealtimeRefresh(authorized?"*":"",async()=>{await refresh();if(detailSchoolId)await openSchool(detailSchoolId)});
 async function refresh(){if(!db||!authorized)return;setLoading(true);setError("");try{const permission=await db.rpc("sc_is_platform_admin");if(permission.error)throw permission.error;if(permission.data!==true){setAuthorized(false);setMetrics(null);setSchools([]);setOrders([]);setAccounts([]);setDetail(null);return;}const [m,s,o,a]=await Promise.all([
 db.rpc("sc_platform_summary"),db.rpc("sc_platform_schools"),db.rpc("sc_platform_orders"),db.rpc("sc_support_contacts",{p_school:null})
 ]);for(const r of [m,s,o,a])if(r.error)throw r.error;
 setAccounts((a.data||[]) as Account[]);setMetrics(m.data as Metrics);setSchools((s.data||[]) as SchoolRow[]);setOrders((o.data||[]) as Order[]);
 }catch(e){setError(errorMessage(e))}finally{setLoading(false)}}
 useEffect(()=>{if(authorized)void refresh()},[authorized,now]);
 async function signOut(){await db?.auth.signOut();router.replace("/masuk")}
 async function openSchool(id:string){if(!db)return;const seq=++detailRequest.current;setDetailSchoolId(id);setDetail(null);setDetailLoading(true);setError("");try{const {data,error}=await db.rpc("sc_platform_school_detail",{p_school:id});if(error)throw error;if(seq===detailRequest.current)setDetail(data as SchoolDetail)}catch(e){if(seq===detailRequest.current){setError(errorMessage(e));setDetail(null)}}finally{if(seq===detailRequest.current)setDetailLoading(false)}}
 const filteredSchools=schools.filter(s=>(customerStatus==="all"||status(s)===customerStatus)&&(s.name+" "+s.id).toLowerCase().includes(query.toLowerCase()));
 const filteredOrders=orders.filter(o=>(o.order_id+" "+o.school_name).toLowerCase().includes(query.toLowerCase()));
 const labels:Record<string,string>={members:"Anggota",students:"Siswa",students_active:"Siswa aktif",students_archived:"Siswa arsip",classes:"Kelas",staff:"SDM",teachers:"Guru",today:"Presensi hari ini",present_30d:"Hadir 30 hari",late_30d:"Terlambat 30 hari",event_checkins_30d:"Check-in agenda 30 hari",grades:"Nilai",journals:"Jurnal mengajar",student_attendance:"Presensi siswa",ai_projects:"Proyek AI",ai_outputs:"Output AI",discipline_events:"Kejadian disiplin",discipline_open_actions:"Tindak lanjut disiplin terbuka",bk_cases:"Kasus BK",bk_records:"Catatan layanan BK",programs:"Program",tasks:"Tugas",tasks_open:"Tugas aktif",tasks_overdue:"Tugas terlambat",evidence:"Bukti kegiatan",transactions:"Transaksi",income:"Total pemasukan",expense:"Total pengeluaran",student_bills:"Tagihan siswa",bill_payments:"Pembayaran tagihan",requests:"Pengajuan SDM",requests_pending:"Pengajuan pending",payroll_records:"Record payroll",payroll_approved:"Payroll final",work_locations:"Lokasi kerja",documents:"Dokumen",reports:"Laporan terbit",imports:"Riwayat import",supervisions:"Supervisi",upcoming_31d:"Agenda 31 hari",attendance_required:"Agenda wajib presensi",total:"Total agenda",orders:"Order pembayaran",pending:"Order pending",paid:"Order lunas",paid_amount:"Nominal lunas"};
 const identityLabels:Record<string,string>={id:"ID sekolah",npsn:"NPSN",address:"Alamat",phone:"Telepon",email:"Email",website:"Website",principal_name:"Kepala sekolah",accreditation:"Akreditasi",province:"Provinsi",city:"Kabupaten / kota",district:"Kecamatan",village:"Kelurahan / desa",postal_code:"Kode pos",semester:"Semester",created_at:"Terdaftar"};
 const metricValue=(key:string,value:number)=>["income","expense","paid_amount"].includes(key)?money(value):new Intl.NumberFormat("id-ID").format(value);
 const DetailGroup=({title,data}:{title:string;data:CountMap})=><section className="platform-detail-group"><h3>{title}</h3><div className="platform-detail-grid">{Object.entries(data||{}).map(([k,v])=><div key={k}><small>{labels[k]||k.replaceAll("_"," ")}</small><strong>{metricValue(k,Number(v)||0)}</strong></div>)}</div></section>;
 if(authorized===null)return <main className="platform-loading">Memeriksa izin Super Admin…</main>;
 if(!authorized)return <main className="platform-loading"><ShieldCheck size={32}/><h2>Akses platform dibatasi</h2><p>Akun ini tidak mempunyai izin Super Admin.</p><Link href="/app">Kembali ke Workspace Sekolah</Link></main>;
 return <div className="platform-admin"><aside className="platform-aside"><Link href="/admin" className="platform-brand"><img src="/sekola-pro-mark.svg" alt="" width={40} height={40}/><span><b>SekolaPro</b><small>Platform Administration</small></span></Link><div className="platform-section-label">KONTROL PLATFORM</div><nav aria-label="Navigasi administrasi platform">{([["overview","Ringkasan",Activity],["schools","Sekolah & Langganan",Building2],["orders","Transaksi Pembayaran",CreditCard],["support","Chat Pelanggan",MessageSquare]] as const).map(([v,label,Icon])=><button key={v} className={tab===v?"selected":""} onClick={()=>{setTab(v);setQuery("")}}><Icon size={19}/>{label}</button>)}</nav><div className="platform-aside-bottom"><div className="platform-admin-pill"><ShieldCheck size={17}/><div><b>Super Admin</b><small>{email}</small></div></div><button className="platform-signout" onClick={()=>void signOut()}><LogOut size={17}/> Keluar</button></div></aside>
 <main className="platform-main"><header className="platform-head"><div><div className="platform-kicker">SUPER ADMIN / PLATFORM MONITORING</div><h1>{tab==="overview"?"Ringkasan Platform":tab==="schools"?"Sekolah & Langganan":tab==="support"?"Chat Pelanggan":"Riwayat Transaksi"}</h1><p>Monitoring menyeluruh tanpa membuka data konseling atau payroll pribadi pelanggan.</p></div><div className="platform-tools"><a href="https://vercel.com/hudbrother62-2859/school-control-pro" target="_blank" rel="noreferrer">Deployment <ExternalLink size={15}/></a><button onClick={()=>void refresh()} disabled={loading}><RefreshCw size={16}/> {loading?"Memperbarui…":"Segarkan"}</button><SupportChat admin/></div></header>
 {error&&<div className="platform-error" role="alert">{error}</div>}
 {tab==="overview"&&<><div className="platform-metrics">{[
 ["Sekolah Terdaftar",metrics?.schools??"—",Building2],["Total Akun",metrics?.accounts??"—",UsersRound],["Trial Aktif",metrics?.trial??"—",CalendarClock],["Langganan Aktif",metrics?.active??"—",CheckCircle2],
 ["Trial/Langganan Berakhir",metrics?.expired??"—",Activity],["Menunggu Pembayaran",metrics?.pending_orders??"—",CreditCard]
 ].map(([title,value,Icon],index)=>{const I=Icon as typeof Building2;return <div className="platform-metric" key={String(title)}><div className="platform-metric-top"><small>{String(title)}</small><I size={19}/></div><strong>{String(value)}</strong><span>{index===0?"Tenant pelanggan aktif/nonaktif":index===1?"Akun platform dan sekolah":index===2?"Belum melewati 7 hari":index===3?"Pembayaran/masa aktif valid":index===4?"Berdasarkan masa berlaku server":"Pesanan berstatus pending"}</span></div>})}</div><div className="platform-revenue"><div><WalletCards size={25}/><span>Total pemasukan terverifikasi<strong>{money(metrics?.revenue_total||0)}</strong><small>Hanya transaksi gateway yang sudah terverifikasi dan berstatus paid.</small></span></div><div><span>PEMASUKAN BULAN INI</span><strong>{money(metrics?.revenue_current_month||0)}</strong><small>{metrics?.paid_orders||0} transaksi berhasil sepanjang waktu</small></div></div><div className="platform-panel"><div className="platform-panel-header"><div><h2>Sekolah Terbaru</h2><p>Status dan tanggal yang berasal dari database langsung.</p></div><button onClick={()=>setTab("schools")}>Lihat semua <ArrowUpRight size={16}/></button></div><div className="platform-table-wrap"><table><thead><tr><th>Sekolah</th><th>Anggota</th><th>Status</th><th>Masa Aktif</th></tr></thead><tbody>{schools.slice(0,7).map(s=><tr key={s.id}><td><b>{s.name}</b>{s.is_internal_test&&<small className="platform-demo">DEMO INTERNAL</small>}</td><td>{s.member_count}</td><td><span className={"platform-status "+status(s)}>{status(s)}</span></td><td>{date(s.current_period_end||s.trial_ends_at)}</td></tr>)}</tbody></table>{!schools.length&&<div className="platform-empty">Belum ada sekolah terdaftar.</div>}</div></div><p className="platform-updated">Data terakhir dimuat: {metrics?.generated_at?date(metrics.generated_at):"—"}. Perubahan data tersinkron otomatis.</p></>}
 {tab==="schools"&&<div className="platform-panel"><div className="platform-panel-header"><div><h2>Daftar Sekolah</h2><p>Seluruh sekolah beserta masa trial, tenggat perpanjangan, status nonaktif, dan detail akun.</p></div><div className="platform-search"><Search size={16}/><input aria-label="Cari sekolah" value={query} onChange={e=>{setQuery(e.target.value);setSchoolPage(0)}} placeholder="Cari nama / ID sekolah"/></div><select aria-label="Filter status pelanggan" value={customerStatus} onChange={e=>{setCustomerStatus(e.target.value);setSchoolPage(0)}}><option value="all">Semua status</option><option value="trial">Trial aktif</option><option value="active">Berlangganan aktif</option><option value="inactive">Nonaktif</option></select></div><div className="platform-table-wrap"><table><thead><tr><th>Sekolah</th><th>Dibuat</th><th>Anggota</th><th>Siswa</th><th>Status</th><th>Trial / Pembayaran / Nonaktif</th><th>Pendapatan</th><th>Aksi</th></tr></thead><tbody>{filteredSchools.slice(schoolPage*25,(schoolPage+1)*25).map(s=><tr key={s.id} className={detailSchoolId===s.id?"selected-row":""}><td><b>{s.name}</b>{s.is_internal_test&&<small className="platform-demo">INTERNAL</small>}<small>{s.id.slice(0,8)}</small></td><td>{date(s.created_at)}</td><td>{s.member_count}</td><td>{s.student_count}</td><td><span className={"platform-status "+status(s)}>{status(s)}</span></td><td><SubscriptionDates value={s} now={now}/></td><td>{money(s.paid_amount)}</td><td><button onClick={()=>void openSchool(s.id)}>{detailLoading&&detailSchoolId===s.id?"Memuat…":"Detail"}</button></td></tr>)}</tbody></table>{!filteredSchools.length&&<div className="platform-empty">Tidak ada sekolah yang cocok.</div>}</div>{filteredSchools.length>25&&<div className="platform-pagination"><button disabled={schoolPage===0} onClick={()=>setSchoolPage(n=>n-1)}>Sebelumnya</button><span>Halaman {schoolPage+1}/{Math.ceil(filteredSchools.length/25)} · {filteredSchools.length} sekolah</span><button disabled={(schoolPage+1)*25>=filteredSchools.length} onClick={()=>setSchoolPage(n=>n+1)}>Berikutnya</button></div>}
 <DataEntryModal open={!!detailSchoolId} title={detailLoading&&!detail?"Memuat detail sekolah":String(detail?.school?.name||"Detail sekolah")} subtitle="Akun, langganan dan aktivitas sekolah" onClose={()=>{detailRequest.current++;setDetail(null);setDetailSchoolId("");setDetailLoading(false)}} wide>{detailLoading&&!detail&&<p role="status">Memuat detail…</p>}{detail&&<div className="platform-school-detail platform-panel">
  <p className="platform-detail-subtitle">{String(detail.school?.education_level||detail.school?.school_type||"Jenjang belum diisi")} · {String(detail.school?.city||"Lokasi belum diisi")} · Tahun {String(detail.school?.academic_year||"—")}</p>
  <div className="platform-detail-identity"><div><small>Owner</small><strong>{detail.owner?.email||"—"}</strong></div><div><small>Langganan</small><strong>{String(detail.subscription?.status||"—")}</strong></div><div><small>Masa aktif</small><strong>{date(detail.subscription?.current_period_end||detail.subscription?.trial_ends_at||null)}</strong></div><div><small>Peran</small><strong>{(detail.roles||[]).map(x=>(ROLE_LABELS[x.role as Role]||x.role)+" "+x.count).join(" · ")||"—"}</strong></div></div>
  <section className="platform-detail-group"><h3>Masa langganan & tenggat</h3><SubscriptionDates value={detail.subscription as any} now={now}/><p className="platform-updated">Akses operasional berhenti tepat saat trial atau masa berbayar berakhir. Chat dukungan dan pembayaran tetap tersedia. Tidak ada penghapusan otomatis data pelanggan.</p></section>
  <section className="platform-detail-group"><h3>Identitas & kontak sekolah</h3><div className="platform-detail-grid">{['id','npsn','address','phone','email','website','principal_name','accreditation','province','city','district','village','postal_code','semester','created_at'].map(k=><div key={k}><small>{identityLabels[k]||k}</small><strong>{k==='created_at'&&detail.school?.[k]?date(String(detail.school[k])):String(detail.school?.[k]||'Belum diisi')}</strong></div>)}</div></section>
  <section className="platform-detail-group"><h3>Seluruh akun sekolah</h3><div className="platform-table-wrap"><table><thead><tr><th>Nama / Email</th><th>Peran</th><th>Terdaftar</th><th>Login terakhir</th><th>Status akun</th><th>Pesan belum dibaca</th></tr></thead><tbody>{accounts.filter(a=>a.school_id===detailSchoolId).map(a=><tr key={a.user_id}><td><b>{a.account_name}</b><small>{a.email}</small><small>ID: {a.user_id}</small></td><td>{ROLE_LABELS[a.role as Role]||a.role}</td><td>{date(a.registered_at)}</td><td>{date(a.last_sign_in_at)}</td><td><b>{a.banned_until&&Date.parse(a.banned_until)>now?"Dibatasi sampai "+date(a.banned_until):"Aktif"}</b><small>{a.email_confirmed_at?"Email terverifikasi":"Email belum diverifikasi"}</small><small>Bergabung: {date(a.member_since)}</small></td><td>{a.unread}</td></tr>)}</tbody></table></div></section>
  <DetailGroup title="Data inti" data={detail.core}/>
  <DetailGroup title="Presensi" data={detail.attendance}/>
  <DetailGroup title="Pembelajaran & AI" data={detail.academic}/>
  <DetailGroup title="Kesiswaan, Disiplin & BK" data={detail.student_affairs}/>
  <DetailGroup title="Program & Tugas" data={detail.programs}/>
  <DetailGroup title="Keuangan" data={detail.finance}/>
  <DetailGroup title="SDM & Payroll" data={detail.hr}/>
  <DetailGroup title="Dokumen, Laporan & Import" data={detail.documents}/>
  <DetailGroup title="Agenda" data={detail.calendar}/>
  <DetailGroup title="Pembayaran" data={detail.payments}/>
  <section className="platform-detail-group"><h3>Aktivitas audit terbaru</h3>{detail.recent_activity?.map((x,i)=><div className="platform-activity" key={i}><div><strong>{x.action}</strong><small>{x.target_id||"Tanpa target"}</small></div><time>{date(x.occurred_at)}</time></div>)}{!detail.recent_activity?.length&&<div className="platform-empty">Belum ada aktivitas audit pada sekolah ini.</div>}</section>
 </div>}</DataEntryModal>
 </div>}
 {tab==="support"&&<SupportChat admin embedded/>}
 {tab==="orders"&&<div className="platform-panel"><div className="platform-panel-header"><div><h2>Pesanan & Pembayaran</h2><p>Hanya callback terverifikasi dari gateway dapat mengubah status pembayaran.</p></div><div className="platform-search"><Search size={16}/><input aria-label="Cari pembayaran" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari order / sekolah"/></div></div><div className="platform-table-wrap"><table><thead><tr><th>Order ID</th><th>Sekolah</th><th>Waktu Pesan</th><th>Nominal</th><th>Durasi</th><th>Status</th><th>Waktu Lunas</th></tr></thead><tbody>{filteredOrders.map(o=><tr key={o.order_id}><td><b>{o.order_id}</b></td><td>{o.school_name}{o.is_internal_test&&<small className="platform-demo">DEMO</small>}</td><td>{date(o.created_at)}</td><td>{money(o.gross_amount)}</td><td>{o.period_days} hari</td><td><span className={"platform-status "+o.status}>{o.status}</span></td><td>{date(o.paid_at)}</td></tr>)}</tbody></table>{!filteredOrders.length&&<div className="platform-empty">Belum ada transaksi yang tercatat.</div>}</div></div>}
 </main></div>;
}

function SubscriptionDates({value,now}:{value:Parameters<typeof subscriptionTimeline>[0];now:number}){const t=subscriptionTimeline(value,now);return <div className="platform-subscription-dates">{t.trialDays!==null&&<strong>Trial: {t.trialDays} hari tersisa</strong>}<span>{t.active?(value.subscription_status==='trial'||value.status==='trial'?'Mulai berlangganan':'Perpanjangan')+': '+t.dueDays+' hari lagi':'Pembayaran / aktivasi diperlukan'}</span><span>{t.active?'Menuju nonaktif: '+(t.hoursLeft<24?t.hoursLeft+' jam':t.dueDays+' hari'):'Sudah nonaktif: '+(t.inactiveDays===null?'tanggal belum tersedia':t.inactiveDays+' hari')}</span><small>{t.active?'Tenggat: '+date(t.deadline):'Nonaktif sejak: '+date(t.inactiveSince)}</small></div>;}
