"use client";
import {useRealtimeRefresh} from "@/lib/school-realtime";
import SearchableSelect from "@/components/SearchableSelect";
import DataEntryModal from "@/components/DataEntryModal";
import type {Role} from "@/lib/modules";
import {errorMessage} from "@/lib/error-message";
import {useEffect,useMemo,useState} from "react";
import RecordListTools,{useRecordList} from "@/components/RecordListTools";
import {readAllRows} from "@/lib/read-all-rows";
import {Archive,Download,Eye,FileText,Search} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import {resolveReportAssets} from "@/lib/report-template-client";
import {downloadOfficialDocx,downloadOfficialExcel,previewOfficialReport,printOfficialReport,type OfficialReportModel,type ReportIdentity} from "@/lib/report-engine";

type Row={id:string;module_key:string;document_type:string;document_number:string;title:string;status:string;period_start:string|null;period_end:string|null;content_snapshot:any;issued_at:string;archived_reason:string|null;archived_previous_status:string|null};

export default function ReportArchive({schoolId,role}:{schoolId:string;role:Role}){
 const manager=["owner","principal","vice_principal"].includes(role);
 const [selected,setSelected]=useState<Row|null>(null),[reason,setReason]=useState(""),[statusFilter,setStatusFilter]=useState(""),[message,setMessage]=useState("");
 const db=useMemo(()=>browserDb(),[]),[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(""),[module,setModule]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 useRealtimeRefresh(schoolId,()=>load());
 async function load(){if(!db)return;const {data,error}=await readAllRows(db.from("sc_report_documents").select("id,module_key,document_type,document_number,title,status,period_start,period_end,content_snapshot,issued_at,archived_reason,archived_previous_status").eq("school_id",schoolId).order("issued_at",{ascending:false}).order("id"));if(error)setError(error.message);else setRows((data||[]) as Row[])}
 useEffect(()=>{void load()},[db,schoolId]);
 const modules=Array.from(new Set(rows.map(r=>r.module_key))).sort();
 const filtered=rows.filter(r=>(!statusFilter||r.status===statusFilter)&&(!module||r.module_key===module)&&((r.document_number+" "+r.title+" "+r.document_type).toLowerCase().includes(query.toLowerCase()));
 const list=useRecordList(filtered,r=>r.document_number+" "+r.title,[],r=>r.issued_at);
 function snapshot(r:Row){const raw=r.content_snapshot||{};const model=(raw.model||raw) as OfficialReportModel,identity=(raw.identity||null) as ReportIdentity|null;return {model,identity}}
 async function open(r:Row,kind:"preview"|"pdf"|"docx"|"xlsx"){setBusy(true);setError("");try{let {model,identity}=snapshot(r);if(!identity){const {data,error}=await db!.from("sc_schools").select("name,npsn,address,academic_year,education_level,principal_name,principal_nip,phone,email,website,province,city,postal_code,logo_url,signature_url,stamp_url,report_settings").eq("id",schoolId).single();if(error)throw error;identity=data as ReportIdentity}identity=await resolveReportAssets(identity,schoolId) as ReportIdentity;if(!model?.title)throw Error("Snapshot dokumen lama belum kompatibel dengan Report Engine.");model={...model,status:r.status==="issued"||r.status==="archived"?"issued":model.status,issuedAt:r.issued_at};if(kind==="preview")previewOfficialReport(identity,model,r.document_number);if(kind==="pdf")printOfficialReport(identity,model,r.document_number);if(kind==="docx")await downloadOfficialDocx(identity,model,r.document_number);if(kind==="xlsx")await downloadOfficialExcel(model,r.document_number,identity)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function archive(r:Row,archive:boolean){setBusy(true);setError("");setMessage("");try{const {error}=await db.rpc("sc_archive_report",{p_school:schoolId,p_document:r.id,p_archive:archive,p_reason:archive?reason:null});if(error)throw error;setSelected(null);setReason("");setMessage(archive?"Laporan diarsipkan; nomor dan isi tetap tersimpan.":"Laporan dipulihkan ke status asal.");await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 return <section className="panel"><div className="sectionhead"><div><h2>Arsip Laporan Resmi</h2><p className="muted">Setiap laporan final yang diterbitkan disimpan sebagai snapshot bernomor. Perubahan data berikutnya tidak mengubah isi snapshot lama.</p></div><Archive/></div>
 <div className="fields"><label className="field">Status<SearchableSelect label="Status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Semua status</option>{["draft","review","approved","issued","archived"].map(status=><option key={status}>{status}</option>)}</SearchableSelect></label><label className="field full">Cari laporan<div className="searchbox"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nomor, judul, atau jenis dokumen"/></div></label><label className="field">Modul<SearchableSelect label="Modul" value={module} onChange={e=>setModule(e.target.value)}><option value="">Semua modul</option>{modules.map(m=><option key={m} value={m}>{m.replaceAll("_"," ")}</option>)}</SearchableSelect></label></div>
 <RecordListTools list={list} label="arsip laporan" showSearch={false} busy={busy}/>
 <div style={{display:"grid",gap:8,marginTop:16}}>{list.visible.map(r=><div className="entry" key={r.id}><div><strong>{r.document_number} · {r.title}</strong><small>{r.module_key.replaceAll("_"," ")} · {r.document_type.replaceAll("_"," ")} · {new Date(r.issued_at).toLocaleString("id-ID")} · {r.status}</small>{r.archived_reason&&<small>Alasan arsip: {r.archived_reason}</small>}</div><div className="flow">{manager&&(r.status==="archived"?<button className="button secondary" disabled={busy||!r.archived_previous_status} onClick={()=>void archive(r,false)}>Pulihkan</button>:<button className="button secondary" disabled={busy} onClick={()=>{setSelected(r);setReason("")}}>Arsipkan</button>)}<button className="button secondary" disabled={busy} onClick={()=>void open(r,"preview")}><Eye size={14}/> Preview</button><button className="button secondary" disabled={busy} onClick={()=>void open(r,"docx")}><FileText size={14}/> Word</button><button className="button secondary" disabled={busy} onClick={()=>void open(r,"xlsx")}><Download size={14}/> Excel</button><button className="button secondary" disabled={busy} onClick={()=>void open(r,"pdf")}><Download size={14}/> PDF</button></div></div>)}{!list.filtered.length&&<div className="empty">Belum ada laporan final pada filter ini.</div>}</div>{message&&<div className="banner success" role="status">{message}</div>}{error&&<div className="banner error" role="alert">{error}</div>}<DataEntryModal open={Boolean(selected)} title="Arsipkan laporan" subtitle={selected?.document_number} onClose={()=>{if(!busy)setSelected(null)}}><label className="field">Alasan arsip<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={1000}/></label><button className="button" disabled={busy||reason.trim().length<3} onClick={()=>selected&&void archive(selected,true)}>Simpan arsip</button></DataEntryModal></section>
}
