"use client";
import {useEffect,useMemo,useState} from "react";
import {Archive,Download,Eye,FileText,Search} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import {downloadOfficialDocx,downloadOfficialExcel,previewOfficialReport,printOfficialReport,type OfficialReportModel,type ReportIdentity} from "@/lib/report-engine";

type Row={id:string;module_key:string;document_type:string;document_number:string;title:string;status:string;period_start:string|null;period_end:string|null;content_snapshot:any;issued_at:string};

export default function ReportArchive({schoolId}:{schoolId:string}){
 const db=useMemo(()=>browserDb(),[]),[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(""),[module,setModule]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function load(){if(!db)return;const {data,error}=await db.from("sc_report_documents").select("id,module_key,document_type,document_number,title,status,period_start,period_end,content_snapshot,issued_at").eq("school_id",schoolId).order("issued_at",{ascending:false}).limit(500);if(error)setError(error.message);else setRows((data||[]) as Row[])}
 useEffect(()=>{void load()},[db,schoolId]);
 const modules=Array.from(new Set(rows.map(r=>r.module_key))).sort();
 const filtered=rows.filter(r=>(!module||r.module_key===module)&&((r.document_number+" "+r.title+" "+r.document_type).toLowerCase().includes(query.toLowerCase())));
 function snapshot(r:Row){const raw=r.content_snapshot||{};const model=(raw.model||raw) as OfficialReportModel,identity=(raw.identity||null) as ReportIdentity|null;return {model,identity}}
 async function open(r:Row,kind:"preview"|"pdf"|"docx"|"xlsx"){setBusy(true);setError("");try{let {model,identity}=snapshot(r);if(!identity){const {data,error}=await db!.from("sc_schools").select("name,npsn,address,academic_year,education_level,principal_name,principal_nip,phone,email,website,province,city,postal_code,logo_url,signature_url,stamp_url,report_settings").eq("id",schoolId).single();if(error)throw error;identity=data as ReportIdentity}if(!model?.title)throw Error("Snapshot dokumen lama belum kompatibel dengan Report Engine.");if(kind==="preview")previewOfficialReport(identity,model,r.document_number);if(kind==="pdf")printOfficialReport(identity,model,r.document_number);if(kind==="docx")await downloadOfficialDocx(identity,model,r.document_number);if(kind==="xlsx")await downloadOfficialExcel(model,r.document_number)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <section className="panel"><div className="sectionhead"><div><h2>Arsip Laporan Resmi</h2><p className="muted">Setiap laporan final yang diterbitkan disimpan sebagai snapshot bernomor. Perubahan data berikutnya tidak mengubah isi snapshot lama.</p></div><Archive/></div>
 <div className="fields"><label className="field full">Cari laporan<div className="searchbox"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nomor, judul, atau jenis dokumen"/></div></label><label className="field">Modul<select value={module} onChange={e=>setModule(e.target.value)}><option value="">Semua modul</option>{modules.map(m=><option key={m} value={m}>{m.replaceAll("_"," ")}</option>)}</select></label></div>
 <div style={{display:"grid",gap:8,marginTop:16}}>{filtered.map(r=><div className="entry" key={r.id}><div><strong>{r.document_number} · {r.title}</strong><small>{r.module_key.replaceAll("_"," ")} · {r.document_type.replaceAll("_"," ")} · {new Date(r.issued_at).toLocaleString("id-ID")} · {r.status}</small></div><div className="flow"><button className="button secondary" disabled={busy} onClick={()=>void open(r,"preview")}><Eye size={14}/> Preview</button><button className="button secondary" disabled={busy} onClick={()=>void open(r,"docx")}><FileText size={14}/> Word</button><button className="button secondary" disabled={busy} onClick={()=>void open(r,"xlsx")}><Download size={14}/> Excel</button><button className="button secondary" disabled={busy} onClick={()=>void open(r,"pdf")}><Download size={14}/> PDF</button></div></div>)}{!filtered.length&&<div className="empty">Belum ada laporan final pada filter ini.</div>}</div>{error&&<div className="banner error">{error}</div>}</section>
}
