"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {isAdmin,type Role} from "@/lib/modules";
type Fact={key:string;value:string;updated_at:string};
export default function SchoolProfile({schoolId,role}:{schoolId:string;role:Role}){
 const db=useMemo(()=>browserDb(),[]),admin=isAdmin(role);
 const [profile,setProfile]=useState({name:"",npsn:"",address:"",academic_year:"2026/2027"}),[facts,setFacts]=useState<Fact[]>([]),[key,setKey]=useState(""),[value,setValue]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 async function load(){if(!db)return;const [{data:p},{data:f}]=await Promise.all([db.from("sc_schools").select("name,npsn,address,academic_year").eq("id",schoolId).maybeSingle(),db.from("sc_school_facts").select("key,value,updated_at").eq("school_id",schoolId).order("key")]);if(p)setProfile({name:p.name,npsn:p.npsn||"",address:p.address||"",academic_year:p.academic_year||"2026/2027"});setFacts((f||[]) as Fact[])}
 useEffect(()=>{void load()},[db,schoolId]);
 async function run(fn:()=>Promise<void>){setError("");setOk("");setBusy(true);try{await fn();await load();setOk("Informasi sekolah tersimpan.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function rpc(fn:string,args:Record<string,unknown>){if(!db)throw Error("Database belum siap.");const {error}=await db.rpc(fn,args);if(error)throw error}
 const field=(k:keyof typeof profile,label:string)=><label className="field">{label}<input value={profile[k]} onChange={e=>setProfile(p=>({...p,[k]:e.target.value}))} disabled={!admin}/></label>;
 return <><section className="panel"><h2>Profil & Identitas Sekolah</h2><p className="muted">Identitas sumber tunggal yang dipakai dokumen, laporan, data induk dan pengaturan tahun ajaran.</p><div className="fields">{field("name","Nama Sekolah")}{field("npsn","NPSN")}{field("academic_year","Tahun Ajaran")}{field("address","Alamat")}</div>{admin&&<button className="button" style={{marginTop:12}} disabled={busy} onClick={()=>void run(()=>rpc("sc_edit_school",{p_school:schoolId,p_name:profile.name,p_npsn:profile.npsn,p_address:profile.address,p_year:profile.academic_year}))}>Simpan Profil</button>}</section><section className="panel"><h2>Memori Sekolah untuk AI</h2><p className="muted">Informasi yang diverifikasi sekolah: visi, misi, fokus mutu, karakteristik umum dan program kerja. Jangan memasukkan informasi rahasia konseling atau data pribadi siswa.</p>{admin&&<div className="fields"><label className="field">Topik<input value={key} onChange={e=>setKey(e.target.value)} placeholder="Contoh: Visi Sekolah"/></label><label className="field full">Informasi<textarea value={value} onChange={e=>setValue(e.target.value)}/></label><button className="button" disabled={busy||key.trim().length<2||!value.trim()} onClick={()=>void run(async()=>{await rpc("sc_save_school_fact",{p_school:schoolId,p_key:key,p_value:value});setKey("");setValue("")})}>Simpan Fakta</button></div>}{facts.map(f=><div className="entry" key={f.key}><div><strong>{f.key}</strong><small>{f.value}</small></div></div>)}{!facts.length&&<div className="empty">Belum ada memori sekolah.</div>}</section>{error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
}
