"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {isAdmin,type Role} from "@/lib/modules";
import {downloadExcel,readExcel} from "@/lib/excel";
type C={id:string;name:string;grade:string|null;academic_year:string};
type S={id:string;class_id:string|null;nis:string|null;name:string;status:string};
type A={id:string;student_id:string;attendance_date:string;lesson_key:string;mark:string};
type G={id:string;student_id:string;subject:string;assessment_name:string;score:number;assessment_date:string};
type J={id:string;class_id:string;subject:string;topic:string;lesson_date:string};
type Agenda={id:string;title:string;event_date:string;notes:string|null;created_by:string};
const now=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"});
export default function SchoolData({mode,schoolId,userId,role,focus}:{mode:"master"|"academic";schoolId:string;userId:string;role:Role;focus?:string}){
 const db=useMemo(()=>browserDb(),[]);
 const [classes,setClasses]=useState<C[]>([]),[students,setStudents]=useState<S[]>([]),[att,setAtt]=useState<A[]>([]),[grades,setGrades]=useState<G[]>([]),[journals,setJournals]=useState<J[]>([]),[agenda,setAgenda]=useState<Agenda[]>([]);
 const [className,setClassName]=useState(""),[grade,setGrade]=useState(""),[year,setYear]=useState("2026/2027");
 const [studentName,setStudentName]=useState(""),[nis,setNis]=useState(""),[classId,setClassId]=useState(""),[studentId,setStudentId]=useState("");
 const [day,setDay]=useState(now()),[lesson,setLesson]=useState("daily"),[mark,setMark]=useState("present");
 const [subject,setSubject]=useState(""),[assessment,setAssessment]=useState(""),[score,setScore]=useState(""),[topic,setTopic]=useState(""),[notes,setNotes]=useState("");
 const [tab,setTab]=useState("attendance"),[error,setError]=useState(""),[ok,setOk]=useState(""),[busy,setBusy]=useState(false),[editGradeId,setEditGradeId]=useState(""),[editScore,setEditScore]=useState(""),[editNote,setEditNote]=useState(""),[importKind,setImportKind]=useState<"attendance"|"grades">("grades"),[preview,setPreview]=useState<Record<string,unknown>[]>([]),[importFile,setImportFile]=useState("");
 const manager=isAdmin(role);const canTeach=manager||role==="teacher";const student=students.find(s=>s.id===studentId);const name=(id:string)=>students.find(s=>s.id===id)?.name||"Siswa";
 async function load(){if(!db)return;const [{data:c},{data:s}]=await Promise.all([db.from("sc_classes").select("id,name,grade,academic_year").eq("school_id",schoolId).order("name"),db.from("sc_students").select("id,class_id,nis,name,status").eq("school_id",schoolId).order("name")]);setClasses((c||[]) as C[]);setStudents((s||[]) as S[]);
 if(mode==="academic"){const [{data:a},{data:g},{data:j},{data:ag}]=await Promise.all([db.from("sc_student_attendance").select("id,student_id,attendance_date,lesson_key,mark").eq("school_id",schoolId).order("attendance_date",{ascending:false}).limit(30),db.from("sc_grades").select("id,student_id,subject,assessment_name,score,assessment_date").eq("school_id",schoolId).order("assessment_date",{ascending:false}).limit(30),db.from("sc_teacher_journals").select("id,class_id,subject,topic,lesson_date").eq("school_id",schoolId).order("lesson_date",{ascending:false}).limit(30),db.from("sc_calendar_events").select("id,title,event_date,notes,created_by").eq("school_id",schoolId).eq("category","teaching").order("event_date",{ascending:false}).limit(60)]);setAtt((a||[]) as A[]);setGrades((g||[]) as G[]);setJournals((j||[]) as J[]);setAgenda((ag||[]) as Agenda[])}}
 useEffect(()=>{void load()},[db,schoolId,mode]);
 useEffect(()=>{const f=(focus||"").toLowerCase();if(f.includes("presensi"))setTab("attendance");else if(f.includes("nilai"))setTab("grades");else if(f.includes("jurnal"))setTab("journal");else if(f.includes("agenda"))setTab("agenda");else if(f.includes("import")||f.includes("export"))setTab("import")},[focus]);
 async function save(action:()=>Promise<void>){setError("");setOk("");setBusy(true);try{await action();await load();setOk("Data tersimpan pada sekolah ini.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function insert(table:string,row:Record<string,unknown>){if(!db)throw Error("Database belum terhubung.");const {error:e}=await db.from(table).insert({...row,school_id:schoolId});if(e)throw e;}
 async function op(name:string,args:Record<string,unknown>){if(!db)throw Error("Database belum terhubung.");const {error:e}=await db.rpc(name,args);if(e)throw e}
 async function remove(entity:string,id:string){if(!confirm("Hapus data ini?"))return;await save(()=>op("sc_delete_operational",{p_school:schoolId,p_entity:entity,p_id:id}))}
 async function academicTemplate(){const guide=[{Kolom:"Panduan",Keterangan:"Gunakan NIS yang sudah ada di Data Induk. Maksimal 500 baris per import."}];const rows=importKind==="grades"?[{NIS:"1001",Mata_Pelajaran:"Matematika",Nama_Penilaian:"Kuis 1",Tanggal:"2026-09-30",Nilai:88}]:[{NIS:"1001",Tanggal:"2026-09-30",Kegiatan:"Matematika",Status:"Hadir"}];await downloadExcel("template-"+importKind+"-school-control.xlsx",[{name:"Data",rows},{name:"Panduan",rows:guide}])}
 async function readAcademic(file?:File){if(!file)return;try{if(file.size>5_000_000)throw Error("File maksimal 5 MB");const rows=await readExcel(file);if(rows.length>500)throw Error("Maksimal 500 baris");setPreview(rows as Record<string,unknown>[]);setImportFile(file.name)}catch(e){setError(e instanceof Error?e.message:String(e));setPreview([])}}
 async function commitAcademicImport(){await save(async()=>{if(!preview.length)return;const rows=importKind==="grades"?preview.map(x=>({nis:String(x.NIS||"").trim(),subject:String(x.Mata_Pelajaran||"").trim(),assessment_name:String(x.Nama_Penilaian||"").trim(),assessment_date:String(x.Tanggal||"").trim(),score:Number(x.Nilai||0)})):preview.map(x=>({nis:String(x.NIS||"").trim(),attendance_date:String(x.Tanggal||"").trim(),lesson_key:String(x.Kegiatan||"").trim(),mark:String(x.Status||"").trim()}));await op(importKind==="grades"?"sc_import_grades":"sc_import_student_attendance",{p_school:schoolId,p_rows:rows});setPreview([]);setImportFile("")})}
 async function exportAcademic(){await downloadExcel("akademik-school-control.xlsx",[{name:"Presensi",rows:att.map(a=>({Tanggal:a.attendance_date,NIS:students.find(s=>s.id===a.student_id)?.nis||"",Nama:name(a.student_id),Kegiatan:a.lesson_key,Status:a.mark}))},{name:"Nilai",rows:grades.map(g=>({Tanggal:g.assessment_date,NIS:students.find(s=>s.id===g.student_id)?.nis||"",Nama:name(g.student_id),Mata_Pelajaran:g.subject,Penilaian:g.assessment_name,Nilai:g.score}))},{name:"Jurnal",rows:journals.map(j=>({Tanggal:j.lesson_date,Kelas:classes.find(c=>c.id===j.class_id)?.name||"",Mata_Pelajaran:j.subject,Topik:j.topic}))}])}
 const field=(title:string,value:string,set:(x:string)=>void,type="text")=><label className="field">{title}<input type={type} value={value} onChange={e=>set(e.target.value)} required/></label>;
 const cls=<label className="field">Kelas<select value={classId} onChange={e=>setClassId(e.target.value)} required><option value="">Pilih kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.academic_year}</option>)}</select></label>;
 const stu=<label className="field">Siswa<select value={studentId} onChange={e=>setStudentId(e.target.value)} required><option value="">Pilih siswa</option>{students.filter(s=>s.class_id&&s.status==="active").map(s=><option key={s.id} value={s.id}>{s.name} {s.nis?"· "+s.nis:""}</option>)}</select></label>;
 const dayField=field("Tanggal",day,setDay,"date");
 const result=<>{error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
 if(mode==="master")return <><section className="panel"><h2>Kelas dan tahun ajaran</h2><p className="muted">Sumber data bersama untuk Buku Kerja, Disiplin Pro, BK dan laporan sekolah.</p>{manager&&<form className="fields" onSubmit={e=>{e.preventDefault();void save(async()=>{await insert("sc_classes",{name:className.trim(),grade:grade.trim()||null,academic_year:year.trim()});setClassName("")})}}>{field("Nama kelas",className,setClassName)}{field("Jenjang",grade,setGrade)}{field("Tahun ajaran",year,setYear)}<button className="button" disabled={busy||!className.trim()}>Tambah Kelas</button></form>}<div className="tablewrap"><table className="data-table"><thead><tr><th>Kelas</th><th>Jenjang</th><th>Tahun ajaran</th></tr></thead><tbody>{classes.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.grade||"—"}</td><td>{c.academic_year}</td></tr>)}</tbody></table>{!classes.length&&<div className="empty">Belum ada kelas.</div>}</div></section><section className="panel"><h2>Data siswa</h2>{manager&&<form className="fields" onSubmit={e=>{e.preventDefault();void save(async()=>{await insert("sc_students",{name:studentName.trim(),nis:nis.trim()||null,class_id:classId});setStudentName("");setNis("")})}}>{field("Nama lengkap",studentName,setStudentName)}{field("NIS (opsional)",nis,setNis)}{cls}<button className="button" disabled={busy||!classId||!studentName.trim()}>Tambah Siswa</button></form>}<div className="tablewrap"><table className="data-table"><thead><tr><th>Nama</th><th>NIS</th><th>Kelas</th><th>Status</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.nis||"—"}</td><td>{classes.find(c=>c.id===s.class_id)?.name||"—"}</td><td>{s.status}</td></tr>)}</tbody></table>{!students.length&&<div className="empty">Belum ada siswa.</div>}</div></section>{result}</>;
 if(!canTeach)return <section className="panel"><p>Data akademik hanya tersedia untuk pengajar dan manajemen berwenang.</p></section>;
 return <section className="panel"><h2>Administrasi guru dan buku kerja digital</h2><div className="flow" style={{marginBottom:16}}>{(["attendance","grades","journal","agenda","import"] as const).map(k=><button key={k} className={"button "+(tab===k?"":"secondary")} onClick={()=>setTab(k)}>{k==="attendance"?"Presensi siswa":k==="grades"?"Penilaian":k==="journal"?"Jurnal mengajar":k==="agenda"?"Agenda mengajar":"Import / Export"}</button>)}</div>
 {tab==="attendance"&&<><div className="banner">Presensi siswa tidak dihapus untuk menjaga riwayat. Koreksi dilakukan dengan menyimpan status yang benar pada tanggal dan kegiatan yang sama.</div><form className="fields" onSubmit={e=>{e.preventDefault();void save(async()=>{await insert("sc_student_attendance",{student_id:studentId,class_id:student?.class_id,attendance_date:day,lesson_key:lesson.trim(),mark,recorded_by:userId});})}}>{stu}{dayField}{field("Kegiatan / mata pelajaran",lesson,setLesson)}<label className="field">Keterangan<select value={mark} onChange={e=>setMark(e.target.value)}>{[["present","Hadir"],["sick","Sakit"],["permission","Izin"],["absent","Alpa"]].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><button className="button" disabled={busy||!student?.class_id}>Simpan Presensi</button></form><div className="tablewrap"><table className="data-table"><thead><tr><th>Tanggal</th><th>Siswa</th><th>Kegiatan</th><th>Keterangan</th></tr></thead><tbody>{att.map(a=><tr key={a.id}><td>{a.attendance_date}</td><td>{name(a.student_id)}</td><td>{a.lesson_key}</td><td>{a.mark}</td></tr>)}</tbody></table></div></>}
 {tab==="grades"&&<><form className="fields" onSubmit={e=>{e.preventDefault();void save(async()=>{await insert("sc_grades",{student_id:studentId,class_id:student?.class_id,subject:subject.trim(),assessment_name:assessment.trim(),assessment_date:day,score:Number(score),recorded_by:userId});setAssessment("");setScore("")})}}>{stu}{field("Mata pelajaran",subject,setSubject)}{field("Nama penilaian",assessment,setAssessment)}{dayField}{field("Nilai (0–100)",score,setScore,"number")}<button className="button" disabled={busy||!student?.class_id||!subject.trim()||!assessment.trim()||score===""||Number(score)<0||Number(score)>100}>Simpan Nilai</button></form><div className="tablewrap"><table className="data-table"><thead><tr><th>Tanggal</th><th>Siswa</th><th>Mapel / Penilaian</th><th>Nilai</th><th>Aksi</th></tr></thead><tbody>{grades.map(g=><tr key={g.id}><td>{g.assessment_date}</td><td>{name(g.student_id)}</td><td>{g.subject} / {g.assessment_name}</td><td>{g.score}</td><td><div className="flow"><button className="button secondary" onClick={()=>{setEditGradeId(g.id);setEditScore(String(g.score));setEditNote("")}}>Edit</button><button className="button danger" onClick={()=>void remove("grade",g.id)}>Hapus</button></div></td></tr>)}</tbody></table></div>{editGradeId&&<div className="panel"><h3>Perbaiki Nilai</h3><p className="muted">Perubahan nilai memerlukan izin guru pencatat atau pengelola dan tersimpan dalam audit log.</p><div className="fields"><label className="field">Nilai baru<input type="number" min={0} max={100} value={editScore} onChange={e=>setEditScore(e.target.value)}/></label><label className="field">Alasan / Catatan<input value={editNote} onChange={e=>setEditNote(e.target.value)}/></label><button className="button" disabled={busy||editScore===""||Number(editScore)<0||Number(editScore)>100} onClick={()=>void save(async()=>{if(!db)throw Error("Database belum siap");const {error:e}=await db.rpc("sc_edit_grade",{p_school:schoolId,p_grade:editGradeId,p_score:Number(editScore),p_note:editNote});if(e)throw e;setEditGradeId("")})}>Simpan Revisi</button><button className="button secondary" onClick={()=>setEditGradeId("")}>Batal</button></div></div>}</>}
 {tab==="journal"&&<><form className="fields" onSubmit={e=>{e.preventDefault();void save(async()=>{await insert("sc_teacher_journals",{teacher_id:userId,class_id:classId,subject:subject.trim(),lesson_date:day,topic:topic.trim(),notes:notes.trim()||null});setTopic("");setNotes("")})}}>{cls}{field("Mata pelajaran",subject,setSubject)}{dayField}{field("Topik pembelajaran",topic,setTopic)}<label className="field full">Catatan<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="button" disabled={busy||!classId||!subject.trim()||!topic.trim()}>Simpan Jurnal</button></form><div className="tablewrap"><table className="data-table"><thead><tr><th>Tanggal</th><th>Kelas</th><th>Mata pelajaran</th><th>Topik</th><th>Aksi</th></tr></thead><tbody>{journals.map(j=><tr key={j.id}><td>{j.lesson_date}</td><td>{classes.find(c=>c.id===j.class_id)?.name||"—"}</td><td>{j.subject}</td><td>{j.topic}</td><td><div className="flow"><button className="button secondary" onClick={()=>{const sub=prompt("Mata pelajaran",j.subject);const top=prompt("Topik",j.topic);const d=prompt("Tanggal YYYY-MM-DD",j.lesson_date);if(sub&&top&&d)void save(()=>op("sc_update_operational",{p_school:schoolId,p_entity:"journal",p_id:j.id,p_patch:{subject:sub,topic:top,lesson_date:d}}))}}>Edit</button><button className="button danger" onClick={()=>void remove("journal",j.id)}>Hapus</button></div></td></tr>)}</tbody></table></div></>}{tab==="agenda"&&<><form className="fields" onSubmit={e=>{e.preventDefault();void save(async()=>{await insert("sc_calendar_events",{title:topic.trim(),event_date:day,category:"teaching",notes:notes.trim()||null,created_by:userId});setTopic("");setNotes("")})}}>{field("Agenda / Kegiatan",topic,setTopic)}{dayField}<label className="field full">Keterangan<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="button" disabled={busy||topic.trim().length<3}>Tambah Agenda</button></form>{agenda.map(a=><div className="entry" key={a.id}><div><strong>{a.title}</strong><small>{a.event_date} · {a.notes||"Tanpa keterangan"}</small></div><div className="flow"><button className="button secondary" onClick={()=>{const title=prompt("Agenda",a.title);const notes=prompt("Keterangan",a.notes||"")||"";if(title)void save(()=>op("sc_update_operational",{p_school:schoolId,p_entity:"calendar",p_id:a.id,p_patch:{title,notes}}))}}>Edit</button><button className="button danger" onClick={()=>void remove("calendar",a.id)}>Hapus</button></div></div>)}</>}
 {tab==="import"&&<><div className="banner">Import Excel menggunakan NIS dari Data Induk sehingga data tetap terhubung ke siswa dan kelas yang sama.</div><div className="fields"><label className="field">Jenis Data<select value={importKind} onChange={e=>{setImportKind(e.target.value as "attendance"|"grades");setPreview([])}}><option value="grades">Nilai</option><option value="attendance">Presensi Siswa</option></select></label><div className="flow"><button className="button secondary" onClick={()=>void academicTemplate()}>Unduh Template Excel</button><label className="button secondary">Pilih Excel<input hidden type="file" accept=".xlsx,.xls" onChange={e=>void readAcademic(e.currentTarget.files?.[0])}/></label><button className="button secondary" onClick={()=>void exportAcademic()}>Export Akademik</button></div></div>{preview.length>0&&<div className="banner"><strong>{importFile} · {preview.length} baris</strong><p className="hint">Pratinjau: {preview.slice(0,3).map(x=>Object.values(x).slice(0,5).join(" | ")).join(" / ")}</p><button className="button" disabled={busy} onClick={()=>void commitAcademicImport()}>Konfirmasi Import</button></div>}</>}
 {result}</section>;
}
