"use client";
import {useRealtimeRefresh} from "@/lib/school-realtime";
import SearchableSelect from "@/components/SearchableSelect";
import {errorMessage} from "@/lib/error-message";
import {useEffect,useMemo,useRef,useState} from "react";
import {CalendarDays,ChevronLeft,ChevronRight,Clock3,Download,MapPin,Plus,Upload,Users} from "lucide-react";
import DataEntryModal from "@/components/DataEntryModal";
import SmartSelect from "@/components/SmartSelect";
import {browserDb} from "@/lib/supabase";
import {ROLE_LABELS,isAdmin,type Role} from "@/lib/modules";
import {agendaMode,visibleAgenda,requiresAgendaAttendance,validAgendaCoordinates} from "@/lib/agenda";
import {readAllRows} from "@/lib/read-all-rows";
import {downloadExcel,readExcel,type SheetRows} from "@/lib/excel";

type EventRow={id:string;title:string;event_date:string;category:string;notes:string|null;created_by:string;scope:string;start_time:string|null;end_time:string|null;location:string|null;owner_user_id:string|null;audience_type:string;audience_grade:string|null;audience_class_id:string|null;attendance_required:boolean;attendance_location_id:string|null;checkin_open_minutes:number;checkin_close_minutes:number;attendance_target:string;attendance_roles:string[];attendance_users:string[];attendance_address:string|null;attendance_latitude:number|null;attendance_longitude:number|null;attendance_radius_meters:number};
type Participant={event_id:string;user_id:string};
type Attendance={event_id:string;user_id:string;check_in_at:string|null;check_out_at:string|null;status:string};
type Person={user_id:string;staff_name:string|null;email:string|null;role:string|null};
type SchoolClass={id:string;name:string;grade:string|null;academic_year:string};
type AttendanceLocation={id:string;name:string;address:string|null;radius_meters:number;latitude:number|null;longitude:number|null};
const pad=(n:number)=>String(n).padStart(2,"0");
const ymd=(d:Date)=>d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate());
const monthStart=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1);
const addMonths=(d:Date,n:number)=>new Date(d.getFullYear(),d.getMonth()+n,1);
const monthKey=(d:Date)=>d.getFullYear()+"-"+pad(d.getMonth()+1);
const same=(a:Date,b:string)=>ymd(a)===b;
const human=(s:string)=>new Date(s+"T00:00:00").toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"});

export default function SchoolCalendar({schoolId,userId,role,compact=false,focus,timezone="Asia/Jakarta"}:{schoolId:string;userId:string;role:Role;compact?:boolean;focus?:string;timezone?:string}){
 const schoolToday=()=>new Date().toLocaleDateString("en-CA",{timeZone:timezone});const schoolNow=()=>new Date(schoolToday()+"T12:00:00");
 const db=useMemo(()=>browserDb(),[]),manager=isAdmin(role),loadEpoch=useRef(0);
 const [cursor,setCursor]=useState(()=>monthStart(schoolNow())),[rows,setRows]=useState<EventRow[]>([]),[participants,setParticipants]=useState<Participant[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[people,setPeople]=useState<Person[]>([]),[classes,setClasses]=useState<SchoolClass[]>([]),[locations,setLocations]=useState<AttendanceLocation[]>([]);
 const [targetUser,setTargetUser]=useState(userId),[modal,setModal]=useState(false),[editing,setEditing]=useState<EventRow|null>(null),[selectedDay,setSelectedDay]=useState(schoolToday());
 const [title,setTitle]=useState(""),[day,setDay]=useState(schoolToday()),[start,setStart]=useState("07:00"),[end,setEnd]=useState(""),[category,setCategory]=useState("school"),[notes,setNotes]=useState(""),[location,setLocation]=useState(""),[scope,setScope]=useState<"school"|"personal">("school"),[selected,setSelected]=useState<string[]>([]);
 const [audienceType,setAudienceType]=useState("school"),[audienceGrade,setAudienceGrade]=useState(""),[audienceClass,setAudienceClass]=useState("");
 const [attendanceRequired,setAttendanceRequired]=useState(false),[attendanceLocation,setAttendanceLocation]=useState(""),[checkinOpen,setCheckinOpen]=useState(30),[checkinClose,setCheckinClose]=useState(60);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState(""),[importRows,setImportRows]=useState<SheetRows>([]),[importFile,setImportFile]=useState("");
 const mode=agendaMode(focus);
 const [attendanceTarget,setAttendanceTarget]=useState("roles"),[attendanceRoles,setAttendanceRoles]=useState<string[]>(["teacher"]),[attendanceUsers,setAttendanceUsers]=useState<string[]>([]),[address,setAddress]=useState(""),[latitude,setLatitude]=useState(""),[longitude,setLongitude]=useState(""),[filter,setFilter]=useState(""),[recapKind,setRecapKind]=useState("all"),[recapUser,setRecapUser]=useState("all"),[schedules,setSchedules]=useState<any[]>([]),[assignments,setAssignments]=useState<any[]>([]),[subjects,setSubjects]=useState<any[]>([]);
 const canWrite=role!=="viewer";

 useRealtimeRefresh(schoolId,()=>load());
 async function load(){
  if(!db)return;const epoch=++loadEpoch.current;
  const from=ymd(new Date(cursor.getFullYear(),cursor.getMonth()-1,1)),to=ymd(new Date(cursor.getFullYear(),cursor.getMonth()+2,0));
  const [ev,cl,loc]=await Promise.all([
   readAllRows(db.from("sc_calendar_events").select("id,title,event_date,category,notes,created_by,scope,start_time,end_time,location,owner_user_id,audience_type,audience_grade,audience_class_id,attendance_required,attendance_location_id,checkin_open_minutes,checkin_close_minutes,attendance_target,attendance_roles,attendance_users,attendance_address,attendance_latitude,attendance_longitude,attendance_radius_meters").eq("school_id",schoolId).gte("event_date",from).lte("event_date",to).order("event_date").order("id")),
   db.from("sc_classes").select("id,name,grade,academic_year").eq("school_id",schoolId).order("name"),
   db.from("sc_hr_locations").select("id,name,address,radius_meters,latitude,longitude").eq("school_id",schoolId).eq("active",true).order("name")
  ]);
  if(epoch!==loadEpoch.current)return;
  if(ev.error){setError(ev.error.message);return}
  const list=(ev.data||[]) as EventRow[];setRows(list);setClasses((cl.data||[]) as SchoolClass[]);setLocations((loc.data||[]) as AttendanceLocation[]);
  const ids=list.map(x=>x.id);
  if(ids.length){
   const [p,a]=await Promise.all([
    db.from("sc_calendar_participants").select("event_id,user_id").eq("school_id",schoolId).in("event_id",ids),
    db.from("sc_event_attendance").select("event_id,user_id,check_in_at,check_out_at,status").eq("school_id",schoolId).in("event_id",ids)
   ]);
   setParticipants((p.data||[]) as Participant[]);setAttendance((a.data||[]) as Attendance[]);
  }else{setParticipants([]);setAttendance([])}
  const [sh,as,su]=await Promise.all([readAllRows(db.from("sc_teacher_schedules").select("*").eq("school_id",schoolId).eq("active",true).order("id")),readAllRows(db.from("sc_teacher_assignments").select("*").eq("school_id",schoolId).order("id")),db.from("sc_subjects").select("id,name").eq("school_id",schoolId)]);if(epoch!==loadEpoch.current)return;setSchedules(sh.data||[]);setAssignments(as.data||[]);setSubjects(su.data||[]);
  const staff=await db.from("sc_staff").select("user_id,name,position").eq("school_id",schoolId).not("user_id","is",null).order("name");
  setPeople((staff.data||[]).map(x=>({user_id:x.user_id as string,staff_name:x.name,email:null,role:x.position||null})));
  if(manager){const dir=await db.rpc("sc_team_directory",{p_school:schoolId});if(!dir.error&&dir.data)setPeople((dir.data as Person[]).map(x=>({...x,staff_name:x.staff_name||x.email||"Pengguna"})))}
 }
 useEffect(()=>{void load()},[db,schoolId,cursor,manager]);
 useEffect(()=>{if(!targetUser)setTargetUser(userId)},[userId,targetUser]);

 function resetForm(nextDay=schoolToday(),nextScope:"school"|"personal"=mode==="personal"?"personal":"school"){
  setEditing(null);setTitle("");setDay(nextDay);setStart("07:00");setEnd("");setCategory(nextScope==="personal"?"personal":mode==="teaching"?"teaching":"school");setNotes("");setLocation("");setScope(nextScope);setSelected([]);
  setAudienceType(nextScope==="personal"?"personal":"school");setAudienceGrade("");setAudienceClass("");setAttendanceRequired(false);setAttendanceLocation("");setCheckinOpen(30);setCheckinClose(60);setAttendanceTarget("roles");setAttendanceRoles(["teacher"]);setAttendanceUsers([]);setAddress("");setLatitude("");setLongitude("");
 }
 function openNew(nextDay?:string){const target=nextDay||selectedDay;setSelectedDay(target);resetForm(target,mode==="personal"?"personal":"school");setModal(true)}
 function openEdit(x:EventRow){setSelectedDay(x.event_date);setEditing(x);setTitle(x.title);setDay(x.event_date);setStart((x.start_time||"").slice(0,5)||"07:00");setEnd((x.end_time||"").slice(0,5));setCategory(x.category);setNotes(x.notes||"");setLocation(x.location||"");setScope(x.scope==="personal"?"personal":"school");setSelected(participants.filter(p=>p.event_id===x.id).map(p=>p.user_id));setAudienceType(x.audience_type||x.scope||"school");setAudienceGrade(x.audience_grade||"");setAudienceClass(x.audience_class_id||"");setAttendanceRequired(!!x.attendance_required);setAttendanceLocation(x.attendance_location_id||"");setCheckinOpen(x.checkin_open_minutes??30);setCheckinClose(x.checkin_close_minutes??60);setAttendanceTarget(x.attendance_target||"roles");setAttendanceRoles(x.attendance_roles||[]);setAttendanceUsers(x.attendance_users||[]);setAddress(x.attendance_address||"");setLatitude(x.attendance_latitude==null?"":String(x.attendance_latitude));setLongitude(x.attendance_longitude==null?"":String(x.attendance_longitude));setModal(true)}
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load()}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
 async function save(){if(!db)return;await run(async()=>{const {error}=await db.rpc("sc_save_calendar_event_v4",{p_school:schoolId,p_event:editing?.id||null,p_payload:{title:title.trim(),event_date:day,start_time:start||null,end_time:end||null,category:scope==='personal'?'personal':category,notes,location,scope,participants:scope==='school'?selected:[],audience_type:scope==='personal'?'personal':audienceType,audience_grade:audienceType==='grade'?audienceGrade:null,audience_class_id:audienceType==='class'?audienceClass:null,attendance_required:scope==='school'&&attendanceRequired,attendance_target:attendanceTarget,attendance_roles:attendanceRoles,attendance_users:attendanceUsers,attendance_address:address,attendance_latitude:latitude?Number(latitude):null,attendance_longitude:longitude?Number(longitude):null,checkin_open_minutes:checkinOpen,checkin_close_minutes:checkinClose}});if(error)throw error;setModal(false);setOk(editing?"Agenda diperbarui.":"Agenda ditambahkan.")})}
 async function remove(x:EventRow){if(!db||!confirm("Hapus agenda ini?"))return;await run(async()=>{const {error}=await db.rpc("sc_delete_calendar_event",{p_school:schoolId,p_event:x.id});if(error)throw error;setOk("Agenda dihapus.")})}
 function position():Promise<{lat:number|null;lng:number|null;accuracy:number|null}>{return new Promise(resolve=>{if(!navigator.geolocation){resolve({lat:null,lng:null,accuracy:null});return}navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),()=>resolve({lat:null,lng:null,accuracy:null}),{enableHighAccuracy:true,timeout:7000,maximumAge:0})})}
 async function clock(x:EventRow,action:"in"|"out"){if(!db)return;await run(async()=>{const p=await position();const fn=action==="in"?"sc_event_check_in":"sc_event_check_out";const {error}=await db.rpc(fn,{p_school:schoolId,p_event:x.id,p_lat:p.lat,p_lng:p.lng,p_accuracy:p.accuracy});if(error)throw error;setOk(action==="in"?"Kehadiran agenda tercatat.":"Check-out agenda tercatat.")})}
 async function agendaTemplate(){await downloadExcel('template-agenda-'+mode+'.xlsx',[{name:'AGENDA',rows:[{Judul:mode==='personal'?'Catatan pribadi':mode==='teaching'?'Pembelajaran Matematika':'Rapat Koordinasi',Tanggal:schoolToday(),Jam_Mulai:'08:00',Jam_Selesai:'09:30',Kategori:mode==='personal'?'personal':mode==='teaching'?'teaching':'meeting',Sasaran:mode==='personal'?'personal':'school',Tingkat:'',Kelas:'',Lokasi_Agenda:'',Wajib_Presensi:'tidak',Sasaran_Presensi:'roles',Peran_Presensi:'teacher',Pengguna_Presensi:'',Alamat_Presensi:'',Latitude:'',Longitude:'',Buka_Checkin_Menit:30,Tutup_Checkin_Menit:60,Keterangan:'Hapus baris contoh sebelum import'}]},{name:'Panduan',rows:[{Kolom:'Kategori',Ketentuan:'school, teaching, meeting, training, program, other; personal hanya untuk agenda pribadi.'},{Kolom:'Sasaran',Ketentuan:'school, grade, class; agenda pribadi selalu personal.'},{Kolom:'Presensi',Ketentuan:'Hanya manajemen dapat mengaktifkan. Alamat dan koordinat wajib; radius selalu 100 m.'},{Kolom:'Peran_Presensi',Ketentuan:'Pisahkan dengan koma: teacher, counselor, staff, hr, owner, principal, vice_principal, treasurer, finance_staff, supervisor. Tidak termasuk viewer.'},{Kolom:'Pengguna_Presensi',Ketentuan:'Sasaran_Presensi users: email anggota dari daftar Referensi Pengguna, pisahkan dengan koma.'}]},{name:'Referensi Pengguna',rows:people.map(p=>({Nama:p.staff_name,Email:p.email||'',Peran:p.role||''}))}])}
 async function readAgendaImport(file?:File){if(!file)return;setError("");try{if(file.size>8_000_000)throw Error("File maksimal 8 MB.");const rr=await readExcel(file);if(rr.length>2000)throw Error("Maksimal 2.000 agenda per import.");setImportRows(rr);setImportFile(file.name);setOk(file.name+" siap diimport · "+rr.length+" baris.")}catch(e){setError(errorMessage(e));setImportRows([]);setImportFile("")}}
 async function commitAgendaImport(){if(!db||!canWrite||!importRows.length)return;await run(async()=>{let imported=0;const failed:SheetRows=[];const reasons:string[]=[];for(const [i,raw] of importRows.entries()){try{
 const cat=String(raw.Kategori||(mode==='personal'?'personal':mode==='teaching'?'teaching':'school')).trim().toLowerCase(),aud=mode==='personal'?'personal':String(raw.Sasaran||'school').trim().toLowerCase(),klass=aud==='class'?classes.find(c=>c.name.toLowerCase()===String(raw.Kelas||'').trim().toLowerCase()):undefined,att=['ya','yes','true','1'].includes(String(raw.Wajib_Presensi||'').trim().toLowerCase()),target=String(raw.Sasaran_Presensi||'roles');
 const emails=String(raw.Pengguna_Presensi||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),users=emails.map(e=>people.find(p=>p.email?.toLowerCase()===e)?.user_id);if(users.some(u=>!u))throw Error('Email peserta tidak ditemukan');if(aud==='class'&&!klass)throw Error('Kelas tidak ditemukan');if(att&&!manager)throw Error('Pengaturan presensi memerlukan manajemen');
 const payload={title:String(raw.Judul||raw.Agenda||'').trim(),event_date:String(raw.Tanggal||'').slice(0,10),start_time:String(raw.Jam_Mulai||'').trim()||null,end_time:String(raw.Jam_Selesai||'').trim()||null,category:mode==='personal'?'personal':cat,scope:mode==='personal'?'personal':'school',audience_type:aud,audience_grade:aud==='grade'?String(raw.Tingkat||''):null,audience_class_id:klass?.id||null,participants:[],notes:String(raw.Keterangan||raw.Catatan||''),location:String(raw.Lokasi_Agenda||''),attendance_required:att,attendance_target:target,attendance_roles:String(raw.Peran_Presensi||'').split(',').map(x=>x.trim()).filter(Boolean),attendance_users:users,attendance_address:String(raw.Alamat_Presensi||''),attendance_latitude:raw.Latitude==null||String(raw.Latitude).trim()===''?null:Number(raw.Latitude),attendance_longitude:raw.Longitude==null||String(raw.Longitude).trim()===''?null:Number(raw.Longitude),checkin_open_minutes:Number(raw.Buka_Checkin_Menit??30),checkin_close_minutes:Number(raw.Tutup_Checkin_Menit??60)};
 const {error}=await db.rpc('sc_save_calendar_event_v4',{p_school:schoolId,p_event:null,p_payload:payload});if(error)throw error;imported++;
 }catch(e){failed.push(raw);reasons.push('Baris '+(i+2)+': '+errorMessage(e))}}
 await db.from('sc_import_history').insert({school_id:schoolId,module_key:'calendar',import_kind:mode+'_agenda',file_name:importFile||'import.xlsx',row_count:importRows.length,imported_count:imported,skipped_count:failed.length,details:{target:'sc_calendar_events',errors:reasons}});setImportRows(failed);if(!failed.length)setImportFile('');setOk(imported+' agenda masuk; '+failed.length+' perlu diperbaiki.');if(reasons.length)setError(reasons.slice(0,5).join(' · '))})}
 async function exportAgenda(){const prefix=mode==="recap"?"rekap-agenda":mode==="teaching"?"agenda-mengajar":mode==="personal"?"agenda-pribadi":"agenda-sekolah";await downloadExcel(prefix+"-"+monthKey(cursor)+".xlsx",[{name:mode==="recap"?"REKAP":"AGENDA",rows:currentMonth.map(x=>({Judul:x.title,Tanggal:x.event_date,Jam_Mulai:(x.start_time||"").slice(0,5),Jam_Selesai:(x.end_time||"").slice(0,5),Kategori:x.category,Sasaran:x.audience_type,Tingkat:x.audience_grade||"",Kelas:className(x.audience_class_id),Lokasi_Agenda:x.location||"",Wajib_Presensi:x.attendance_required?"ya":"tidak",Sasaran_Presensi:x.attendance_target,Peran_Presensi:(x.attendance_roles||[]).join(","),Pengguna_Presensi:(x.attendance_users||[]).map(id=>people.find(p=>p.user_id===id)?.email||id).join(","),Alamat_Presensi:x.attendance_address||"",Latitude:x.attendance_latitude??"",Longitude:x.attendance_longitude??"",Radius_Meter:100,Buka_Checkin_Menit:x.checkin_open_minutes,Tutup_Checkin_Menit:x.checkin_close_minutes,Keterangan:x.notes||""}))}])}

 const visible=rows.filter(x=>visibleAgenda(x,mode,userId,role,targetUser,participants.filter(p=>p.event_id===x.id).map(p=>p.user_id),people.find(p=>p.user_id===targetUser)?.role||undefined)&&(mode!=="recap"||recapUser==="all"||visibleAgenda(x,"users",userId,role,recapUser,participants.filter(p=>p.event_id===x.id).map(p=>p.user_id),people.find(p=>p.user_id===recapUser)?.role||undefined))&&(recapKind==='all'||mode!=='recap'||x.category===recapKind)&&(x.title+' '+(x.location||'')).toLowerCase().includes(filter.toLowerCase()));
 const selectedRows=visible.filter(x=>x.event_date===selectedDay);
 const currentMonth=visible.filter(x=>x.event_date.startsWith(monthKey(cursor)));
 const levels=[...new Set(classes.map(c=>c.grade).filter(Boolean) as string[])].sort((a,b)=>a.localeCompare(b,"id",{numeric:true}));
 const className=(id:string|null)=>classes.find(c=>c.id===id)?.name||"";
 const groupOf=(x:EventRow)=>{
  if(x.scope==="personal"||x.audience_type==="personal")return "Pribadi";
  if(x.audience_type==="grade")return x.audience_grade||"Tingkat Lain";
  if(x.audience_type==="class"){const c=classes.find(k=>k.id===x.audience_class_id);return c?.grade||c?.name||"Kelas Lain";}
  if(x.audience_type==="users")return "Pengguna Terpilih";
  return "Umum Sekolah";
 };
 const groups=[...new Set(currentMonth.map(groupOf))];
 const tomorrow=schoolNow();tomorrow.setDate(tomorrow.getDate()+1);
 const nextMonthStart=addMonths(monthStart(schoolNow()),1),nextMonthEnd=new Date(nextMonthStart.getFullYear(),nextMonthStart.getMonth()+1,0);
 const tomorrowRows=rows.filter(x=>x.scope==="school"&&same(tomorrow,x.event_date)),nextMonthRows=rows.filter(x=>{const d=new Date(x.event_date+"T00:00:00");return x.scope==="school"&&d>=nextMonthStart&&d<=nextMonthEnd});
 if(compact)return <section className="panel"><div className="sectionhead"><div><h2>Agenda Terdekat</h2><p className="muted">Agenda sekolah yang akan datang.</p></div></div><div className="grid"><div className="card"><label>Besok</label><strong>{tomorrowRows.length}</strong><small>{tomorrowRows.slice(0,2).map(x=>x.title).join(" · ")||"Tidak ada agenda"}</small></div><div className="card"><label>Bulan depan</label><strong>{nextMonthRows.length}</strong><small>{nextMonthRows.slice(0,2).map(x=>x.title).join(" · ")||"Belum ada agenda"}</small></div></div></section>;

 const first=monthStart(cursor),offset=(first.getDay()+6)%7,cells=Array.from({length:42},(_,i)=>new Date(first.getFullYear(),first.getMonth(),i-offset+1));
 const canEditSelected=canWrite&&(!editing||manager||editing.owner_user_id===userId);
 const audienceOptions=[{value:"school",label:"Seluruh sekolah",subtitle:"Agenda umum untuk semua tingkat"},{value:"grade",label:"Tingkat / jenjang tertentu",subtitle:"Rekap dipisah per tingkat"},{value:"class",label:"Kelas tertentu",subtitle:"Hanya satu kelas"},{value:"users",label:"Pengguna tertentu",subtitle:"Pilih guru / staf yang terlibat"}];
 return <>
  <section className="agenda-mode-head"><span className="eyebrow">AGENDA TERHUBUNG</span><h2>{focus||"Kalender Sekolah"}</h2><p className="muted">{({school:"Kegiatan sekolah, rapat, pelatihan dan program. Jadwal pembelajaran dan agenda pribadi memiliki ruang sendiri.",teaching:"Jadwal mingguan dari penugasan guru dan kegiatan pembelajaran bertanggal.",personal:"Catatan pribadi Anda. Tidak tampil sebagai kegiatan sekolah dan tidak meminta presensi tim.",users:"Agenda yang ditugaskan kepada pengguna tertentu.",recap:"Ringkasan kegiatan sekolah per bulan, kategori dan pengguna. Buka kegiatan untuk melihat detail.",attendance:"Hanya agenda yang mewajibkan Anda hadir. GPS wajib dalam radius 100 meter dan waktu presensi ditentukan server."})[mode]}</p><label className="field">Cari agenda<input type="search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Nama agenda atau lokasi"/></label></section>
  {mode!=="attendance"&&mode!=="users"&&mode!=="recap"&&canWrite&&<section className="panel excel-toolbar"><div><h2>{mode==="teaching"?"Kelola Agenda Mengajar":mode==="personal"?"Kelola Agenda Pribadi":"Kelola Agenda Sekolah"}</h2><p className="muted">{mode==="teaching"?"Tambah kegiatan pembelajaran bertanggal, import agenda mengajar, atau ekspor agenda bulan ini.":mode==="personal"?"Catatan pribadi hanya untuk akun Anda dan tidak menjadi agenda wajib sekolah.":"Tambah rapat, pelatihan, program, dan kegiatan sekolah. Presensi wajib diatur per agenda bila diperlukan."}</p></div><div className="flow"><button className="button secondary" onClick={()=>void agendaTemplate()}><Download size={14}/> Template Excel</button><label className="button secondary"><Upload size={14}/> Import Excel<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={e=>void readAgendaImport(e.target.files?.[0])}/></label><button className="button secondary" onClick={()=>void exportAgenda()}><Download size={14}/> Export Bulan</button><button className="button" onClick={()=>openNew(selectedDay)}><Plus size={15}/> Tambah Agenda</button></div>{importRows.length>0&&<div className="banner"><strong>{importFile} · {importRows.length} baris siap</strong><div className="flow" style={{marginTop:8}}><button className="button" disabled={busy} onClick={()=>void commitAgendaImport()}>Proses Import</button><button className="button secondary" onClick={()=>{setImportRows([]);setImportFile("")}}>Batal</button></div></div>}</section>}
  {mode==="users"&&manager&&<section className="panel page-control"><div><h2>Agenda Pengguna</h2><p className="muted">Pilih guru/staf untuk melihat agenda yang melibatkannya.</p></div><label className="field">Pengguna<SearchableSelect label="Pengguna" value={targetUser} onChange={e=>setTargetUser(e.target.value)}><option value={userId}>Saya</option>{people.map(p=><option key={p.user_id} value={p.user_id}>{p.staff_name||p.email||p.user_id.slice(0,8)}</option>)}</SearchableSelect></label></section>}

  {mode==="recap"&&<section className="panel agenda-summary-panel"><div className="flow"><label className="field">Periode rekap<input aria-label="Période agenda" type="month" value={monthKey(cursor)} onChange={e=>{if(e.target.value){const [y,m]=e.target.value.split("-").map(Number);setCursor(new Date(y,m-1,1))}}}/></label><label className="field">Kategori rekap<select aria-label="Kategori rekap" value={recapKind} onChange={e=>setRecapKind(e.target.value)}><option value="all">Semua kegiatan sekolah</option>{["school","teaching","meeting","training","program","other"].map(k=><option key={k} value={k}>{({school:"Sekolah",teaching:"Pembelajaran",meeting:"Rapat",training:"Pelatihan",program:"Program",other:"Lainnya"})[k as "school"]}</option>)}</select></label>{manager&&<label className="field">Pengguna rekap<select aria-label="Pengguna rekap" value={recapUser} onChange={e=>setRecapUser(e.target.value)}><option value="all">Semua pengguna</option>{people.map(p=><option key={p.user_id} value={p.user_id}>{p.staff_name||p.email}</option>)}</select></label>}<button className="button secondary" onClick={()=>void exportAgenda()}><Download size={14}/> Export Rekap</button></div><div className="agenda-stat-grid"><div><strong>{currentMonth.length}</strong><span>Agenda bulan ini</span></div><div><strong>{currentMonth.filter(e=>e.attendance_required).length}</strong><span>Wajib presensi</span></div><div><strong>{groups.length}</strong><span>Kelompok sasaran</span></div></div></section>}
  {mode==="teaching"&&<section className="panel"><div className="sectionhead"><h2>Jadwal mengajar mingguan</h2><a className="button secondary" href="#menu=buku_kerja&fitur=Jadwal+Mingguan">Kelola jadwal</a></div><div className="teaching-week-grid">{["Senin","Selasa","Rabu","Kamis","Jumat","Sabtu","Minggu"].map((d,i)=><article key={d}><h3>{d}</h3>{schedules.filter(x=>Number(x.weekday)===i+1).map(x=>{const a=assignments.find(a=>a.id===x.assignment_id);return <div className="teaching-slot" key={x.id}><strong>{String(x.starts_at).slice(0,5)}–{String(x.ends_at).slice(0,5)}</strong><span>{subjects.find(s=>s.id===a?.subject_id)?.name||"Mata pelajaran"} · {className(a?.class_id||null)}</span><small>{x.room||"Ruang belum ditentukan"}</small></div>})}</article>)}</div>{!schedules.length&&<p className="muted">Belum ada jadwal mingguan. Isi melalui penugasan guru dan Jadwal Mingguan.</p>}</section>}
  {mode!=="attendance"&&<div className={"agenda-layout "+(mode==="recap"?"recap-only":"")}>
   {mode!=="recap"&&<section className="panel mini-calendar-panel">
    <div className="calendar-head"><button className="iconbutton" onClick={()=>setCursor(addMonths(cursor,-1))} aria-label="Bulan sebelumnya"><ChevronLeft size={17}/></button><h2>{cursor.toLocaleDateString("id-ID",{month:"long",year:"numeric"})}</h2><button className="iconbutton" onClick={()=>setCursor(addMonths(cursor,1))} aria-label="Bulan berikutnya"><ChevronRight size={17}/></button></div>
    <div className="calendar-week">{["Sen","Sel","Rab","Kam","Jum","Sab","Min"].map(x=><span key={x}>{x}</span>)}</div>
    <div className="agenda-mini-grid">{cells.map(d=>{const key=ymd(d),count=visible.filter(x=>x.event_date===key).length;return <button type="button" key={key} className={(d.getMonth()===cursor.getMonth()?"":"outside ") +(same(schoolNow(),key)?"today ":"")+(selectedDay===key?"selected":"")} onClick={()=>{setSelectedDay(key);setDay(key)}}>
      <b>{d.getDate()}</b>{count>0&&<i aria-label={count+" agenda"} title={count+" agenda"}/>}
     </button>})}</div>
    <div className="agenda-calendar-legend"><span><i/> Ada agenda</span><span>Tanggal tanpa tanda = kosong</span></div>
    <label className="field">Pilih bulan<input aria-label="Période agenda" type="month" value={monthKey(cursor)} onChange={e=>{const [y,m]=e.target.value.split("-").map(Number);setCursor(new Date(y,m-1,1))}}/></label>
   </section>}

   <div className="agenda-workspace">
    {mode!=="recap"&&<section className="panel">
     <div className="sectionhead"><div><span className="eyebrow">AGENDA HARI TERPILIH</span><h2>{human(selectedDay)}</h2><p className="muted">{selectedRows.length?selectedRows.length+" agenda pada tanggal ini.":"Belum ada agenda pada tanggal ini."}</p></div></div>
     <div className="agenda-day-list">{selectedRows.map(x=><article className="agenda-card" key={x.id} onClick={()=>openEdit(x)}><div className="agenda-time"><b>{x.start_time?x.start_time.slice(0,5):"—"}</b><small>{x.end_time?x.end_time.slice(0,5):""}</small></div><div><strong>{x.title}</strong><small>{groupOf(x)} · {x.category}</small>{x.location&&<small><MapPin size={11}/> {x.location}</small>}{x.attendance_required&&<small><Clock3 size={11}/> Presensi agenda aktif</small>}</div><span className="pill">{participants.filter(p=>p.event_id===x.id).length} peserta</span></article>)}{!selectedRows.length&&<div className="empty">Tanggal ini masih kosong. Tidak ada tanda pada kalender sampai agenda ditambahkan.</div>}</div>
    </section>}

    <section className="panel agenda-recap">
     <div className="sectionhead"><div><span className="eyebrow">REKAP BULANAN</span><h2>Rekap Agenda · {cursor.toLocaleDateString("id-ID",{month:"long",year:"numeric"})}</h2><p className="muted">Agenda tidak digabung menjadi satu. Setiap tingkat/kelompok tampil pada bagian terpisah.</p></div><CalendarDays size={20}/></div>
     {groups.map(group=><div className="agenda-grade-group" key={group}><div className="agenda-grade-head"><strong>{group}</strong><span>{currentMonth.filter(x=>groupOf(x)===group).length} agenda</span></div>{currentMonth.filter(x=>groupOf(x)===group).sort((a,b)=>a.event_date.localeCompare(b.event_date)||(a.start_time||"").localeCompare(b.start_time||"")).map(x=><button className="agenda-recap-row" key={x.id} onClick={()=>openEdit(x)}><time><b>{new Date(x.event_date+"T00:00:00").getDate()}</b><small>{new Date(x.event_date+"T00:00:00").toLocaleDateString("id-ID",{month:"short"})}</small></time><div><strong>{x.title}</strong><small>{x.start_time?x.start_time.slice(0,5):"Tanpa jam"}{x.location?" · "+x.location:""}{x.audience_type==="class"&&x.audience_class_id?" · "+className(x.audience_class_id):""}</small></div><span className="pill">{x.category}</span></button>)}</div>)}
     {!groups.length&&<div className="empty">Belum ada agenda pada bulan ini.</div>}
    </section>
   </div>
  </div>}

  {mode==="attendance"&&<section className="panel"><div className="sectionhead"><div><h2>Kehadiran Agenda</h2><p className="muted">Check-in hanya diterima pada jendela waktu agenda. Jika lokasi presensi ditetapkan, GPS juga wajib berada di dalam radius.</p></div><Clock3 size={20}/></div>
   {visible.map(x=>{const a=attendance.find(z=>z.event_id===x.id&&z.user_id===userId);return <div className="entry agenda-attendance-card" key={x.id}><div><strong>{x.title}</strong><small>{x.event_date}{x.start_time?" · "+x.start_time.slice(0,5):""} · {x.attendance_address||x.location||"Koordinat perlu dilengkapi pengelola"}</small><small>Radius 100 m · Sasaran {x.attendance_target==="users"?"pengguna terpilih":(x.attendance_roles||[]).map(r=>ROLE_LABELS[r as Role]||r).join(", ")}</small><small>Status: {a?.status||"Belum check-in"} {a?.check_in_at?"· Masuk "+new Date(a.check_in_at).toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit",timeZone:timezone}):""}</small></div><div className="flow"><button className="button" disabled={busy||!!a?.check_in_at} onClick={()=>void clock(x,"in")}>Check-in</button><button className="button secondary" disabled={busy||!a?.check_in_at||!!a?.check_out_at} onClick={()=>void clock(x,"out")}>Check-out</button></div></div>})}
   {!visible.length&&<div className="empty">Belum ada agenda yang membutuhkan kehadiran Anda.</div>}
  </section>}

  <DataEntryModal open={modal} onClose={()=>setModal(false)} title={editing?(canEditSelected?"Edit Agenda":"Detail Agenda"):"Tambah Agenda"} subtitle={editing&&!canEditSelected?"Agenda ini dapat dilihat, tetapi hanya pembuat atau manajemen yang dapat mengubahnya.":"Atur sasaran, waktu, lokasi, dan pengguna yang terlibat."} wide>
   {error&&<div className="banner error" role="alert">{error}</div>}
   <div className="fields">
    <label className="field full">Nama agenda<input value={title} onChange={e=>setTitle(e.target.value)} autoFocus disabled={!canEditSelected}/></label>
    <label className="field">Tanggal<input type="date" value={day} onChange={e=>{setDay(e.target.value);setSelectedDay(e.target.value)}} disabled={!canEditSelected}/></label>
    <label className="field">Jenis<SearchableSelect label="Jenis" value={scope} onChange={e=>{const v=e.target.value as "school"|"personal";setScope(v);if(v==="personal"){setAudienceType("personal");setAttendanceRequired(false);setCategory("personal")}else{setAudienceType("school");setCategory("school")}}} disabled={!canEditSelected}><option value="school">Agenda Sekolah</option><option value="personal">Agenda Pribadi</option></SearchableSelect></label>
    <label className="field">Mulai<input type="time" value={start} onChange={e=>setStart(e.target.value)} disabled={!canEditSelected}/></label>
    <label className="field">Selesai<input type="time" value={end} onChange={e=>setEnd(e.target.value)} disabled={!canEditSelected}/></label>
    <label className="field">Kategori<SearchableSelect label="Kategori" value={category} onChange={e=>setCategory(e.target.value)} disabled={!canEditSelected}><option value="school">Sekolah</option><option value="teaching">Pembelajaran</option><option value="meeting">Rapat</option><option value="training">Pelatihan</option><option value="program">Program</option><option value="other">Lainnya</option><option value="personal">Pribadi</option></SearchableSelect></label>
    {scope==="school"&&<div className="field full"><SmartSelect label="Sasaran agenda" value={audienceType} options={audienceOptions} onChange={v=>{setAudienceType(v);setAudienceGrade("");setAudienceClass("")}} disabled={!canEditSelected}/></div>}
    {scope==="school"&&audienceType==="grade"&&<div className="field full"><SmartSelect label="Tingkat / jenjang" value={audienceGrade} options={levels.map(x=>({value:x,label:x}))} onChange={setAudienceGrade} allowCustom customLabel="Gunakan tingkat ini" disabled={!canEditSelected}/></div>}
    {scope==="school"&&audienceType==="class"&&<div className="field full"><SmartSelect label="Kelas sasaran" value={audienceClass} options={classes.map(x=>({value:x.id,label:x.name,subtitle:x.grade||x.academic_year}))} onChange={setAudienceClass} disabled={!canEditSelected}/></div>}
    <label className="field full">Lokasi agenda<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Ruang rapat / kelas / aula / online" disabled={!canEditSelected}/></label>
    {scope==="school"&&manager&&<label className="field full"><span>Presensi guru/staf pada agenda</span><span className="flow"><input type="checkbox" checked={attendanceRequired} onChange={e=>setAttendanceRequired(e.target.checked)} disabled={!canEditSelected}/> Wajib check-in sesuai jam dan lokasi</span></label>}
    {scope==="school"&&attendanceRequired&&<>
     <label className="field full">Sasaran wajib presensi<select aria-label="Sasaran wajib presensi" value={attendanceTarget} onChange={e=>setAttendanceTarget(e.target.value)} disabled={!canEditSelected||!manager}><option value="roles">Peran tertentu</option><option value="users">Pengguna tertentu</option></select></label>
     <div className="field full check-grid">{attendanceTarget==='roles'?Object.entries(ROLE_LABELS).filter(([r])=>r!=='viewer').map(([r,label])=><label key={r}><input type="checkbox" checked={attendanceRoles.includes(r)} disabled={!canEditSelected||!manager} onChange={e=>setAttendanceRoles(old=>e.target.checked?[...old,r]:old.filter(x=>x!==r))}/>{label}</label>):people.filter(p=>p.role!=='viewer').map(p=><label key={p.user_id}><input type="checkbox" checked={attendanceUsers.includes(p.user_id)} disabled={!canEditSelected||!manager} onChange={e=>setAttendanceUsers(old=>e.target.checked?[...old,p.user_id]:old.filter(x=>x!==p.user_id))}/>{p.staff_name||p.email||'Pengguna'}</label>)}</div>
     <label className="field full">Gunakan lokasi tersimpan (opsional)<SearchableSelect label="Gunakan lokasi tersimpan" value={attendanceLocation} onChange={e=>{setAttendanceLocation(e.target.value);const l=locations.find(x=>x.id===e.target.value);if(l){setAddress(l.address||l.name);setLatitude(l.latitude==null?'':String(l.latitude));setLongitude(l.longitude==null?'':String(l.longitude))}}} disabled={!canEditSelected||!manager}><option value="">Tentukan langsung pada agenda</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</SearchableSelect></label>
     <label className="field full">Alamat presensi<input aria-label="Alamat presensi" value={address} onChange={e=>setAddress(e.target.value)} disabled={!canEditSelected||!manager}/></label>
     <label className="field">Latitude agenda<input aria-label="Latitude agenda" type="number" step="any" min={-90} max={90} value={latitude} onChange={e=>setLatitude(e.target.value)} disabled={!canEditSelected||!manager}/></label>
     <label className="field">Longitude agenda<input aria-label="Longitude agenda" type="number" step="any" min={-180} max={180} value={longitude} onChange={e=>setLongitude(e.target.value)} disabled={!canEditSelected||!manager}/></label>
     <div className="field full"><span>Radius presensi: 100 meter</span><small className="hint">GPS harus berada maksimal 100 m dari titik agenda. Akurasi GPS tidak memperbesar radius.</small>{canEditSelected&&manager&&<button className="button secondary" disabled={busy} onClick={()=>void position().then(p=>{if(p.lat===null||p.lng===null){setError('Izin lokasi diperlukan untuk mengambil koordinat.');return}setLatitude(String(p.lat));setLongitude(String(p.lng))})}>Gunakan koordinat saya</button>}{validAgendaCoordinates(latitude,longitude)&&<a href={'https://www.google.com/maps?q='+encodeURIComponent(latitude+','+longitude)} target="_blank" rel="noreferrer">Lihat titik di peta</a>}</div>
     <label className="field">Buka check-in (menit sebelum mulai)<input type="number" min={0} max={720} value={checkinOpen} onChange={e=>setCheckinOpen(Math.max(0,Number(e.target.value)||0))} disabled={!canEditSelected}/></label>
     <label className="field">Tutup check-in (menit setelah mulai)<input type="number" min={0} max={1440} value={checkinClose} onChange={e=>setCheckinClose(Math.max(0,Number(e.target.value)||0))} disabled={!canEditSelected}/></label>
    </>}
    <label className="field full">Keterangan<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={4} disabled={!canEditSelected}/></label>
   </div>
   {scope==="school"&&(audienceType==="users"||selected.length>0)&&<div className="participant-picker"><b>Guru / staf yang terlibat</b><p className="muted">Boleh dipakai juga untuk menambahkan PIC/peserta pada agenda tingkat atau kelas.</p><div className="check-grid">{people.map(p=><label key={p.user_id}><input type="checkbox" checked={selected.includes(p.user_id)} disabled={!canEditSelected} onChange={e=>setSelected(s=>e.target.checked?[...s,p.user_id]:s.filter(id=>id!==p.user_id))}/><span>{p.staff_name||p.email||p.user_id.slice(0,8)}</span></label>)}</div></div>}
   {scope==="school"&&audienceType!=="users"&&canEditSelected&&<details className="optional-participants"><summary>Tambahkan guru/staf tertentu (opsional)</summary><div className="check-grid">{people.map(p=><label key={p.user_id}><input type="checkbox" checked={selected.includes(p.user_id)} onChange={e=>setSelected(s=>e.target.checked?[...s,p.user_id]:s.filter(id=>id!==p.user_id))}/><span>{p.staff_name||p.email||p.user_id.slice(0,8)}</span></label>)}</div></details>}
   {editing&&manager&&editing.attendance_required&&<section className="modal-section"><h3>Pemantauan kehadiran agenda</h3><div className="tablewrap"><table className="data-table"><thead><tr><th>Peserta wajib</th><th>Status</th><th>Masuk</th><th>Keluar</th></tr></thead><tbody>{people.filter(p=>requiresAgendaAttendance(editing,p.user_id,p.role as Role)).map(p=>{const a=attendance.find(z=>z.event_id===editing.id&&z.user_id===p.user_id);return <tr key={p.user_id}><td>{p.staff_name||p.email}</td><td>{a?.status==='late'?'Terlambat':a?.check_in_at?'Hadir':'Belum presensi'}</td><td>{a?.check_in_at?new Date(a.check_in_at).toLocaleString('id-ID',{timeZone:timezone}):'—'}</td><td>{a?.check_out_at?new Date(a.check_out_at).toLocaleString('id-ID',{timeZone:timezone}):'—'}</td></tr>})}</tbody></table></div></section>}
   <div className="modal-actions"><button className="button secondary" onClick={()=>setModal(false)}>{canEditSelected?"Batal":"Tutup"}</button>{editing&&canEditSelected&&<button className="button danger" onClick={()=>void remove(editing)}>Hapus</button>}{canEditSelected&&<button className="button" disabled={busy||title.trim().length<3||!day||(scope==="school"&&audienceType==="grade"&&!audienceGrade)||(scope==="school"&&audienceType==="class"&&!audienceClass)||(attendanceRequired&&(!start||!validAgendaCoordinates(latitude,longitude)||address.trim().length<3||(attendanceTarget==="roles"?!attendanceRoles.length:!attendanceUsers.length)))} onClick={()=>void save()}>{busy?"Menyimpan…":"Simpan Agenda"}</button>}</div>
  </DataEntryModal>
  {!modal&&error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}
 </>;
}
