"use client";
import {useEffect,useMemo,useState} from 'react';
import {BarChart3,ArrowRight,Download} from 'lucide-react';
import {browserDb} from '@/lib/supabase';
import {readAllRows} from '@/lib/read-all-rows';
import {useSchoolRevision} from '@/lib/school-realtime';
import {errorMessage} from '@/lib/error-message';
import {isAdmin,type Role,type ModuleKey} from '@/lib/modules';
import {chartLabels,chartsForRole,chartPreference,monthRange,recordedRate,type ChartKey,type SchoolAnalytics as Analytics} from '@/lib/school-analytics';
import {downloadExcel} from '@/lib/excel';
import './school-analytics.css';
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Jakarta'});
const money=(n:number)=>new Intl.NumberFormat('id-ID',{notation:'compact',maximumFractionDigits:1}).format(n);
const taskNames:Record<string,string>={todo:'Belum mulai',doing:'Berjalan',blocked:'Terkendala',review:'Menunggu review',done:'Selesai'};
export default function SchoolAnalytics({schoolId,userId,role,onRoute}:{schoolId:string;userId:string;role:Role;onRoute?:(m:ModuleKey,f?:string)=>void}){
 const db=useMemo(()=>browserDb(),[]),revision=useSchoolRevision(schoolId),allowed=chartsForRole(role),storageKey='sc-dashboard-chart:'+schoolId+':'+userId;
 const [chart,setChart]=useState<ChartKey>(allowed[0]),[month,setMonth]=useState(today().slice(0,7)),[classId,setClassId]=useState(''),[classes,setClasses]=useState<{id:string;name:string}[]>([]),[data,setData]=useState<Analytics|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState('');
 useEffect(()=>{setChart(chartPreference(localStorage.getItem(storageKey),chartsForRole(role),chartsForRole(role)[0]))},[storageKey,role]);
 useEffect(()=>{if(!db)return;let alive=true;(async()=>{const q=db.from('sc_classes').select('id,name').eq('school_id',schoolId).order('name').order('id');const c=await readAllRows(q);let rows=c.data||[];if(role==='teacher'){const a=await readAllRows(db.from('sc_teacher_assignments').select('class_id').eq('school_id',schoolId).eq('teacher_id',userId).order('id'));const ids=new Set((a.data||[]).map(x=>x.class_id));rows=rows.filter(x=>ids.has(x.id))}if(alive)setClasses(rows)})();return()=>{alive=false}},[db,schoolId,userId,role,revision]);
 useEffect(()=>{if(!db)return;let alive=true;setBusy(true);setError('');setData(null);(async()=>{try{const {start,end}=monthRange(month);const {data:d,error:e}=await db.rpc('sc_dashboard_analytics',{p_school:schoolId,p_start:start,p_end:end,p_class:classId||null});if(e)throw e;if(!d||typeof d!=='object'||!Array.isArray(d.student))throw Error('Grafik belum tersedia. Coba muat ulang.');if(alive)setData(d as Analytics)}catch(e){if(alive)setError(errorMessage(e))}finally{if(alive)setBusy(false)}})();return()=>{alive=false}},[db,schoolId,month,classId,revision]);
 function choose(value:ChartKey){setChart(value);localStorage.setItem(storageKey,value)}
 const series=data?(chart==='student'?data.student.map(r=>({label:r.day.slice(8),values:[Number(r.present),Number(r.sick),Number(r.leave),Number(r.absent)],details:r.day})):chart==='staff'?data.attendance.map(r=>({label:r.day.slice(8),values:[Number(r.present)-Number(r.late||0),Number(r.late||0)],details:r.day})):chart==='finance'?data.finance.map(r=>({label:r.day.slice(8),values:[Number(r.income),Number(r.expense)],details:r.day})):chart==='program'?data.program.map(r=>({label:taskNames[r.status]||r.status,values:[Number(r.count)],details:r.status})):chart==='grades'?data.grades.map(r=>({label:r.subject,values:[Number(r.average)],details:r.count+' nilai tercatat'})):data.journal_trend.map(r=>({label:r.day.slice(8),values:[Number(r.daily),Number(r.student),Number(r.teaching)],details:r.day}))):[];
 const labels=chart==='student'?['Hadir','Sakit','Izin','Alpa']:chart==='staff'?['Tepat waktu','Terlambat']:chart==='finance'?['Pemasukan','Pengeluaran']:chart==='grades'?['Rata-rata / 100']:chart==='journals'?['Harian','Siswa','Mengajar']:['Jumlah tugas'];
 const max=Math.max(chart==='grades'?100:1,...series.flatMap(r=>r.values));
 const destination:{[K in ChartKey]:[ModuleKey,string]}={student:['buku_kerja','Presensi Siswa'],staff:['attendance','Riwayat kehadiran'],finance:['sikas','Dashboard Keuangan'],program:['command','Progres'],grades:['buku_kerja','Lembar Nilai'],journals:['journals','Rekap Bulanan']};
 async function exportData(){try{await downloadExcel('Grafik-Sekolah-'+month+'.xlsx',[{name:chartLabels[chart],rows:series.length?series.map(r=>Object.fromEntries([['Periode',month],['Kategori',r.details],...labels.map((l,i)=>[l,r.values[i]])])):[{Periode:month,Keterangan:'Belum ada data tercatat.'}]}])}catch(e){setError(errorMessage(e))}}
 return <section className="panel school-analytics"><div className="sectionhead"><div><span className="eyebrow">DASHBOARD ANDA</span><h2>Grafik aktivitas sekolah</h2><p className="muted">Pilih informasi yang dibutuhkan. Pilihan grafik diingat untuk akun ini.</p></div><BarChart3 size={24}/></div><div className="analytics-controls"><label className="field">Grafik<select aria-label="Pilih grafik" value={chart} onChange={e=>choose(e.target.value as ChartKey)}>{allowed.map(k=><option key={k} value={k}>{chartLabels[k]}</option>)}</select></label><label className="field">Bulan<input aria-label="Bulan grafik" type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></label>{['student','grades','journals'].includes(chart)&&<label className="field">Kelas<select aria-label="Kelas grafik" value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Semua kelas sesuai akses</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}<button className="button secondary" disabled={busy||!data} onClick={()=>void exportData()}><Download size={16}/>Excel grafik</button></div>
 {busy?<div className="empty" role="status">Memuat grafik…</div>:error?<div className="banner error" role="alert">{error}</div>:data&&<><div className="analytics-summary"><span>{data.scope}</span><strong>{chart==='student'?(recordedRate(data.student)===null?'Belum ada presensi':recordedRate(data.student)+'% hadir dari catatan'):chart==='staff'?(recordedRate(data.attendance)===null?'Belum ada kehadiran':recordedRate(data.attendance)+'% hadir dari catatan'):chart==='finance'?'Rp '+money(data.finance.reduce((s,r)=>s+Number(r.income)-Number(r.expense),0))+' arus kas bersih':chart==='program'?data.program.reduce((s,r)=>s+Number(r.count),0)+' tugas aktif / tercatat':chart==='grades'?data.grades.reduce((s,r)=>s+Number(r.count),0)+' nilai tercatat':data.journal_trend.reduce((s,r)=>s+Number(r.daily)+Number(r.student)+Number(r.teaching),0)+' jurnal tercatat'}</strong></div>
 {series.length?<><div className="analytics-scroll"><div className="analytics-bars" style={{minWidth:Math.max(280,series.length*54)}} role="img" aria-label={'Grafik '+chartLabels[chart]+' bulan '+month}>{series.map(r=><div className="analytics-column" key={r.details}><div className="analytics-tracks">{r.values.map((v,i)=><div key={i} className={'analytics-bar tone-'+i} style={{height:(v/max*100)+'%'}} title={r.details+' · '+labels[i]+': '+v}><span>{chart==='finance'?money(v):Math.round(v*10)/10}</span></div>)}</div><small title={r.label}>{r.label}</small></div>)}</div></div><div className="chart-legend">{labels.map((l,i)=><span key={l}><i className={'tone-'+i}/>{l}</span>)}</div><details className="analytics-table"><summary>Lihat angka lengkap</summary><div className="tablewrap"><table className="data-table"><thead><tr><th>Tanggal / kategori</th>{labels.map(l=><th key={l}>{l}</th>)}</tr></thead><tbody>{series.map(r=><tr key={r.details}><td>{r.details}</td>{r.values.map((v,i)=><td key={i}>{v.toLocaleString('id-ID')}</td>)}</tr>)}</tbody></table></div></details></>:<div className="empty">Belum ada data pada periode dan kelas ini. Grafik akan mengikuti data yang disimpan pada modul sumber.</div>}
 {isAdmin(role)&&chart==='journals'&&<div className="tablewrap"><h3>Aktivitas per guru / pengguna</h3><p className="muted">Jumlah laporan dan hari tercatat untuk pemantauan. Bukan peringkat kualitas guru.</p><table className="data-table"><thead><tr><th>Nama</th><th>Harian</th><th>Siswa</th><th>Mengajar</th><th>Hari tercatat</th></tr></thead><tbody>{data.journals.map(r=><tr key={r.user_id}><td>{r.name}</td><td>{r.daily}</td><td>{r.student}</td><td>{r.teaching}</td><td>{r.days}</td></tr>)}</tbody></table></div>}
 <div className="analytics-foot"><small>Data diperbarui {new Date(data.generated_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})}. {chart==='student'?'Siswa tanpa catatan belum dianggap alpa.':chart==='grades'?'Nilai dinormalisasi terhadap skor maksimum setiap asesmen.':chart==='journals'?'Jurnal harian/siswa hanya yang dikirim atau direview; jurnal mengajar dari modul pembelajaran.':chart==='finance'?'Transaksi batal tidak dihitung.':''}</small><button className="button secondary" onClick={()=>onRoute?.(...destination[chart])}>Buka data sumber <ArrowRight size={15}/></button></div></>}
 </section>;
}
