"use client";
import {useEffect,useMemo,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {isAdmin,type Role} from "@/lib/modules";
type C={id:string;name:string;grade:string|null;academic_year:string};
type S={id:string;class_id:string|null;nis:string|null;name:string;status:string};
type A={id:string;student_id:string;attendance_date:string;lesson_key:string;mark:string};
type G={id:string;student_id:string;subject:string;assessment_name:string;score:number;assessment_date:string};
type J={id:string;class_id:string;subject:string;topic:string;lesson_date:string};
const now=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"});
export default function SchoolData({mode,schoolId,userId,role,focus}:{mode:"master"|"academic";schoolId:string;userId:string;role:Role;focus?:string}){
 const db=useMemo(()=>browserDb(),[]);
 const [classes,setClasses]=useState<C[]>([]),[students,setStudents]=useState<S[]>([]),[att,setAtt]=useState<A[]>([]),[grades,setGrades]=useState<G[]>([]),[journals,setJournals]=useState<J[]>([]);
 const [className,setClassName]=useState(""),[grade,setGrade]=useState(""),[year,setYear]=useState("2026/2027");
 const [studentName,setStudentName]=useState(""),[nis,setNis]=useState(""),[classId,setClassId]=useState(""),[studentId,setStudentId]=useState("");
 const [day,setDay]=useState(now()),[lesson,setLesson]=useState("daily"),[mark,setMark]=useState("present");
 const [subject,setSubject]=useState(""),[assessment,setAssessment]=useState(""),[score,setScore]=useState(""),[topic,setTopic]=useState(""),[notes,setNotes]=useState("");
 const [tab,setTab]=useState("attendance"),[error,setError]=useState(""),[ok,setOk]=useState(""),[busy,setBusy]=useState(false),[editGradeId,setEditGradeId]=useState(""),[editScore,setEditScore]=useState(""),[editNote,setEditNote]=useState("");
 const manager=isAdmin(role);const canTeach=manager||role==="teacher";const student=students.find(s=>s.id===studentId);const name=(id:string)=>students.find(s=>s.id===id)?.name||"Siswa";
 async function load(){if(!db)return;const [{data:c},{data:s}]=await Promise.all([db.from("sc_classes").select("id,name,grade,academic_year").eq("school_id",schoolId).order("name"),db.from("sc_students").select("id,class_id,nis,name,status").eq("school_id",schoolId).order("name")]);setClasses((c||[]) as C[]);setStudents((s||[]) as S[]);
 if(mode==="academic"){const [{data:a},{data:g},{data:j}]=await Promise.all([db.from("sc_student_attendance").select("id,student_id,attendance_date,lesson_key,mark").eq("school_id",schoolId).order("attendance_date",{ascending:false}).limit(30),db.from("sc_grades").select("id,student_id,subject,assessment_name,score,assessment_date").eq("school_id",schoolId).order("assessment_date",{ascending:false}).limit(30),db.from("sc_teacher_journals").select("id,class_id,subject,topic,lesson_date").eq("school_id",schoolId).order("lesson_date",{ascending:false}).limit(30)]);setAtt((a||[]) as A[]);setGrades((g||[]) as G[]);setJournals((j||[]) as J[])}}
 useEffect(()=>{void load()},[db,schoolId,mode]);
 useEffect(()=>{const f=(focus||"").toLowerCase();if(f.includes("presensi"))setTab("attendance");else if(f.includes("nilai"))setTab("grades");else if(f.includes("jurnal"))setTab("journal")},[focus]);
 async function save(action:()=>Promise<void>){setError("");setOk("");setBusy(true);try{await action();await load();setOk("Data tersimpan pada sekolah ini.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function insert(table:string,row:Record<string,unknown>){if(!db)throw Error("Database belum terhubung.");const {error:e}=await db.from(table).insert({...row,school_id:schoolId});if(e)throw e;}
 const field=(title:string,value:string,set:(x:string)=>void,type="text")=><label className="field">{title}<input type={type} value={value} onChange={e=>set(e.target.value)} required/></label>;
 const cls=<label className="field">Kelas<select value={classId} onChange={e=>setClassId(e.target.value)} required><option value="">Pilih kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} · {c.academic_year}</option>)}</select></label>;
 const stu=<label className="field">Siswa<select value={studentId} onChange={e=>setStudentId(e.target.value)} required><option value="">Pilih siswa</option>{students.filter(s=>s.class_id&&s.status==="active").map(s=><option key={s.id} value={s.id}>{s.name} {s.nis?"· "+s.nis:""}</option>)}</select></label>;
 const dayField=field("Tanggal",day,setDay,"date");
 const result=<>{error&&<div className="banner error" role="alert">{error}</div>}{ok&&<div className="banner success" role="status">{ok}</div>}</>;
 if(mode==="master")return <><section className="panel"><h2>Kelas dan tahun ajaran</h2><p className="muted">Sumber data bersama untuk Buku Kerja, Disiplin Pro, BK dan laporan sekolah.</p>{manager&&<form className="fields" onSubmit={e=>{e.preventDefault();void save(async()=>{await insert("sc_classes",{name:className.trim(),grade:grade.trim()||null,academic_year:year.trim()});setClassName("")})}}>{field("Nama kelas",className,setClassName)}{field("Jenjang",grade,setGrade)}{field("Tahun ajaran",year,setYear)}<button className="button" disabled={busy||!className.trim()}>Tambah Kelas</button></form>}<div className="tablewrap"><table className="data-table"><thead><tr><th>Kelas</th><th>Jenjang</th><th>Tahun ajaran</th></tr></thead><tbody>{classes.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.grade||"—"}</td><td>{c.academic_year}</td></tr>)}</tbody></table>{!classes.length&&<div className="empty">Belum ada kelas.</div>}</div></section><section className="panel"><h2>Data siswa</h2>{manager&&<form className="fields" onSubmit={e=>{e.preventDefault();void save(async()=>{await insert("sc_students",{name:studentName.trim(),nis:nis.trim()||null,class_id:classId});setStudentName("");setNis("")})}}>{field("Nama lengkap",studentName,setStudentName)}{field("NIS (opsional)",nis,setNis)}{cls}<button className="button" disabled={busy||!classId||!studentName.trim()}>Tambah Siswa</button></form>}<div className="tablewrap"><table className="data-table"><thead><tr><th>Nama</th><th>NIS</th><th>Kelas</th><th>Status</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.nis||"—"}</td><td>{classes.find(c=>c.id===s.class_id)?.name||"—"}</td><td>{s.status}</td></tr>)}</tbody></table>{!students.length&&<div className="empty">Belum ada siswa.</div>}</div></section>{result}</>;
 if(!canTeach)return <section className="panel"><p>Data akademik hanya tersedia untuk pengajar dan manajemen berwenang.</p></section>;
 return <section className="panel"><h2>Administrasi guru dan buku kerja digital</h2><div className="flow" style={{marginBottom:16}}>{(["attendance","grades","journal"] as const).map(k=><button key={k} className={"button "+(tab===k?"":"secondary")} onClick={()=>setTab(k)}>{k==="attendance"?"Presensi siswa":k==="grades"?"Penilaian":"Jurnal mengajar"}</button>)}</div>
 {tab==="attendance"&&<><form className="fields" onSubmit={e=>{e.preventDefault();void save(async()=>{await insert("sc_student_attendance",{student_id:studentId,class_id:student?.class_id,attendance_date:day,lesson_key:lesson.trim(),mark,recorded_by:userId});})}}>{stu}{dayField}{field("Kegiatan / mata pelajaran",lesson,setLesson)}<label className="field">Keterangan<select value={mark} onChange={e=>setMark(e.target.value)}>{[["present","Hadir"],["sick","Sakit"],["permission","Izin"],["absent","Alpa"]].map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></label><button className="button" disabled={busy||!student?.class_id}>Simpan Presensi</button></form><div className="tablewrap"><table className="data-table"><thead><tr><th>Tanggal</th><th>Siswa</th><th>Kegiatan</th><th>Keterangan</th></tr></thead><tbody>{att.map(a=><tr key={a.id}><td>{a.attendance_date}</td><td>{name(a.student_id)}</td><td>{a.lesson_key}</td><td>{a.mark}</td></tr>)}</tbody></table></div></>}
 {tab==="grades"&&<><form className="fields" onSubmit={e=>{e.preventDefault();void save(async()=>{await insert("sc_grades",{student_id:studentId,class_id:student?.class_id,subject:subject.trim(),assessment_name:assessment.trim(),assessment_date:day,score:Number(score),recorded_by:userId});setAssessment("");setScore("")})}}>{stu}{field("Mata pelajaran",subject,setSubject)}{field("Nama penilaian",assessment,setAssessment)}{dayField}{field("Nilai (0–100)",score,setScore,"number")}<button className="button" disabled={busy||!student?.class_id||!subject.trim()||!assessment.trim()||score===""||Number(score)<0||Number(score)>100}>Simpan Nilai</button></form><div className="tablewrap"><table className="data-table"><thead><tr><th>Tanggal</th><th>Siswa</th><th>Mapel / Penilaian</th><th>Nilai</th><th>Aksi</th></tr></thead><tbody>{grades.map(g=><tr key={g.id}><td>{g.assessment_date}</td><td>{name(g.student_id)}</td><td>{g.subject} / {g.assessment_name}</td><td>{g.score}</td><td><button className="button secondary" onClick={()=>{setEditGradeId(g.id);setEditScore(String(g.score));setEditNote("")}}>Edit</button></td></tr>)}</tbody></table></div>{editGradeId&&<div className="panel"><h3>Perbaiki Nilai</h3><p className="muted">Perubahan nilai memerlukan izin guru pencatat atau pengelola dan tersimpan dalam audit log.</p><div className="fields"><label className="field">Nilai baru<input type="number" min={0} max={100} value={editScore} onChange={e=>setEditScore(e.target.value)}/></label><label className="field">Alasan / Catatan<input value={editNote} onChange={e=>setEditNote(e.target.value)}/></label><button className="button" disabled={busy||editScore===""||Number(editScore)<0||Number(editScore)>100} onClick={()=>void save(async()=>{if(!db)throw Error("Database belum siap");const {error:e}=await db.rpc("sc_edit_grade",{p_school:schoolId,p_grade:editGradeId,p_score:Number(editScore),p_note:editNote});if(e)throw e;setEditGradeId("")})}>Simpan Revisi</button><button className="button secondary" onClick={()=>setEditGradeId("")}>Batal</button></div></div>}</>}
 {tab==="journal"&&<><form className="fields" onSubmit={e=>{e.preventDefault();void save(async()=>{await insert("sc_teacher_journals",{teacher_id:userId,class_id:classId,subject:subject.trim(),lesson_date:day,topic:topic.trim(),notes:notes.trim()||null});setTopic("");setNotes("")})}}>{cls}{field("Mata pelajaran",subject,setSubject)}{dayField}{field("Topik pembelajaran",topic,setTopic)}<label className="field full">Catatan<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className="button" disabled={busy||!classId||!subject.trim()||!topic.trim()}>Simpan Jurnal</button></form><div className="tablewrap"><table className="data-table"><thead><tr><th>Tanggal</th><th>Kelas</th><th>Mata pelajaran</th><th>Topik</th></tr></thead><tbody>{journals.map(j=><tr key={j.id}><td>{j.lesson_date}</td><td>{classes.find(c=>c.id===j.class_id)?.name||"—"}</td><td>{j.subject}</td><td>{j.topic}</td></tr>)}</tbody></table></div></>}{result}</section>;
}
