"use client";
import {useEffect,useState} from "react";
import {browserDb} from "@/lib/supabase";
import {isAdmin,type Role,type Staff} from "@/lib/modules";

type Kind="attendance"|"performance"|"staff"|"leave";
type Evidence={id:string;staff_user_id:string;event_type:string;title:string;occurred_at:string;verified_at:string|null};
type Leave={id:string;user_id:string;kind:string;from_date:string;to_date:string;reason:string;status:string};
const dateToday=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"});
const roleHR=(r:Role)=>isAdmin(r)||r==="hr";
export default function StaffWorkflows({kind,schoolId,userId,role,staff,onChanged}:{kind:Kind;schoolId:string;userId:string;role:Role;staff:Staff[];onChanged:()=>Promise<void>}){
 const db=browserDb();
 const [items,setItems]=useState<Evidence[]>([]),[leave,setLeave]=useState<Leave[]>([]);
 const [target,setTarget]=useState(""),[title,setTitle]=useState(""),[eventType,setEventType]=useState("program"),[day,setDay]=useState(dateToday());
 const [reason,setReason]=useState(""),[leaveKind,setLeaveKind]=useState("permission"),[start,setStart]=useState(dateToday()),[end,setEnd]=useState(dateToday());
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const [staffId,setStaffId]=useState(""),[editName,setEditName]=useState(""),[position,setPosition]=useState(""),[shift,setShift]=useState("07:00"),[tolerance,setTolerance]=useState("15");
 const manager=isAdmin(role);
 async function load(){if(!db)return;if(kind==="performance"){const {data,error:e}=await db.from("sc_staff_events").select("id,staff_user_id,event_type,title,occurred_at,verified_at").eq("school_id",schoolId).order("occurred_at",{ascending:false}).limit(100);if(e)setError(e.message);setItems((data||[]) as Evidence[])}
 if(kind==="leave"){const {data,error:e}=await db.from("sc_leave_requests").select("id,user_id,kind,from_date,to_date,reason,status").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(100);if(e)setError(e.message);setLeave((data||[]) as Leave[])}}
 useEffect(()=>{void load()},[db,kind,schoolId]);
 function selectStaff(id:string){setStaffId(id);const s=staff.find(z=>z.id===id);if(s){setEditName(s.name);setPosition(s.position||"");setShift((s.shift_start||"07:00").slice(0,5));setTolerance(String(s.late_tolerance_minutes??15));}}
 async function execute(fn:()=>Promise<void>){setBusy(true);setError("");setSuccess("");try{await fn();await load();await onChanged();setSuccess("Perubahan tersimpan.")}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function rpc(fn:string,payload:Record<string,unknown>){if(!db)throw Error("Database belum terhubung.");const {error:e}=await db.rpc(fn,payload);if(e)throw e;}
 const staffLinked=staff.filter(s=>s.user_id);
 const field=(label:string,value:string,set:(x:string)=>void,type="text")=><label className="field">{label}<input type={type} value={value} onChange={e=>set(e.target.value)} required/></label>;
 const feedback=<>{error&&<p role="alert" className="banner error">{error}</p>}{success&&<p role="status" className="banner success">{success}</p>}</>;
 if(kind==="staff"&&!manager)return null;
 if(kind==="staff")return <section className="panel"><h2>Pengaturan jadwal dan identitas SDM</h2><p className="muted">Pengaturan shift dan toleransi keterlambatan hanya dapat diubah manajemen. Perubahan tercatat dalam audit log.</p><div className="fields"><label className="field">Pilih anggota<select value={staffId} onChange={e=>selectStaff(e.target.value)}><option value="">Pilih SDM</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>{field("Nama",editName,setEditName)}{field("Jabatan",position,setPosition)}{field("Mulai shift",shift,setShift,"time")}{field("Toleransi (menit)",tolerance,setTolerance,"number")}<div className="flow"><button className="button" disabled={busy||!staffId||!editName.trim()||!shift||Number(tolerance)<0||Number(tolerance)>120} onClick={()=>void execute(()=>rpc("sc_update_staff",{p_school:schoolId,p_staff:staffId,p_name:editName,p_position:position,p_shift:shift,p_tolerance:Number(tolerance)}))}>Simpan Jadwal</button></div></div>{feedback}</section>;
 if(kind==="attendance"&&!manager)return null;
 if(kind==="attendance")return <section className="panel"><h2>Koreksi presensi manual</h2><p className="muted">Untuk catatan yang belum ada pada hari tersebut. Tidak mengubah jam check-in sebenarnya dan alasan koreksi wajib dicatat.</p><div className="fields"><label className="field">SDM<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Pilih SDM</option>{staffLinked.map(s=><option key={s.id} value={s.user_id!}>{s.name}</option>)}</select></label>{field("Tanggal",day,setDay,"date")}<label className="field full">Alasan koreksi<textarea value={reason} minLength={10} onChange={e=>setReason(e.target.value)} placeholder="Minimal 10 karakter"/></label><button className="button secondary" disabled={busy||!target||reason.trim().length<10} onClick={()=>void execute(()=>rpc("sc_manual_attendance",{p_school:schoolId,p_user:target,p_day:day,p_reason:reason}))}>Catat Manual</button></div>{feedback}</section>;
 if(kind==="performance")return <section className="panel"><h2>Bukti kinerja & pengembangan guru</h2><p className="muted">Program sekolah dan pelatihan masuk rekap setelah diverifikasi oleh manajemen. Presensi mandiri disimpan terpisah.</p>
 {manager&&<div className="fields"><label className="field">Guru/SDM<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Pilih anggota</option>{staffLinked.map(s=><option key={s.id} value={s.user_id!}>{s.name}</option>)}</select></label><label className="field">Kategori<select value={eventType} onChange={e=>setEventType(e.target.value)}>{["program","training","supervision","achievement","feedback"].map(v=><option key={v} value={v}>{v}</option>)}</select></label>{field("Nama kegiatan atau bukti",title,setTitle)}{field("Tanggal",day,setDay,"date")}<button className="button" disabled={busy||!target||title.trim().length<3} onClick={()=>void execute(async()=>{await rpc("sc_add_staff_event",{p_school:schoolId,p_user:target,p_type:eventType,p_title:title,p_day:day,p_evidence:null});setTitle("")})}>Tambah Bukti</button></div>}
 <div style={{marginTop:15}}>{items.map(item=><div className="entry" key={item.id}><div><strong>{item.title}</strong><small>{staff.find(s=>s.user_id===item.staff_user_id)?.name||"Anggota"} · {item.event_type} · {item.occurred_at}</small></div><div className="flow"><span className="pill">{item.verified_at?"Terverifikasi":"Menunggu verifikasi"}</span>{manager&&!item.verified_at&&<button className="button secondary" disabled={busy} onClick={()=>void execute(()=>rpc("sc_verify_staff_event",{p_school:schoolId,p_event:item.id}))}>Verifikasi</button>}</div></div>)}{items.length===0&&<div className="empty">Belum ada bukti kinerja.</div>}</div>{feedback}</section>;
 return <section className="panel"><h2>Izin dan cuti karyawan sekolah</h2><p className="muted">Pengajuan pribadi; hanya kepala sekolah/manajemen SDM yang dapat menyetujui atau menolak.</p><div className="fields"><label className="field">Jenis<select value={leaveKind} onChange={e=>setLeaveKind(e.target.value)}><option value="permission">Izin</option><option value="sick">Sakit</option><option value="annual">Cuti tahunan</option><option value="other">Lainnya</option></select></label>{field("Tanggal awal",start,setStart,"date")}{field("Tanggal akhir",end,setEnd,"date")}<label className="field full">Alasan<textarea value={reason} onChange={e=>setReason(e.target.value)} required/></label><button className="button" disabled={busy||!reason.trim()||end<start} onClick={()=>void execute(async()=>{if(!db)throw Error("Database tidak siap.");const {error:e}=await db.from("sc_leave_requests").insert({school_id:schoolId,user_id:userId,kind:leaveKind,from_date:start,to_date:end,reason:reason.trim()});if(e)throw e;setReason("")})}>Kirim Pengajuan</button></div><h3 style={{marginTop:22}}>Riwayat pengajuan</h3>{leave.map(l=><div className="entry" key={l.id}><div><strong>{staff.find(s=>s.user_id===l.user_id)?.name||"Pengguna"} · {l.kind}</strong><small>{l.from_date} – {l.to_date} · {l.reason}</small></div><div className="flow"><span className="pill">{l.status}</span>{roleHR(role)&&l.status==="pending"&&<><button className="button secondary" disabled={busy} onClick={()=>void execute(()=>rpc("sc_decide_leave",{p_school:schoolId,p_request:l.id,p_approve:true}))}>Setujui</button><button className="button danger" disabled={busy} onClick={()=>void execute(()=>rpc("sc_decide_leave",{p_school:schoolId,p_request:l.id,p_approve:false}))}>Tolak</button></>}</div></div>)}{!leave.length&&<div className="empty">Belum ada pengajuan.</div>}{feedback}</section>;
}
