"use client";
import {useEffect,useMemo,useState} from "react";
import {Check,Download,Link2,Users} from "lucide-react";
import {browserDb} from "@/lib/supabase";
import {downloadExcel} from "@/lib/excel";
import type {Role,Staff} from "@/lib/modules";

type Assign={id:string;supervisor_user_id:string;staff_id:string};
type Directory={user_id:string;email:string|null;role:string;staff_name:string|null};
type Attendance={id:string;user_id:string;duty_date:string;check_in_at:string|null;check_out_at:string|null;status:string;note:string|null};
type Request={id:string;user_id:string;kind:string;from_at:string|null;to_at:string|null;amount:number;reason:string;status:string;created_at:string};
const monthNow=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Jakarta"}).slice(0,7);
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0);
const labels:Record<string,string>={permission:"Izin",sick:"Sakit",annual_leave:"Cuti tahunan",other_leave:"Cuti lainnya",overtime:"Lembur",cash_advance:"Kasbon",reimbursement:"Reimburse"};

export default function SupervisorLegacyParity({schoolId,userId,role,staff,focus}:{schoolId:string;userId:string;role:Role;staff:Staff[];focus:string}){
 const db=useMemo(()=>browserDb(),[]),manager=["owner","hr"].includes(role);
 const [assignments,setAssignments]=useState<Assign[]>([]),[directory,setDirectory]=useState<Directory[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[requests,setRequests]=useState<Request[]>([]);
 const [staffId,setStaffId]=useState(""),[accountId,setAccountId]=useState(""),[supervisorId,setSupervisorId]=useState(""),[month,setMonth]=useState(monthNow()),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ok,setOk]=useState("");
 async function load(){if(!db)return;const from=month+"-01",d=new Date(from+"T00:00:00");d.setMonth(d.getMonth()+1);const to=d.toISOString().slice(0,10);const [a,dir,att,req]=await Promise.all([
  db.from("sc_supervisor_assignments").select("id,supervisor_user_id,staff_id").eq("school_id",schoolId),
  db.rpc("sc_team_directory",{p_school:schoolId}),
  db.from("sc_attendance").select("id,user_id,duty_date,check_in_at,check_out_at,status,note").eq("school_id",schoolId).gte("duty_date",from).lt("duty_date",to).order("duty_date",{ascending:false}).limit(2000),
  db.from("sc_hr_requests").select("id,user_id,kind,from_at,to_at,amount,reason,status,created_at").eq("school_id",schoolId).order("created_at",{ascending:false}).limit(500)
 ]);setAssignments((a.data||[]) as Assign[]);if(!dir.error)setDirectory((dir.data||[]) as Directory[]);setAttendance((att.data||[]) as Attendance[]);setRequests((req.data||[]) as Request[])}
 useEffect(()=>{void load()},[db,schoolId,month]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError("");setOk("");try{await fn();await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 async function rpc(name:string,args:Record<string,unknown>){if(!db)throw Error("Database belum terhubung");const {error}=await db.rpc(name,args);if(error)throw error}
 const assignedIds=assignments.filter(a=>manager||a.supervisor_user_id===userId).map(a=>a.staff_id);
 const team=staff.filter(s=>assignedIds.includes(s.id));
 const teamUsers=new Set(team.map(s=>s.user_id).filter(Boolean) as string[]);
 const staffName=(uid:string)=>staff.find(s=>s.user_id===uid)?.name||directory.find(d=>d.user_id===uid)?.staff_name||"Pegawai";
 async function link(){if(!staffId||!accountId)return;await run(async()=>{await rpc("sc_link_staff_account",{p_school:schoolId,p_staff:staffId,p_user:accountId});setOk("Akun berhasil dihubungkan ke data pegawai.")})}
 async function assign(){if(!staffId||!supervisorId)return;await run(async()=>{await rpc("sc_assign_supervisor",{p_school:schoolId,p_supervisor:supervisorId,p_staff:staffId});setOk("Pegawai masuk tim supervisor.")})}
 async function decide(id:string,status:string){await run(async()=>{const note=prompt("Catatan keputusan (opsional)")||null;await rpc("sc_decide_hr_request",{p_school:schoolId,p_request:id,p_status:status,p_note:note});setOk("Pengajuan diperbarui.")})}
 const teamAttendance=attendance.filter(a=>teamUsers.has(a.user_id)),teamRequests=requests.filter(r=>teamUsers.has(r.user_id));
 async function report(){await downloadExcel("rekap-tim-"+month+".xlsx",[{name:"Kehadiran",rows:teamAttendance.map(a=>({Tanggal:a.duty_date,Nama:staffName(a.user_id),Status:a.status,Masuk:a.check_in_at,Pulang:a.check_out_at,Catatan:a.note}))},{name:"Pengajuan",rows:teamRequests.map(r=>({Nama:staffName(r.user_id),Jenis:labels[r.kind]||r.kind,Mulai:r.from_at,Selesai:r.to_at,Nominal:r.amount,Alasan:r.reason,Status:r.status}))}]);setOk("Rekap tim berhasil dibuat.")}
 const feedback=<>{error&&<div className="banner error">{error}</div>}{ok&&<div className="banner success">{ok}</div>}</>;

 if(focus==="Tim SDM")return <section className="panel"><div className="sectionhead"><div><h2>Tim SDM & Hubungan Akun</h2><p className="muted">Hubungkan akun sekolah ke data pegawai, lalu tetapkan supervisor. Riwayat pegawai tidak dihapus saat akses akun berubah.</p></div><Users/></div>{manager&&<><h3>Hubungkan akun ↔ pegawai</h3><div className="fields"><label className="field">Pegawai<select value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Pilih pegawai</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name} {s.user_id?"· sudah terhubung":""}</option>)}</select></label><label className="field">Akun<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">Pilih akun</option>{directory.map(d=><option key={d.user_id} value={d.user_id}>{d.staff_name||d.email||d.user_id.slice(0,8)} · {d.role}</option>)}</select></label><button className="button" disabled={busy||!staffId||!accountId} onClick={()=>void link()}><Link2 size={14}/> Hubungkan</button></div><h3 style={{marginTop:20}}>Tetapkan supervisor</h3><div className="fields"><label className="field">Pegawai<select value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Pilih pegawai</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field">Supervisor<select value={supervisorId} onChange={e=>setSupervisorId(e.target.value)}><option value="">Pilih supervisor</option>{directory.filter(d=>["vice_principal","principal","hr"].includes(d.role)).map(d=><option key={d.user_id} value={d.user_id}>{d.staff_name||d.email||"Supervisor"} · {d.role}</option>)}</select></label><button className="button secondary" disabled={busy||!staffId||!supervisorId} onClick={()=>void assign()}>Tetapkan</button></div></>}{staff.map(s=>{const a=assignments.find(x=>x.staff_id===s.id),sup=directory.find(d=>d.user_id===a?.supervisor_user_id);return <div className="entry" key={s.id}><div><strong>{s.name}</strong><small>Akun: {s.user_id?directory.find(d=>d.user_id===s.user_id)?.email||"terhubung":"belum terhubung"} · Supervisor: {sup?.staff_name||sup?.email||"belum ditetapkan"}</small></div></div>})}{feedback}</section>;

 if(focus==="Tim Saya")return <section className="panel"><div className="sectionhead"><div><h2>Tim Saya</h2><p className="muted">Daftar pegawai yang ditugaskan kepada supervisor saat ini.</p></div><Users/></div>{team.map(s=><div className="entry" key={s.id}><div><strong>{s.name}</strong><small>{s.position||"Jabatan belum diisi"} · {s.user_id?"akun terhubung":"akun belum terhubung"}</small></div></div>)}{!team.length&&<div className="empty">Belum ada anggota tim yang ditugaskan.</div>}</section>;

 if(focus==="Kehadiran Tim")return <section className="panel"><div className="sectionhead"><div><h2>Kehadiran Tim</h2><p className="muted">Rekap check-in/check-out anggota tim pada bulan terpilih.</p></div></div><label className="field">Bulan<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>{teamAttendance.map(a=><div className="entry" key={a.id}><div><strong>{staffName(a.user_id)} · {a.duty_date}</strong><small>{a.status} · masuk {a.check_in_at?new Date(a.check_in_at).toLocaleTimeString("id-ID"):"—"} · pulang {a.check_out_at?new Date(a.check_out_at).toLocaleTimeString("id-ID"):"—"}</small></div></div>)}{!teamAttendance.length&&<div className="empty">Belum ada catatan kehadiran tim pada periode ini.</div>}</section>;

 if(focus==="Approval Tim")return <section className="panel"><div className="sectionhead"><div><h2>Approval Tim</h2><p className="muted">Supervisor hanya dapat memutuskan pengajuan anggota yang memang berada dalam timnya.</p></div><Check/></div>{teamRequests.map(r=><div className="entry" key={r.id}><div><strong>{staffName(r.user_id)} · {labels[r.kind]||r.kind}</strong><small>{r.from_at?new Date(r.from_at).toLocaleString("id-ID"):"—"} · {r.amount?money(r.amount)+" · ":""}{r.status}</small><p>{r.reason}</p></div><div className="flow"><span className="pill">{r.status}</span>{r.status==="pending"&&<><button className="button" onClick={()=>void decide(r.id,"approved")}>Setujui</button><button className="button danger" onClick={()=>void decide(r.id,"rejected")}>Tolak</button></>}</div></div>)}{!teamRequests.length&&<div className="empty">Belum ada pengajuan tim.</div>}{feedback}</section>;

 return <section className="panel"><div className="sectionhead"><div><h2>Rekap Tim</h2><p className="muted">Gabungkan kehadiran dan pengajuan tim per bulan.</p></div><button className="button" onClick={()=>void report()}><Download size={14}/> Excel</button></div><label className="field">Bulan<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><div className="grid"><div className="card"><label>Anggota</label><strong>{team.length}</strong></div><div className="card"><label>Catatan kehadiran</label><strong>{teamAttendance.length}</strong></div><div className="card"><label>Pengajuan</label><strong>{teamRequests.length}</strong></div><div className="card"><label>Menunggu approval</label><strong>{teamRequests.filter(r=>r.status==="pending").length}</strong></div></div>{feedback}</section>;
}
