"use client";
import {ArrowRight,BookOpen,CalendarDays,WalletCards,Users,ClipboardCheck} from 'lucide-react';
import {resolveWorkspaceRoute} from '@/lib/workspace-navigation';
import type {Role,ModuleKey} from '@/lib/modules';
export const workspaces=[
 {title:'Mengajar & memantau siswa',icon:BookOpen,desc:'Data kelas dipakai bersama oleh presensi, nilai, jurnal dan laporan.',steps:[['master','Penugasan Guru'],['buku_kerja','Presensi Siswa'],['buku_kerja','Lembar Nilai'],['buku_kerja','Jurnal Mengajar'],['journals','Jurnal Siswa'],['buku_kerja','Rekap Bulanan']]},
 {title:'Kegiatan & laporan harian',icon:CalendarDays,desc:'Catat kegiatan berdasarkan agenda atau tugas, lalu laporkan untuk review.',steps:[['calendar','Kalender Sekolah'],['command','Tugas'],['journals','Jurnal Harian'],['journals','Review Jurnal'],['journals','Rekap Bulanan']]},
 {title:'Tagihan & kas',icon:WalletCards,desc:'Pembayaran mengurangi tagihan dan masuk ke kas tanpa pencatatan pemasukan ulang.',steps:[['sikas','Kas/Rekening'],['sikas','Tagihan Siswa'],['sikas','Pembayaran'],['sikas','Riwayat Pembayaran'],['sikas','Buku Kas Umum'],['sikas','Laporan']]},
 {title:'SDM & pengembangan',icon:Users,desc:'Presensi, pengajuan, bukti kegiatan dan payroll tetap memakai profil SDM yang sama.',steps:[['attendance','Check-in/check-out'],['gajian','Pengajuan SDM'],['journals','Jurnal Harian'],['performance','Bukti capaian'],['gajian','Proses Payroll'],['payslip','Riwayat Slip']]},
 {title:'Perencanaan sampai pelaksanaan',icon:ClipboardCheck,desc:'Rencana menjadi acuan program; tugas, agenda, bukti dan laporan membuka data sumber yang sama.',steps:[['kepsek_ai','RKT'],['command','Program Kerja'],['command','Tugas'],['calendar','Kalender Sekolah'],['command','Verifikasi Bukti'],['command','Laporan Program']]}
];
export default function WorkHub({role,onRoute}:{role:Role;onRoute:(m:ModuleKey,f:string)=>void}){return <><section className="command-hero"><div><span className="eyebrow">RUANG KERJA TERPADU</span><h2>Satu pekerjaan, satu alur</h2><p>Pilih pekerjaan lalu ikuti langkahnya. Setiap tombol membuka fitur asli dengan data yang sama.</p></div></section><div className="work-hub-grid">{workspaces.map(w=>{const steps=w.steps.map(([m,f])=>resolveWorkspaceRoute(m,f,role)).filter(x=>x!==null);if(!steps.length)return null;const Icon=w.icon;return <section className="panel" key={w.title}><Icon size={24}/><h2>{w.title}</h2><p className="muted">{w.desc}</p><div className="work-hub-steps">{steps.map((s,i)=><button className="button secondary" key={s.module+s.feature} onClick={()=>onRoute(s.module,s.feature)}><span>{i+1}</span>{s.feature}<ArrowRight size={15}/></button>)}</div></section>})}</div></>}
