import type {ModuleKey} from "./modules";
export type TaskHelp={purpose:string;before:string;steps:string[];result:string};
const help:Record<ModuleKey,TaskHelp>={
 notes:{purpose:"Simpan catatan pribadi atau arahkan catatan kepada peran tertentu dalam sekolah.",before:"Catatan pribadi tetap dapat dibaca kepala sekolah dan pemilik akun sebagai pengawasan. Hanya penulis yang dapat mengubah dan menghapus.",steps:["Buka Catatan Pribadi untuk mencatat milik sendiri atau Catatan Peran untuk pesan/pekerjaan tim.","Klik Tambah Catatan, pilih jenis dan peran tujuan bila dibutuhkan.","Isi judul dan isi lalu simpan. Gunakan pencarian, filter peran, sematkan, atau arsipkan.","Kepala sekolah membuka Semua Catatan untuk melihat catatan lintas peran dan seluruh penulis."],result:"Catatan tersimpan per sekolah dengan pembatasan akses berdasarkan peran dan penulis."},
 journals:{purpose:"Catat kegiatan harian dan pengamatan belajar siswa, lalu laporkan kepada manajemen.",before:"Jurnal siswa memerlukan kelas yang ditugaskan dan siswa dari Data Induk. Catatan rahasia BK tetap di modul BK.",steps:["Buat jurnal sesuai jenisnya dan tautkan agenda/tugas bila berkaitan.","Simpan draf, periksa isi, lalu Kirim untuk Review.","Pengelola memberi catatan review atau meminta revisi; penulis memperbaiki dan mengirim kembali.","Pilih bulan dan pengguna pada Rekap Bulanan, lalu preview atau ekspor Excel/Word/PDF. Arsipkan jurnal sebelum menghapus permanen."],result:"Jurnal, rekap, dashboard dan konteks AI mengikuti data yang sama sesuai akses."},
 overview:{purpose:"Pantau kondisi sekolah dari data yang sudah tersimpan.",before:"Angka beranda mengikuti data operasional sekolah, bukan data contoh.",steps:["Lihat ringkasan siswa, kehadiran, tugas dan agenda.","Buka pekerjaan melalui Akses Cepat atau pilih Analitik Sekolah.","Gunakan Agenda & Deadline untuk melihat tugas yang perlu ditindaklanjuti."],result:"Anda mengetahui pekerjaan berikutnya dan dapat membuka sumber datanya."},
 master:{purpose:"Siapkan satu sumber data untuk seluruh pekerjaan sekolah.",before:"Isi kelas lebih dahulu; siswa dan penugasan guru memerlukan kelas yang benar.",steps:["Pilih jenis data pada submenu: kelas, siswa, guru, staf, mapel atau penugasan.","Gunakan Tambah Data untuk satu record; untuk data banyak, unduh template dari submenu yang sama.","Ganti baris contoh, pertahankan judul kolom, lalu periksa pratinjau sebelum import.","Cari data lama untuk mengedit. Arsipkan data yang tidak aktif agar riwayatnya tetap tersimpan."],result:"Data tersedia pada pilihan siswa, kelas, guru dan mata pelajaran di modul terkait."},
 calendar:{purpose:"Atur kegiatan sekolah, sasaran, waktu, lokasi dan peserta pada satu kalender.",before:"Untuk agenda tingkat/kelas, lengkapi kelas dan tingkat pada Data Induk.",steps:["Pilih bulan lalu klik tanggal yang ingin dilihat.","Klik Tambah Agenda, isi judul, tanggal, jam, lokasi dan sasaran kegiatan.","Jika peserta wajib absen, aktifkan presensi agenda dan tentukan lokasi serta jendela check-in.","Gunakan Rekap Agenda untuk daftar bulanan; Agenda Mengajar hanya menampilkan kategori pembelajaran."],result:"Tanggal berisi agenda ditandai dan kegiatan masuk ke rekap sesuai sasarannya."},
 reports:{purpose:"Buka laporan dari data operasional yang sesuai dengan jenis laporan.",before:"Lengkapi identitas dan branding sekolah, lalu periksa data serta periode pada modul sumber.",steps:["Atur unggahan DOCX, logo, tanda tangan dan stempel melalui Template Laporan Sekolah, lalu uji hasil Word.","Pilih kategori laporan dan buka laporan yang diperlukan.","Tentukan periode, kelas atau filter yang tersedia.","Periksa Preview Draft sebelum menerbitkan Excel, Word atau PDF.","Dokumen terbit dapat ditemukan kembali melalui Arsip Laporan."],result:"Laporan menggunakan identitas sekolah dan data dari modul yang relevan."},
 attendance:{purpose:"Catat kehadiran kerja guru/staf satu kali per hari. Jam pulang melengkapi catatan yang sama, bukan presensi kedua.",before:"Akun harus memiliki profil SDM yang terhubung. Pastikan sekolah, nama, jabatan dan jadwal yang ditampilkan benar; izinkan GPS bila sekolah mewajibkan titik presensi.",steps:["Buka Presensi Saya. Periksa nama sekolah, identitas Anda dan jadwal mulai kerja.","Ketuk Catat Kehadiran Hari Ini satu kali saat mulai bertugas; setelah tercatat tombol masuk hilang.","Jika sekolah membutuhkan rekam waktu kerja, ketuk Catat Jam Pulang saat selesai. Ini memperbarui entri yang sama.","Periksa Riwayat Kehadiran Saya di bawahnya dan gunakan filter tanggal. Pengelola memakai Kehadiran Tim untuk rekap seluruh staf.","Pengelola menata Jadwal & Shift, Lokasi Presensi, Koreksi Presensi dan pengajuan Izin & Cuti pada menu terkait."],result:"Satu catatan kehadiran per pegawai per hari, dengan riwayat pribadi tanpa pencatatan ganda."},
 performance:{purpose:"Catat dan tinjau kegiatan pengembangan serta bukti kinerja.",before:"Hubungkan akun pegawai dan siapkan bukti kegiatan yang dapat diperiksa.",steps:["Pilih Kehadiran untuk rekap faktual, atau kategori kegiatan yang ingin dicatat.","Pengelola menambah bukti dengan pegawai, kegiatan dan tanggal yang tepat.","Periksa bukti sebelum verifikasi; jangan menganggap jumlah kehadiran sebagai penilaian otomatis.","Gunakan Evaluasi untuk penilaian dan Tanggapan guru untuk respons pegawai."],result:"Kegiatan, evaluasi dan tanggapan tersimpan sesuai pemilik dan hak akses."},
 guru_ai:{purpose:"Susun perangkat pembelajaran dengan input khusus untuk tiap jenis dokumen.",before:"Siapkan jenjang, kelas, mapel, topik, CP/TP, durasi, karakter siswa dan sumber daya.",steps:["Pilih jenis perangkat: Modul Ajar, RPP, LKPD, asesmen, bahan ajar, rubrik atau alat lainnya.","Lengkapi konteks pembelajaran dan pertanyaan tambahan khusus alat tersebut.","Periksa standar output, lalu generate dan tinjau isi draf.","Gunakan Riwayat draf untuk versi proyek dan Dokumen Pembelajaran untuk dokumen kerja/review."],result:"Draf mengikuti alat yang dipilih dan dapat ditinjau sebelum dipakai mengajar."},
 assistant:{purpose:"Pilih asisten sesuai pekerjaan, tanpa mencampur generator dokumen dengan percakapan.",before:"Bantuan AI memerlukan koneksi server yang tersedia atau key pribadi untuk alat yang mendukungnya.",steps:["Pilih Asisten Guru, Asisten Kepala Sekolah, Asisten Kelas atau Universal AI Orchestrator sesuai akses Anda.","Tulis tujuan, konteks dan batasan secara jelas; jangan masukkan catatan BK rahasia.","Untuk chat, pilih proyek agar riwayat tetap terpisah. Untuk kelas, tentukan bulan data yang dianalisis.","Periksa hasil. Universal AI Orchestrator mengunci tujuan, memetakan dampak, policy, approval dan verifikasi; perubahan data tetap dilakukan melalui fitur yang berwenang."],result:"Anda mendapat bantuan yang sesuai konteks dan tetap mengendalikan keputusan serta penyimpanan data."},
 buku_kerja:{purpose:"Catat presensi siswa, jurnal dan penilaian dari kelas yang ditugaskan.",before:"Lengkapi siswa, kelas, mata pelajaran dan penugasan guru pada Data Induk.",steps:["Pilih submenu yang sesuai: Presensi Siswa, Lembar Nilai atau Jurnal Mengajar.","Tentukan kelas, tanggal dan mata pelajaran sebelum mengisi.","Simpan catatan, lalu periksa riwayat dan data siswa yang terhubung.","Gunakan Rekap Bulanan atau Laporan Lengkap untuk meninjau hasil periode; jadwal rutin ada di Jadwal Mingguan."],result:"Presensi, nilai dan jurnal terkait kelas/siswa yang sama dan masuk ke laporan."},
 disiplin:{purpose:"Catat pelanggaran dan prestasi, lalu tindak lanjuti melalui pembinaan.",before:"Isi siswa aktif serta master jenis kejadian, poin dan sanksi sekolah.",steps:["Pilih Pelanggaran atau Prestasi, lalu cari siswa dan jenis kejadian.","Isi kronologi, tanggal, waktu serta pencatat; periksa poin sebelum menyimpan.","Catat Pembinaan dan Tindak Lanjut sesuai kebutuhan siswa.","Gunakan rekap, analitik atau surat berdasarkan catatan yang sudah diperiksa."],result:"Kejadian dan tindak lanjut mempunyai riwayat tanpa mengubah poin lama secara diam-diam."},
 bk:{purpose:"Kelola kasus dan layanan BK dengan pembatasan catatan rahasia.",before:"Layanan dan detail kasus diisi oleh Guru BK. Kepala sekolah menggunakan ringkasan agregat.",steps:["Guru BK memilih jenis kasus/layanan yang benar dan siswa dari Data Induk.","Isi tujuan, asesmen/metode, hasil serta jadwal tindak lanjut sesuai formulir layanan.","Gunakan Siswa 360° untuk meninjau riwayat yang diizinkan.","Gunakan analitik dan laporan agregat untuk pemantauan; simpan catatan rahasia hanya di tempat yang disediakan."],result:"Layanan mengikuti jenisnya; pemantauan sekolah tetap menjaga privasi siswa."},
 library:{purpose:"Kelola koleksi, inventaris, anggota, sirkulasi, kunjungan, pengadaan, perawatan dan laporan perpustakaan dari satu sumber data.",before:"Pastikan siswa dan guru/staf sudah benar di Data Induk. Siapkan judul buku dan nomor inventaris sebelum transaksi peminjaman.",steps:["Masukkan Koleksi Buku lalu buat Eksemplar & Inventaris untuk setiap buku fisik.","Gunakan Anggota Perpustakaan dari Data Induk; jangan membuat data siswa/guru kedua.","Catat Peminjaman dan Pengembalian pada eksemplar yang tepat. Gunakan pencarian dan filter untuk menemukan transaksi.","Catat Kunjungan, Pengadaan dan Perawatan; nilai kategori/sumber/tindakan sekolah dapat dicari atau diketik sendiri.","Gunakan Program & Literasi untuk membuka Program & Tugas dan Laporan & Statistik untuk ekspor data."],result:"Koleksi, sirkulasi, kunjungan dan laporan memakai sumber data yang sama tanpa duplikasi anggota."},
 sarpras:{purpose:"Kelola siklus hidup sarana dan prasarana sekolah tanpa memenuhi sidebar dengan menu kecil.",before:"Tetapkan ruangan, nama barang dan merek. Merek wajib untuk setiap barang; foto tidak disimpan agar storage tetap ringan.",steps:["Gunakan Inventaris untuk barang, stok dan ruangan. Cari/filter berdasarkan merek, kondisi, status dan lokasi.","Gunakan Permintaan & Peminjaman untuk pinjam barang/ruang, perbaikan, permintaan stok dan usulan pengadaan.","Gunakan Perawatan & Pengadaan untuk work order, vendor, biaya dan penerimaan barang. Penerimaan dapat membuat inventaris/stok otomatis.","Gunakan Opname & Laporan untuk membandingkan data sistem dengan kondisi fisik. Temuan opname tidak mengubah inventaris otomatis.","Pantau peringatan stok minimum, kerusakan, permintaan dan pinjaman terlambat dari Dashboard Sarpras."],result:"Aset, ruangan, stok, peminjaman, perawatan, pengadaan dan audit sarpras terhubung dalam lima workspace utama."},
 kepsek_ai:{purpose:"Susun perencanaan sekolah, kelola dokumen dan lakukan supervisi.",before:"Siapkan fakta mutu sekolah dan acuan internal yang sudah diverifikasi.",steps:["Pilih dokumen perencanaan yang ingin disusun dan lengkapi input khususnya.","Tinjau draf AI; buka Pusat dokumen untuk menyimpan/editor dan ajukan review.","Gunakan Persetujuan dokumen untuk draf yang menunggu keputusan.","Catat supervisi dan kinerja melalui submenu masing-masing; pustaka/sumber adalah referensi, bukan pengganti data sekolah."],result:"Rencana, dokumen dan supervisi menjalankan alur masing-masing dengan data sekolah yang benar."},
 command:{purpose:"Jalankan program dari penanggung jawab sampai bukti dan laporan.",before:"Buat data pegawai dan program kerja sebelum tugas turunan.",steps:["Buat Program Kerja, tetapkan PIC dan indikator hasil.","Tambahkan Tugas beserta penanggung jawab, tenggat dan progres.","Catat kendala/rapat dan tindak lanjut; lampirkan Bukti Kegiatan pada program yang benar.","Verifikasi bukti sebelum menyusun Laporan Program. Tanggal pelaksanaan diatur lewat Agenda Sekolah."],result:"Program, tugas, keputusan rapat dan bukti saling terhubung."},
 sikas:{purpose:"Kelola kas sekolah, transaksi, anggaran dan pembayaran siswa.",before:"Buat kas/rekening tujuan dan siapkan Data Induk siswa untuk tagihan.",steps:["Catat Pemasukan/Pengeluaran pada kas, kategori dan tanggal yang benar.","Buat anggaran atau tagihan sesuai kegiatan/periode.","Pembayaran siswa dicatat terhadap tagihan yang tepat dan kas tujuan; jangan input ulang sebagai pemasukan manual.","Periksa Riwayat Pembayaran, BKU dan laporan sebelum ekspor. Koreksi transaksi menggunakan alasan agar jejak audit tetap ada."],result:"Saldo kas dan sisa tagihan mengikuti transaksi serta pembayaran yang tersimpan."},
 gajian:{purpose:"Kelola pengajuan pegawai, struktur tim, komponen gaji, payroll dan rekrutmen tanpa menggandakan menu presensi.",before:"Hubungkan akun pegawai dengan Data Induk SDM. Jadwal, lokasi dan kehadiran dikelola di Presensi & Kehadiran; payroll dikelola pemilik akun/HR.",steps:["Buka Pengajuan SDM untuk Lembur, Kasbon atau Reimburse; jenis dipilih di dalam satu halaman.","Kelola struktur tim dan approval sesuai kewenangan.","Siapkan Komponen Gaji dan Komponen Dinamis untuk pegawai yang akan dibayar.","Buka Proses Payroll: hitung draft, periksa rincian, ajukan review, setujui dan kunci periode. Slip muncul setelah periode terkunci/dibayar."],result:"SDM/payroll fokus pada kompensasi dan proses gaji, sedangkan presensi tetap satu pintu."},
 payslip:{purpose:"Lihat dan cetak slip gaji milik akun Anda.",before:"Akun pegawai terhubung dengan SDM dan periode payroll sudah dikunci/dibayar.",steps:["Pilih periode pada daftar Riwayat Slip.","Periksa gaji pokok, tunjangan, potongan dan nilai bersih.","Tekan Cetak Slip untuk mencetak atau menyimpan PDF dari browser."],result:"Slip memakai snapshot periode yang diterbitkan dan hanya menampilkan gaji Anda."},
 access:{purpose:"Undang anggota sekolah dan tetapkan akses berdasarkan pekerjaannya.",before:"Hanya pemilik akun/kepala sekolah yang mengelola anggota dan undangan.",steps:["Pilih Tambah Pengguna dan tentukan peran yang sesuai.","Buat kode undangan sekali pakai dan kirim melalui kanal pribadi.","Anggota menggunakan akun sendiri untuk menerima undangan sekolah.","Periksa Anggota Tim dan hubungkan akun pegawai melalui Tim SDM bila diperlukan."],result:"Anggota berada di sekolah yang benar dengan menu dan data sesuai hak akses."},
 settings:{purpose:"Lengkapi identitas, akademik, branding dan langganan sekolah.",before:"Gunakan informasi sekolah yang benar; kontak dan logo dipakai bersama oleh laporan.",steps:["Pilih bagian pengaturan, isi perubahan dan simpan.","Periksa jenjang, tahun ajaran, timezone dan branding sebelum mencetak laporan.","Simpan konteks AI yang aman pada Memori sekolah.","Gunakan Langganan dan Riwayat pembayaran untuk status akses sekolah; ini terpisah dari tagihan siswa."],result:"Identitas dan preferensi sekolah dipakai konsisten di fitur terkait."},
 help:{purpose:"Temukan urutan kerja dan buka fitur dari petunjuknya.",before:"Pilih panduan sesuai pekerjaan Anda.",steps:["Mulai dari Sini menampilkan langkah awal dan pintasan sesuai peran.","Cari topik atau pilih submenu panduan yang diperlukan.","Buka bagian panduan dan ikuti langkah, lalu gunakan tombol Buka fitur.","Jika hasil belum sesuai, periksa bagian Kalau gagal dan data yang menjadi prasyarat."],result:"Anda mengetahui langkah, hasil yang harus muncul dan cara mengatasi masalah umum."},
};
const overrides:Record<string,Partial<TaskHelp>>={
 "calendar::Kehadiran Agenda":{purpose:"Presensi khusus kegiatan yang mewajibkan Anda hadir.",before:"Pengelola telah menetapkan peserta, alamat, koordinat dan jam agenda.",steps:["Buka agenda yang mewajibkan peran atau nama Anda; pembuat agenda tidak otomatis menjadi peserta.","Aktifkan GPS, pastikan jarak maksimal 100 meter dari titik agenda dan akurasi GPS maksimal 100 meter.","Check-in dalam jendela waktu agenda. Check-out dibuka setelah jam selesai kegiatan.","Jika ditolak, periksa pesan validasi lokasi, akurasi, jam atau peserta."],result:"Presensi tercatat pada kegiatan yang tepat, terpisah dari presensi kerja harian."},
 "guru_ai::Proyek Pembelajaran":{purpose:"Pisahkan pekerjaan pembelajaran per proyek.",steps:["Isi nama proyek minimal tiga karakter, lalu Buat Proyek.","Pilih proyek yang akan dikerjakan; generator perangkat memakai konteks pembelajaran pada formulir alatnya.","Gunakan Riwayat draf untuk memasukkan hasil generator sebagai versi proyek.","Arsipkan proyek yang tidak aktif; pilih proyek aktif untuk melanjutkan percakapan."],result:"Versi hasil dan percakapan dapat ditelusuri per proyek."},
 "guru_ai::Riwayat draf":{steps:["Pilih proyek tujuan.","Pada draf generator, tekan Jadikan versi baru.","Periksa versi proyek dan salin isi yang diperlukan.","Tandai versi final setelah ditinjau; versi lama tetap tersimpan."]},
 "assistant::Universal AI Orchestrator":{purpose:"Ubah tujuan menjadi control plan lintas modul yang mempunyai risk, dependency, approval, checkpoint dan verifikasi.",steps:["Tulis tujuan konkret dan, bila perlu, tambahkan catatan sumber yang sudah diverifikasi.","Pilih Simulasi untuk dry-run atau Terarah untuk workflow yang dikerjakan melalui modul sumber.","Periksa Goal Lock, pre-flight, impact map, tingkat risiko dan langkah yang memerlukan approval.","Simpan run untuk checkpoint. Buka fitur tujuan, kerjakan langkah, verifikasi hasil aktual, lalu tandai selesai."],result:"Workflow mempunyai jejak audit dan tidak dianggap selesai sebelum hasil aktual diverifikasi."},
 "assistant::Rencana Pekerjaan":{purpose:"Alias lama Universal AI Orchestrator.",steps:["Buka Universal AI Orchestrator dari menu Asisten AI."],result:"Gunakan control plane terbaru untuk workflow lintas modul."},
 "sikas::Pembayaran":{purpose:"Catat pembayaran terhadap tagihan siswa yang sudah dibuat.",steps:["Pilih tagihan yang ingin dibayar dan periksa sisa tagihannya.","Isi kas tujuan, nominal, nomor kuitansi, metode dan bukti bila tersedia.","Simpan pembayaran; penerimaan dihubungkan ke kas oleh sistem.","Periksa Riwayat Pembayaran dan sisa tagihan. Jangan membuat pemasukan manual untuk pembayaran yang sama."],result:"Tagihan berkurang dan penerimaan masuk ke kas yang benar."},
 "gajian::Proses Payroll":{purpose:"Selesaikan penggajian pada satu layar berurutan, dari draft sampai dibayar.",steps:["Pilih periode dan tekan Buat / Hitung Draft setelah komponen gaji siap.","Buka Rincian tiap pegawai; tambah penyesuaian hanya saat masih draft.","Ajukan Review. Pemilik akun memeriksa, menyetujui dan mengunci periode.","Setelah terkunci, ekspor laporan final dan periksa Slip Gaji Saya. Tandai Dibayar hanya setelah pembayaran dilakukan."],result:"Status bergerak draft → review → approved → locked → paid sesuai kewenangan."},
 "kepsek_ai::Persetujuan dokumen":{purpose:"Tinjau dokumen yang sedang menunggu review.",steps:["Buka dokumen berstatus review dari daftar.","Periksa judul, jenis dan isi; cocokkan dengan fakta sekolah.","Setujui dokumen hanya jika benar dan Anda berwenang.","Dokumen yang disetujui dipertahankan sebagai hasil final; pengubahan isi final mengikuti alur revisi yang tersedia."],result:"Daftar ini hanya berisi dokumen yang memerlukan persetujuan."},
};
export function taskHelp(module:ModuleKey,feature:string):TaskHelp{return {...help[module],...overrides[module+"::"+feature]}}
